import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "ai-builder" as const;

export const aiBuilder: Topic = {
  id: T,
  name: "Being an AI Builder",
  emoji: "🛠️",
  tagline: "Mindset, workflow, and stack of a modern AI builder.",
  color: "#28e0b3",
  visual: "build",
  levels: [
    level(T, 1, "The builder mindset", "Ship small, learn fast.", 4, [
      spark("Tiny ships > big plans", {
        type: "microread",
        title: "Default to tiny",
        body: "AI moves so fast that 6-month roadmaps are fiction. Modern AI builders ship in 1–7 day loops: pick a tiny problem, build the crappiest version that works, get a real user to try it, learn, repeat. The compounding return on weekly ships beats any quarterly grand plan.",
        takeaway: "Weekly ships compound. Quarterly plans rot.",
        visual: "rocket",
        bodyByAgeBand: {
          kid: "AI is changing so fast that long plans go stale. The best way to build is in tiny chunks: pick the smallest version of your idea, make a rough one in a few days, show a friend, see what they think, fix it, do it again. Lots of small finishes beat one big plan that never actually ships. Each tiny build teaches you something the plan never could.",
          teen: "AI moves so fast that any 6-month plan is basically fiction by month two. The best builders ship in 1–7 day loops: pick a tiny problem, make the rough first version, show one real person, see what breaks, fix it, repeat. Five small finished things you can show > one big perfect plan you never finished. Tiny ships compound; big plans rot. The skill is shrinking the next step until it can be done this week.",
        },
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Start every project with a Loom video of the experience you want, even before code. If you can't make the Loom, the idea isn't crisp enough.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Coding is virtually solved", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "In a year or two, it's not going to matter. Coding is virtually solved. I imagine a world where everyone is able to program, anyone can just build software any time.",
        takeaway:
          "The bottleneck on building is shifting from typing code to knowing what to build. Practice describing what you want clearly — that becomes the new programming language.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Boris Cherny",
          guestRole: "head of Claude Code, Anthropic",
          episodeTitle: "How Claude Code rewrites the job of an engineer",
          timestamp: "00:00:22",
        },
        ctaPrompt:
          "Open Claude Code. Pick the dumbest tiny tool you've wished existed. Describe it in three sentences. Ship the result somewhere a friend can click.",
        visual: "rocket",
      }),
      spark("Productivity per engineer is up 200%", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "I have never enjoyed coding as much as I do today, because I don't have to deal with all the minutia. Productivity per engineer has increased 200%.",
        takeaway:
          "The ceiling on what one person can ship has just doubled. The builders winning right now aren't writing more code — they're giving better instructions to agents.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Boris Cherny",
          guestRole: "head of Claude Code, Anthropic",
          episodeTitle: "How Claude Code rewrites the job of an engineer",
          timestamp: "00:00:21",
        },
        ctaPrompt:
          "Pick a task you'd normally do solo. Spin up two parallel agents on it instead. Notice where you become the bottleneck.",
      }),
      spark("Software engineer becomes builder", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "By the end of the year everyone is going to be a product manager, and everyone codes. The title software engineer is going to start to go away. It's just going to be replaced by builder.",
        takeaway:
          "The PM/engineer split is collapsing into one role. The premium goes to people who can think and ship in the same hour — and the title nobody owns yet is 'builder'.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Boris Cherny",
          guestRole: "head of Claude Code, Anthropic",
          episodeTitle: "How Claude Code rewrites the job of an engineer",
          timestamp: "00:00:44",
        },
        ctaPrompt:
          "Write your next project description from a builder's voice, not a PM's. State the user, the unmet need, and what 'done' looks like — in under 100 words.",
      }),
      spark("Working harder, more AI-pilled", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "AI's supposed to make us more productive. It feels like the people that are most AI-pilled are working harder than they've ever worked. I can fire up four agents in parallel and have them work on four different problems. By 11am, I am wiped out.",
        takeaway:
          "AI doesn't reduce hours — it raises ambition. The right comparison isn't 'less work'; it's 'the project I'd never have attempted' vs 'the project I would've taken three months on'.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Simon Willison",
          guestRole: "software engineer of 25 years",
          episodeTitle: "The November inflection: AI coding crosses the threshold",
          timestamp: "00:00:43",
        },
      }),
      spark("Crappy first version", {
        type: "microread",
        title: "Aim for embarrassing v1",
        body: "If your v1 doesn't make you slightly embarrassed, you waited too long. The point of v1 isn't to be impressive — it's to learn what's wrong. The fastest builders ship things they wouldn't tweet about, watch a real user use them, then fix the loudest thing first. Polish without learning is procrastination dressed up as work.",
        takeaway: "Embarrassing v1, talk to one user, fix the loudest thing. Repeat.",
        bodyByAgeBand: {
          kid: "When you build something new, the first try should look kind of bad. That's good. The whole point of building it is to find out what's wrong. If you wait until it's pretty before showing anyone, you wasted time fixing things that didn't matter. Show a friend, see what they don't get, fix that one thing, show them again.",
          teen: "Your v1 should be slightly embarrassing — that's the point. v1 isn't about being impressive, it's about learning what's broken. The fastest builders ship things they wouldn't tweet, watch one real person use it, then fix the loudest thing. Polish without learning is procrastination dressed up as work. Ship rough, ship soon, fix what users actually trip on.",
        },
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Set a 'walk away' alarm — 90 minutes max on any debug session. If it isn't fixed, /clear, write a 3-sentence summary of where you are, restart the agent. Most spirals are agent confusion you've absorbed.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pick the builder move", {
        type: "scenario",
        setup: "You have an idea for an AI tool but it's vague. You have one weekend.",
        prompt: "Best first move?",
        options: [
          "Write a detailed spec doc",
          "Ship the crappiest version that does ONE thing for ONE user",
          "Pick the perfect model first",
          "Set up auth, billing, and CI",
        ],
        answer: 1,
        explain: "Crappy v1 + one real user = signal. Spec docs without users = fiction.",
      }),
      spark("Builder vs perfectionist", {
        type: "patternmatch",
        prompt: "Match each habit to whether it speeds shipping or slows it",
        pairs: [
          { left: "Show v1 to one user", right: "Speeds" },
          { left: "Polish UI before functionality works", right: "Slows" },
          { left: "Time-box every debug session", right: "Speeds" },
          { left: "Wait for feature complete before launch", right: "Slows" },
        ],
        explain: "Speed comes from learning loops, not from raw effort.",
      }),
      spark("Mission > offer", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "They get these offers and then they say, 'My best case scenario at Meta is that we make money, and my best case scenario at Anthropic is we affect the future of humanity.'",
        takeaway:
          "The strongest retention a frontier company has isn't comp — it's a mission so concrete that a $100M offer feels like a downgrade. Builders: pick employers (or projects) whose mission you'd take a pay cut for.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Benjamin Mann",
          guestRole: "co-founder of Anthropic",
          episodeTitle: "Inside Anthropic — alignment, scaling, AGI timelines",
          timestamp: "00:00:45",
        },
      }),
      spark("Two-week proof of life", {
        type: "microread",
        title: "Set a 14-day clock on every idea",
        body: "When you start an idea, start a 14-day countdown. By day 14: a real user has used it AND told you whether to keep going. If you can't get to that point in two weeks, the idea is too big or the user is too vague — both fixable. The 14-day rule prevents the most expensive builder mistake: spending 3 months on something nobody wanted, because nobody actually used it for the first 11 weeks.",
        takeaway: "14 days from idea to 'one real user used it and told me'. If not, kill or shrink.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Keep a 'wins log' — every shipped feature gets one line and a date. On bad days, scroll up. The compounding is invisible until you see 30 lines from the past 12 weeks.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 2, "The modern stack", "Where to start.", 4, [
      spark("Default starter kit", {
        type: "microread",
        title: "Stack in one paragraph",
        body: "Frontend: Next.js or Vite. LLM: Anthropic Claude or OpenAI GPT. Vector DB: pgvector (Postgres) or Pinecone. Auth: Clerk or Supabase Auth. Hosting: Vercel/Render/Fly. Observability: Helicone or LangSmith. Eval: hand-rolled YAML + LLM-as-judge for now. This stack ships 80% of AI products today. Don't optimize before shipping.",
        takeaway: "Boring, well-documented defaults. Ship first.",
        visual: "stack",
        category: "tooling",
        addedAt: "2026-02-01",
        vocab: [
          { term: "pgvector", definition: "A Postgres extension that lets you store + search embedding vectors right inside your existing database. The simplest vector DB for most early-stage apps." },
          { term: "Pinecone", definition: "A managed, hosted vector database. Pay per index; no infra to run. Trade-off vs pgvector: faster at scale, but yet-another-service." },
          { term: "Helicone", definition: "A drop-in proxy for LLM API calls. Logs every request/response, costs, and latencies — so you can debug, audit, and tune without writing the plumbing yourself." },
          { term: "LangSmith", definition: "LangChain's hosted observability + eval suite. Traces every agent step, lets you replay, score outputs against an eval set." },
          { term: "LLM-as-judge", definition: "Use a stronger model to grade a weaker model's outputs against criteria you wrote in plain English. Cheap, scales, surprisingly good as a smoke test before you build real evals." },
        ],
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Best vector DB for small/medium AI apps starting out?",
        options: ["Build your own", "pgvector inside your existing Postgres", "Deploy Cassandra", "CSV file"],
        answer: 1,
        explain: "pgvector keeps your stack simple and gets you going in an hour.",
      }),
      spark("Boring stack, fast ship", {
        type: "microread",
        title: "Don't reinvent the boring parts",
        body: "Most failed AI projects didn't fail at AI. They failed at auth, deploy, billing, or the database — the boring parts. Use Clerk for auth (one afternoon, done). Use Supabase or Neon for the database (zero ops). Use Vercel or Fly for hosting (git push, live). The boring choices buy you weeks. Spend those weeks on the AI parts that are actually hard.",
        takeaway: "Boring choices everywhere except where you have a real edge.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Use Helicone or LangSmith from day one. Free tier covers prototypes. The day you wonder 'why is this slow?' you'll wish you had every request logged with cost + latency.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("MCP, briefly", {
        type: "microread",
        title: "MCP = USB for tools",
        body: "Model Context Protocol (MCP) is Anthropic's open standard for letting any LLM connect to any tool — your database, GitHub, a Notion workspace, a custom internal API. Write the MCP server once; Claude, GPT-5 (via the SDK), and others can all use it. It's the closest thing to a plug-and-play tool ecosystem AI has had. Worth learning even if you don't ship a server today — you'll consume MCP tools soon.",
        takeaway: "MCP is becoming the standard plug for connecting AI to your stack.",
        category: "tooling",
        addedAt: "2026-05-01",
        vocab: [
          { term: "MCP", definition: "Model Context Protocol — Anthropic-led open standard so any LLM can call any tool/server. Think 'USB for AI'." },
        ],
      }),
      spark("Pick the right LLM provider", {
        type: "patternmatch",
        prompt: "Match the job to a sensible default",
        pairs: [
          { left: "General product chat / agentic loop", right: "Claude Sonnet 4.6" },
          { left: "Hardest reasoning, code, planning", right: "Claude Opus 4.7" },
          { left: "Cheap classify / extract / route", right: "Claude Haiku 4.5 or Gemini Flash" },
          { left: "Multi-modal video / screen understanding", right: "Gemini 2.5 Pro" },
        ],
        explain: "There's no winner-take-all. Build a thin abstraction over 2–3 providers — switch costs are weeks; lock-in costs are years.",
      }),
      spark("Build it: starter kit in 30 minutes", {
        type: "buildcard",
        title: "Build: deploy a real AI app this hour",
        pitch: "From zero to live URL in 30 min. Stop reading; start shipping.",
        promptToCopy:
          "Bootstrap a Next.js app with TypeScript and Tailwind. Add a /api/ask endpoint that calls Anthropic's Claude Sonnet 4.6 SDK with streaming. Build a single chat UI on the homepage. Add Clerk for auth. Deploy to Vercel. Show me the deploy URL when done.",
        successCriteria: "You can text the URL to a friend right now and they can chat with your AI.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Wrap every model call in a try/catch with a fallback to a smaller cheaper model. When the big model 429's at 2am, your product still works at half quality instead of dying.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Stack pitfall", {
        type: "scenario",
        setup: "You're starting an AI side project. You're tempted to set up Kubernetes, custom auth, your own embeddings, and a self-hosted vector DB.",
        prompt: "Best move?",
        options: [
          "Do all of it for full ownership",
          "Use boring managed services (Vercel, Clerk, Supabase) and only self-host where you have a real reason",
          "Pick exotic tools to stand out",
          "Wait until you have funding",
        ],
        answer: 1,
        explain: "Custom infra at v0 is an expensive way to lose to people who shipped on the boring stack last weekend.",
      }),
      spark("The Vercel AI SDK trick", {
        type: "microread",
        title: "One SDK, many models",
        body: "The Vercel AI SDK gives you one consistent streaming/tools interface across Anthropic, OpenAI, Google, and most open-source models. Switch providers with a 1-line model swap. Built-in React hooks (useChat, useCompletion) cut the typical chat UI from 200 lines to 20. Even if you don't deploy on Vercel, the SDK is worth using for the abstraction alone. LangChain is the alternative — heavier, more 'frameworky'.",
        takeaway: "Vercel AI SDK = one interface across providers. Saves weeks on every new project.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pin model versions", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Pin model versions in env vars (CLAUDE_MODEL=claude-sonnet-4-6). Don't hard-code 'sonnet' — when 4.7 lands, you want a config flip, not a code change. Future-you wants this.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Beyond English: i18n on day one", {
        type: "microread",
        title: "Don't ship English-only by accident",
        body: "Most AI products are accidentally English-only because the prompts are English and the model defaults to mirroring the input. If your users speak Spanish, Japanese, or Tagalog, set the system prompt to 'reply in the user's language' and add an explicit fallback. Tokens for non-English are 2–3× more expensive (worse tokenizer fit) — budget that. Your TAM doubles when the product works in five languages instead of one.",
        takeaway: "i18n is a one-line system prompt change. TAM doubles for the cost of one 'reply in the user's language'.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Stack architecture match", {
        type: "patternmatch",
        prompt: "Match each shape to its right backbone",
        pairs: [
          { left: "Chat product", right: "Streaming + state in DB + thumbs feedback" },
          { left: "Agent / autonomous task", right: "Tool calling + memory + run logs" },
          { left: "RAG over docs", right: "pgvector + re-ranker + citation render" },
          { left: "Code product", right: "Sandboxed execution + diff display + revert" },
        ],
        explain: "Each shape has a different backbone. Pick the backbone first; the model is the engine, not the chassis.",
      }),
    ]),
    level(T, 3, "Working with Claude Code", "AI as your pair programmer.", 4, [
      spark("Pair, don't dictate", {
        type: "microread",
        title: "Treat the AI like a junior",
        body: "Claude Code (and similar agentic IDEs) work best when you brief like a colleague: 'we're trying to X, here's the constraint, here's a file to read first.' Vague prompts get vague code. Crisp prompts plus a few targeted reads beat any 'write me an app' prompt every time.",
        takeaway: "Brief like a senior. Verify like an editor.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When Claude Code spirals, stop and `/clear`. Re-explain in 3 sentences. Faster than fighting through a confused context window.",
        category: "tooling",
        addedAt: "2026-02-01",
      }),
      spark("Build it", {
        type: "buildcard",
        title: "Build: a 1-screen toy",
        pitch: "Practice the brief-and-verify loop.",
        promptToCopy:
          "We're building a one-screen web app: paste in a long article, click button, get back a 3-bullet summary plus a single 'so what?' line. Use Vite + React + Tailwind. Use the Anthropic SDK with claude-sonnet-4-6. Show loading + error states.",
        successCriteria: "Working in 15 minutes. You learn pacing, not the code.",
      }),
      spark("Agents take the test step for you", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "It used to be you'd ask ChatGPT for some code and it would spit out some code, and you have to run it and test it. The coding agents — they take that step for you.",
        takeaway:
          "The leap from autocomplete to agent is the leap from 'I write, the AI helps' to 'the AI ships, I review.' Practice that posture: stop typing into the editor; start describing into the agent.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Simon Willison",
          guestRole: "co-creator of Django, coined 'prompt injection'",
          episodeTitle: "The November inflection: AI coding crosses the threshold",
          timestamp: "00:00:00",
        },
      }),
      spark("CLAUDE.md is the cheat code", {
        type: "microread",
        title: "Hand the agent a manual",
        body: "Most Claude Code productivity comes from a `CLAUDE.md` at the repo root. Write what the project is, what the agent can change, what it must not, the test/build commands, where features live, and the tone you want. Claude reads it on every session — your codebase suddenly has a senior engineer's onboarding doc baked in. The same trick works in Cursor (`.cursor/rules`), Windsurf, and any agent that respects per-repo context.",
        takeaway: "A 200-line CLAUDE.md beats 100 carefully-crafted prompts.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Open Claude Code with a clear plan: 'Read X. Tell me how it works. Then I'll tell you what to change.' Two-step prompts beat 'do this big thing' by a mile.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Parallel agents", {
        type: "microread",
        title: "Run three agents at once",
        body: "The unlock most builders haven't tried: spawn 2–3 Claude Code or Cursor agents in parallel git worktrees, each on a different feature. While agent A is thinking, you brief agent B. While B runs, you review A. Throughput per human goes up dramatically — bottleneck shifts from 'AI is slow' to 'I can't context-switch fast enough'. Simon Willison runs four. Most builders haven't tried two.",
        takeaway: "Parallelism is the next 2× — and it's an attention problem, not an AI problem.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Verify like an editor", {
        type: "microread",
        title: "AI code is a draft, not a commit",
        body: "Coding agents will confidently produce 200 lines that compile, look right, and silently break a downstream test. Your job changed: you're an editor, not a writer. Read every diff. Run the tests. Spot-check the new behavior in the running app. The agent's velocity is asymmetric — it can spit out bad code as fast as good. Your verification rate is the real ceiling on quality.",
        takeaway: "Verification is the new bottleneck. Read every diff like a senior reviewer.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Scenario: confused agent", {
        type: "scenario",
        setup: "Claude Code is 30 turns deep, the diffs are getting weirder, and it just deleted a file you didn't ask it to.",
        prompt: "Best move?",
        options: [
          "Keep going, ask it to fix what it broke",
          "/clear, summarize the goal in 3 sentences, restart with the clean tree",
          "Switch to GPT-5",
          "Open the file in a regular editor and fix by hand",
        ],
        answer: 1,
        explain: "Confused context windows compound. Reset is faster than rescuing. The skill is recognizing the confusion 5 turns earlier next time.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add 'and tests' to every Claude Code task, even small ones. The agent will ship broken code with no tests if you let it. Demanding tests forces it to slow down and verify itself.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Build it: agent commit-message helper", {
        type: "buildcard",
        title: "Build: a commit-message agent",
        pitch: "30 minutes. You'll never write a commit message yourself again.",
        promptToCopy:
          "Create a CLI tool aicommit in TypeScript that reads `git diff --cached` from the current repo, calls Claude Sonnet 4.6 with a prompt that asks for a conventional-commit style message, and writes the result to .git/COMMIT_EDITMSG. Add a fallback to Haiku 4.5 if Sonnet fails. Make it work as `git commit` (no -m).",
        successCriteria: "You commit something via your tool. Message is good. You ship it as a 1-page README + npm package by tonight.",
      }),
      spark("Cursor vs Claude Code vs Windsurf", {
        type: "patternmatch",
        prompt: "Match the agent IDE to its strongest fit",
        pairs: [
          { left: "Cursor", right: "Mature multi-file edits in a familiar VS Code shell" },
          { left: "Claude Code", right: "Terminal-first, agent-first, deep CLAUDE.md customization" },
          { left: "Windsurf", right: "Cascade-style multi-step refactors with strong autonomy" },
          { left: "Bolt / Lovable", right: "Browser-first prototyping for non-engineers" },
        ],
        explain: "All four are great. The right pick depends on whether you live in a terminal, a browser, or VS Code. Try two; commit to one.",
      }),
    ]),
    level(T, 4, "From prototype to product", "What changes after 'it works'.", 4, [
      spark("The boring 80%", {
        type: "microread",
        title: "After it works, the real work begins",
        body: "Demo working = 20% done. The other 80%: auth, billing, error handling, retries, logging, evals, on-call, abuse prevention, billing-aware rate limits, model fallback, prompt versioning, user feedback collection. Most failed AI startups had a great demo and never did the boring 80%.",
        takeaway: "Demo = start line. Boring 80% = product.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Retry with backoff", {
        type: "microread",
        title: "The single biggest reliability win",
        body: "LLM APIs 429 (rate limit) and 529 (overload) more than you'd guess — sometimes 1–5% of calls in busy hours. A retry-with-exponential-backoff wrapper recovers nearly all of them invisibly. Add a circuit breaker to fall back to a smaller model after 3 retries. This one pattern accounts for the difference between 'feels flaky' and 'feels solid' from the user's seat.",
        takeaway: "Retries with backoff + fallback = the cheapest reliability you can buy.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Version every prompt. Even if it's just a string in code, prefix it with v3 or stash it in a Postgres table with timestamps. The day you regress, you'll need to roll back instantly.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Streaming changes everything", {
        type: "microread",
        title: "First token in 500ms or it feels broken",
        body: "Without streaming, your AI feels dead until the answer arrives. With streaming, even a 5-second response feels alive — the user sees thinking. Every modern SDK supports it (Anthropic, OpenAI, Vercel AI SDK). Wire it up in week one, not week ten. The perception of speed beats actual speed by a wide margin.",
        takeaway: "Stream tokens from day one. Perceived latency is the real latency.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("User feedback loop", {
        type: "microread",
        title: "Add 👍 / 👎 in week one",
        body: "Most products discover they have a quality problem from churn. AI products can know the moment a response was bad — if you wired thumbs-up/thumbs-down on day one. Every 👎 becomes an eval case, a fine-tune candidate, or a prompt fix. The product that learns fastest from real users wins. Add the buttons before the launch, not after the first complaint.",
        takeaway: "Thumbs-up / thumbs-down + 'why?' on day one. It compounds.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("From prototype to ship", {
        type: "patternmatch",
        prompt: "Match each missing piece to its production category",
        pairs: [
          { left: "Auth + billing", right: "Boring infra" },
          { left: "Retries + fallback", right: "Reliability" },
          { left: "Eval set + judge", right: "Quality" },
          { left: "Thumbs + comments", right: "Feedback loop" },
        ],
        explain: "These four buckets are 'the boring 80%'. None alone wins; all four together = a real product.",
      }),
      spark("Observability is non-optional", {
        type: "microread",
        title: "Log every call, day one",
        body: "Without observability you fly blind through your first outage. Helicone, LangSmith, Langfuse, OpenLLMetry — pick any of them and wire it before launch. You want every call logged with: model, prompt, response, latency, cost, user id. The day a customer says 'it gave me a weird answer last Tuesday', you'll have the trace. Without it, you have a shrug.",
        takeaway: "Wire observability before launch. Future-you will thank present-you.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Build a /admin page that lets you replay any past LLM call with a tweaked prompt. Saves dozens of hours of 'why did it answer that?' debugging.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 5, "Cost engineering", "Three levers.", 4, [
      spark("Cheaper, smaller, cached", {
        type: "microread",
        title: "Cost levers that actually work",
        body: "Three real cost levers: (1) right-size — use a smaller model for easy steps, big model for hard ones (router pattern). (2) cache — Anthropic's prompt caching cuts costs ~90% on repeated system prompts. (3) batch — async batch APIs are 50% cheaper for non-realtime work. Apply all three before negotiating contracts.",
        takeaway: "Router + cache + batch ≈ 5x cost reduction.",
        category: "pattern",
        addedAt: "2025-10-01",
        vocab: [
          { term: "router pattern", definition: "Have a small, cheap classifier model decide whether a query is easy (fast model) or hard (smart model). Cuts cost dramatically without dropping average quality." },
          { term: "prompt caching", definition: "Tell the API to remember the static prefix of your prompt (system instructions, long context). Subsequent calls reuse it — Anthropic charges ~10% for cached tokens." },
          { term: "batch APIs", definition: "Submit a batch of requests together, get results within ~24h. Anthropic + OpenAI both offer ~50% off list pricing for batch work." },
        ],
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add prompt caching to long system prompts that don't change. One-line change in the SDK. Free 80–90% cost cut on those tokens.",
        category: "tooling",
        addedAt: "2026-02-01",
      }),
      spark("The router pattern", {
        type: "microread",
        title: "Cheap model decides, smart model thinks",
        body: "Best cost trick in the agent era is the router pattern: a tiny, cheap classifier (Haiku, Gemini Flash) reads the user's request first. Easy? Route to the small model. Hard? Route to Sonnet 4.6 or Opus 4.7. Done well, you serve 80% of traffic on cheap models and reserve the expensive thinking for the hard 20%. Average cost falls 5–10×; quality holds because the easy 80% didn't need a Ferrari anyway.",
        takeaway: "Don't pay Opus prices for Haiku tasks. Route by difficulty.",
        category: "pattern",
        addedAt: "2025-10-01",
        vocab: [
          { term: "router pattern", definition: "A small, fast model classifies a request and decides which expensive model handles it. Cheapest big quality lever in modern AI products." },
        ],
      }),
      spark("Batch APIs are 50% off", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Anthropic and OpenAI both offer batch APIs at ~50% off list pricing. Results within 24 hours. Anything async — re-embedding, nightly summaries, eval grading — should run on batch by default.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Output tokens are 5× input", {
        type: "microread",
        title: "Where your bill actually comes from",
        body: "On Claude Sonnet 4.6: input is ~$3/M tokens, output is ~$15/M. Output is 5× more expensive. So the highest-leverage cost optimization is *shorter answers*. Tell the model 'respond in ≤ 50 words'. Use structured JSON instead of prose where you can. Strip pleasantries. Most teams burn more cash on chatty replies than on smart prompts.",
        takeaway: "Shorter answers cut cost more than smaller models. Brevity is a billing strategy.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pick the cheapest first move", {
        type: "scenario",
        setup: "Your AI feature works but costs $0.30 per user session. Investors don't love that.",
        prompt: "First move?",
        options: [
          "Switch to a smaller model everywhere",
          "Add prompt caching to your system prompt + cap output tokens",
          "Negotiate enterprise pricing",
          "Train your own model",
        ],
        answer: 1,
        explain: "One afternoon's work for an 80–90% cost cut on cached tokens, plus shorter outputs. Then think about routing.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Set per-user daily token budgets in your DB. When a user blows through theirs, drop them to a cheaper model + send a 'hey, slow down' message. Free unlimited AI is how startups die.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Cost monitor scenario", {
        type: "scenario",
        setup: "Your AI feature's monthly bill jumped 4× overnight. No code change. No new launch.",
        prompt: "First investigation step?",
        options: [
          "Email the provider asking for a credit",
          "Check Helicone / your logs for which user or prompt is responsible — it's almost always abuse or a runaway agent",
          "Switch providers",
          "Throttle everyone immediately",
        ],
        answer: 1,
        explain: "Cost spikes have a cause. Find the responsible user/prompt first; rate-limits, abuse-detection, or a model fallback fixes the cause cleanly.",
      }),
    ]),
    level(T, 6, "Working with non-determinism", "It will surprise you.", 4, [
      spark("Embrace variance", {
        type: "microread",
        title: "Test the distribution",
        body: "Same input, slightly different output every time. Stop trying to make it deterministic — design around variance instead. Your tests check distributional properties: 'output is valid JSON 99% of the time', 'always cites at least one source', 'never mentions X'. Specific examples become spot-checks; the eval set is the real assertion.",
        takeaway: "Test properties, not exact strings.",
        bodyByAgeBand: {
          kid: "AI doesn't give the exact same answer every time, even to the exact same question. Stop fighting that — work with it. Instead of 'did it say *this exact sentence*?', ask things like 'is the answer in good shape almost every time? Does it ever say something hurtful? Does it always show its work?' You're testing how the AI *behaves*, not memorising one perfect answer.",
          teen: "Same prompt, slightly different output every time — that's how AI works. Stop trying to force it to be exact. Instead, design tests around behaviour: 'output is valid JSON 99% of the time', 'always cites at least one source', 'never says anything harmful'. You check the *shape* of the answers across many runs, not whether one specific reply matches a target string. That's the right mental model — and it scales.",
        },
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Temperature, briefly", {
        type: "microread",
        title: "Turn the dial, not the model",
        body: "Temperature controls how 'spicy' the model's sampling is. 0 = always pick the most likely next token (most deterministic, most boring). 0.7 = the default for chat (creative but coherent). 1.0+ = wild and surprising. Set temperature 0 for extraction, JSON, and high-stakes structured outputs. Set 0.7 for chat, drafts, brainstorming. Temperature is the cheapest knob you have — turn it before changing models.",
        takeaway: "Temperature 0 for structure. ~0.7 for chat. Try the dial before swapping models.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Run every prompt 5 times in CI. If the 'shape' of the answer is unstable across runs (sometimes JSON, sometimes prose), your prompt is broken — not the model.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Schema-constrained output", {
        type: "microread",
        title: "Force the shape, not the content",
        body: "Modern APIs (Anthropic tool use, OpenAI function calling, Pydantic structured output) let you specify the JSON schema and the model is constrained to fit it. The model might still hallucinate values, but it can't return broken JSON or miss a field. This single feature kills 80% of 'AI is unreliable in production' complaints. If you're parsing model output with regex, stop — use the schema-constrained mode.",
        takeaway: "Schema-constrained output kills 80% of structured-output bugs.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Distributional testing", {
        type: "scenario",
        setup: "Your prompt outputs valid JSON 95% of the time. The other 5% it returns prose.",
        prompt: "Best response?",
        options: [
          "Ship it — 95% is fine",
          "Use schema-constrained output mode + add a fallback parser for legacy outputs",
          "Switch to a 10× bigger model",
          "Set temperature to 0",
        ],
        answer: 1,
        explain: "Schema constraints + defensive parser get you to 99.9%+. Don't blame the model for what was always a contract problem.",
      }),
      spark("Log raw responses to debug variance", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When fighting flaky outputs, log the model's raw response 100× side-by-side. Patterns will emerge — usually the prompt has two valid interpretations the model is split between.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 7, "Picking models", "Match model to job.", 4, [
      spark("Speed/quality/cost triangle", {
        type: "microread",
        title: "The three-way trade",
        body: "Fast and cheap: small models (Haiku 4.5, Gemini Flash, GPT-4.1 mini) for classification, extraction, simple chat. Balanced: Sonnet 4.6 for most product work. Heavy lifting: Opus 4.7 or reasoning models for hard analysis, code, multi-step plans. Build a router so each task lands on the right model — your single biggest quality+cost win.",
        takeaway: "One app, many models. Route by task.",
        category: "tooling",
        addedAt: "2026-02-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match each job to a tier",
        pairs: [
          { left: "Classify support email tone", right: "Small / fast" },
          { left: "Plan a 5-step refactor", right: "Reasoning / heavy" },
          { left: "Draft 3 marketing variants", right: "Mid-tier" },
          { left: "Extract phone numbers", right: "Small / fast" },
        ],
        explain: "Pay for what you actually need.",
      }),
      spark("Switch costs are real", {
        type: "microread",
        title: "Build a thin abstraction layer",
        body: "Today's fastest model is tomorrow's mid-tier. Don't hard-code provider SDK calls all over your codebase. Wrap them in one tiny module: `chat({ model, messages })`. Want to flip from Claude to Gemini? Change one line. Lock-in costs are months; abstraction costs are hours. The Vercel AI SDK and LiteLLM both already give you this for free.",
        takeaway: "One thin LLM wrapper. Provider switches become Tuesday tasks.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When a new model drops (Claude X.Y, Gemini Z.0), don't rewrite — just flip the model name and re-run your eval set. Most upgrades are free wins; some break things. Evals catch which is which.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Open-source models in production", {
        type: "microread",
        title: "When to bother with Llama",
        body: "Llama 4, Qwen 3, and DeepSeek R1 are good enough for many production jobs — extraction, classification, structured generation. You'd self-host (Together, Fireworks, your own GPU) when: (1) you need data residency, (2) you ship at scale where API margins hurt, (3) you have one specialized task you can fine-tune. For everything else, the API economics still beat self-hosting until you're at serious volume.",
        takeaway: "Self-host open models when you have a real reason. API beats self-host until volume justifies it.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Multi-modal as default", {
        type: "microread",
        title: "Vision and audio are now table stakes",
        body: "Claude Opus 4.7, Gemini 2.5, GPT-5 all handle images, audio, and (for some) video natively in 2026. If your product description starts with 'first the user uploads...', the user can probably take a photo or talk instead. Multi-modal isn't a feature anymore — it's a default. The product idea you didn't build last year because vision was unreliable: try it again now.",
        takeaway: "Multi-modal is default in 2026. Photos and voice are first-class inputs now.",
        category: "frontier",
        addedAt: "2026-05-01",
      }),
      spark("Pick the right tier", {
        type: "scenario",
        setup: "You're routing a customer support flow. 90% of incoming tickets are simple (refund / address change). 10% are complex (multi-step debugging).",
        prompt: "Best architecture?",
        options: [
          "Send everything to Opus 4.7 to be safe",
          "Tiny classifier first → Haiku for simple, Sonnet for medium, Opus for the rare hard cases",
          "Send everything to Haiku and hope",
          "Hire 50 humans",
        ],
        answer: 1,
        explain: "Routing by difficulty cuts cost 5–10× without dropping quality on the hard tickets.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When a new model lab launches, your first move is run YOUR eval set — not their benchmarks. Benchmarks are PR; your evals are reality. The new model is worth switching to only if your evals say so.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Latency tier vs quality tier", {
        type: "microread",
        title: "User-facing chat ≠ background agent",
        body: "The model you pick depends on whether the user is waiting. User-facing chat: optimize for time-to-first-token (Haiku, Flash, Mini). Background agent / batch jobs: optimize for raw quality and cost (Opus, Gemini Pro, batch APIs). Mixing them is a quality-of-experience disaster: a slow model in chat feels broken even if its answer is excellent.",
        takeaway: "Latency tier for chat. Quality tier for background. Don't cross the streams.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Keep a tiny per-task model overrides table in your DB or YAML — task → model. New eval result lifts Sonnet over Opus on extraction? Flip the override; ship the change without redeploying.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 8, "Shipping in public", "Distribution as a builder skill.", 4, [
      spark("Build in the open", {
        type: "microread",
        title: "Distribution beats secrecy",
        body: "Most AI builders' secret weapon isn't a clever model — it's a public build journal. Ship a feature, post a 30-sec video, get 50 reactions, get 5 testers, iterate. Repeat 30 times and you have a niche audience. Stay quiet until 'it's ready' and you'll launch to crickets.",
        takeaway: "Tiny ships, public videos, real testers, every week.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Record a 30-second Loom for every shipped feature. Auto-post to one channel (X, LinkedIn, Discord). The bar for 'ship' becomes one video, not a launch.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("95% of my code I didn't type", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "Today probably 95% of the code that I produce I didn't type it myself. I write so much of my code on my phone, it's wild. I can get good work done walking the dog along the beach.",
        takeaway:
          "'Sitting at a desk to code' is becoming optional. The new skill is having a clear specification loaded in your head — when you have that, the input device hardly matters.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Simon Willison",
          guestRole: "software engineer of 25 years",
          episodeTitle: "The November inflection: AI coding crosses the threshold",
          timestamp: "00:00:23",
        },
      }),
      spark("Demo videos beat blog posts", {
        type: "microread",
        title: "30 seconds of working > 500 words about it",
        body: "AI products are weird; people don't believe yours works until they see it. A 30-second screen recording of a real workflow does more outreach than 5 blog posts. Loom, Cap, ScreenStudio — pick one and make videos a default output of every shipped feature. The first 5 will be awkward. The next 50 build a track record nobody can argue with.",
        takeaway: "Default to demo videos. Words age; videos prove.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Tag every public ship: 'built with Claude Code in 2 hours' or '12 LOC, 3 prompts.' Specifics beat vague boasts. People save and share concrete numbers.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Find your 100 true fans", {
        type: "microread",
        title: "Niche audiences > broad ones",
        body: "Most AI builders chase 'go viral on X'. Wrong move. Build for one specific person — a friend who'd actually pay for this — and find 100 more like them. A niche of 100 paying users beats 100k bored followers. Hang out where they hang out (Discord servers, slacks, niche subreddits, niche Twitter). Reply, help, ship for them. Distribution is a person, not a megaphone.",
        takeaway: "Build for a niche of 100 you can name. Skip the 100k.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Newsletter > algorithm", {
        type: "microread",
        title: "Own the relationship",
        body: "X, LinkedIn, TikTok all rent you reach. Algorithms tweak; reach evaporates. A newsletter (Substack, Beehiiv, ConvertKit) is your direct line — 200 subscribers who opted in and open emails will outlast any algorithm twist. Capture emails on every public ship. Every demo video links to the list. The list is the asset.",
        takeaway: "Build a newsletter alongside everything. The list is the only audience nobody can take.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Public habit setup", {
        type: "scenario",
        setup: "You ship something cool but nobody knows. You hate the idea of 'becoming an influencer'.",
        prompt: "Smallest viable habit?",
        options: [
          "Quit and build in stealth",
          "Auto-publish 30-sec demo + 1 sentence to one channel after every ship",
          "Hire a marketer",
          "Wait until you have 10 features",
        ],
        answer: 1,
        explain: "One channel + auto-post + 30-sec video = 'shipping in public' for introverts. The bar isn't influencer; it's existing in public at all.",
      }),
      spark("Distribution channels match", {
        type: "patternmatch",
        prompt: "Match the channel to its strongest fit",
        pairs: [
          { left: "X / Twitter", right: "Other AI builders, fast feedback, niche memes" },
          { left: "LinkedIn", right: "B2B buyers, hiring managers, enterprise eyes" },
          { left: "TikTok / Shorts", right: "Consumer products, demo-heavy, younger audiences" },
          { left: "Newsletter", right: "Owned audience, deeper attention, no algorithm" },
        ],
        explain: "Pick one or two; saturate them; ignore the rest. Every channel takes a year of consistent posts to compound.",
      }),
    ]),
    level(T, 9, "AI builder antipatterns", "What sinks projects.", 4, [
      spark("Six killers", {
        type: "microread",
        title: "Common ways to die",
        body: "(1) Over-architecting before product-market fit. (2) Assuming bigger model fixes a data problem. (3) Skipping evals because 'it works'. (4) Free unlimited AI usage. (5) Hiding the AI in UX so users don't trust it. (6) Building in stealth for 6 months. Each one alone is survivable. Two together is fatal.",
        takeaway: "Watch for these. They kill more startups than competition.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("The ChatGPT wrapper trap", {
        type: "microread",
        title: "Wrapper isn't the slur — moat is the slur",
        body: "'It's just a ChatGPT wrapper' was the 2024 dismissal. Then Cursor and Perplexity built billion-dollar wrappers. The lesson isn't 'wrappers are great'; it's 'wrappers without a moat die'. Moats: proprietary data, deep workflow integration, distribution, brand. Build one of those into your wrapper from day one or your product is a single API price-cut away from being free.",
        takeaway: "Wrappers are fine. Wrappers without a moat are zombies.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "If your only differentiator is 'we use GPT-5', you don't have a product, you have a referral. Your moat must survive any API price war.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Hiding the AI", {
        type: "microread",
        title: "Trust comes from showing your work",
        body: "Anti-pattern: AI does all the work behind the scenes; user thinks a human did it. Feels magical until something breaks and now they don't trust your team. Better: show what the AI did. 'Drafted by Claude, edited by human.' 'Summary by AI — see source.' 'Confidence: low — please verify.' Honest provenance builds more trust than fake humans ever do.",
        takeaway: "Show the AI's hand. Hidden AI breaks trust the moment something goes wrong.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Scope creep in agent products", {
        type: "scenario",
        setup: "You shipped an AI feature that summarizes meetings. Users now want it to schedule follow-ups, send emails, update Salesforce, and run their lives.",
        prompt: "Smart move?",
        options: [
          "Build all of it; users want it",
          "Pick one extension that compounds (e.g., scheduling), ship that, watch what they ask for next",
          "Refuse all extensions",
          "Pivot to a horizontal AI assistant",
        ],
        answer: 1,
        explain: "User requests are signal, not commands. Pick the next extension that compounds. Building everything they ask is how AI assistants become slow and bad at every task.",
      }),
      spark("Antipattern map", {
        type: "patternmatch",
        prompt: "Match the antipattern to the early warning sign",
        pairs: [
          { left: "Over-architecting", right: "You haven't shipped to a user this month" },
          { left: "No evals", right: "'I think this prompt is better?' debates" },
          { left: "Free unlimited AI", right: "Top users cost more than they pay" },
          { left: "Stealth mode", right: "Launch day = crickets" },
        ],
        explain: "Each antipattern has a tell. Notice the tell early; the antipattern is already eating your runway.",
      }),
      spark("The fine-tune trap", {
        type: "microread",
        title: "Fine-tuning is the last move, not the first",
        body: "When prompts feel limited, the temptation is to fine-tune. Don't yet. Most quality problems trace back to: (1) bad eval set so you don't actually know what's wrong, (2) bad retrieval so the model lacks context, (3) bad system prompt. Fix those first. Fine-tuning is expensive, slow to iterate, and freezes you on a model version. Try it after you've exhausted prompting and retrieval, not before.",
        takeaway: "Fine-tune is the last move, not the first. Evals + retrieval + prompts first.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pricing trap: free unlimited AI", {
        type: "microread",
        title: "Free + unlimited = death",
        body: "Many AI startups launch with free unlimited usage to grow fast. They die. Why: 5% of users will use 95% of the tokens, and your unit economics flip negative within weeks. Counter-pattern: cap free tier hard (10 / 50 / 100 messages per day), surface the limit clearly, charge for more from day one. Scale the free tier up later when you can afford it. Anthropic, OpenAI, Cursor — none of them do free unlimited; that's a tell.",
        takeaway: "Cap free usage hard from day one. Free unlimited AI burns 18 months in 6.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 10, "Boss: builder check", "Are you ready?", 6, [
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: AI Builder",
        questions: [
          {
            type: "quickpick",
            prompt: "Best first move when starting a new AI feature?",
            options: ["Pick the model first", "Write 30-sec demo script + 10 eval cases", "Set up monitoring", "Hire infra engineer"],
            answer: 1,
            explain: "Demo + evals = clarity on what you're shipping.",
          },
          {
            type: "quickpick",
            prompt: "Same prompt gives slightly different outputs each call. Best response?",
            options: ["Block ship", "Set temperature 0 always", "Test distributional properties via evals", "Switch model"],
            answer: 2,
            explain: "Embrace variance, test properties.",
          },
          {
            type: "quickpick",
            prompt: "You ship weekly. What changes after 8 weeks?",
            options: ["Nothing", "Compound learning + small audience + sharper instincts", "You burn out automatically", "Funding"],
            answer: 1,
            explain: "Velocity compounds. That's the whole point.",
          },
          {
            type: "quickpick",
            prompt: "Best lever to cut AI costs without dropping quality?",
            options: ["Switch labs", "Build your own model", "Router pattern + prompt caching + capped output", "Lower temperature to 0"],
            answer: 2,
            explain: "Three classic levers stack to ~5–10× cost cuts. Lab switching is a last resort.",
          },
          {
            type: "quickpick",
            prompt: "Production AI feature is hallucinating. First move?",
            options: [
              "Switch to a bigger model",
              "Add ground truth via RAG and force the model to cite sources",
              "Lower temperature to 0",
              "Disable the feature",
            ],
            answer: 1,
            explain: "Hallucination = no ground truth. RAG anchors the model in real documents and dramatically cuts the failure mode.",
          },
        ],
      }),
    ]),
  ],
};
