import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "ai-devtools" as const;

export const aiDevtools: Topic = {
  id: T,
  name: "AI Dev Tools",
  emoji: "⚙️",
  tagline: "Claude Code, Cursor, Copilot, agentic IDEs.",
  color: "#28e0b3",
  visual: "build",
  levels: [
    level(T, 1, "The new IDE wave", "AI inside your editor.", 6, [
      spark("Three flavors", {
        type: "microread",
        title: "Suggest, chat, agent",
        body: "AI dev tools come in three flavors: (1) Suggest — inline ghost text (Copilot, Cursor Tab). (2) Chat — a side panel for back-and-forth (Cursor Chat, JetBrains AI). (3) Agent — autonomous, multi-file edits (Claude Code, Cursor Agent, Devin). Each fits a different brain mode. The best teams mix all three across the day.",
        takeaway: "Suggest for typing. Chat for thinking. Agent for grunt work.",
        bodyByAgeBand: {
          kid: "AI in your code editor comes in three flavors. (1) Suggest — it finishes your sentences as you type, like autocomplete. (2) Chat — a little assistant on the side you can ask questions. (3) Agent — a helper that does whole jobs by itself (read files, run things, edit code). Pick the one that matches the kind of thinking you're doing.",
          teen: "AI dev tools come in three flavors. Suggest = autocomplete on steroids (Copilot, Cursor Tab). Chat = a sidebar where you ask questions while you code (Cursor Chat). Agent = a teammate that edits multiple files on its own (Claude Code, Cursor Agent, Devin). Match the tool to the kind of work you're doing.",
        },
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match each task to the best mode",
        pairs: [
          { left: "Refactor across 12 files", right: "Agent" },
          { left: "Finish a tedious utility function", right: "Suggest" },
          { left: "Debug a confusing error", right: "Chat" },
          { left: "Migrate to a new API", right: "Agent" },
        ],
        explain: "Match the tool to the mental gear.",
      }),
      spark("Ghost text 101", {
        type: "microread",
        title: "How inline suggestion actually works",
        body: "Copilot and Cursor Tab watch your cursor and the surrounding code, then stream a completion model in the background. The suggestion only renders as gray text until you hit Tab. Latency budget is brutal — under ~300ms or you start typing past it. This is why these models are small distilled variants (Copilot uses GPT-4o-mini-class), not frontier reasoners. Speed beats smarts in the suggest lane.",
        takeaway: "Inline suggest is a latency game. Small fast models always win it.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: accept selectively", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Don't accept whole multi-line ghost suggestions blind. Hit Esc, retype the first word you wanted, let it re-suggest. The model converges to your real intent within two tries.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Why is inline suggest powered by a smaller model than chat?",
        options: ["Cheaper to train", "Latency budget under 300ms", "Smaller models are smarter", "Tab key only fires once"],
        answer: 1,
        explain: "Suggest fights typing speed. Anything slow gets typed past.",
      }),
      spark("Cursor Tab vs Copilot", {
        type: "microread",
        title: "Two flavors of inline",
        body: "GitHub Copilot suggests one cursor position at a time — classic ghost text. Cursor Tab is multi-cursor: it predicts the next *jump* (file, line, location) and prefills there too. On a refactor that's the difference between 6 Tab presses and 1. If you live in IntelliJ, JetBrains AI does similar with its Multi-Line Edit. The capability bar moved.",
        takeaway: "Modern Tab predicts where you're going next, not just what you'll type.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Five stack ranks", {
        type: "patternmatch",
        prompt: "Match the tool to its strongest lane",
        pairs: [
          { left: "Cursor", right: "VS Code fork with multi-file Composer" },
          { left: "Claude Code", right: "Terminal-first agent" },
          { left: "Copilot", right: "Ubiquitous inline + chat" },
          { left: "Windsurf", right: "Codeium-built Cascade agent" },
        ],
        explain: "Each lane has a default leader. Try at least two before committing.",
      }),
      spark("Scenario: pick the mode", {
        type: "scenario",
        setup: "You need to rename a function used in 38 files across a TypeScript monorepo.",
        prompt: "Best AI mode?",
        options: ["Inline suggest, file by file", "Chat to write a sed command", "Agent with a one-line brief", "Find/replace by hand"],
        answer: 2,
        explain: "Multi-file deterministic edit = agent territory. Brief it, watch the diff.",
      }),
      spark("Tip: keep agents narrow", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Agents drift when briefs are vague. Anchor every run with one verb (rename, extract, add) plus one explicit success criterion (tests green, types clean). Drift drops 80%.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("History snap", {
        type: "microread",
        title: "From Tabnine to Devin in five years",
        body: "Tabnine (2018) was the first mainstream AI autocomplete — n-gram based, mostly comic. Copilot (2021) was the GPT-3-fueled inflection point. Cursor (2023) showed multi-file Composer. Claude Code (2024) reframed the editor as a terminal-first agent. Devin (2024) tried fully autonomous. The arc: from completing a line, to completing a refactor, to completing a ticket. Each layer adds delegation depth.",
        takeaway: "Five years moved from 'finish the line' to 'finish the ticket'. Plan for delegation depth growing again.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quickpick: agent definition", {
        type: "quickpick",
        prompt: "What separates an 'agent' from 'chat with code edits'?",
        options: ["Better model", "It loops: tool call → result → tool call until done", "It writes more lines", "It uses VS Code"],
        answer: 1,
        explain: "Agent = self-driven tool-use loop. Chat is one-shot per turn.",
      }),
      spark("Watching agents work", {
        type: "youtubenugget",
        quote: "The mental shift with Claude Code isn't 'how do I write the prompt' — it's 'what's the smallest verifiable diff I can ask for, and what's the test that proves it landed.' Agent quality lives or dies on that loop.",
        takeaway: "Agent UX is a TDD loop. Smallest verifiable diff in, a test out, repeat.",
        source: {
          platform: "youtube",
          videoUrl: "https://www.youtube.com/@AnthropicAI",
          videoTitle: "Claude Code in practice",
          channelName: "Anthropic",
          publishedAt: "2026-04-10",
          durationMinutes: 18,
        },
        ctaPrompt: "Open Claude Code on a tiny side repo. Ask for one file's worth of code + the test that proves it. Do the loop three times.",
        category: "tooling",
        addedAt: "2026-04-22",
      }),
      spark("Skill ladder", {
        type: "microread",
        title: "Three rungs to climb",
        body: "Most engineers plateau on rung one. (1) Tab-and-pray: accept inline suggestions, ship faster, don't change workflow. (2) Conversational: open chat for hard spots, paste errors, iterate. (3) Delegated: write a brief, hand to an agent, review the diff. Pay rises with rung. The bottleneck isn't talent — it's the willingness to let the AI try and you review.",
        takeaway: "Climb past Tab-and-pray. Delegation is where the leverage lives.",
        bodyByAgeBand: {
          teen: "Three levels of using AI to code. Level 1: tab to accept autocomplete. Level 2: chat to debug. Level 3: hand it a job and review the result. Most people get stuck on level 1. Level 3 is where it actually saves you hours.",
        },
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 2, "Claude Code mental model", "Briefing an autonomous teammate.", 6, [
      spark("Brief, run, verify", {
        type: "microread",
        title: "How Claude Code thinks",
        body: "Claude Code is an agent: it reads files, runs commands, edits code, asks for permission on risky things. Best results come from clear briefs ('we're trying to X, here's a relevant file'), small diffs ('add only the function, no refactors'), and active verification ('run the test, show me output'). Treat it like a sharp pair partner, not an oracle.",
        takeaway: "Brief tightly. Verify often. Small diffs.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: CLAUDE.md", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add a CLAUDE.md to your repo with the project's conventions. Claude Code reads it on startup and follows your house style without you repeating yourself.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Build it: tiny utility", {
        type: "buildcard",
        title: "Build: tiny utility with Claude Code",
        pitch: "5 min. Get a feel for the loop.",
        promptToCopy:
          "Add a small Python script `scripts/word_count.py` that reads stdin and prints word count + char count + estimated tokens (chars/4). Add a unit test with pytest. Run the test.",
        successCriteria: "Script + green test, no manual fixes from you.",
      }),
      spark("Plan mode", {
        type: "microread",
        title: "Plan first, edit second",
        body: "Claude Code's Plan Mode (Shift+Tab on the prompt) makes the agent draft a step list before touching a file. It surfaces wrong assumptions before they become wrong commits. Use it whenever the change spans more than two files or you're working in unfamiliar code. It's the cheapest way to catch a bad brief — five seconds of reading a plan beats five minutes reviewing a doomed diff.",
        takeaway: "Plan Mode = a free dry-run. Use it on anything multi-file.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Slash commands", {
        type: "microread",
        title: "Promptbook your repo",
        body: "Drop a markdown file in `.claude/commands/` and it becomes a slash command everyone on the team can run. Examples seen in the wild: /pr-description, /security-review, /add-changelog, /deploy-staging. Each is just instructions Claude Code follows. The first time you write one feels weird; by the third you wonder how anyone shares prompts via Slack screenshots.",
        takeaway: "Slash commands turn one engineer's prompt taste into team infrastructure.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: subagents", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Long task? Spawn a subagent for the read-heavy part (grep, scan, summarize) and keep the main thread focused on the edit. Saves your context window for what matters.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Permission tiers", {
        type: "microread",
        title: "Yes, no, allow always",
        body: "Claude Code's permission prompts split into three lanes. Read-only commands (ls, cat, git status) — auto-allow. Mutating but reversible (edits inside the repo) — confirm once per session. Irreversible (rm, push --force, db migrations) — confirm every single time. Tune the allowlist in `~/.claude/settings.json`. Most productivity gains come from auto-allowing the safe stuff so the loop never stalls.",
        takeaway: "Auto-allow the boring. Confirm the dangerous. Never blanket-allow.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quickpick: small diffs", {
        type: "quickpick",
        prompt: "Why ask Claude Code for the smallest possible diff?",
        options: ["Smaller is cheaper", "Easier to verify, easier to revert", "Models prefer it", "Git likes it"],
        answer: 1,
        explain: "Verification cost grows with diff size. Small diffs = fast trust loop.",
      }),
      spark("Scenario: stuck agent", {
        type: "scenario",
        setup: "Claude Code is on its fourth attempt to fix a flaky test. Each retry runs the full suite.",
        prompt: "Best move?",
        options: [
          "Let it keep retrying",
          "Stop, narrow the test command to just the flaky test, then let it loop",
          "Switch to Cursor",
          "Bigger model",
        ],
        answer: 1,
        explain: "Tighten the loop. Fewer files in scope = faster signal.",
      }),
      spark("Pattern match: brief shape", {
        type: "patternmatch",
        prompt: "Match each brief fragment to its job",
        pairs: [
          { left: "We're trying to add idempotency keys", right: "Goal" },
          { left: "Touch only routes/payments.ts and its test", right: "Scope" },
          { left: "Test passes when duplicate key returns 409", right: "Success criterion" },
          { left: "Don't refactor the wrapper", right: "Constraint" },
        ],
        explain: "Goal + scope + success + constraint = a brief that doesn't drift.",
      }),
      spark("Tip: hooks", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add a PostToolUse hook in settings.json to auto-run prettier or eslint after every edit. Claude Code never ships you unformatted code again.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Microread: context discipline", {
        type: "microread",
        title: "Don't paste the world",
        body: "A 200k context window is a trap. The more irrelevant code in context, the more the model attends to noise. Best practice: tell the agent the *one* file you care about; let it `grep` and read others itself, only loading what it needs. Counter-intuitive but real — narrower context, sharper edits.",
        takeaway: "Less context, sharper edits. Big windows are not free.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Build it: refactor with rollback", {
        type: "buildcard",
        title: "Build: agent refactor with safety net",
        pitch: "10 min. Practice the verify loop.",
        promptToCopy:
          "In a side branch of any repo, ask Claude Code to extract one duplicated helper into a shared module. Require: tests pass before and after, the diff fits in <50 lines, and you can revert in one command. Show me the test output.",
        successCriteria: "Green tests, tiny diff, you actually ran git diff before merging.",
      }),
    ]),
    level(T, 3, "Cursor & friends", "When to use what.", 6, [
      spark("Editor wars", {
        type: "microread",
        title: "Quick comparison",
        body: "Cursor: VS Code fork with deep AI (Tab completion, Composer for multi-file). Windsurf (Codeium): similar territory, strong autocomplete. JetBrains AI: native to IntelliJ family. Claude Code: terminal-first, agent-strong. GitHub Copilot: ubiquitous, integrates everywhere. Try 2-3 in a real workflow before committing — your taste matters more than reviews.",
        takeaway: "Try a few. Pick what fits your flow.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Cursor Composer", {
        type: "microread",
        title: "Multi-file edits in a sidebar",
        body: "Cursor Composer (Cmd+I) takes a natural-language brief and proposes an edit set across files, shown as a reviewable diff. It's the spiritual ancestor of every modern in-editor agent. Strengths: visual diff review, easy partial-accept. Weaknesses: shorter context than Claude Code, less terminal access. Great for UI work, weaker for CLI-heavy backends.",
        takeaway: "Composer = visual multi-file edits. Fast for UI, slower for backend ops.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: cursorrules", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "A `.cursorrules` file at repo root acts like CLAUDE.md for Cursor. Put your team's conventions there once and stop re-explaining them in every chat.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Windsurf Cascade", {
        type: "microread",
        title: "The autonomous one from Codeium",
        body: "Codeium's Windsurf shipped Cascade — a flow that picks up where you left off and proposes the next agentic edit. The pitch: 'AI that reads your mind between keystrokes.' In practice it works best when the codebase has consistent patterns (one of those 'it learns your style' deals). Worth trying if you live in a single language and want fewer prompts.",
        takeaway: "Windsurf Cascade = momentum-aware AI. Best in pattern-rich codebases.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Copilot today", {
        type: "microread",
        title: "Copilot is more than autocomplete now",
        body: "GitHub Copilot in 2026 ships inline suggest, chat, code review, agent mode (Copilot Workspace), and CLI. It also lets you swap the underlying model — Claude Sonnet, GPT-5, Gemini 2.5 — depending on the lane. The boring choice if your org already pays for it. Often beats nothing.",
        takeaway: "Copilot is a multi-model platform now, not just ghost text.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quickpick: switching costs", {
        type: "quickpick",
        prompt: "Biggest hidden cost of switching IDEs every quarter?",
        options: ["Subscription fees", "Lost muscle memory + reconfigured prompts/rules", "GPU usage", "Slow git"],
        answer: 1,
        explain: "Tooling fluency compounds. Switching resets the curve.",
      }),
      spark("Pattern match: pick the editor", {
        type: "patternmatch",
        prompt: "Match the use case to the best-fit tool",
        pairs: [
          { left: "Pure CLI / DevOps work", right: "Claude Code" },
          { left: "Big visual diff review of UI changes", right: "Cursor Composer" },
          { left: "Java/Kotlin in a JetBrains shop", right: "JetBrains AI" },
          { left: "Existing GitHub Enterprise SSO", right: "GitHub Copilot" },
        ],
        explain: "Tools have lanes. Match the lane to the day.",
      }),
      spark("Zed AI", {
        type: "microread",
        title: "The fast newcomer",
        body: "Zed (the editor) shipped Zed AI — multiplayer-first, GPU-rendered, with bring-your-own-key Anthropic/OpenAI integration. Strength: speed (60fps editing, no perceptible lag) and built-in collab — your AI session is shareable. Weakness: smaller plugin ecosystem than VS Code derivatives. The 'Sublime Text mood' for AI coding.",
        takeaway: "Zed = the speed/collab option. Smaller ecosystem, snappier editor.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: BYOK", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Bring-your-own-key (Cursor, Zed, Continue, Aider) lets you swap models per task and bill direct to Anthropic/OpenAI. Often cheaper than the editor's default plan once you ship.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Aider in the terminal", {
        type: "microread",
        title: "Open-source pair-programmer",
        body: "Aider is a Python-based CLI agent: it git-commits each change, supports any major API model, and runs entirely local. Killer feature: every edit is a clean atomic commit, so reverting is `git revert`. Free to use beyond API costs. The hacker's pick — strong on Python and Rust, lighter on TypeScript.",
        takeaway: "Aider = open-source agent with one-commit-per-edit hygiene.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Continue.dev", {
        type: "microread",
        title: "VS Code without forking",
        body: "Continue is an MIT-licensed VS Code/JetBrains extension giving you Cursor-shaped chat + edit + autocomplete without leaving your stock editor. Plug your Anthropic/OpenAI/Ollama key, point at any model. Strong if your org bans new editors but tolerates extensions. Maintained, in production at multiple Fortune 500s.",
        takeaway: "Continue.dev = bring AI into stock VS Code. Open source. No editor lock-in.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quickpick: best fit for ops work", {
        type: "quickpick",
        prompt: "You spend 80% of your day in tmux/SSH sessions. Best AI tool?",
        options: ["Cursor", "VS Code + Copilot", "Claude Code in the terminal", "JetBrains AI"],
        answer: 2,
        explain: "Terminal-first work wants terminal-first agent.",
      }),
      spark("Scenario: legacy codebase", {
        type: "scenario",
        setup: "Your codebase is 2M lines of Java in IntelliJ, with custom build conventions and no CLAUDE.md.",
        prompt: "Best first AI tool?",
        options: [
          "Claude Code from scratch",
          "JetBrains AI — already understands your project model",
          "Cursor — start over",
          "No AI",
        ],
        answer: 1,
        explain: "JetBrains AI plugs into the existing project index. Lowest setup tax.",
      }),
    ]),
    level(T, 4, "Vibe coding vs spec coding", "When to lean which way.", 6, [
      spark("Two modes", {
        type: "microread",
        title: "Vibe vs spec",
        body: "Vibe coding: 'just make it work', iterate by feel — great for prototypes, throwaways, exploration. Spec coding: write the contract first (types, tests, docstrings), let AI fill the body — great for production, libraries, maintained systems. Mixing them blindly creates messes. Pick mode per task.",
        takeaway: "Vibe to explore. Spec to ship.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Karpathy on vibe coding", {
        type: "podcastnugget",
        quote: "There's a new kind of coding I call vibe coding, where you fully give in to the vibes, embrace exponentials, and forget that the code even exists. It's not too bad for throwaway weekend projects.",
        takeaway: "Vibe coding is fine for throwaways. Don't ship it as your billing system.",
        creatorId: "lenny",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Andrej Karpathy",
          guestRole: "Founding member of OpenAI, Tesla AI Director",
          episodeTitle: "Software is changing (again)",
        },
        ctaPrompt: "Pick a project. Decide before you start: is this vibe-mode or spec-mode? Stick to it for the session.",
      }),
      spark("Spec-first checklist", {
        type: "microread",
        title: "Five things spec coders do first",
        body: "Before any AI-assisted production work: (1) write the function signature with types. (2) write the docstring describing inputs/outputs. (3) write at least one happy-path test. (4) write at least one error-path test. (5) THEN ask the AI to fill the body. The AI's hit rate triples vs starting from prose. This is the cheapest reliability hack on the table.",
        takeaway: "Sig, docstring, two tests — only then unleash the model.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Vibe red flags", {
        type: "microread",
        title: "When vibe coding turns expensive",
        body: "Vibe is cheap until: (a) you can't reproduce a bug because there are no tests, (b) the AI 'fixed' it three times each touching different files, (c) the codebase has no consistent style for new code to follow, (d) you're past hour two on something that should've taken thirty minutes. At any of these, stop. Switch to spec mode. Write a test that fails on the bug, hand it back.",
        takeaway: "Past hour two with no tests, you're not vibing — you're drowning.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match each task to vibe or spec",
        pairs: [
          { left: "Hackathon UI for Saturday demo", right: "Vibe" },
          { left: "Stripe webhook handler in production", right: "Spec" },
          { left: "Throwaway scraper to test an idea", right: "Vibe" },
          { left: "Auth library used by 12 services", right: "Spec" },
        ],
        explain: "Stakes + lifetime decide the mode.",
      }),
      spark("Tip: vibe-to-spec convert", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Liked your vibe prototype? Before committing it long-term, ask the AI: 'add types + tests + docstrings to this file without changing behavior.' Five-minute upgrade from vibe to spec.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quickpick: ratio in real teams", {
        type: "quickpick",
        prompt: "Healthy mix for shipping teams?",
        options: ["100% vibe", "100% spec", "Vibe in /experiments, spec everywhere production-bound", "Spec only on Mondays"],
        answer: 2,
        explain: "Mode by directory. Vibe for /experiments, spec on the deploy path.",
      }),
      spark("Scenario: prototype graduation", {
        type: "scenario",
        setup: "Your weekend vibe-coded chatbot is now used by 200 users. PMs ask for SLAs.",
        prompt: "First move?",
        options: [
          "Keep vibing",
          "Add typed contract on every external boundary + test the failure modes",
          "Rewrite from scratch",
          "Switch frameworks",
        ],
        answer: 1,
        explain: "Don't rewrite. Spec-fy at the boundaries first.",
      }),
      spark("Build it: spec a function", {
        type: "buildcard",
        title: "Build: spec-mode warmup",
        pitch: "8 min. Practice the discipline.",
        promptToCopy:
          "Pick a function in any repo with no tests. Write its signature with types, a 1-line docstring, and 2 pytest cases (happy + edge). Then ask Claude Code to make the tests pass without changing the signature. Show me before/after.",
        successCriteria: "Tests pass, signature unchanged, you didn't touch the body manually.",
      }),
      spark("The TDD comeback", {
        type: "microread",
        title: "AI made TDD fun",
        body: "TDD got a reputation as religion. Then AI agents arrived and TDD became practical: write the failing test, hand to the agent, get a passing implementation in seconds. The agent treats red tests as a compass. Many teams that resisted TDD for years adopted it the week they got Claude Code. The AI did the discipline-of-writing-the-test-first what the human couldn't.",
        takeaway: "AI makes TDD economical. The discipline finally pays its rent.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip: throwaway tag", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add a `// VIBE — REVISIT BEFORE PROD` comment on any vibe-coded section. Grep finds them when you graduate the prototype. Saves 'I'll remember' regret.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 5, "Tests as the AI's compass", "TDD finally easy.", 6, [
      spark("AI loves tests", {
        type: "microread",
        title: "Tests = clarity for the AI",
        body: "Tests give the AI an unambiguous signal: pass or fail. Write the test first, hand it to the agent, let it iterate against red. AI burnout? Bad tests. AI shipping clean code? Good tests. TDD never had a more natural partner.",
        takeaway: "Test-first. AI iterates faster than you ever could.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip: bug-as-test", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When the AI gets stuck, don't help directly — write one more test that exposes the bug. The AI will fix it itself.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Test types tier list", {
        type: "microread",
        title: "What kind of test gives the AI the best signal",
        body: "Best to worst signal for an agent: (1) unit test on a pure function — clear input, clear output. (2) integration test with mocked I/O. (3) end-to-end test with real services — slow, flaky, agent will rerun forever. (4) snapshot test — agent updates the snapshot to match its broken output and calls it green. Lean on (1) and (2) for the agent's loop. Use (3) sparingly. Avoid (4) when AI is in the loop.",
        takeaway: "Unit and integration > e2e > snapshot for AI feedback loops.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quickpick: snapshot trap", {
        type: "quickpick",
        prompt: "Why are snapshot tests dangerous in AI loops?",
        options: ["Slow", "AI will overwrite the snapshot to match its own broken output", "Hard to read", "Don't run on CI"],
        answer: 1,
        explain: "Always-pass = no signal. The agent learns the wrong lesson.",
      }),
      spark("Property-based for free", {
        type: "microread",
        title: "Hypothesis, fast-check, proptest",
        body: "Property-based testing (Python's Hypothesis, JS's fast-check, Rust's proptest) generates random inputs and finds the smallest one that breaks the property. Pair it with an AI agent and you get free regression coverage on every implementation. Ask Claude Code: 'add three property tests for this function: encode/decode roundtrips, length-preservation, idempotency'. Done in seconds.",
        takeaway: "Property tests + AI = regression coverage you didn't have to think about.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: tighten the loop", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Set the agent's `test_command` to the *single* failing test, not the whole suite. Loop time drops 10x; the agent makes 5 attempts in the time it used to make 1.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the task to the test type",
        pairs: [
          { left: "Pure parser function", right: "Unit test" },
          { left: "API handler that hits a database", right: "Integration test" },
          { left: "Login flow across 3 pages", right: "E2E test" },
          { left: "JSON serializer roundtrip", right: "Property test" },
        ],
        explain: "Each test type has a sweet spot. Match for clean signal.",
      }),
      spark("Mutation testing for AI code", {
        type: "microread",
        title: "Tests that test your tests",
        body: "Mutation testing tools (Stryker, mutmut, PIT) flip an operator (== → !=) and rerun your tests. If they still pass, the test was useless. AI-generated tests are notoriously confident-but-shallow; mutation scoring is the cheapest way to catch the lie. Run mutmut once a sprint and you'll find which AI-written tests don't actually defend anything.",
        takeaway: "Mutation testing exposes AI-written tests that pass for the wrong reason.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Scenario: flaky test", {
        type: "scenario",
        setup: "Agent reports green for the suite. CI is red on a flaky test 1 in 10 runs.",
        prompt: "Best move?",
        options: [
          "Retry until green",
          "Tell the agent to reproduce it 10 times in a loop, then root-cause",
          "Mark it skip",
          "Switch CI provider",
        ],
        answer: 1,
        explain: "Make the flake reproducible first. AI loops on signal it can see.",
      }),
      spark("Build it: TDD with Claude Code", {
        type: "buildcard",
        title: "Build: red-green-refactor with an agent",
        pitch: "12 min. The classic loop, AI-assisted.",
        promptToCopy:
          "In any repo, ask Claude Code to: (1) write 3 failing tests for a function called `parse_iso_duration` that takes 'PT5M30S' and returns total seconds. (2) implement the function. (3) refactor for clarity without changing behavior. Show test output between each phase.",
        successCriteria: "Three phases, three commits, all tests green at each phase.",
      }),
      spark("Tip: commit per phase", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Tell the agent to commit after each phase (red, green, refactor). Cheap rollback if the refactor breaks things — `git reset HEAD~1` and you're back to green.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quickpick: fastest signal", {
        type: "quickpick",
        prompt: "Which gives the AI the fastest fix-loop signal?",
        options: ["Print statements", "A single failing unit test with one assertion", "A 200-line e2e test", "Manual click-through"],
        answer: 1,
        explain: "Tight test = tight signal. Agent converges faster.",
      }),
    ]),
    level(T, 6, "Code review with AI", "Faster, fairer, deeper.", 6, [
      spark("Pre-PR scan", {
        type: "microread",
        title: "AI review = first pass",
        body: "Run AI review on your diff before opening the PR. Most catch typos, missing error handling, security smells, weak tests. Saves humans from boring nits and lets them focus on architecture/intent. Tools: GitHub Copilot Review, CodeRabbit, custom Claude Code workflows.",
        takeaway: "AI does the boring review. Humans do the hard.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("CodeRabbit", {
        type: "microread",
        title: "What CodeRabbit actually finds",
        body: "CodeRabbit auto-comments on PRs with line-level suggestions, summary, and a nit-vs-blocker tier. Sweet spot: catches the unsanitized input, the missing await, the off-by-one in pagination — issues humans miss after lunch. Weakness: pattern-blind on novel architectures, occasionally over-confident on style. Use it as a tireless first reviewer, not the last word.",
        takeaway: "CodeRabbit catches the lunch-time misses. Pair it with a human reviewer.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Custom review prompts", {
        type: "microread",
        title: "Build your team's review style",
        body: "Generic AI review = generic feedback. The win: write a 50-line `/review` slash command that knows your stack ('this team uses Result<T, E> not exceptions', 'always check tenant_id on queries'). Suddenly the AI catches the team-specific footguns no general tool would. The prompt becomes the team's lived-tradition encoded as text.",
        takeaway: "Custom review prompt > generic tool. Encode your team's hard-won rules.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip: security pass", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Run a separate /security-review pass with a prompt that lists your top 10 footguns (auth, crypto, SSRF, IDOR, secrets in logs). AI scans only for those. 5x more useful than 'review for security.'",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quickpick: nit fatigue", {
        type: "quickpick",
        prompt: "Best way to stop AI reviewers from drowning the PR in nits?",
        options: [
          "Disable the tool",
          "Configure severity thresholds + auto-resolve cosmetic comments",
          "Bigger model",
          "Yell at it",
        ],
        answer: 1,
        explain: "Threshold + auto-resolve. Keep blockers, drop the rest.",
      }),
      spark("PR description generator", {
        type: "microread",
        title: "AI-generated PR bodies that actually help",
        body: "Bad PR bodies: 'fixed bug.' Good ones: what changed, why, how to test, risks, rollback. AI can generate the second from the diff. The trick is the prompt: tell it your team's PR template, give it the diff, ask for the body. Quality goes from 'meh' to 'better than what most humans write under deadline.'",
        takeaway: "PR-body generator beats the average human's last-minute write-up.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pattern match: review roles", {
        type: "patternmatch",
        prompt: "Match each reviewer to its strength",
        pairs: [
          { left: "AI", right: "Boring nits, security smells, broad coverage" },
          { left: "Senior eng", right: "Architecture, system fit, taste" },
          { left: "Domain expert", right: "Business logic correctness" },
          { left: "Author self-review", right: "Catching their own dumb mistakes" },
        ],
        explain: "Layered review beats any single reviewer. AI is the cheap layer.",
      }),
      spark("Tip: review your own review", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Before merging an AI-flagged 'critical' issue, ask the AI to defend it in 3 sentences. False positives crumble; real issues sharpen. Cheap sanity gate.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Scenario: false positive flood", {
        type: "scenario",
        setup: "Your AI reviewer flags 'unsafe SQL' on every parameterized query because the codebase uses raw f-strings inside a custom safe-builder.",
        prompt: "Best fix?",
        options: [
          "Disable the tool",
          "Add a project-level note in the review prompt explaining the safe-builder pattern",
          "Switch databases",
          "Ignore the warnings",
        ],
        answer: 1,
        explain: "Teach the reviewer your codebase's exceptions. Once.",
      }),
      spark("Build it: review your own diff", {
        type: "buildcard",
        title: "Build: a personal review prompt",
        pitch: "10 min. Bake your taste into a prompt.",
        promptToCopy:
          "Write a /review slash command for Claude Code that runs git diff, then reviews against these rules: (1) no console.log left in, (2) every async function has try/catch or explicit propagation, (3) every new env var is documented in .env.example. Output a checklist with line numbers.",
        successCriteria: "Run it on a real diff. It catches at least one thing you'd have missed.",
      }),
      spark("Quickpick: when to skip AI review", {
        type: "quickpick",
        prompt: "When is AI review least useful?",
        options: [
          "Trivial typo PRs",
          "Architectural design changes",
          "Adding tests",
          "Renaming files",
        ],
        answer: 1,
        explain: "Architecture asks 'should this exist?' — AI reviewers answer 'is the syntax fine?'",
      }),
    ]),
    level(T, 7, "MCP servers & extensions", "Plug AI into your tools.", 6, [
      spark("Model Context Protocol", {
        type: "microread",
        title: "What MCP unlocks",
        body: "MCP (Model Context Protocol) is an open standard for plugging tools into AI clients. Build once, work in Claude Code, Cursor, others. Common MCPs: Postgres, GitHub, Linear, Slack, filesystem, browser. Building one is ~50 lines. Suddenly your agent can query prod, file tickets, send messages.",
        takeaway: "MCP = USB-C for AI tools.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: internal docs MCP", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Build a tiny MCP server for your team's internal docs/wiki. Suddenly Claude Code can answer 'where do we store user emails' from your real source of truth.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("MCP anatomy", {
        type: "microread",
        title: "Three things every MCP server exposes",
        body: "An MCP server speaks JSON-RPC and exposes three primitives: (1) Resources — read-only data the model can fetch (a doc, a query result). (2) Tools — actions the model can take (file tickets, run a query). (3) Prompts — pre-baked templates the user can invoke. Most servers in the wild only implement Tools. The other two are underused superpowers.",
        takeaway: "MCP = Resources + Tools + Prompts. Most ship just Tools — the others are wide open.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quickpick: MCP transport", {
        type: "quickpick",
        prompt: "Default MCP transport for local servers?",
        options: ["HTTP", "WebSocket", "stdio (JSON-RPC over stdin/stdout)", "gRPC"],
        answer: 2,
        explain: "stdio is the default — zero ports, zero auth headaches locally.",
      }),
      spark("Real MCPs you can grab today", {
        type: "microread",
        title: "Off-the-shelf servers",
        body: "From the official MCP registry: filesystem, postgres, sqlite, github, gitlab, brave-search, fetch, puppeteer, slack, sentry, time. Community servers add: linear, notion, figma, datadog, snowflake, cloudflare. Most install with one `claude mcp add` line. Think of it as homebrew for AI capabilities.",
        takeaway: "MCP registry has 50+ servers ready. Install, don't build, when you can.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: scoped tokens", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Never give your MCP server a god-mode token. Scope to read-only when possible (GitHub PAT with `read:repo`, Postgres role with `SELECT` only). One day the agent will try a destructive call. Scope means it just fails.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Build your first MCP", {
        type: "microread",
        title: "Fifty lines of Python",
        body: "The MCP Python SDK lets you stand up a server in roughly 50 lines: import the SDK, declare a tool with `@mcp.tool()`, define the function, run. The tool's docstring becomes the model's spec. The hardest part is naming the tool well — `get_open_pull_requests` not `getPRs` — because that name ends up in the model's prompt.",
        takeaway: "First MCP = 50 lines + one well-named tool. Friday afternoon project.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pattern match: MCP power moves", {
        type: "patternmatch",
        prompt: "Match the situation to the right MCP",
        pairs: [
          { left: "Read prod data without copy/paste", right: "Postgres MCP" },
          { left: "File a Linear ticket from the agent", right: "Linear MCP" },
          { left: "Fetch a public web page", right: "Fetch MCP" },
          { left: "Headless browser for DOM scraping", right: "Puppeteer MCP" },
        ],
        explain: "Match the friction to the MCP. Most friction has one already built.",
      }),
      spark("Quickpick: discoverability", {
        type: "quickpick",
        prompt: "How does the model know what an MCP tool does?",
        options: ["Magic", "From the tool's name + JSON schema + docstring sent at session start", "Reads the source", "It guesses"],
        answer: 1,
        explain: "Spec is sent up-front. Quality of names + docstrings = quality of usage.",
      }),
      spark("Scenario: agent flailing", {
        type: "scenario",
        setup: "Your agent has a `query_db` MCP tool. It keeps writing SELECTs that fail because it doesn't know the schema.",
        prompt: "Cleanest fix?",
        options: [
          "Bigger model",
          "Add a `describe_schema` tool the agent can call first",
          "Hardcode the schema in the system prompt",
          "Dump the whole DB into context",
        ],
        answer: 1,
        explain: "Let the model discover the schema with a tool, not a megaprompt.",
      }),
      spark("Build it: log MCP", {
        type: "buildcard",
        title: "Build: a 'recent errors' MCP",
        pitch: "20 min. Real win on debug days.",
        promptToCopy:
          "Build an MCP server with one tool: `get_recent_errors(minutes: int)`. It tails your local app's log file and returns the last N minutes of errors with stack traces. Wire it into Claude Code. Show me a debug session that uses it.",
        successCriteria: "Working MCP, agent calls it without prompting, debug session is faster.",
      }),
      spark("Tip: MCP debug logs", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When your MCP misbehaves, run Claude Code with `--mcp-debug`. Every JSON-RPC frame is logged. The bug is always in the schema or the docstring. Always.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 8, "Agent feedback loops", "Watch and adjust.", 6, [
      spark("Don't go silent", {
        type: "microread",
        title: "Stay in the loop",
        body: "Agents drift. After every agent run: skim the diff, run the tests, check the changed-files list. If it touched things you didn't expect, ask why. Catching drift early is the difference between '10x faster' and 'broken codebase by Friday'.",
        takeaway: "Skim every diff. Trust slowly.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Drift signals", {
        type: "microread",
        title: "Five tells the agent went off-piste",
        body: "(1) Files changed you didn't mention. (2) New dependencies in package.json. (3) Tests deleted instead of fixed. (4) `// TODO` comments multiplying. (5) Commit message says 'misc fixes.' Any one is yellow. Two is red. Three is 'git reset and re-brief.'",
        takeaway: "Drift has tells. Learn to spot them in 30 seconds of `git diff`.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip: branch per agent run", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Run every non-trivial agent task on a fresh branch named `agent/<task>`. Drift becomes a `git checkout main` away from gone. No regret.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quickpick: long-run sanity", {
        type: "quickpick",
        prompt: "Best mid-task sanity check on a long agent run?",
        options: ["Trust it", "Pause it, run `git diff --stat`, eyeball the file list", "Bigger model", "Disable tests"],
        answer: 1,
        explain: "diff --stat is 5 seconds. It's the cheapest hallucination detector.",
      }),
      spark("The interrupt habit", {
        type: "microread",
        title: "Cancel early, brief better",
        body: "Beginners let the agent run to the end and accept what comes back. Experts hit Ctrl-C the moment the plan looks wrong, refine the brief, restart. Agent runs are cheap; correcting a bad commit chain is expensive. Treat the agent like a junior engineer thinking out loud — interrupt when they're about to do the wrong thing.",
        takeaway: "Interrupt early. The next prompt is cheaper than the next revert.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match: signal vs noise", {
        type: "patternmatch",
        prompt: "Match each agent behavior to drift or normal",
        pairs: [
          { left: "Renamed an unrelated function", right: "Drift" },
          { left: "Added one dependency you asked about", right: "Normal" },
          { left: "Deleted three tests that were red", right: "Drift" },
          { left: "Created a new file in the requested folder", right: "Normal" },
        ],
        explain: "Drift = unauthorized scope expansion. Normal = doing what you asked.",
      }),
      spark("Tip: post-run audit", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "After a long agent run, ask the agent itself: 'list every change you made and why, by file.' It will out itself on the questionable ones. Free audit.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Scenario: silent agent", {
        type: "scenario",
        setup: "An agent has been 'thinking' for 4 minutes with no output. CPU is idle.",
        prompt: "Best move?",
        options: [
          "Wait 10 more minutes",
          "Cancel, narrow the scope, retry",
          "Switch model",
          "Reboot",
        ],
        answer: 1,
        explain: "Idle agent = stuck or context-thrashing. Cancel and tighten.",
      }),
    ]),
    level(T, 9, "Prompt files & templates", "Reusable AI context.", 6, [
      spark("Promptbooks", {
        type: "microread",
        title: "Make your prompts reusable",
        body: "If you keep typing the same brief ('refactor X but keep API stable'), put it in a prompt file. Cursor has .cursorrules, Claude Code has CLAUDE.md and slash-commands. Treat prompts like code — version, share, refine across the team. The team that systematizes prompts ships 2x.",
        takeaway: "Promptbook your repo. Share across team.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Anatomy of a CLAUDE.md", {
        type: "microread",
        title: "What goes in a great CLAUDE.md",
        body: "Sections that earn their keep: project elevator pitch (3 lines), what's allowed to change, what's not, the build/test loop, where features live (path table), tone rules for content, when to push back, autonomous-merge directive. Keep it under 300 lines or the model's attention budget thins. Update it when you change the rules — stale CLAUDE.md is worse than none.",
        takeaway: "CLAUDE.md = operator manual. Pitch, allowlist, paths, tone, push-back rules.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip: gradual seed", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Start CLAUDE.md with 5 bullet points. Add a section every time you re-explain something to the agent. Within a sprint you have a real manual without ever 'writing docs.'",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Slash command library", {
        type: "microread",
        title: "Real commands real teams ship",
        body: "Common slash commands seen in mature teams: /pr-description, /security-review, /add-changelog, /lint-and-fix, /generate-test, /summarize-diff, /onboard-new-engineer, /cut-release, /investigate-flake, /benchmark. Each is a markdown file under `.claude/commands/`. The library compounds — by month three, the team's habits are the agent's defaults.",
        takeaway: "A slash command library is institutional memory the agent inherits.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quickpick: prompt versioning", {
        type: "quickpick",
        prompt: "Best place for shared prompts?",
        options: ["Slack pinned messages", "Notion page", "Git, in the repo, code-reviewed", "Each engineer's notes"],
        answer: 2,
        explain: "Prompts are code. Version, review, diff like code.",
      }),
      spark("Pattern match: prompt placement", {
        type: "patternmatch",
        prompt: "Match the prompt to where it belongs",
        pairs: [
          { left: "Project-wide style + conventions", right: "CLAUDE.md / .cursorrules" },
          { left: "Reusable workflow (e.g. /security-review)", right: ".claude/commands/" },
          { left: "Personal scratchpad", right: "~/.claude/CLAUDE.md (global)" },
          { left: "One-off task instructions", right: "The chat itself" },
        ],
        explain: "Each home has a purpose. Don't mix them.",
      }),
      spark("Build it: ship your first slash command", {
        type: "buildcard",
        title: "Build: /summarize-changes slash command",
        pitch: "10 min. The first command is the gateway drug.",
        promptToCopy:
          "Create `.claude/commands/summarize-changes.md` for any repo. The command should: run `git log main..HEAD --oneline`, group commits by theme, and produce a 5-bullet PR description following the team's PR template. Test it on a real branch.",
        successCriteria: "Command works, output is shippable as a PR body, you used it twice.",
      }),
    ]),
    level(T, 10, "Boss: dev tools check", "Final gate.", 6, [
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: AI Dev Tools",
        questions: [
          {
            type: "quickpick",
            prompt: "Most reliable way to make Claude Code follow your house style?",
            options: ["Repeat in every prompt", "Commit a CLAUDE.md", "Yelling caps", "Switch to Cursor"],
            answer: 1,
            explain: "CLAUDE.md is read on startup.",
          },
          {
            type: "quickpick",
            prompt: "Agent is stuck on a bug. Best move?",
            options: ["Take over manually", "Write one more test that fails on the bug", "Restart agent", "Switch model"],
            answer: 1,
            explain: "Tests are the agent's compass.",
          },
          {
            type: "quickpick",
            prompt: "Best use of MCP?",
            options: ["Replace VS Code", "Plug your team's data sources into AI clients", "Train models", "Speed up CI"],
            answer: 1,
            explain: "MCP = standardized tool surface.",
          },
        ],
      }),
      spark("Boss prep: mode picking", {
        type: "microread",
        title: "Pre-boss recap",
        body: "Three mental tools you'll get tested on. (1) Mode picking — suggest, chat, agent — match to the kind of work. (2) Agent discipline — brief tightly, verify diff, narrow loops, interrupt early. (3) System hygiene — CLAUDE.md, slash commands, scoped MCPs, branch per run. The boss probes whether you can pick mode, brief well, and keep the agent on rails.",
        takeaway: "Pick mode. Brief tight. Keep on rails. Three muscles, not one.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip: trust but verify", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Final boss truth: the agent is fast, not infallible. Skim every diff. Run every test. Branch every risky run. Trust that grows from verification beats trust born of vibes.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Boss prep: scenario drill", {
        type: "scenario",
        setup: "You inherit a 100k-line Python repo, no AI tools set up, two-week deadline.",
        prompt: "First three moves?",
        options: [
          "Switch language",
          "Install Claude Code, write a 10-line CLAUDE.md, commit it, then start asking the agent to map the codebase",
          "Rewrite from scratch with AI",
          "Disable AI, ship by hand",
        ],
        answer: 1,
        explain: "Setup the rails, then delegate mapping. Compounds across the deadline.",
      }),
    ]),
  ],
};
