import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "ai-foundations" as const;

export const aiFoundations: Topic = {
  id: T,
  name: "AI Foundations",
  emoji: "🧠",
  tagline: "What AI is, how it learns, and why it works (or doesn't).",
  color: "#7c5cff",
  visual: "neural",
  levels: [
    level(T, 1, "What is AI, really?", "Build a working mental model of AI.", 5, [
      spark("AI is pattern, not magic", {
        type: "microread",
        title: "AI is pattern, not magic",
        body: "AI is software that learns patterns from examples instead of being told the rules. Show it 100,000 cat photos labeled 'cat' and it learns the statistical fingerprint of 'cat'. New photo arrives — it scores how cat-like it looks. That's it. No spark of consciousness. The 'magic' is scale: huge datasets, huge models, and clever math (gradient descent) that nudges billions of knobs until the predictions get good.",
        takeaway: "AI = learned patterns at scale, not programmed rules.",
        bodyByAgeBand: {
          // Sprint #2 seed — proves the kid-voice rules from
          // docs/content-freshness.md §4 work. Same takeaway, simpler
          // language and examples (Pokémon vs cat photos), no companies.
          kid: "AI is just a computer that gets really good at noticing patterns. Imagine you show it 100,000 pictures and tell it which ones are Pokémon and which aren't. After enough examples, it can guess on a new picture all by itself. Nobody had to write rules like 'if it has a tail, it might be Pikachu' — it figured that out by looking. The 'AI' part isn't magic. It's *practice at scale*.",
          teen: "AI is software that learns patterns from examples, not from rules someone typed. Feed it 100,000 photos of cats and it builds its own fingerprint for what cat-shaped looks like. Then it can score a new photo without anyone teaching it edges, whiskers, or fur. The 'intelligence' is really pattern-matching at huge scale — billions of tiny dials nudged until the guesses get better.",
        },
        category: "principle",
        addedAt: "2026-04-15",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "What does an AI model do at its core?",
        options: [
          "Follows hand-coded rules a human wrote",
          "Predicts an output from patterns it learned",
          "Searches the internet in real time",
          "Stores answers in a giant lookup table",
        ],
        answer: 1,
        explain: "Models predict; they don't store rules. Patterns + math = prediction.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When an AI surprises you, ask: 'what pattern in the training data would explain this?' That single question demystifies most weird outputs.",
        bonusXP: 5,
        category: "principle",
        addedAt: "2025-10-01",
      }),
      // Sprint #2 seed — YouTube source-anchored Spark. Pilot content
      // per docs/content-freshness.md §7. Marked SEED — a human must
      // verify the video URL + timestamp + exact quote before public
      // ship. The pattern is the deliverable here, not the specific
      // attribution.
      spark("3Blue1Brown: why attention works", {
        type: "youtubenugget",
        quote:
          "Attention is doing something deceptively simple. Each token asks every other token a question, gets an answer weighted by relevance, and updates its own meaning. The magic isn't the math — it's that the questions and answers are themselves learned.",
        takeaway: "Attention is *learned* questions and answers between tokens, not just weighted averaging.",
        source: {
          platform: "youtube",
          videoUrl: "https://www.youtube.com/@3blue1brown", // SEED — VERIFY: replace with actual video URL
          videoTitle: "Attention, Revisited",
          channelName: "3Blue1Brown",
          publishedAt: "2026-04-11",
          durationMinutes: 24,
          timestamp: "08:55",
        },
        category: "principle",
        addedAt: "2026-05-01",
      }),
      spark("Match the type", {
        type: "patternmatch",
        prompt: "Match each AI flavor to what it does",
        pairs: [
          { left: "Classifier", right: "Picks a label" },
          { left: "Regressor", right: "Predicts a number" },
          { left: "Generator", right: "Creates new content" },
          { left: "Recommender", right: "Suggests next item" },
        ],
        explain: "Most products combine 2–3 of these.",
      }),
      spark("Three breakthroughs that made modern AI", {
        type: "microread",
        title: "Three things had to line up",
        body: "Modern AI didn't fall from the sky. Three curves crossed: (1) the Transformer paper in 2017 gave us an architecture that scaled. (2) GPUs got cheap enough that training on billions of examples was a Tuesday, not a moonshot. (3) the open web gave us a free, messy, planet-scale corpus. Take any one away and Claude, Gemini, Llama don't exist. The lesson: breakthroughs ride on three or four prerequisites you forget to celebrate.",
        takeaway: "Modern AI = Transformers + cheap GPUs + the open web.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("AI vs ML vs deep learning", {
        type: "microread",
        title: "Three nested circles",
        body: "AI is the broadest goal: 'machines that act intelligent'. Machine Learning is the subset where the machine learns from data instead of hand-coded rules. Deep Learning is the subset of ML that uses neural networks with many layers — what powers modern chatbots and image generators. When someone says 'I built an AI app', they almost always mean 'I called a deep-learning model via an API'. Knowing the nesting saves you from being snowed by jargon.",
        takeaway: "Deep learning ⊂ ML ⊂ AI. Most products today live in the innermost circle.",
        bodyByAgeBand: {
          kid: "Three words that get mixed up: AI, machine learning, and deep learning. AI is the big idea — computers that act smart. Machine learning is one way to do AI: instead of telling the computer the rules, you show it lots of examples until it figures them out. Deep learning is one *kind* of machine learning, using big stacks of math called neural networks. Picture three circles, each inside the next.",
          teen: "AI is the big umbrella: machines doing smart-looking things. Machine learning is one way to get there — instead of writing rules, you show the model examples and let it figure things out. Deep learning is the slice of machine learning that uses big neural networks with lots of layers. Almost every modern AI product (Claude, ChatGPT, image generators) is deep learning. Three nested circles, smallest at the centre.",
        },
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Why people anthropomorphize AI", {
        type: "microread",
        title: "It talks like a human, so we project",
        body: "ChatGPT writes 'I think...' and our brains fill in a thinker. There isn't one. The model has no memory between calls, no goals, no preferences except those baked into its training. Anthropomorphizing is harmless when you're chatting; dangerous when you're shipping product. If you assume the model 'wants' to help, you stop checking its output. Treat it like a very fast, slightly drunk intern who's read everything and remembers nothing.",
        takeaway: "It sounds like a person. It isn't. Don't outsource trust.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("A model is a frozen brain", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Once trained, a model's weights don't change. Every conversation starts from zero — anything it 'remembers' was either in your prompt or fetched from a tool. Build with that in mind.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pick the AI flavor", {
        type: "quickpick",
        prompt: "You want to detect spam emails. Which type fits best?",
        options: [
          "Generative model — write the spam policy",
          "Classifier — label each email spam or not",
          "Recommender — suggest emails to read",
          "Diffusion model — denoise the inbox",
        ],
        answer: 1,
        explain: "Spam detection is a label-picking job. Classifiers are the right tool — small, fast, cheap.",
      }),
      spark("The 'AI winter' hangover", {
        type: "microread",
        title: "AI has crashed before",
        body: "We're in the third AI boom. The first (1950s–60s) collapsed when symbolic AI hit a wall. The second (1980s expert systems) collapsed when hand-written rules couldn't scale. Researchers who lived through 'AI winters' are professionally skeptical for a reason. The current boom looks different — products people pay for, capabilities that improve every six months — but pattern-recognize the past. Hype always overshoots. The work that survives the next winter is what you bet on.",
        takeaway: "Bet on what survives a hype crash, not what fuels one.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Narrow vs general AI", {
        type: "quickpick",
        prompt: "Today's GPT, Claude, Gemini are best described as:",
        options: [
          "Artificial General Intelligence (AGI) — they think like humans",
          "Narrow AI — very good at language tasks, not at everything",
          "Superintelligence — smarter than humans across the board",
          "Symbolic AI — they reason from explicit rules",
        ],
        answer: 1,
        explain: "Frontier LLMs are very capable narrow AI: language is their domain. They're not AGI yet, despite what marketing says.",
      }),
      spark("The November 2025 inflection", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "In November we had what I call the inflection point where GPT 5.1 and Claude Opus 4.5 came along. Previously you had to pay very close attention. Suddenly we went from that to almost all of the time it does what you told it to do.",
        takeaway:
          "Late-2025 was the year coding agents crossed from experimental to reliable. If you tried agents in summer 2025 and bounced — try again, the floor has moved.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Simon Willison",
          guestRole: "co-creator of Django, coined 'prompt injection'",
          episodeTitle: "The November inflection: AI coding crosses the threshold",
          timestamp: "00:04:23",
        },
      }),
      spark("Build it: predict your own next word", {
        type: "buildcard",
        title: "Build: a 30-line next-token predictor",
        pitch: "Feel how AI works from the inside in 15 minutes.",
        promptToCopy:
          "In Python, build a tiny next-token predictor: load a small text file (Shakespeare, your old emails), count which words follow which, and given a starting word, sample the next word weighted by frequency. Run 50 times to generate a sentence. No ML libraries — just dicts.",
        successCriteria: "You generate Shakespeare-flavored gibberish. You also internalize that LLMs are this idea, with billions more parameters.",
      }),
      spark("Why models are 'foundation models'", {
        type: "microread",
        title: "One brain, many uses",
        body: "Old AI: one model per task — a spam classifier here, a translation model there, a fraud detector somewhere else. Modern AI: one giant 'foundation model' (Claude, GPT-5, Gemini, Llama) that can do hundreds of tasks via prompting. The shift matters because: (1) you don't need labeled data per task, (2) capabilities transfer between tasks, (3) the same model gets better in many places at once. The label 'foundation' was coined by Stanford in 2021 and stuck.",
        takeaway: "Foundation models = one generalist that beats most specialists. The default architecture of modern AI.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When trying out AI, start with the question 'what's the best free generalist I can use today?' rather than 'which specialized model fits this task?' — usually the generalist wins, and you'll save weeks.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pick the boom", {
        type: "patternmatch",
        prompt: "Match each AI era to its defining bet",
        pairs: [
          { left: "1950s–60s symbolic AI", right: "Hand-coded rules" },
          { left: "1980s expert systems", right: "Knowledge bases of facts" },
          { left: "2010s deep learning", right: "Neural networks + GPUs" },
          { left: "2020s foundation models", right: "Pre-train one giant model, prompt it for everything" },
        ],
        explain: "Each era was the previous one's heresy. 'Just predict the next token' would have sounded silly in 1985.",
      }),
      spark("Anatomy of a 'large' language model", {
        type: "microread",
        title: "Layers, parameters, attention",
        body: "An LLM under the hood is a stack of repeated blocks called Transformer layers. Each layer has self-attention (tokens compare themselves to other tokens) and a feedforward network (each token gets crunched through math). Stack 80–100 of these layers, fill them with 70–500 billion learnable numbers (parameters), and you get a frontier model. The numbers are the only thing that gets trained. The architecture has barely changed since 2017.",
        takeaway: "An LLM is repeated Transformer blocks. The parameters are what gets trained.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When a paper or post says '70B model', the B is billions of parameters. Llama 3 405B has 405 billion. Bigger is sometimes better, often slower, always more expensive — never assume bigger means smarter for your task.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("AI literally reads probabilities", {
        type: "quickpick",
        prompt: "When an LLM outputs the word 'cat', what is it doing?",
        options: [
          "Looking 'cat' up in a database",
          "Sampling from a probability distribution over tens of thousands of tokens",
          "Translating from a binary representation",
          "Picking the word with the highest temperature",
        ],
        answer: 1,
        explain: "Every output token is sampled from a probability distribution. Temperature changes the shape of that distribution; it's not the picker.",
      }),
    ]),
    level(T, 2, "Training vs Inference", "Tell apart the two phases that matter.", 4, [
      spark("Two-phase life", {
        type: "microread",
        title: "Train once, infer forever",
        body: "Training is the slow, expensive phase: feed the model billions of examples and adjust its weights. It costs millions and takes weeks. Inference is what happens every time you call the model — it just runs the math on your input. Inference is cheap (milliseconds) but you do it billions of times. Almost all production cost lives in inference, not training. That's why latency, batching, and model size matter so much.",
        takeaway: "Training shapes the brain once. Inference uses it constantly.",
        bodyByAgeBand: {
          kid: "AI has two stages, like learning a sport. Training is practice — slow, hard, takes weeks, and you only do it once. The model studies billions of examples until it gets good. Inference is the actual game — quick, easy, you do it every time someone asks the AI a question. Practice is rare and expensive. Playing the game happens a million times a day. That's why making each game faster matters way more than making practice fancier.",
          teen: "AI has two phases. Training is the slow, expensive part: show the model billions of examples and adjust its weights until predictions get good. That takes weeks and costs millions. Inference is what happens every time you ask it something — it just runs the math on your input in milliseconds. Training happens rarely. Inference happens constantly. So almost all the cost (and engineering attention) goes into making each inference faster, smaller, and cheaper.",
        },
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Where does cost hide?", {
        type: "quickpick",
        prompt: "For a popular AI app, which usually costs more over a year?",
        options: ["Training the model", "Storing the model", "Running inference", "The website hosting"],
        answer: 2,
        explain: "Inference scales with users. Training is a one-time (or rare) hit.",
      }),
      spark("Fill the stack", {
        type: "fillstack",
        prompt: "When you call an AI API, you are paying for ___.",
        options: ["training", "inference", "fine-tuning", "labeling"],
        answer: 1,
        explain: "Each API call is one inference run.",
      }),
      spark("What pre-training actually does", {
        type: "microread",
        title: "Predict the next word, a trillion times",
        body: "Pre-training a base model is shockingly simple as an objective: read a huge chunk of text, hide the next word, ask the model to guess it, nudge the weights based on how wrong it was. Repeat across the internet, billions of times. Out of that boring task — next-token prediction — emerge syntax, world knowledge, code, multilingual fluency, and the seeds of reasoning. A simple loss function plus enormous scale produces shocking emergent behavior.",
        takeaway: "Pre-training is one task — predict the next token — repeated at planet scale.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Three flavors of post-training", {
        type: "microread",
        title: "Base models are weird; post-training fixes that",
        body: "A raw base model trained only on next-token prediction will happily complete 'How do I make a bomb?' verbatim. Post-training shapes it for product use: (1) Supervised fine-tuning — show it good examples of being helpful. (2) RLHF — humans rate its outputs, the model learns to favor good ones. (3) Constitutional AI — Anthropic's twist: written principles the model checks itself against. Stack them and you get Claude, ChatGPT, Gemini.",
        takeaway: "Base model = raw clay. SFT + RLHF + constitution = the assistant you ship.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Inference cost in real numbers", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Claude Sonnet 4.6 runs about $3/M input tokens, $15/M output. Output is 5× input — design prompts that force short answers and you cut your bill more than any infra change.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Why GPUs (and now TPUs)", {
        type: "microread",
        title: "Matrix multiplication, all the way down",
        body: "Training and inference both reduce to one operation done a billion times: multiply a vector by a matrix. CPUs do this serially — slow. GPUs are arrays of tiny cores that do thousands of multiplies in parallel — fast. Google's TPUs go further: chips designed only for matrix math. Nvidia's H100 and B100 dominate today not because they're 'better at AI' but because their hardware lines up exactly with what Transformers need.",
        takeaway: "AI scales because GPUs and TPUs do parallel matrix math at a speed CPUs can't touch.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Latency is a product feature", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Time-to-first-token under 500ms feels alive; over 2s feels broken. Stream responses token-by-token from day one — perceived speed beats any backend optimization.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Order the stages", {
        type: "patternmatch",
        prompt: "Match each phase to what it produces",
        pairs: [
          { left: "Pre-training", right: "Base model that completes text" },
          { left: "SFT", right: "Model that follows instructions" },
          { left: "RLHF / RLAIF", right: "Model whose taste matches humans" },
          { left: "Inference", right: "An answer for one user request" },
        ],
        explain: "Three training stages, then a lifetime of inference. Each stage builds on the last.",
      }),
      spark("Distillation: the teacher-student trick", {
        type: "microread",
        title: "Big model teaches small model",
        body: "Distillation is how you get a tiny model that punches like a big one: train the small student to mimic the big teacher's output distribution, not just hard labels. Anthropic's Haiku family, Google's Gemini Flash, Meta's Llama Guard — all distilled from larger siblings. The student keeps most of the teacher's quality at 5–20% of the parameters. If you ever fine-tune a small open-source model, you're probably distilling from a big closed one.",
        takeaway: "Distillation = small model trained to mimic a big one. Most fast, cheap models are distilled.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Inference latency is dominated by output length, not input. A 5,000-token prompt + 50-token answer is faster than a 500-token prompt + 1,000-token answer. Cap output token budgets ruthlessly.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 3, "Data: the real moat", "Why data quality beats model size.", 4, [
      spark("Garbage in, garbage out", {
        type: "microread",
        title: "Data is the model",
        body: "Two teams use the exact same model architecture. Team A trains on a noisy scrape; team B curates 100k high-signal examples and dedupes carefully. Team B wins, often by a landslide. Modern AI proved a hard truth: cleaner, more diverse data beats more parameters. That's why frontier labs spend nine figures on data labeling, and why your fine-tune lives or dies by the 200 examples you hand-pick.",
        takeaway: "Better data > bigger model. Almost always.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Before fine-tuning, hand-write 50 ideal input/output pairs yourself. If you can't write 50 good ones, the task isn't ready for AI yet — clarify it first.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Your demo model hallucinates customer names half the time. Your boss says 'just train a bigger model'.",
        prompt: "Best first move?",
        options: [
          "Switch to a 10x bigger base model",
          "Audit and clean the training data first",
          "Add more GPUs to inference",
          "Lower the temperature to 0",
        ],
        answer: 1,
        explain: "Hallucinations almost always trace back to data gaps. Bigger model just hallucinates more confidently.",
      }),
      spark("The data flywheel", {
        type: "microread",
        title: "The product is the data factory",
        body: "Every great AI product secretly runs a data flywheel: users use the product → the product captures examples of correct behavior → those examples train the next model → that model is better → more users come. Tesla's Autopilot, GitHub Copilot, ChatGPT — same loop. If you're building, ask: what user action becomes a training example? If the answer is 'nothing', you don't have a flywheel. You have a one-shot product.",
        takeaway: "If user actions don't become training data, you don't have a flywheel.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Synthetic data: real or hype?", {
        type: "microread",
        title: "Models that train on their own outputs",
        body: "Frontier labs increasingly use synthetic data — text generated by a strong model and used to train another. It works for tasks where the strong model has the answer (math, code, structured extraction). It fails when the synthetic distribution drifts from reality, causing 'model collapse'. Anthropic's Claude was trained partly on Claude-generated data; DeepSeek R1's reasoning traces became training fuel for the next round. Use synthetic data with a real-data anchor.",
        takeaway: "Synthetic data scales the easy parts. Real data still anchors the hard parts.",
        category: "frontier",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Before fine-tuning, run a deduplication pass on your training set — even MinHash on text. Duplicates inflate confidence, distort eval scores, and waste training compute.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Data leakage trap", {
        type: "scenario",
        setup: "Your model crushes your test set: 95% accuracy. In production it gets 60%. Eval logs are fine.",
        prompt: "Most likely cause?",
        options: [
          "Production users are dumber than test cases",
          "Data leakage — your test cases bled into training",
          "Inference is non-deterministic",
          "GPU drift over time",
        ],
        answer: 1,
        explain: "Classic data leakage. Production-mirror test sets are sacred — never let them touch training, even by accident through scraping.",
      }),
      spark("Labeled vs unlabeled data", {
        type: "microread",
        title: "Labels are expensive; raw text is free",
        body: "Two flavors of training data. Labeled: input + correct answer (cat photo + 'cat'). Expensive — humans had to label it. Unlabeled: just the input (the entire web). Cheap — just scrape it. Pre-training uses unlabeled data with a self-supervised trick (predict the next word). Fine-tuning uses small amounts of labeled data to specialize. The economics: pre-train on free unlabeled web, fine-tune on expensive labels. That's why frontier labs have data labeling teams in the hundreds.",
        takeaway: "Free unlabeled web for pre-training. Expensive labels for fine-tuning. Both are necessary.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When your AI feature underperforms, don't reach for a bigger model — reach for 50 more hand-labeled examples. Data wins almost every fight against architecture.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("The chinchilla scaling law, briefly", {
        type: "microread",
        title: "Tokens beat parameters",
        body: "DeepMind's 2022 'Chinchilla' paper showed something counterintuitive: most large models had been under-trained — too many parameters, not enough tokens of training data. The optimal ratio was roughly 20 tokens per parameter. The lesson rippled through the industry: Llama 3 405B saw 15+ trillion training tokens. Modern frontier labs train smaller models on far more data. Quality emerges from data volume × quality, not just from parameter count.",
        takeaway: "Optimal model size isn't 'as big as possible'. Tokens-per-parameter matters as much as raw size.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Where do labels come from?", {
        type: "patternmatch",
        prompt: "Match the labeling source to its strength",
        pairs: [
          { left: "Internal experts", right: "Best for niche / regulated domains" },
          { left: "Crowdworkers (Surge, Scale)", right: "Best for scale on general tasks" },
          { left: "User feedback (👍 / 👎)", right: "Free, zero-friction, naturally distributed" },
          { left: "LLM-as-labeler", right: "Cheap pre-labeling — but verify before training" },
        ],
        explain: "Most labeled-data pipelines mix all four. Pick by trust requirement, scale, and cost.",
      }),
    ]),
    level(T, 4, "Bias and limits", "What AI struggles with — and why.", 4, [
      spark("Mirrors of the data", {
        type: "microread",
        title: "Bias isn't a bug — it's the data",
        body: "If 80% of your hiring data shows men in engineering roles, the model learns 'male = engineer'. It's not malicious; it's statistical. AI inherits every skew, gap, and stereotype baked into its training corpus. The fix isn't a clever algorithm — it's curating the data, evaluating against fairness slices, and being honest about what your model can't do well.",
        takeaway: "Models reflect their data. Audit the data, not just the output.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Why does an AI model sometimes seem biased?",
        options: [
          "It has its own opinions",
          "It learned patterns from skewed data",
          "Its compiler is broken",
          "Random number generators",
        ],
        answer: 1,
        explain: "Skewed data → skewed predictions. Always.",
      }),
      spark("Align before superintelligence", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "Once we get to superintelligence, it will be too late to align the models. My best granularity forecast for could we have an X-risk or extremely bad outcome is somewhere between 0 and 10%.",
        takeaway:
          "Alignment work is a now problem, not a future one. The window to bake values into a system closes the moment that system gets smarter than you.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Benjamin Mann",
          guestRole: "co-founder of Anthropic",
          episodeTitle: "Inside Anthropic — alignment, scaling, AGI timelines",
          timestamp: "00:00:32",
        },
      }),
      spark("Hallucination in one sentence", {
        type: "microread",
        title: "It's filling a gap, confidently",
        body: "Hallucination isn't a bug — it's the model doing its job in places where it has no ground truth. Trained to predict 'the most likely next token', when no good answer is in its weights, it invents one that *sounds* right. Fixes: ground it in real documents (RAG), let it say 'I don't know' (fine-tune for refusal), or check its output against a database (verifier model). Don't blame the model; blame the lack of ground truth.",
        takeaway: "Hallucination = confident prediction without ground truth. Fix the ground, not the model.",
        bodyByAgeBand: {
          kid: "When AI 'hallucinates', it makes something up that *sounds* right. It's not lying on purpose — it doesn't know what's true. It's just guessing the next word, and sometimes the guess looks like a fact. The trick is to give it real notes (like a textbook) to look at, or let it say 'I don't know' instead of guessing.",
          teen: "AI hallucination is the model inventing a plausible-sounding fact when it has no real answer. It's not lying — it's a next-token predictor doing its job in a place where no good answer exists. The fix is to give it real source documents to look at (RAG), train it to say 'I don't know', or check its answer against a database before showing the user.",
        },
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Run your model on a 'fairness slice' — same prompt, different demographics swapped in. If the answer changes for reasons it shouldn't, you've found a bias to document, not a feature to ship.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("The model can't math", {
        type: "microread",
        title: "Why GPT-4 fails at 17 × 24",
        body: "LLMs are trained on text, not arithmetic. They predict tokens that *look* like the answer. Multi-digit math is a worst case: every wrong digit cascades. Modern fixes: give the model a calculator tool (function calling), let it 'think step by step' (chain of thought), or ship a reasoning model (Opus 4.7, o3) that's trained to write out scratch work. If your product depends on real math, plug in a real math tool — don't trust the LLM to do it in its head.",
        takeaway: "LLMs don't compute. Hand them a calculator, or a reasoning chain.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Knowledge cutoff", {
        type: "microread",
        title: "The model's clock stopped",
        body: "Every base model has a knowledge cutoff — the last date its training data was scraped. Claude Sonnet 4.6's cutoff is roughly January 2026. After that, the model literally doesn't know what happened. If you ask 'who won the 2026 Super Bowl?' it'll either refuse, or hallucinate. The fix: give the model fresh facts via web search, RAG, or a tool call. Never assume the model knows about anything that happened in the last 6 months.",
        takeaway: "Models freeze at their training cutoff. Anything fresher needs a tool or a doc.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Three things AI still can't do well", {
        type: "microread",
        title: "Honest list of weak spots",
        body: "Even Claude Opus 4.7 stumbles on: (1) novel reasoning across many domains at once — combine biology, finance, and game theory and watch it freeze. (2) consistent counting — ask 'how many R's in strawberry' and it sometimes still misses. (3) calibrated uncertainty — it'll say 'I'm sure' when it shouldn't. The fix isn't waiting for a smarter model. It's building products that route around these failure modes: tools for math, RAG for fresh knowledge, and verifier models for high-stakes outputs.",
        takeaway: "AI's weak spots are predictable. Architect around them; don't wait for them to vanish.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("AI doesn't know it doesn't know", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Models are bad at calibrated uncertainty. Always ask 'how confident are you, on a 1-10 scale, and what would you check?' — then verify the things they list. Trust the verification, not the confidence.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Jailbreaks and refusal", {
        type: "microread",
        title: "Why models refuse — and why some still don't",
        body: "Modern models are post-trained to refuse harmful requests (weapons, illegal advice, hate speech). Refusal is a learned behavior, not a hard wall — adversarial prompts ('jailbreaks') sometimes bypass it. Anthropic's Constitutional AI, OpenAI's spec-based RLHF, Meta's Llama Guard all try to make refusal robust. As a builder, never assume the base model will refuse what you don't want — add your own classifier guard at the input AND output.",
        takeaway: "Refusal is learned, not hard-coded. Always add your own guardrails.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 5, "Generative vs predictive", "Two families, two playbooks.", 4, [
      spark("The split", {
        type: "microread",
        title: "Predict labels vs make stuff",
        body: "Predictive AI says 'is this fraud? yes/no, 0.92 confidence'. Generative AI says 'write me a fraud-alert email in the customer's tone'. Predictive needs labeled data and crisp metrics (accuracy, F1). Generative needs evals and taste — there's no single right answer. Most modern AI products mix both: a generative core wrapped in predictive guardrails (toxicity classifier, PII detector, retrieval relevance scorer).",
        takeaway: "Predictive picks. Generative produces. Real products use both.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Match", {
        type: "patternmatch",
        prompt: "Pair each task with its family",
        pairs: [
          { left: "Spam filter", right: "Predictive" },
          { left: "Email draft", right: "Generative" },
          { left: "Image caption", right: "Generative" },
          { left: "Credit score", right: "Predictive" },
        ],
        explain: "If output is a label/number → predictive. If it's new content → generative.",
      }),
      spark("Diffusion vs autoregressive", {
        type: "microread",
        title: "Two ways to generate",
        body: "Modern generative AI uses two main shapes. Autoregressive: predict one token at a time, left to right (Claude, GPT, Gemini for text). Diffusion: start with pure noise and progressively de-noise it into an image, video, or audio (Stable Diffusion, Sora, Veo). Same goal — generate something coherent — but completely different math. Text was easier to make autoregressive; pixels were easier to make diffusion. Knowing which is which tells you why a model is fast or slow at a given task.",
        takeaway: "Text = autoregressive. Images / video = diffusion. Different generators, different trade-offs.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Wrap a generative LLM with a small predictive classifier on the output: PII detector, toxicity check, JSON validator. Generative produces; predictive guards. That sandwich is most production AI.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pick the right family", {
        type: "scenario",
        setup: "You're shipping a customer-service AI. Two parts: (1) decide if a message needs human escalation, (2) draft a friendly reply if not.",
        prompt: "Best architecture?",
        options: [
          "One generative model handles both",
          "A small classifier for escalation, a generative model for replies",
          "A diffusion model for both",
          "A rule engine, no AI",
        ],
        answer: 1,
        explain: "Predictive picks; generative produces. Save the LLM cost for the part that needs creativity.",
      }),
      spark("Diffusion for text? It's coming", {
        type: "microread",
        title: "Mercury, Inception, and the diffusion-text bet",
        body: "Most text models are autoregressive — one token at a time. Mercury (Inception Labs) is one of the first commercial bets on diffusion-style text generation: parallel denoising of an entire response at once. Wins: enormous speedups (10×+) when latency matters. Losses (so far): quality lags the autoregressive frontier. It's an open question whether diffusion beats autoregression for text the way it beat GANs for images. Watch this space — it could reshape inference economics.",
        takeaway: "Diffusion text models (Mercury) are an open bet. If they hit quality parity, latency economics flip.",
        category: "frontier",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 6, "Embeddings 101", "Turning meaning into math.", 5, [
      spark("Vectors of meaning", {
        type: "microread",
        title: "Words as coordinates",
        body: "An embedding turns text (or images, audio) into a list of numbers — a vector — where similar things land near each other in space. 'King' and 'queen' end up close. 'King' minus 'man' plus 'woman' lands near 'queen'. This is the trick behind semantic search, recommendations, deduplication, RAG, and most 'AI search' you see today. The model doesn't 'know' meaning — it just learned to place related things nearby.",
        takeaway: "Embeddings = meaning encoded as nearby points in space.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Cosine similarity > 0.85 usually means 'very related'. Below 0.5 means 'probably unrelated'. Tune this threshold per use case — it's the most under-tuned dial in RAG systems.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "What's the main use of embeddings?",
        options: [
          "To compress images for faster loading",
          "To represent meaning so you can compare things mathematically",
          "To translate code between languages",
          "To encrypt data",
        ],
        answer: 1,
        explain: "Embeddings power semantic similarity — the heart of search and RAG.",
      }),
      spark("Build it", {
        type: "buildcard",
        title: "Build: tiny semantic search",
        pitch: "20 lines. You'll feel why embeddings are magic.",
        promptToCopy:
          "Build a tiny CLI tool in Python that takes a folder of .txt files, embeds each one with a free model (sentence-transformers/all-MiniLM-L6-v2), and lets me search them with natural language. Show top 3 matches with cosine similarity scores.",
        successCriteria: "You can ask 'documents about pricing' and get the right files even if 'pricing' isn't in them.",
      }),
      spark("Why dimensions matter", {
        type: "microread",
        title: "More dimensions ≠ always better",
        body: "An embedding is a vector — a list of numbers. Older models gave you 384 dimensions; OpenAI's text-embedding-3-large hands you 3072. More dimensions can capture more nuance, but they cost more to store and search. The pragmatic move: pick a mid-range model (like Cohere's embed-v3 at 1024 dims), test if a smaller one is good enough, and only scale up if your retrieval evals say the bigger model wins. Don't pay 8× to store 8× the floats by default.",
        takeaway: "Pick embedding dimension by eval, not by aspiration. Smaller is often plenty.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("RAG in one sentence", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "RAG = embed your docs, find the closest few to a user's question, paste them into the prompt, ask the model to answer using only those. That's it — the rest is engineering details.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("pgvector vs Pinecone", {
        type: "microread",
        title: "Boring beats exotic",
        body: "pgvector is a Postgres extension — your existing database becomes a vector DB. Pinecone is a hosted, dedicated vector service. For < 10M vectors, pgvector is faster to ship, easier to back up, and you already know SQL. Pinecone wins at very large scale or when you want managed sharding. Most early-stage AI products that switched 'because pgvector won't scale' regretted the migration cost. Default to pgvector. Outgrow it before replacing it.",
        takeaway: "Default to pgvector. Pinecone when scale demands it, not before.",
        category: "tooling",
        addedAt: "2026-05-01",
        vocab: [
          { term: "pgvector", definition: "A Postgres extension that stores embedding vectors and runs nearest-neighbor search inside your existing database." },
          { term: "Pinecone", definition: "A managed, hosted vector database. Pay-per-index, no infra to run." },
        ],
      }),
      spark("Cosine vs Euclidean", {
        type: "quickpick",
        prompt: "When comparing two embeddings, which distance metric is most common in modern AI?",
        options: [
          "Manhattan distance",
          "Cosine similarity",
          "Euclidean distance",
          "Hamming distance",
        ],
        answer: 1,
        explain: "Cosine measures the angle between vectors — robust to magnitude, the de-facto choice for text embeddings.",
      }),
      spark("Embedding drift", {
        type: "scenario",
        setup: "Your search worked great in dev. In prod, results feel 'close but wrong'. You used a different embedding model than at index time.",
        prompt: "Best fix?",
        options: [
          "Adjust cosine threshold up",
          "Re-embed all documents with the production model and rebuild the index",
          "Switch to keyword search",
          "Add a re-ranker",
        ],
        answer: 1,
        explain: "Different embedding models live in different vector spaces. Mixing them is incoherent. Always re-embed.",
      }),
      spark("Hybrid search beats pure RAG", {
        type: "microread",
        title: "Add a keyword channel",
        body: "Pure embedding search is great at semantic match (find docs about pricing) but bad at exact match (find the doc that mentions invoice #12345). Hybrid search runs both: embedding lookup PLUS BM25 keyword search, then merges the rankings. Most production RAG stacks (Anthropic Contextual Retrieval, Cohere Rerank, Pinecone hybrid) do this. Result: 30–50% relevance lift over pure embedding search at near-zero cost.",
        takeaway: "Hybrid search (embeddings + BM25) beats pure RAG for almost free. Wire it.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add a small re-ranker (Cohere Rerank, Voyage Rerank-2) over your top 30 retrieved docs. It's the single biggest quality lever in RAG, and it's a few dollars per million queries.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 7, "Tokens and context", "The unit AI thinks in.", 4, [
      spark("Tokens are slices", {
        type: "microread",
        title: "Tokens, not words",
        body: "AI doesn't see 'unbelievable' as one word — it sees ['un', 'believ', 'able'] or similar chunks called tokens. A token averages ~4 characters in English. Why care? Because pricing, context windows, and latency are all token-based. A 200,000-token context isn't 200,000 words — it's roughly 150,000 words. Fitting your knowledge base in context vs. retrieving slices via RAG is one of the central design choices of any AI product.",
        takeaway: "Think in tokens, not words. Cost and capacity live there.",
        bodyByAgeBand: {
          kid: "AI doesn't read whole words — it reads chunks called tokens. The word 'unbelievable' might split into 'un', 'believ', 'able' — three tokens. A token is about 4 letters on average. Why does it matter? Because everything an AI does is counted in tokens: how much it can read at once, how fast it answers, how much it costs to use. So when grown-ups talk about a '200,000 token window', that's not 200,000 words — it's about 150,000.",
          teen: "AI doesn't see whole words — it sees tokens, which are little chunks of text. 'Unbelievable' splits into 'un', 'believ', 'able' — three tokens. One token is roughly 4 characters in English. This matters because everything is measured in tokens: how much the model can read in one go (its context window), how fast it answers, how much it costs to run. A 200,000-token context window is closer to 150,000 words than 200,000 — and that gap shapes how AI tools are built.",
        },
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Estimate", {
        type: "quickpick",
        prompt: "Roughly how many tokens is a typical English page (~500 words)?",
        options: ["~50", "~250", "~650", "~5,000"],
        answer: 2,
        explain: "1 word ≈ 1.3 tokens in English. So 500 words ≈ 650 tokens.",
      }),
      spark("The context window is a sliding scratchpad", {
        type: "microread",
        title: "Long context isn't free memory",
        body: "Claude Opus 4.7 takes 1M tokens of context. Sounds like infinite memory. It isn't. Performance degrades as you fill the window — middle tokens get less attention than start/end (the 'lost in the middle' problem). Latency and cost both grow roughly with input size. The 1M number unlocks new product shapes (read a whole codebase, a whole book), but for most tasks, retrieving 5–10 relevant snippets via RAG beats stuffing everything in. Big windows are a tool, not a default.",
        takeaway: "1M-token windows enable new shapes. They don't make RAG obsolete.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Put your most important instructions at the START and END of the prompt. The middle gets less attention from the model — a real, measured effect, not a vibe.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tokenizer surprises", {
        type: "microread",
        title: "Some words are tokens; some are syllables",
        body: "Tokenizers are trained on text, so common words like 'the' are one token, but rare words shatter. 'Antidisestablishmentarianism' splits into 6+ tokens. Your name might be 1 token if you're famous, or 5 if you're not. Code, math, and non-English languages tokenize less efficiently than English prose — Claude's Japanese tokenization is roughly 2× more tokens per character than English. The lesson: tokens aren't fair across languages or domains. Budget extra for non-English.",
        takeaway: "Tokenizers favor common English words. Everything else costs more tokens.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Match the count", {
        type: "patternmatch",
        prompt: "Match each chunk of text to its rough token count",
        pairs: [
          { left: "A tweet (~280 chars)", right: "~70 tokens" },
          { left: "A 500-word page", right: "~650 tokens" },
          { left: "A 200-page book", right: "~120,000 tokens" },
          { left: "Claude Opus 4.7's max context", right: "~1,000,000 tokens" },
        ],
        explain: "Rough conversion: 4 chars ≈ 1 token in English. Doubles or triples for code, JSON, non-English.",
      }),
      spark("KV cache, briefly", {
        type: "microread",
        title: "How models stream so fast",
        body: "When a model generates token-by-token, it doesn't re-read the entire prompt for each new token. Instead it caches intermediate computations from prior tokens — the 'KV cache' (keys and values from attention). This is what makes streaming feel fast: each new token is a small additional compute, not a redo. It's also why long contexts cost more memory than time. The KV cache is where prompt caching lives — Anthropic's prompt caching is essentially 'reuse the KV cache for a fixed prefix'.",
        takeaway: "The KV cache makes streaming fast. Prompt caching = reusing it across requests.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When designing prompts, put the static, reusable system prompt first and the dynamic user input last. Caches hit on the static prefix only. Reorder and you'll see the cost difference.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 8, "How models 'reason'", "It's prediction, but staged.", 5, [
      spark("Chain of thought", {
        type: "microread",
        title: "Reasoning is just longer prediction",
        body: "When a model 'reasons', it's not thinking — it's predicting more tokens before committing to an answer. Asking it to 'think step by step' gives it room to lay out scratch work, which dramatically improves accuracy on math, logic, and multi-hop questions. Newer reasoning models (like o-series, Claude with thinking) bake this in: they generate hidden thinking tokens automatically. Same engine, more deliberation.",
        takeaway: "Reasoning = giving the model room to lay out steps before answering.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "On a hard task, just append: 'Think step by step. Show your work.' Free 5-15% accuracy boost on most non-trivial prompts.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Your model gets 70% on a multi-step math benchmark.",
        prompt: "Cheapest way to push it past 80%?",
        options: [
          "Train your own foundation model",
          "Add 'think step by step' and let it expand reasoning",
          "Switch hosting providers",
          "Lower temperature to 0",
        ],
        answer: 1,
        explain: "Prompting for reasoning is the cheapest, fastest accuracy lever you have.",
      }),
      spark("Reasoning models, briefly", {
        type: "microread",
        title: "Models that pay to think",
        body: "OpenAI's o3 and Claude Opus 4.7's extended thinking are 'reasoning models': before answering, they generate hidden thinking tokens — sometimes thousands — that you don't see but pay for. They crush math, coding, planning, and multi-step logic. They're slow (10–60 seconds per answer) and expensive (10–20× the cost of regular Sonnet). Use them for the hard 5% of your tasks; route everything else to fast Haiku-tier models. The router is the architecture; reasoning is just one route.",
        takeaway: "Reasoning models are slow, expensive, and brilliant at hard tasks. Route, don't default.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "If 'think step by step' helps, try giving the model a structured template: 'First identify the goal. Second, list constraints. Third, propose options. Fourth, pick one and justify.' Structure beats freeform.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Self-consistency", {
        type: "microread",
        title: "Run it three times, take the majority",
        body: "On hard problems, ask the model the same question 3–5 times at moderate temperature, then pick the most common answer. Called 'self-consistency'. Boosts math accuracy ~10–20% with no model change — you're just paying for parallel rolls of the dice and trusting the vote. Cheap insurance when correctness matters more than latency. Don't use it for chat; do use it for structured extraction or verification.",
        takeaway: "When stakes are high, run it 3× and take the majority vote.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pick the reasoning lever", {
        type: "quickpick",
        prompt: "Cheapest, fastest accuracy lever for non-trivial tasks?",
        options: [
          "Buy more GPUs",
          "Add 'think step by step' to the prompt",
          "Switch to a different lab's model",
          "Lower temperature",
        ],
        answer: 1,
        explain: "Free, instant, often 5–15% better. Try this before any expensive change.",
      }),
      spark("Tools beat thinking", {
        type: "microread",
        title: "When in doubt, hand it a tool",
        body: "A reasoning model thinking really hard about 17 × 24 will sometimes still get it wrong. A regular model with access to a calculator function gets it right every time. Tool use (function calling, MCP) is the architecture move that beats raw reasoning for any task with a verifiable answer: math, dates, current events, internal data lookups. Spec your tools first; let reasoning fill the gap. Don't ask the model to be smarter than it needs to be.",
        takeaway: "Tools first, reasoning second. Hand the model a calculator before asking it to compute.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Most reasoning models let you set a token budget for thinking. On Claude Opus 4.7, capping thinking at 4k tokens gives 90% of the quality at 30% of the cost on most tasks. Tune this knob.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 9, "Evals: the only ground truth", "Without evals you're flying blind.", 5, [
      spark("Vibes don't ship", {
        type: "microread",
        title: "Evals beat vibes",
        body: "Every team eventually learns the same lesson: 'looks great in demo' ≠ 'works in prod'. Evals are repeatable test sets you score your system against, ideally tied to real user outcomes. Start with 20 hand-crafted hard cases. Score every prompt change against them. When you can't tell whether a change is better, your eval set is too small or too easy. Evals are unsexy. They're also the difference between a toy and a product.",
        takeaway: "Evals are the unit tests of AI. No evals, no progress.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "What's the best first eval set for a new AI feature?",
        options: [
          "1,000 random examples",
          "20 hand-picked tricky cases",
          "Whatever the model output last week",
          "User reviews from the app store",
        ],
        answer: 1,
        explain: "Small, sharp, hand-picked beats big and noisy. Iterate from there.",
      }),
      spark("LLM-as-judge", {
        type: "microread",
        title: "Use a strong model to grade a weak one",
        body: "Hand-grading 1000 outputs is brutal. Modern eval shortcut: write the rubric in plain English, hand it to Claude Opus 4.7 or GPT-5 along with the outputs, ask it to grade each one. Surprisingly accurate when the judge is meaningfully smarter than the model under test. Caveats: the judge has biases (favors longer answers, its own writing style). Spot-check 20 of its grades by hand to calibrate. LLM-as-judge isn't a replacement for human eyes — it's a force multiplier.",
        takeaway: "LLM-as-judge scales eval grading. Spot-check the judge.",
        category: "pattern",
        addedAt: "2025-10-01",
        vocab: [
          { term: "LLM-as-judge", definition: "Use a stronger model to grade a weaker one's outputs against a written rubric. Cheap, scales, surprisingly good." },
        ],
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Run your eval set on every prompt change. Two minutes of automation saves a hundred 'I think this is better?' debates.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Three eval shapes", {
        type: "microread",
        title: "Pick the right grading shape",
        body: "Three real shapes for AI evals: (1) exact-match — 'output equals X'. Fast but brittle. (2) regex / structured — 'output is valid JSON with field foo'. Catches format breaks. (3) judged — an LLM or human rates against a rubric. Slow but flexible. Most production stacks layer all three: cheap structural checks first, expensive judged checks for the survivors. The wrong eval shape will tell you 'great!' while users churn.",
        takeaway: "Match eval shape to task. Layer cheap-then-expensive checks.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Eval the eval set", {
        type: "scenario",
        setup: "Your eval scores keep going up — but users complain more. The team is starting to ignore the eval.",
        prompt: "Best move?",
        options: [
          "Scrap the evals",
          "Audit the eval set against real production failures and add the gaps",
          "Lower the bar so it matches production",
          "Change models",
        ],
        answer: 1,
        explain: "When eval and reality diverge, the eval set is wrong, not reality. Real production traces are the source of truth.",
      }),
      spark("Eval before launch — always", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Block any prompt change behind a CI gate that runs the eval set. 'I'll just tweak this real quick' is how regressions ship at midnight. Make eval pass a merge requirement, not a vibe check.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 10, "Boss: foundations check", "Prove you've internalized it.", 6, [
      spark("Recap: the foundations spine", {
        type: "microread",
        title: "What you should be able to recite cold",
        body: "AI is pattern-matching at scale. Training shapes the model; inference uses it. Data quality beats model size. Bias lives in the data. Generative produces; predictive picks. Embeddings turn meaning into math. Tokens are the unit; output is 5× input. Reasoning = giving room to think. Evals are the only ground truth. If you can riff on each of these in two sentences, you have the spine. Everything else hangs off it.",
        takeaway: "These ten ideas form the spine of modern AI. Recite them cold; the rest is detail.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: AI Foundations",
        questions: [
          {
            type: "quickpick",
            prompt: "A model 'hallucinates'. Most likely cause?",
            options: ["GPU error", "Gaps or noise in training data", "Cosmic rays", "Bad internet"],
            answer: 1,
            explain: "The model fills gaps with plausible patterns. Gaps come from data.",
          },
          {
            type: "quickpick",
            prompt: "You want fast, cheap classification. Best choice?",
            options: ["Big generative LLM", "Small fine-tuned classifier", "Image generator", "Diffusion model"],
            answer: 1,
            explain: "Right tool for the job. Generative is overkill for picking labels.",
          },
          {
            type: "quickpick",
            prompt: "Which lever has the biggest accuracy ROI early on?",
            options: ["Bigger model", "Cleaner data + better evals", "More GPUs", "Lower temperature"],
            answer: 1,
            explain: "Always. Data and evals first.",
          },
        ],
      }),
    ]),
  ],
};
