import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "ai-news" as const;

export const aiNews: Topic = {
  id: T,
  name: "AI News & Pulse",
  emoji: "📰",
  tagline: "How to read the firehose without drowning.",
  color: "#28e0b3",
  visual: "news",
  levels: [
    level(T, 1, "Build a low-noise feed", "Signal beats velocity.", 4, [
      spark("Curate ruthlessly", {
        type: "microread",
        title: "Your AI news diet",
        body: "AI news is a firehose of hype. Build a small high-signal feed: 5-8 trusted writers, lab blogs (Anthropic, OpenAI, DeepMind, Meta), one weekly digest (e.g. The Rundown, Latent Space, Import AI), and one paper aggregator. Mute the rest. Quality > quantity. You'll know more, faster, with less anxiety.",
        takeaway: "Small curated feed > infinite scroll.",
        source: { name: "AlphaSignal", url: "https://alphasignal.ai/archive" },
        category: "principle",
        addedAt: "2026-04-20",
      }),
      // Sprint #2 seed — external-source nugget from AlphaSignal feed.
      // Demonstrates the freshness chip on a `news`-category Spark with
      // a recent addedAt date. SEED — VERIFY before public publish.
      spark("Long-context is a refactor signal", {
        type: "microread",
        title: "Claude Opus 4.7 (1M context) is GA",
        body: "Anthropic shipped Claude Opus 4.7 with a 1M-token context window, available to API customers and inside Claude Code. That's roughly 750k words — a full mid-size codebase or every email you've sent this year. The pricing tier above 200k tokens is higher per token, so the practical pattern is still RAG for hot paths and 1M context for one-shot codebase reasoning. If you've been chunking aggressively to fit 200k, audit which of those pipelines are now just noise.",
        takeaway: "Long-context isn't a gimmick anymore — it's a refactor signal for any RAG pipeline you built before 2026.",
        source: { name: "AlphaSignal", url: "https://alphasignal.ai/archive" },
        category: "news",
        addedAt: "2026-04-22",
      }),
      spark("The two-sources rule", {
        type: "microread",
        title: "Lab + independent",
        body: "For every model release, read two sources before reacting: the lab's own announcement (Anthropic, OpenAI, DeepMind) and one independent take (Simon Willison, Latent Space, AlphaSignal). The lab tells you what shipped. The independent voice tells you what's real. The gap between the two is the signal. If the gap is wide, wait a week.",
        takeaway: "Lab post + one independent. Always two voices, never one.",
        source: { name: "Simon Willison", url: "https://simonwillison.net" },
        category: "principle",
        addedAt: "2026-05-01",
        bodyByAgeBand: {
          teen: "Every time a big AI lab announces a new model, read two articles before forming an opinion: the lab's own post (Anthropic, OpenAI, Google DeepMind) and one independent voice (Simon Willison's blog, Latent Space). The lab tells you what shipped on paper. The independent tells you what actually works in practice. The space between those two is where the truth lives. If the gap is huge, wait a week and read again — the hype usually fades fast.",
        },
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Make a 'Friday-only' feeds folder in your RSS reader. The truly important stuff is still important on Friday. The rest was noise.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Best AI news diet for a working builder?",
        options: [
          "Twitter all day, every day",
          "1 weekly digest + 2 trusted lab blogs + 1 independent voice + 1 paper aggregator",
          "Hacker News only",
          "Whatever the algorithm shows",
        ],
        answer: 1,
        explain: "Curated, narrow, and Friday-paced.",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the source to its strength",
        pairs: [
          { left: "AlphaSignal newsletter", right: "Daily TL;DR scan" },
          { left: "Simon Willison's blog", right: "Engineering-grade independent test" },
          { left: "Anthropic news page", right: "First-party model + safety drops" },
          { left: "Hacker News front page", right: "Builder-community sentiment" },
        ],
        explain: "Each source has one job. Read for that job, not as a substitute.",
      }),
      spark("The 'wait a week' default", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When a new model drops, calendar yourself a 'rerun the eval set' task for 7 days later. Most launches that look great on day 1 look ordinary on day 8.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("How to read a model-release post", {
        type: "microread",
        title: "Skip the quote, read the table",
        body: "Look for these three things in any model release: (1) eval-bench moves vs. the lab's own prior model; (2) price-per-token at the new context length; (3) what's still gated or limited at launch. Anthropic's Claude 4.7 1M-context release is a clean example — it states bench numbers, names the higher tier above 200k tokens, and flags the rollout cohort. Skip the hero quotes. Read the table.",
        takeaway: "Bench + price + gating. Skip the hero quote.",
        source: { name: "Anthropic", url: "https://www.anthropic.com/news" },
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Save model-release posts to Pocket. After a month, re-read three at random. The ones that aged well taught you what 'real signal' sounds like.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("AI is the most-funded space, not the best-reported", {
        type: "microread",
        title: "Coverage ≠ truth",
        body: "AI is the most-funded sector in tech, which means more PR teams, more SEO content, more 'thought leadership' than any space in living memory. This means more noise per useful signal than 2010-era cloud or 2018-era crypto. Adjust your filtering threshold up. Your job isn't to read more — it's to refuse more.",
        takeaway: "Coverage volume ≠ signal volume. Refuse more.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Build card: My AI feed in a folder", {
        type: "buildcard",
        title: "Build a one-page personal feed",
        pitch: "RSS readers are heavy. A one-page HTML site that pulls 5 RSS feeds is honest, fast, and yours.",
        promptToCopy: "Build a single static page that fetches and renders the latest 10 items from these feeds: AlphaSignal, Simon Willison, Anthropic news, Hugging Face blog, DeepMind blog. Group by source, newest first. Refresh every 30 minutes via a Cloudflare Worker. Make it the new tab page.",
        successCriteria: "Set as your browser homepage. Loads in <1s. Five feeds, sortable by source, no ads.",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the source kind to the right cadence",
        pairs: [
          { left: "Daily digest (AlphaSignal)", right: "Daily — 90 seconds" },
          { left: "Lab blogs (Anthropic, DeepMind)", right: "Friday folder" },
          { left: "Single-author blog (Simon Willison)", right: "RSS, read-as-arrives" },
          { left: "Hacker News", right: "Sentiment check, not news" },
        ],
        explain: "Different sources, different cadences. Mixing them is how anxiety starts.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "You see a 'top 10 AI tools' listicle. Most useful response?",
        options: ["Read it carefully", "Close it — listicles are SEO bait", "Email it to your team", "Bookmark for later"],
        answer: 1,
        explain: "Listicles in AI are 95% SEO. Skip without guilt.",
      }),
    ]),
    level(T, 2, "Press release vs reality", "What labs say vs what shipped.", 4, [
      spark("Decode launches", {
        type: "microread",
        title: "Hype filters",
        body: "Common patterns: 'achieves SOTA on X' (often cherry-picked benchmark), 'agentic capabilities' (sometimes a single demo), 'available soon' (months out), 'researchers' price (not commercial). Rule: wait 1 week, read independent reviews, run your own evals before switching production.",
        takeaway: "Read launch posts skeptically. Wait for replication.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("'SOTA' is a footnote, not a verdict", {
        type: "microread",
        title: "Decoding state-of-the-art",
        body: "When a lab claims 'state of the art' on a benchmark, the right next question is *which benchmark, when, vs. whom*. SOTA on MMLU in March is meaningless by August. SOTA on a benchmark with 12 contributors and zero independent runs is marketing. Read which benchmark, the date, the comparison set, and any test-set contamination disclosure. Most launches won't disclose all four — that gap is the signal.",
        takeaway: "Which benchmark, when, vs. whom, contamination — or it's marketing.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When a launch says 'beats GPT-X', search 'lmarena <model name>' the next day. The arena leaderboard cuts through cherry-picked benchmarks within a week.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Lab X announces 'agentic capabilities — coming soon'. What does this most often translate to?",
        options: ["GA tomorrow", "Months out, gated, or one demo video", "Already shipping at scale", "Open-source"],
        answer: 1,
        explain: "'Soon' usually means months. 'Agentic' often means one demo.",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "A new model claims 30% better at coding. Your CTO wants to switch production tomorrow.",
        prompt: "Best response?",
        options: [
          "Switch immediately",
          "Run your own eval set on the new model first; budget for a 1-week burn-in alongside current production",
          "Wait six months",
          "Tweet about it",
        ],
        answer: 1,
        explain: "Your eval set is the truth. The bench is press.",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the launch phrase to what it usually means",
        pairs: [
          { left: "'Available soon'", right: "Months out, often gated" },
          { left: "'Researcher pricing'", right: "Not yet commercial" },
          { left: "'Agentic capabilities'", right: "Watch the demo for caveats" },
          { left: "'GA today'", right: "Actually shipping — check pricing" },
        ],
        explain: "The lexicon repeats. Once you know it, you skim faster.",
      }),
      spark("Independent eval beats the bench", {
        type: "microread",
        title: "Why arena scores moved",
        body: "Public leaderboards like LMArena and Hugging Face's chatbot arena let real users vote head-to-head. They're noisier than benchmarks but harder to game — you can't curate your test set when humans pick the prompt. Within a week of any major release, the arena tells you whether the SOTA claim survives contact with users. If it doesn't, that's the real story.",
        takeaway: "LMArena and the like are noisy but un-gameable. Read them weekly.",
        source: { name: "Simon Willison", url: "https://simonwillison.net" },
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 3, "Spotting real breakthroughs", "Three tells.", 4, [
      spark("Three signals", {
        type: "microread",
        title: "What real breakthroughs look like",
        body: "(1) The capability is replicated by an independent team within weeks. (2) Pricing/latency is good enough for production, not just demo. (3) The technique generalizes — papers cite it across domains. If a 'breakthrough' fails all three after a month, it's just a demo.",
        takeaway: "Replicated + practical + generalizable. Else: demo.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("The two-week replication test", {
        type: "microread",
        title: "Wait for the second team",
        body: "A real capability gets reproduced by a second team within ~14 days. AlphaGo was reproduced by independent labs. Diffusion models were reproduced. RLHF was reproduced. Things that don't reproduce — single-paper benchmarks, single-demo agents — usually never escape the launch week. Set a 14-day timer on every breakthrough claim. If only one team can do it after two weeks, it's not a capability yet, it's an artifact.",
        takeaway: "14-day timer. Two-team test or it's an artifact.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Track the gap between paper publication and the first independent reproduction. Tightening gap = healthier field. Widening gap = vibe research.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Strongest signal a 'breakthrough' is real?",
        options: [
          "It trended on Twitter",
          "Two independent teams reproduced it within a month",
          "The lab CEO tweeted it",
          "The benchmark is high",
        ],
        answer: 1,
        explain: "Replication > everything.",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Real or hype?",
        pairs: [
          { left: "Reproduced by 3 teams in a month", right: "Real" },
          { left: "1 demo video, no code, no eval", right: "Hype" },
          { left: "Paper + working open-source impl in week 1", right: "Real" },
          { left: "Single-bench SOTA from one lab, no peer eval", right: "Hype" },
        ],
        explain: "Same signals every cycle. Trust them.",
      }),
      spark("Generalizability matters", {
        type: "microread",
        title: "If it only works on one task…",
        body: "A real capability generalizes. Transformers were a breakthrough partly because they worked across language, vision, and protein folding. A 'breakthrough' that only works on one benchmark is a specialization, not a capability. Look for the second domain where the technique landed within 6 months. If it never appeared anywhere else, mark it as a curiosity and move on.",
        takeaway: "If it never crosses domains, it's a specialization, not a breakthrough.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "A startup demos an 'AI that beats radiologists' with one paper, on one dataset, behind a closed model.",
        prompt: "Best response?",
        options: [
          "Build product around it immediately",
          "Wait for an independent reproduction or external dataset before integrating",
          "Tweet about it",
          "Buy the company",
        ],
        answer: 1,
        explain: "One paper + one dataset + closed weights = wait.",
      }),
      spark("DeepSeek R1: an open replication shock", {
        type: "microread",
        title: "Why open weights changed the cycle",
        body: "When DeepSeek R1 dropped open weights for a reasoning model that approached frontier-lab quality, the news cycle shifted overnight — because anyone could reproduce, fine-tune, or audit. Open replication is the strongest 'real breakthrough' signal we have, because it removes the lab-credit asymmetry. Watch for the open releases. They move the field faster than any closed launch.",
        takeaway: "Open replication is the strongest 'real' signal of the cycle.",
        source: { name: "Hugging Face", url: "https://huggingface.co/blog" },
        category: "frontier",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When a closed lab and an open lab claim the same capability, run both through your eval set. Often the 'gap' is half what the press release implies.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 4, "Reading research papers fast", "10-min skim.", 4, [
      spark("Skim like a builder", {
        type: "microread",
        title: "Paper triage in 10 min",
        body: "Read in this order: title, abstract, fig 1, conclusion. Then: limitations, related work. If still interested, method. Skip math sections unless you'll implement. 90% of papers don't survive the abstract test. The 10% that do, read carefully + look for an open-source impl.",
        takeaway: "Title → abstract → fig 1 → conclusion. Triage hard.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Drop a paper into Claude with: 'TL;DR in 5 bullets, plus one paragraph on why a builder should care or shouldn't.' Saves 80% of paper-reading time.",
        category: "tooling",
        addedAt: "2026-02-01",
      }),
      spark("The Karpathy paper-skim", {
        type: "microread",
        title: "How a senior reads",
        body: "Andrej Karpathy popularized a skim that takes 8 minutes: title → abstract → fig 1 → conclusion → table 1 → limitations. If still interested, methods. If not, close. Most papers don't pass minute 4. The 10% that do, you read with a notebook. The 90% you skipped didn't deserve the time anyway.",
        takeaway: "8-minute skim. Notebook only on survivors.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the paper section to what it actually tells you",
        pairs: [
          { left: "Abstract", right: "Best-case marketing" },
          { left: "Limitations", right: "Honest caveats — read first" },
          { left: "Figure 1", right: "The pitch in one image" },
          { left: "Conclusion", right: "What the authors think generalized" },
        ],
        explain: "Read limitations early. The truth lives there.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Single most-skipped section that changes a paper's value?",
        options: ["Abstract", "Limitations / caveats", "References", "Acknowledgments"],
        answer: 1,
        explain: "Limitations tell you what won't generalize. Most readers skip it.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When a paper's eval set is opaque, ctrl-F for 'contamination' and 'data leakage'. If neither word appears, treat the result as suspicious until proven otherwise.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("ArXiv velocity is the firehose", {
        type: "microread",
        title: "Don't read ArXiv directly",
        body: "ArXiv now sees thousands of AI papers per week. Reading it directly is unproductive. Use aggregators that pre-filter: AlphaSignal's daily digest, Hugging Face's trending papers, Latent Space, or AK on Twitter. They surface the ~5 papers a week that actually matter to a builder. Save the others for the weekly digest.",
        takeaway: "Aggregators, not arXiv direct. ~5 a week is enough.",
        source: { name: "AlphaSignal", url: "https://alphasignal.ai/archive" },
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Your inbox has 40 AI papers from this week. You have 30 minutes.",
        prompt: "Best move?",
        options: [
          "Read the abstracts of all 40 carefully",
          "Skim Karpathy-style on the top 5 from your trusted aggregator; ignore the rest",
          "Pick at random",
          "Read cover-to-cover on one",
        ],
        answer: 1,
        explain: "Triage. The aggregator's top-5 is your read list.",
      }),
      spark("Hugging Face papers tab", {
        type: "microread",
        title: "Where builders read",
        body: "Hugging Face's papers page shows trending arXiv papers ranked by community attention, with comments and code links. Builders use it as a daily filter on the firehose. The signal isn't perfect — popularity ≠ importance — but it's better than reading arXiv direct, and the comment threads frequently surface implementation notes you'd otherwise miss. Add it to your morning rotation.",
        takeaway: "huggingface.co/papers — popularity-filtered arXiv with builder comments.",
        source: { name: "Hugging Face", url: "https://huggingface.co/blog" },
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When skimming a paper, search for the words 'we observe' and 'surprisingly'. Authors hide their honest findings near those phrases.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 5, "Conferences worth watching", "NeurIPS, ICML, AAAI, ICLR.", 4, [
      spark("Where research lands", {
        type: "microread",
        title: "Big AI conferences",
        body: "NeurIPS (Dec, broad), ICML (Jul, theory + applied), ICLR (Apr/May, deep learning), AAAI (Feb, broad AI), CVPR (Jun, vision), ACL (Jul, NLP). You don't need to attend — track best-paper lists, recorded talks, social conversation. Even skimming the awards each year keeps you grounded.",
        takeaway: "Skim award winners. That's 80% of the value.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Best-paper > best-attended", {
        type: "microread",
        title: "Don't watch the keynote",
        body: "Conference keynotes are entertainment. Best-paper awards are signal. Each year's best-paper list at NeurIPS / ICML / ICLR is a 90% accurate filter on 'what mattered' two years from now. Read the awards, watch the 12-minute oral talks (recorded), skip the keynote unless the speaker has earned it. You'll know more, faster.",
        takeaway: "Awards + oral talks. Skip the keynote.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the conference to its dominant topic",
        pairs: [
          { left: "NeurIPS (Dec)", right: "Broad AI / ML" },
          { left: "CVPR (Jun)", right: "Computer vision" },
          { left: "ACL (Jul)", right: "NLP" },
          { left: "ICLR (May)", right: "Deep learning representations" },
        ],
        explain: "Match the venue to your need. ACL papers won't move your vision pipeline.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "After a major conference, search YouTube for '<conference> oral'. The 12-min talks are paced for senior reviewers — denser than reading the paper, faster than the workshop.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "ICLR just ended. You've got 90 minutes and want to stay current as a builder.",
        prompt: "Best plan?",
        options: [
          "Watch the keynote",
          "Read the 3 best-paper award abstracts, watch 2 oral talks, skim Twitter takes from 5 trusted voices",
          "Read every accepted paper",
          "Wait for the proceedings book",
        ],
        answer: 1,
        explain: "Awards + oral talks + trusted-voice takes = 90 minutes well spent.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Highest-signal artifact from a major AI conference for a builder?",
        options: ["Sponsor booth swag", "Best-paper awards + oral-talk recordings", "Keynote", "Hashtag scroll"],
        answer: 1,
        explain: "Awards + orals. The rest is decoration.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Two weeks after a conference, search 'awesome <conference> <year>' on GitHub. Builders cluster the best-papers + open-source impls there better than the official site does.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Workshops > main conference for builders", {
        type: "microread",
        title: "The hidden conference",
        body: "The best signal at NeurIPS, ICML, and ICLR isn't the main track — it's the workshops. They're smaller, more focused, and often where the next year's main-track papers first appear. Search '<conference> workshop <topic>' for any niche you care about. The 12-paper workshop with 80 attendees is often where the real conversation lives.",
        takeaway: "Workshops > main conference. Smaller room, denser signal.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Best calendar move when a major conference happens?",
        options: [
          "Block the whole week to catch up",
          "Block 90 min the Friday after — read awards, watch 2 oral talks, log 5 takeaways",
          "Skip — it's just academia",
          "Watch every keynote live",
        ],
        answer: 1,
        explain: "90 minutes, 2 weeks late, more leverage than the live blast.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Bookmark the 'Outstanding Paper' track of NeurIPS / ICML / ICLR / ACL each year. Six papers a year, ~6 hours of reading total. That's it. That's the diet.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 6, "Following key Twitter/X voices", "Curate the firehose.", 4, [
      spark("People to follow", {
        type: "microread",
        title: "A starter follow list",
        body: "Andrej Karpathy (clear explainers), Ethan Mollick (practical), Dario + Sam + Demis (lab leaders), Simon Willison (tools, infra), Jim Fan (research takes), Latent Space podcast, Allie Miller (industry). Avoid pure hypers. Follow 30, mute keywords aggressively.",
        takeaway: "30 real voices > 3000 hypers.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("The mute-keywords list", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Mute these keywords on X: 'AGI', 'doom', 'mind-blown', '🤯', 'this changes everything', 'most powerful'. Your timeline calms 70% in a day.",
        category: "principle",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "Mute these words on X (Twitter): AGI, doom, mind-blown, 🤯, 'this changes everything', 'most powerful'. Your feed will calm down by 70% in a day. The actually useful posts almost never use those words. The hype machine almost always does.",
        },
      }),
      spark("Lists > follows", {
        type: "microread",
        title: "How senior people read X",
        body: "Don't try to curate via the main feed — the algorithm fights you. Build a Twitter/X List of 20 voices. Read the List, not the feed. Karpathy, Simon Willison, swyx, Ethan Mollick, Jim Fan, AK, Dwarkesh, Nathan Lambert, Logan Kilpatrick, Lilian Weng, Karina Nguyen, Gergely Orosz. Mute, don't unfollow — keeps your network graph honest.",
        takeaway: "Build a List of 20. Read the List. Mute, don't unfollow.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the voice to what they're best at",
        pairs: [
          { left: "Andrej Karpathy", right: "Clearest explanations of fundamentals" },
          { left: "Simon Willison", right: "Hands-on test reports + prompt-injection takes" },
          { left: "Ethan Mollick", right: "Real-world use cases + classroom takes" },
          { left: "Jim Fan", right: "Research synthesis + agent takes" },
        ],
        explain: "Pick voices for what they uniquely do, not for follower count.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Healthier signal for a working builder?",
        options: [
          "100k follower 'AI thought leader' with daily threads",
          "8k follower senior researcher who posts twice a week with code",
          "Anonymous account with 'leaked benchmarks'",
          "Whoever is trending",
        ],
        answer: 1,
        explain: "Quiet, specific, code-attached. The thread-makers are the noise.",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "An AI 'leak' tweet is going viral. Screenshots claim a major capability jump nobody can verify.",
        prompt: "Best move?",
        options: [
          "Quote-tweet immediately",
          "Wait 48 hours; check whether the lab confirms or denies, and whether anyone independently reproduced",
          "Believe it",
          "Write a takedown thread",
        ],
        answer: 1,
        explain: "Most 'leaks' are wrong, distorted, or stale within 48 hours.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Use TweetDeck/X-Pro columns for AI Lists, not for the home feed. Three columns max: friends, builders, labs. The home feed is for browsing, not for working.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Hacker News is a sentiment gauge", {
        type: "microread",
        title: "Where builder sentiment lives",
        body: "Hacker News isn't where AI news *breaks* — it's where builder sentiment *settles*. When a model launch hits HN's front page, read the top three comment threads, not the headline. They'll tell you what working developers actually think about the launch, often within 24 hours of release. Treat HN as a one-day-delayed sentiment instrument, not a news source.",
        takeaway: "HN comments > HN headlines. Sentiment, not news.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Set up an RSS feed for HN comments above 100 points filtered by 'Claude OR GPT OR Gemini OR open-source AI'. You'll surface the highest-density builder discussions automatically.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Anti-follow list", {
        type: "microread",
        title: "Names worth muting",
        body: "Build an anti-follow list as deliberately as your follow list: accounts that consistently post hype with no substance, doom with no engineering, or 'leaked' material that turns out to be fake. Mute on sight — not block, not unfollow, mute. Your timeline calms 80%. The work of building taste is in the muting, not the following.",
        takeaway: "Mute lists are taste. Build them deliberately.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "A respected researcher shares a working repo for a new AI technique. A famous influencer posts a thread claiming the same idea is 'going to change everything'.",
        prompt: "Best response?",
        options: [
          "Read the thread",
          "Clone the repo, run it locally, decide for yourself",
          "Ignore both",
          "Argue in replies",
        ],
        answer: 1,
        explain: "Code beats commentary. Always.",
      }),
    ]),
    level(T, 7, "Newsletters that are worth it", "Weekly signal.", 4, [
      spark("Newsletter list", {
        type: "microread",
        title: "Weekly diet",
        body: "Import AI (Jack Clark, deep), The Rundown (broad), Latent Space (engineer-focused), Ben's Bites (consumer-friendly), TLDR AI (quick). Pick 1-2. Reading 5 every day is procrastination dressed as learning.",
        takeaway: "1-2 newsletters. Anything more is performance.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Daily digest as a habit, not a feed", {
        type: "microread",
        title: "AlphaSignal in 90 seconds",
        body: "Daily AI digests like AlphaSignal exist so you don't have to. Open the email at the same time every day (10am works), spend 90 seconds, close it. The discipline isn't comprehensiveness — it's pace. If you find yourself reading for 20 minutes, the digest got too good or you got too anxious. Either way, close it. The day is for shipping.",
        takeaway: "90 seconds, same time daily. Discipline > coverage.",
        source: { name: "AlphaSignal", url: "https://alphasignal.ai/archive" },
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Send all newsletters to a separate folder, not your inbox. Read at a fixed time. Inbox is for reply, not for reading.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Latent Space for the engineering layer", {
        type: "microread",
        title: "When to add a deep newsletter",
        body: "Once your daily digest habit is solid, add one engineering-grade newsletter — Latent Space, Import AI, or Stratechery (for strategy). They cost 30 minutes a week, not 2 minutes a day. The trick: read them on Saturday with coffee, not in the workday. They're meant for thinking, not for inbox triage.",
        takeaway: "One Saturday-morning newsletter. Read for thinking, not triage.",
        source: { name: "Latent Space", url: "https://www.latent.space" },
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the newsletter to its job",
        pairs: [
          { left: "AlphaSignal", right: "Daily 90-second scan" },
          { left: "Latent Space", right: "Saturday-morning thinking" },
          { left: "Import AI", right: "Policy + frontier-lab synthesis" },
          { left: "TLDR AI", right: "Cross-functional team scan" },
        ],
        explain: "Each newsletter has one job. Don't expect daily-scan and Saturday-thinking from the same source.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "How many newsletters is the right number?",
        options: ["10+, to be comprehensive", "1 daily digest + 1 deep weekly read", "0", "Whatever your colleague forwards"],
        answer: 1,
        explain: "1 + 1 is the durable diet.",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Your team's #ai-news Slack channel posts ~15 articles a day. You don't read most of them.",
        prompt: "Best move?",
        options: [
          "Read everything",
          "Pick 1 daily digest as the team's shared canon; mute the firehose; review the digest at standup",
          "Mute the channel forever",
          "Forward everything to your boss",
        ],
        answer: 1,
        explain: "One shared digest beats 15 personal links a day.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Unsubscribe from any newsletter where you can't remember a thing it taught you in the last month. The bar is 'one durable lesson per month.'",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Why simonwillison.net works", {
        type: "microread",
        title: "Anatomy of a good single-author feed",
        body: "Simon Willison's blog is the cleanest example of the personal-publishing engine done right: short posts, often code-attached, daily-ish, cross-linked. He coined 'prompt injection' on it. The lesson isn't to copy his voice — it's that a single author with taste, posting regularly, with code, beats most paid newsletters. Pick one such voice per niche and subscribe to the RSS.",
        takeaway: "One single-author blog per niche. RSS, not algorithm.",
        source: { name: "Simon Willison", url: "https://simonwillison.net" },
        category: "principle",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 8, "Avoiding doom + hype loops", "Mental hygiene.", 4, [
      spark("Both ends are loud", {
        type: "microread",
        title: "Don't get pulled to extremes",
        body: "AI Twitter has two megaphones: 'AGI tomorrow' and 'all useless slop'. Reality is grayer + more interesting. When you feel strong emotions about an AI thread, close the app. Go ship something. The doomers and the boomers will still be loud tomorrow; your week's progress won't.",
        takeaway: "Mute the extremes. Ship instead.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("FOMO is engagement, not information", {
        type: "microread",
        title: "Why you feel behind",
        body: "If you feel constantly behind on AI news, that's a feature of the medium, not a defect of you. Algorithms reward novelty over depth. The cure isn't reading more — it's reading slower. Pick three sources. Read them well. Skip the rest. The friend who 'follows everything' is doing worse than the friend who reads three things and shipped.",
        takeaway: "Three sources, read well. The 'follow everything' friend is performing, not learning.",
        category: "principle",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "If you feel constantly behind on AI news, that's how the algorithm wants you to feel — it's how it keeps you scrolling. Reading more doesn't fix it; reading slower does. Pick three sources you trust. Read them well. Skip everything else without guilt. The friend who 'follows everything' is performing, not learning. The friend who reads three things and ships a project is the one you should copy.",
        },
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When a thread makes you anxious, screenshot it, close the app, ship for 25 minutes. Most anxiety threads are forgotten by lunch.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the thread genre to the right response",
        pairs: [
          { left: "'AGI is here' viral thread", right: "Wait 2 weeks, see if anything shipped" },
          { left: "'Everything is slop' takedown", right: "Run your own evals, decide" },
          { left: "Anonymous 'leaked benchmark'", right: "Wait 48 hours; usually wrong" },
          { left: "Working open-source repo from a researcher", right: "Try it tonight" },
        ],
        explain: "Not every loud thread deserves your attention budget.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Best response to a 'this changes everything' AI tweet?",
        options: [
          "Quote-tweet immediately",
          "Bookmark it; revisit in 2 weeks; if it still matters, dig in",
          "Believe it",
          "Argue in replies",
        ],
        answer: 1,
        explain: "2-week delay filters 90% of 'changes everything' to 'changed nothing'.",
      }),
      spark("Don't argue with the doomers", {
        type: "microread",
        title: "Mental hygiene rule",
        body: "The doomer/boomer fight on AI Twitter is theater. Both sides have absorbed years of arguments and aren't moving. Engaging steals your day, costs your reputation, and changes nobody's mind. The cleanest move: read the best of each, form your own view, and don't post about it. Ship instead. Your work is the argument.",
        takeaway: "Read both. Post neither. Ship.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "You spent 3 hours doomscrolling AI news on Sunday. Monday you can't focus on the actual feature you were shipping.",
        prompt: "Best self-correction?",
        options: [
          "Read more news to 'understand the landscape'",
          "Set a hard 15-minute daily news cap; fill the freed time with one shipped commit",
          "Quit Twitter forever",
          "Switch to LinkedIn",
        ],
        answer: 1,
        explain: "Cap, replace, ship. Doomscrolling is a habit; replace it with a smaller habit.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Track 'screen time' on X / Threads / TikTok in a weekly review. AI news anxiety usually correlates 1:1 with screen time. The fix is the cap, not better filtering.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Mollick's two-week rule", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "Every panic about AI Twitter is two weeks old by the time it reaches you. Wait two weeks before reacting and 90% of panics dissolve.",
        takeaway:
          "A two-week pause is the cheapest sanity tool in the AI cycle. The viral panic that survives two weeks is the one worth thinking about; the rest is forgotten.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Ethan Mollick",
          guestRole: "professor at Wharton, author of Co-Intelligence",
          episodeTitle: "How to keep your head in the AI cycle",
          timestamp: "00:00:00",
        },
      }),
    ]),
    level(T, 9, "Synthesizing it weekly", "Your own digest.", 4, [
      spark("Personal digest habit", {
        type: "microread",
        title: "Write your own pulse",
        body: "Every Friday, write 5 bullets to yourself (or your team): top thing I learned, biggest model release, most interesting startup move, paper to revisit, hot take. Forces you to process, not just consume. Compound this for a year and you're a domain expert.",
        takeaway: "Write the digest. Compounds into expertise.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Use LearnAI's Tasks tab to capture interesting articles or talks during the week. Friday: review tasks, write 5 bullets, archive.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Public Friday digest = career compound", {
        type: "microread",
        title: "Why share it",
        body: "Writing the Friday digest privately captures 80% of the value. Sharing it publicly captures the remaining 80% (yes, the math is intentional). You get corrected, you build a public track record, and over a year you accumulate a network of senior people who know your taste. simonwillison.net is exactly this pattern, scaled. Most niches are wide open for a 'good Friday digest' voice.",
        takeaway: "Public > private. The corrections and the network are the prize.",
        source: { name: "Simon Willison", url: "https://simonwillison.net" },
        category: "principle",
        addedAt: "2026-05-01",
      }),
      spark("Build card: One-page Friday digest site", {
        type: "buildcard",
        title: "Ship a public Friday digest site",
        pitch: "Discipline outsourced to a deadline you can't hide from. Public digest = real career compound.",
        promptToCopy: "Build a Next.js site at /digest that lists Friday digests in reverse-chronological order. Each digest is a Markdown file with: top learning, biggest release, startup move, paper to revisit, hot take. Add an RSS feed. Deploy to Vercel. Add a Cloudflare-Workers cron that pings me every Friday 9am if no digest has been pushed.",
        successCriteria: "First digest live by next Friday. RSS validates. The cron pings you if you skip a week.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Best Friday-digest format for compounding learning?",
        options: [
          "300-word essay",
          "5 bullets: learning / release / startup / paper / hot take — same shape every week",
          "Whatever you feel like",
          "Just retweet stuff",
        ],
        answer: 1,
        explain: "Same shape every week. Compounding requires consistency.",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the synthesis habit to its career outcome",
        pairs: [
          { left: "Daily-scan only, no synthesis", right: "Anxious, knows little for sure" },
          { left: "Private weekly notes", right: "Builds personal taste" },
          { left: "Public weekly digest", right: "Builds taste + network + reputation" },
          { left: "Daily takes on Twitter", right: "Confused with thought leadership" },
        ],
        explain: "Cadence + audience = compounding shape.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Skip the digest one week and you'll be tempted to skip three. The cure: ship even a 4-bullet half-quality version. Streak > polish.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("DeepMind's drops are weekly homework", {
        type: "microread",
        title: "Where Friday material lives",
        body: "Google DeepMind's blog publishes the kind of meaty research drops that pair perfectly with the Friday digest habit — something more substantial than a model release, often less hyped than the lab posts you've already read. Add their RSS to your Friday-only folder, alongside Anthropic's news and Hugging Face blog. The mix gives you one strategic, one product, one ecosystem voice each week.",
        takeaway: "DeepMind + Anthropic + Hugging Face = a balanced Friday set.",
        source: { name: "Google DeepMind", url: "https://deepmind.google/discover/blog/" },
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "You've kept a private Friday-digest streak for 6 weeks. A peer asks if you'd start sharing it.",
        prompt: "Best response?",
        options: [
          "Wait until it's perfect",
          "Publish it Monday — even messy. Public reps compound; private polish doesn't.",
          "Stop the streak",
          "Charge for it",
        ],
        answer: 1,
        explain: "The public version is the version that compounds. Polish later.",
      }),
    ]),
    level(T, 10, "Boss: news check", "Final gate.", 6, [
      spark("Capstone microread", {
        type: "microread",
        title: "What stays after the cycle",
        body: "Three years of AI news cycles teaches one durable lesson: most launches don't matter, and the ones that do are obvious in retrospect. The signal you cultivate isn't 'spot every release.' It's 'know the difference between *this is a tool I'll use this quarter* and *this is performance art.* Curate sources that help you tell those two apart. Then close the app and ship.",
        takeaway: "Tool vs. theater. The rest is noise.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Once a quarter, audit your sources. Drop the one that hasn't taught you something practical. Add one a friend you respect recommends. Compounds.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("The Karpathy mute test", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "If muting an AI account makes you nervous, that account is doing its job on you, not for you.",
        takeaway:
          "Test every follow with the mute thought-experiment. Anxiety is a signal of dependence, not value. Real signal sources can be muted without panic.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Lenny Rachitsky",
          guestRole: "host, Lenny's Podcast",
          episodeTitle: "How working PMs build a healthy AI media diet",
          timestamp: "00:00:00",
        },
      }),
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: AI News",
        questions: [
          {
            type: "quickpick",
            prompt: "Best response to a new model release?",
            options: ["Switch production immediately", "Run your house eval, decide based on data", "Tweet about it", "Ignore"],
            answer: 1,
            explain: "Your evals are the truth.",
          },
          {
            type: "quickpick",
            prompt: "Most efficient way to read a research paper?",
            options: ["Cover to cover", "Title → abstract → fig 1 → conclusion → decide", "Math first", "Skip — just tweet"],
            answer: 1,
            explain: "Triage like a senior reader.",
          },
          {
            type: "quickpick",
            prompt: "How many newsletters is healthy?",
            options: ["10+", "1-2 chosen carefully", "0", "Random"],
            answer: 1,
            explain: "Quality > quantity.",
          },
        ],
      }),
    ]),
  ],
};
