import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "ai-pm" as const;

export const aiPm: Topic = {
  id: T,
  name: "AI Product Management",
  emoji: "🎯",
  tagline: "Ship AI features users actually use and trust.",
  color: "#ffb547",
  visual: "compass",
  levels: [
    level(T, 1, "What an AI PM does differently", "Probabilistic ≠ deterministic.", 4, [
      spark("Specs in distributions", {
        type: "microread",
        title: "Specs become probabilistic",
        body: "Classic PM: 'when user clicks X, do Y.' AI PM: 'when user asks X, the answer should be helpful 95% of the time, never harmful, and cite sources when it's a fact.' You write specs in target distributions, not guarantees. You ship evals, not just designs. You measure quality continuously, not at QA only.",
        takeaway: "AI PM = specs as distributions, evals as guardrails.",
        visual: "compass",
        category: "principle",
        addedAt: "2025-10-01",
        vocab: [
          { term: "evals", definition: "A scored test set you run on every release of an AI feature. Each row is an input + the criteria a 'good answer' must meet. Replaces 'does it click X' with 'does it score above the bar on 50 hard cases.'" },
          { term: "target distributions", definition: "Instead of a single 'this must work,' you state the *distribution* of acceptable outcomes: helpful 95% of the time, harmful 0% of the time, factual when it's a fact. AI PMs ship distributions; classic PMs shipped binary specs." },
        ],
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Replace 'must always work' in your specs with 'must work in 95% of these 50 cases'. Forces you to write the eval set up-front.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Best success metric for an AI summarizer feature?",
        options: ["LOC of code", "User retention + thumbs-up rate + factual accuracy on eval set", "API latency only", "Number of features"],
        answer: 1,
        explain: "Quality + usage + correctness, not just one.",
      }),
      spark("PM and engineer collapse into builder", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "By the end of the year everyone is going to be a product manager, and everyone codes. The title software engineer is going to start to go away. It's just going to be replaced by builder.",
        takeaway:
          "The roles aren't disappearing — they're collapsing into one. The premium goes to people who can think and ship in the same hour.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Boris Cherny",
          guestRole: "head of Claude Code, Anthropic",
          episodeTitle: "How Claude Code rewrites the job of an engineer",
          timestamp: "00:00:44",
        },
        ctaPrompt:
          "Write your next project description from a builder's voice, not a PM's. State the user, the unmet need, and what 'done' looks like — in under 100 words.",
      }),
      spark("PM job description rewrites itself", {
        type: "microread",
        title: "What replaces the JIRA ticket",
        body: "The classic PM artifact was the spec doc + ticket queue. The AI-native one is a working prototype. When you can vibe-code a v0 in Cursor between meetings, the bar for 'is this worth building' moves from 'is the doc convincing' to 'does the prototype change the conversation.' PMs who only write win less. PMs who write *and* ship a half-real demo before standup win the room.",
        takeaway: "Bring the prototype, not the slide.",
        category: "principle",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "An old-school product manager wrote a doc explaining what the team should build. The AI-native version writes the doc *and* shows up to the meeting with a half-working version they vibe-coded with Cursor or Claude Code. The doc convinces a few people. The half-working version changes the conversation. If you can build a prototype in an hour, every meeting starts with a real thing instead of a slide.",
          kid: "An AI product manager isn't just someone who writes ideas down anymore. They show up with a working version, even a rough one, that you can poke at. A note says 'imagine if it did this.' A working version says 'tap here.' The second one wins.",
        },
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Before any spec review, paste the spec into Claude with: 'Find three assumptions that aren't backed by user data.' Cuts review time in half.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("AI changes the unit of work", {
        type: "microread",
        title: "From feature → outcome",
        body: "When inference is cheap, the unit of work moves up the stack. Old PMs shipped 'a button that does X.' AI PMs ship 'the user gets the outcome they wanted, however the model gets there.' That sounds woolly until you stress-test it: Linear's AI triage isn't a feature, it's an outcome (issues end up in the right place). Notion AI isn't a button, it's an outcome (the doc finishes itself).",
        takeaway: "Ship outcomes, not features. Features are the old packaging.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the artifact to the era",
        pairs: [
          { left: "16-page PRD", right: "Pre-AI PM" },
          { left: "Vibe-coded v0 in Cursor", right: "AI-native PM" },
          { left: "JIRA ticket queue", right: "Pre-AI PM" },
          { left: "Eval set + working demo", right: "AI-native PM" },
        ],
        explain: "The doc didn't disappear — it got moved to second place behind the prototype.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "First artifact an AI-native PM ships for a new feature?",
        options: ["A 12-page PRD", "A vibe-coded prototype + a 20-row eval set", "A roadmap deck", "An OKR doc"],
        answer: 1,
        explain: "Prototype + eval = the new spec.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Open every feature kickoff by reading the eval set out loud. If it doesn't exist, the kickoff is premature.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Engineering wants to start coding next week. You don't yet have an eval set.",
        prompt: "Best response?",
        options: [
          "Ship code first, write evals later",
          "Spend two days hand-curating 30 example inputs + expected behaviors before any code is merged",
          "Skip evals — they'll slow us down",
          "Hire a vendor for evals",
        ],
        answer: 1,
        explain: "Two days now buys six weeks of fewer regressions later.",
      }),
    ]),
    level(T, 2, "Picking the right problem", "Where AI is unfair advantage.", 4, [
      spark("Repeat + boring + judgment", {
        type: "microread",
        title: "Where AI wins big",
        body: "AI works best where work is repetitive, requires light judgment, and humans hate doing it. Inbox triage. Spec drafting. Code review nudges. Image moderation. It works terribly where stakes are extreme, edge cases dominate, or the user wants control. Don't pick AI to be cool — pick it where humans burn out and tolerance for 90% accuracy is high.",
        takeaway: "Boring + repeated + 90%-good-enough = AI gold.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match each task to its AI fit",
        pairs: [
          { left: "Drafting marketing emails", right: "Strong fit" },
          { left: "Final medical diagnosis", right: "Weak fit" },
          { left: "Auto-tagging support tickets", right: "Strong fit" },
          { left: "Approving million-dollar wires", right: "Weak fit" },
        ],
        explain: "Stakes + tolerance for error decide it.",
      }),
      spark("Sometimes it's positioning, not the product", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "If your product isn't doing well, there's a chance that it may not be the product that's the problem — it may be your positioning.",
        takeaway:
          "Before you rebuild the feature, rewrite the sentence. 'What is this and who is it for?' — answered in one line, in the prospect's words — is a higher-leverage edit than three sprints of new code.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "April Dunford",
          guestRole: "author of Obviously Awesome",
          episodeTitle: "Why positioning is your highest-leverage PM lever",
          timestamp: "00:00:00",
        },
        ctaPrompt:
          "Write your product's one-sentence positioning today. Then ask three users to tell you what your product is. Compare. The gap is your homework.",
      }),
      spark("The reverse-RICE filter", {
        type: "microread",
        title: "Don't pick AI for the wow",
        body: "Run every AI feature idea through a reverse-RICE: how angry would users be if it was wrong 5% of the time? If 'fine, I'd just edit it' — green light. If 'they'd churn' — needs a different shape. Notion AI took off because being wrong on a draft email is a $0 mistake. AI legal review stalled because being wrong on a contract is $50k. The cost of being wrong is the picker.",
        takeaway: "Cost-of-wrong, not coolness, decides AI fit.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "List five workflows your users complain about. Cross out anything where 'wrong by 10%' would lose the customer. The remainder is your AI roadmap.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "You're a PM at a property-listing site. Two AI ideas surface in planning.",
        prompt: "Which to ship first?",
        options: [
          "Auto-decline tenant applications based on AI risk scoring",
          "Auto-suggest a listing description draft the agent edits before publish",
          "Auto-set the listing price",
          "Auto-blur faces in photos",
        ],
        answer: 1,
        explain: "Drafting is reversible and low-stakes. Auto-deciding tenants and prices isn't.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Why did Notion AI work where AI legal review struggled?",
        options: ["More VC funding", "Cost of being wrong is near-zero on a draft, high on a contract", "Better model", "Better marketing"],
        answer: 1,
        explain: "AI fit follows cost-of-wrong, not capability.",
      }),
      spark("Linear's wedge: not features, taste", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "We didn't add AI to do more — we added AI to remove steps. Most of the value is in things the user never has to think about.",
        takeaway:
          "When AI competes feature-for-feature, the winner is whoever has the most taste in deletion. Pick the chore that vanishes, not the demo that dazzles.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Karri Saarinen",
          guestRole: "co-founder, Linear",
          episodeTitle: "Building Linear: opinions, taste, and AI",
          timestamp: "00:00:00",
        },
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the AI feature to its dominant risk",
        pairs: [
          { left: "AI auto-replies to customer email", right: "Tone disaster on edge case" },
          { left: "AI summarizes a sales call", right: "Quietly drops the key objection" },
          { left: "AI reschedules calendar conflicts", right: "Books over a parent's funeral" },
          { left: "AI drafts a Slack DM", right: "Low — easy to fix before send" },
        ],
        explain: "Every AI feature has a worst-case story. Write yours before you ship.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Ask: 'What's the worst thing this could output, and would it land in screenshot-of-the-week on Twitter?' If yes, the rollout plan needs a human gate.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 3, "UX patterns for AI", "Design for uncertainty.", 5, [
      spark("Show the seams", {
        type: "microread",
        title: "Confidence + control",
        body: "Best AI UX shows the seams: cite sources, show confidence, let users edit/regenerate, never auto-commit irreversible actions. Hide the AI? Users feel tricked. Over-explain? They tune out. Sweet spot: visible AI suggestions + easy human override + a clear undo. Look at GitHub Copilot ghost text or Notion AI: opt-in, easy to dismiss, easy to accept.",
        takeaway: "Confident-but-correctable. Always.",
        bodyByAgeBand: {
          kid: "Good AI shows its work and lets you fix it. If an AI is hidden, it feels sneaky. If it explains everything for ten lines, you stop reading. The sweet spot: the AI suggests something, you can clearly see it's a suggestion, and one tap accepts or changes it. Like a friend whispering an idea instead of grabbing the pencil out of your hand.",
          teen: "The best AI features show the seams. They cite where an answer came from, signal how sure they are, and always let you edit or undo. Hidden AI feels sneaky; over-explained AI gets tuned out. The pattern that works: a visible suggestion + a clear way to accept it + an obvious way to change or reject it. Think autocomplete you can dismiss, not autopilot you can't.",
        },
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add a 'why' button next to AI outputs. 'Because document X said Y on date Z.' Builds trust faster than any UI polish.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Your AI categorizes user expenses. Sometimes it's wrong.",
        prompt: "Best UX?",
        options: [
          "Auto-categorize silently, no UI",
          "Show category as a chip with one-tap edit",
          "Email the user every wrong guess",
          "Disable until 100% accurate",
        ],
        answer: 1,
        explain: "Visible + correctable. The 5-second fix beats a buried setting.",
      }),
      spark("The undo budget", {
        type: "microread",
        title: "Undo is the AI feature",
        body: "Every AI action you let the user not-undo costs you trust. Cursor's killer move wasn't its diff quality — it was a one-keystroke 'reject' on every suggestion. Notion AI's was the discard button on every block. The undo isn't a polish item; it's the headline. If you can't ship with a clean undo, ship a smaller AI feature you can.",
        takeaway: "Undo first. AI second.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Best place to put confidence in an AI UI?",
        options: ["A footer disclaimer", "Right next to the action — and in the action's tone", "Onboarding tooltip", "Settings page"],
        answer: 1,
        explain: "Confidence shown at the moment of decision changes behavior. Anywhere else is decoration.",
      }),
      spark("Streaming is a UX move, not a tech one", {
        type: "microread",
        title: "Why ChatGPT streams",
        body: "Streaming tokens isn't just a latency hack — it's the trust pattern. Users see the model think, can interrupt the moment it goes off-rails, and feel agency over a session that would otherwise be a black box. Cursor's chat streams. Claude streams. Try a non-streaming AI chat and you'll feel the difference inside ten seconds: it feels broken even when it's faster.",
        takeaway: "Stream by default. Black-box answers feel slower than they are.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add a 'stop generating' button on every streaming output. The button isn't for stopping — it's for telling the user they're in charge.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the UX move to the user emotion it produces",
        pairs: [
          { left: "Cite the source on every claim", right: "Trust" },
          { left: "Stream tokens as they generate", right: "Agency" },
          { left: "One-tap reject on every suggestion", right: "Control" },
          { left: "Hide that AI is involved", right: "Suspicion" },
        ],
        explain: "Every UI move maps to an emotion. AI features die when the emotion is suspicion.",
      }),
      spark("Empty states are AI's first impression", {
        type: "microread",
        title: "Don't waste the empty state",
        body: "Most AI features fumble the empty state — a blank input with 'Ask anything…'. Compare to Notion AI's empty state: it offers four concrete actions ('summarize this page', 'extract action items'…). One ships discoverability for free; the other punts. The empty state is your spec for what the feature is *for*. Hand-curate three to five examples that match real workflows. Refresh quarterly.",
        takeaway: "Empty state = product spec. Curate, don't shrug.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Users keep typing one-word queries into your AI doc-search and getting nothing useful.",
        prompt: "Most leveraged fix?",
        options: [
          "Add a 'try harder' button",
          "Replace the empty state with 5 concrete example questions sourced from real searches",
          "Buy a bigger model",
          "Add a tutorial video",
        ],
        answer: 1,
        explain: "The empty state teaches the input shape better than docs ever will.",
      }),
    ]),
    level(T, 4, "Pricing AI features", "Tokens cost money.", 4, [
      spark("Margin awareness", {
        type: "microread",
        title: "Inference cost vs price",
        body: "Unlike most software, AI features have non-zero marginal cost. A 'free unlimited' AI feature can bankrupt you. Build cost dashboards from day one. Track tokens per user per day. Cap heavy users. Push the most expensive workflows to higher pricing tiers. Many AI products fail not on quality but unit economics.",
        takeaway: "Track inference $/user. Caps and tiers from day one.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Most important early metric for an AI feature's economics?",
        options: ["Brand mentions", "Tokens per active user per day", "DAU/MAU only", "Star rating"],
        answer: 1,
        explain: "Cost per user predicts whether the unit economics work.",
      }),
      spark("The cheaper-than-Slack rule", {
        type: "microread",
        title: "Pick a willingness-to-pay anchor",
        body: "The cleanest pricing question for an AI feature: 'Is this saving the user something they already pay for?' If your AI inbox triage saves 30 min/day, the anchor is the price of an EA, not the price of inference. Linear charges per-seat for AI; it's anchored to seat value, not token cost. Notion AI is $10/seat add-on, anchored against editor time. Anchor up the value chain, not down to your COGS.",
        takeaway: "Anchor to the workflow's existing budget, not your inference bill.",
        category: "principle",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "When you price an AI feature, don't ask 'what does it cost us to run?' Ask 'what is the user already paying to get this outcome a different way?' If your AI does 30 minutes of inbox sorting a day, the comparison isn't tokens — it's the cost of a personal assistant. Notion charges $10/seat for AI because it's anchored to a *person's* time, not a model's electricity bill. Price up to the workflow's existing budget, not down to your COGS.",
        },
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Before pricing, write the user's elevator-pitch ROI sentence: 'I used to pay $X to do Y. Your AI does Y for $Z.' If you can't write Z < X, the math isn't there yet.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Build card: Token-budget alarm", {
        type: "buildcard",
        title: "Build a per-user token alarm in 30 min",
        pitch: "Most teams realize too late that one whale user is burning their margin. A token-budget alarm fires before that happens.",
        promptToCopy: "Build a serverless function that reads my OpenAI/Anthropic usage from yesterday, groups tokens by userId, and posts to Slack any user above a configurable daily threshold. Use Cloudflare Workers + KV. Include a /healthcheck endpoint and a README with the env vars.",
        successCriteria: "When you exceed the threshold from a test account, you get a Slack ping within an hour. README spells out env vars and threshold tuning.",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the AI feature to the right pricing wrapper",
        pairs: [
          { left: "AI sales-call summarizer", right: "Per-seat add-on" },
          { left: "AI batch-tagging API for engineers", right: "Per-1k-token metered" },
          { left: "AI image generation", right: "Credit packs" },
          { left: "AI-generated landing pages", right: "Per-output flat fee" },
        ],
        explain: "Each shape maps a pricing model. Mismatched shape → users feel cheated or you bleed margin.",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "You ship 'free unlimited AI summaries' on the marketing landing page. Two months in, three power users are using 60% of your inference budget.",
        prompt: "Best move?",
        options: [
          "Quietly throttle them and hope they don't notice",
          "Introduce a generous-but-finite quota for free, charge above; grandfather their last 30 days",
          "Email them an apology and shut off",
          "Raise prices for everyone equally",
        ],
        answer: 1,
        explain: "Generous floor + paid ceiling + grandfathering = retention without bankruptcy. Linear, Cursor, Vercel all use this pattern.",
      }),
      spark("The free-tier trap is asymmetry", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "Free tier is a CAC line item. The worst version is when 1% of users consume 90% of inference and they'd never have paid anyway.",
        takeaway:
          "Treat free-tier inference as a marketing budget — deliberate, capped, and measured by conversion to paid. Unlimited free is a lottery your finance team didn't agree to play.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Olivier Pomel",
          guestRole: "co-founder, Datadog",
          episodeTitle: "How Datadog priced telemetry — and what AI products can learn",
          timestamp: "00:00:00",
        },
      }),
      spark("BYO-key as a pricing escape hatch", {
        type: "microread",
        title: "Let power users pay the lab",
        body: "When inference cost dominates your unit economics, offer 'bring your own API key' on a higher tier. Cursor, Continue, Aider all do this. The user pays Anthropic / OpenAI directly, you charge a flat platform fee. Solves the whale problem without throttling. Bonus: your enterprise pitch ('our customers' tokens never touch our servers') gets way easier.",
        takeaway: "BYO-key turns whales into platform-fee customers.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Plot tokens-per-active-user as a histogram, not an average. The long tail tells the story; the average lies.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 5, "Evals as a PM artifact", "PMs own evals now.", 4, [
      spark("Curate the cases", {
        type: "microread",
        title: "PMs write the evals",
        body: "The PM owns the 'what good looks like' set. You hand-curate edge cases from real user logs, define rubric (1-5 scores), and update the set monthly. Engineers wire them to CI. Without you, they default to 'looks good in dev' — and you'll ship regressions. With you, every prompt change is measurable.",
        takeaway: "Eval set = your spec. Own it like you own roadmap.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Weekly: copy 5 surprising user logs into your eval set. Within 3 months you'll have 60 hard cases that catch 80% of regressions.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Vibes are not evals", {
        type: "microread",
        title: "Don't trust the dogfood",
        body: "Founders dogfooding the AI feature catches 5% of failure modes. Your real users are stranger, sloppier, and operate at edge cases you'd never type. Build the eval set from production logs — sample 20 random failures + 20 random successes weekly. Tag each. Score in groups. The team-vibe-check version of QA flatters you. The eval set is honest.",
        takeaway: "Sample production. Vibes are the enemy.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("LLM-as-judge: cheaper than humans, with caveats", {
        type: "microread",
        title: "When LLM grading works",
        body: "Use a stronger model (Claude Opus, GPT-5) to grade outputs from your shipping model on a rubric you wrote. It's 30× cheaper than humans, scales overnight, and catches obvious badness. But: judge bias creeps in (favors longer answers, similar style), so calibrate against 50 human-graded rows monthly. LLM-as-judge is great for trend, weak for absolute scores.",
        takeaway: "LLM-as-judge for trend, humans for ground truth.",
        category: "pattern",
        addedAt: "2025-10-01",
        vocab: [
          { term: "rubric", definition: "A structured checklist of what 'good' looks like — e.g. 'is the answer factually accurate? cites sources? avoids hedging?'. The grader (human or LLM) scores each criterion 1-5, not a single overall vibe." },
        ],
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "How big should your eval set be in month 1?",
        options: ["1000 cases", "20-50 hand-curated cases that cover real failure modes", "Whatever the engineer made", "Leave to QA"],
        answer: 1,
        explain: "Small + curated > big + noisy. Grow the set with production logs.",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Your model upgrade scores 3% better on the eval set but feels worse to power users.",
        prompt: "Best response?",
        options: [
          "Ship it — eval is the source of truth",
          "Pull 20 power-user-flagged examples and add them to the eval set; rerun",
          "Roll back, blame the model",
          "Ignore power users",
        ],
        answer: 1,
        explain: "Your eval set was incomplete. Power-user complaints are gold for new eval rows.",
      }),
      spark("The 'why this row failed' column", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add a 'why' column to your eval CSV — one sentence per row on what makes the case hard. Engineers stop saying 'the model just sucks' once each row has a story.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the eval failure mode to its likely fix",
        pairs: [
          { left: "Model hallucinates a citation", right: "Tighten retrieval / require source" },
          { left: "Model is too verbose", right: "Adjust prompt + temperature, not retrain" },
          { left: "Model fails on Spanish queries", right: "Eval set lacked language coverage" },
          { left: "Model refuses safe queries", right: "Loosen safety prompt or switch model" },
        ],
        explain: "Different failures map to different fixes. Sorting them is half the job.",
      }),
      spark("PM owns the rubric", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "If your engineers are writing the rubric, you don't have a product spec — you have a vibes review. The PM's job is to define what good means before code is written.",
        takeaway:
          "The rubric is the spec for AI features. PMs who delegate it become observers; PMs who own it stay in the cockpit.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Aparna Chennapragada",
          guestRole: "CPO, Microsoft (formerly Google, Robinhood)",
          episodeTitle: "What product management looks like in the AI era",
          timestamp: "00:00:00",
        },
      }),
    ]),
    level(T, 6, "User trust loops", "Earn it slowly, lose it fast.", 4, [
      spark("Trust is asymmetric", {
        type: "microread",
        title: "One failure undoes ten wins",
        body: "AI features feel magical until they confidently mislead once. From that moment users discount everything. So: ship boring-but-reliable before flashy-but-fragile. Add 'sources' UI, conservative refusal language ('I don't have that info'), and easy human escape hatches. Trust compounds. So does distrust.",
        takeaway: "Underpromise. Overdeliver. Sources visible.",
        bodyByAgeBand: {
          kid: "Trust with AI works the same as trust with a friend who tells stories. Ten cool true stories make you believe them. One confident lie, and you start checking everything they say. So good AI tools play it safe: they say 'I don't know' a lot, they show where they got their info, and they make it easy to fix mistakes. Boring and reliable beats flashy and wrong.",
          teen: "AI feels magical right up until it confidently misleads you once. From that moment, you discount every answer it gives — even the right ones. So the smartest move is shipping boring-but-reliable before flashy-but-fragile. Show sources. Use cautious language ('I don't have that info'). Make it easy to ask a human. Trust compounds with every quiet correct answer; one loud wrong one resets the count.",
        },
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("The Challenger disaster of AI", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "Lots of people knew those little O-rings were unreliable, but every single time you get away with launching a space shuttle without the O-rings failing, you institutionally feel more confident in what you're doing. We've been using these systems in increasingly unsafe ways. My prediction is we're going to see a Challenger disaster.",
        takeaway:
          "Ship velocity is masking risk. Treat each AI agent run as if the worst-case prompt-injection has already happened — because the day it does, 'we always did it this way' won't save you.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Simon Willison",
          guestRole: "co-creator of Django, coined 'prompt injection'",
          episodeTitle: "The November inflection: AI coding crosses the threshold",
          timestamp: "00:01:08",
        },
      }),
      spark("Refusal is a feature", {
        type: "microread",
        title: "When 'I don't know' wins",
        body: "Most AI products try to always answer. The ones users trust learn to refuse cleanly: 'I don't have data on that — try X.' Anthropic's Claude often outperforms competitors not on raw capability but on calibrated refusals. The PM move: write 'good refusal' examples into your eval set with the same weight as 'good answer' examples. A confident wrong answer is the worst output your product ships.",
        takeaway: "Calibrated refusal beats confident hallucination.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Add 'good refusal' rows to your eval set: questions where the only correct answer is 'I can't help with that'. Score refusals like answers.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "User asks an AI assistant something it shouldn't answer. Best behavior?",
        options: [
          "Make something up so it sounds smart",
          "Refuse cleanly, explain why, suggest a next step",
          "Stay silent",
          "Forward to support without asking",
        ],
        answer: 1,
        explain: "Refusal + redirect = trust. Hedge + hallucinate = brand damage.",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Your AI accountant tool confidently mis-categorized $40k of expenses for a customer in their first month.",
        prompt: "Best recovery move?",
        options: [
          "Issue a generic apology, ship a fix later",
          "Refund the month, post a public root-cause memo, add the failure to your eval set with a public link",
          "Hope they don't notice",
          "Blame the model",
        ],
        answer: 1,
        explain: "Public, specific, root-caused. Treats one customer's bad month as everyone's safety upgrade. Anthropic and Linear handle incidents this way.",
      }),
      spark("Sources are the cheapest trust UI", {
        type: "microread",
        title: "Cite or die",
        body: "Three years of AI products have proven one thing: users tolerate AI being wrong if they can see *where* the answer came from. Perplexity's whole moat is sources next to claims. Phind, Glean, You.com — all citation-first. The PM lesson: citations aren't a polish item, they're the trust mechanism. If your AI feature can cite, it should. If it can't, the use case may be too high-stakes for your current capability.",
        takeaway: "If you can cite, cite. If you can't, reconsider the use case.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "On every AI claim, render the source chip *next to* the claim, not at the bottom. Distance from claim = degradation of trust.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the trust signal to the user emotion it nudges",
        pairs: [
          { left: "Inline citation chip", right: "Verifiable" },
          { left: "Confidence percentage on output", right: "Calibrated" },
          { left: "Visible 'why this answer' button", right: "Curious" },
          { left: "No signal at all", right: "Skeptical" },
        ],
        explain: "Trust UX is built one quiet signal at a time.",
      }),
    ]),
    level(T, 7, "Roadmapping AI products", "Capabilities ladder.", 4, [
      spark("Crawl-walk-run", {
        type: "microread",
        title: "From assistive → autonomous",
        body: "Roadmap AI features along an autonomy ladder: (1) suggest, human accepts, (2) draft, human reviews, (3) act, human can undo, (4) act autonomously, audit log only. Each step requires more eval depth, more guardrails, more trust. Most successful AI products live at level 1-2 for years before earning level 3.",
        takeaway: "Move down the ladder by earning trust, not by shipping faster.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the autonomy level",
        pairs: [
          { left: "Copilot ghost text suggestions", right: "Suggest" },
          { left: "Background agent fixing typos in PRs", right: "Act + undoable" },
          { left: "Drafting an email for review", right: "Draft" },
          { left: "Self-healing infra responder", right: "Autonomous + audited" },
        ],
        explain: "Each step = more autonomy, more guardrails.",
      }),
      spark("AI raises ambition, not free time", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "AI's supposed to make us more productive. It feels like the people that are most AI-pilled are working harder than they've ever worked. I can fire up four agents in parallel and have them work on four different problems. By 11am, I am wiped out.",
        takeaway:
          "AI doesn't reduce hours — it raises ambition. The right comparison isn't 'less work' vs. 'same work.' It's 'the project I'd never have attempted' vs. 'the project I would've taken three months on.'",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Simon Willison",
          guestRole: "co-creator of Django, coined 'prompt injection'",
          episodeTitle: "The November inflection: AI coding crosses the threshold",
          timestamp: "00:00:43",
        },
      }),
      spark("Roadmap rows are decisions, not deliverables", {
        type: "microread",
        title: "Trade the Gantt for a hypothesis",
        body: "AI roadmaps that ship are hypothesis-shaped: 'we believe AI inbox triage will lift 7-day retention by 5%; we'll know in 4 weeks; if not, we kill it.' Compare to 'Q3: ship inbox triage' — that's a project plan, not a roadmap. The hypothesis frame makes the kill decision easy. The deliverable frame makes pivots feel like failures.",
        takeaway: "Hypothesis-shaped roadmaps. Kill cleanly.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Every roadmap row gets a kill-criterion: 'we'll discontinue if X by Y date'. Forces the conversation about what success and failure actually look like.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Best roadmap row format for an AI feature?",
        options: ["Gantt chart with weekly milestones", "Hypothesis + metric + kill criterion + 4-6 week horizon", "Just the project name", "Detailed PRD link"],
        answer: 1,
        explain: "AI ships in evidence loops, not Gantt swim-lanes.",
      }),
      spark("The 6-week-or-die rule", {
        type: "microread",
        title: "Force the kill review",
        body: "AI features rot in roadmaps because no one wants to admit one isn't working. Pre-commit: every AI feature gets a 6-week review. The review has three options — double down, simplify, or kill. 'Keep going as-is' isn't on the menu. Linear, Vercel, and Notion all run versions of this. It's not harsh; it's the only thing that frees the team to bet again.",
        takeaway: "6-week review with kill-option. Default-yes to revisiting.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Map each roadmap signal to the right next step",
        pairs: [
          { left: "Feature retention is great, cost is brutal", right: "Simplify (smaller model, caching)" },
          { left: "Engagement is meh, retention is meh", right: "Kill" },
          { left: "Power users love it, mass users ignore", right: "Double down + reposition" },
          { left: "Nobody uses it, but it demos great", right: "Kill — demos are not validation" },
        ],
        explain: "Read the four cells before committing another sprint.",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Your AI feature's NPS is high, retention is flat, and inference cost is 4x what you projected.",
        prompt: "Best move?",
        options: [
          "Double down — NPS is high",
          "Cut cost first (smaller model, caching, BYO-key tier) and re-examine retention in 4 weeks",
          "Kill it",
          "Raise prices",
        ],
        answer: 1,
        explain: "Cost is the easy fix. Retention is the hard one. Kill candidates need both legs broken.",
      }),
      spark("Build card: Public roadmap with kill-dates", {
        type: "buildcard",
        title: "Ship a public roadmap with kill-criteria",
        pitch: "Force your team to commit to kill criteria publicly. The discipline lands faster than any process doc.",
        promptToCopy: "Build a single-page Next.js site with three columns — Now, Next, Later. Each card has: title, hypothesis, target metric + value, expected kill-or-keep date. Pull from a JSON file in the repo so non-eng can edit via PR. Deploy to Vercel.",
        successCriteria: "A non-engineer can edit the JSON, open a PR, and see it live within 5 minutes. Each card visibly shows its kill date.",
      }),
      spark("Sequence the autonomy ladder by user trust earned", {
        type: "microread",
        title: "Don't skip rungs",
        body: "Cursor moved from 'autocomplete a line' → 'rewrite a function' → 'agent edits the codebase' over three years. Each rung shipped only after the prior one had earned trust. PMs who try to ship rung 4 from rung 1 (e.g. 'autonomous AI lawyer' as a v1) lose the user before the model is even the bottleneck. Sequence: assist → draft → act-with-undo → autonomous. Don't skip.",
        takeaway: "Don't skip autonomy rungs. Trust is earned linearly.",
        category: "pattern",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "Cursor became the most-used AI code editor by climbing one rung at a time: first it just suggested a single line; then it suggested a whole function; then it became an agent that could edit a whole codebase. Each step waited until users trusted the previous step. Skipping rungs (a v1 'autonomous AI lawyer'?) is how AI products burn early goodwill before they even have a chance to be smart enough.",
        },
      }),
    ]),
    level(T, 8, "Measuring AI quality", "Beyond accuracy.", 4, [
      spark("Multi-axis quality", {
        type: "microread",
        title: "Five axes of quality",
        body: "Don't reduce AI quality to 'accuracy'. Track (1) correctness, (2) helpfulness, (3) safety, (4) latency, (5) cost. Score each on every release. Trade-offs are normal — a faster model may lose 2 points correctness. Show the trade-off explicitly so leadership can pick.",
        takeaway: "Quality is a 5D shape. Show all axes.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Make a single 'AI Quality Radar' chart in your weekly review. 5 axes, before/after each release. Forces honest trade-off conversations.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Latency is a quality axis", {
        type: "microread",
        title: "Slow correct beats nothing — barely",
        body: "Users abandon AI features that take more than ~3 seconds to start showing output. So latency isn't an engineering metric — it's a quality metric. ChatGPT's biggest UX innovation was streaming. Cursor's was sub-second autocomplete. The PM trade you'll face: a 3% smarter model that's 2× slower. Sometimes the right call is the dumber-but-faster one. Measure perceived latency (time-to-first-token), not just total latency.",
        takeaway: "Time-to-first-token is the quality metric. Total time is second.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Two model options. Same accuracy. A: 4s total, 0.3s to first token. B: 2s total, 1.5s to first token. Which feels better?",
        options: ["A — fewer total seconds", "B — fewer total seconds", "A — first token in 0.3s, user feels engaged", "Same"],
        answer: 2,
        explain: "Perceived latency is dominated by time-to-first-token.",
      }),
      spark("Cost-per-correct-answer", {
        type: "microread",
        title: "The metric that beats both",
        body: "Cost-per-token misleads. Accuracy alone misleads. The synthesis metric: cost-per-correct-answer = inference cost / (eval pass rate × queries). A model that's 30% cheaper but 10% less accurate often has worse cost-per-correct because retries and human review eat the saving. Track this from week one. It changes which trade-offs you'd accept.",
        takeaway: "Cost-per-correct beats cost-per-token. Always.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "On every model evaluation, compute (cost × queries) ÷ (eval pass rate). The cheapest model on this number is rarely the cheapest on raw price.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the quality complaint to the axis it's hitting",
        pairs: [
          { left: "'It's right but takes forever'", right: "Latency" },
          { left: "'It made up a number'", right: "Correctness" },
          { left: "'It refused something fine'", right: "Helpfulness" },
          { left: "'It cost us $4k yesterday'", right: "Economics" },
        ],
        explain: "Different axes, different fixes. Don't conflate them in standup.",
      }),
      spark("Helpfulness is the most-skipped axis", {
        type: "microread",
        title: "Beyond correctness",
        body: "Most AI quality dashboards measure correctness obsessively, helpfulness barely. But a 'correct' answer that solves nothing is the most common user complaint. Score every eval row on a second axis: 'did this move the user forward?' Linear's AI triage scores high on this; many AI search tools don't. Helpfulness drives retention; correctness drives trust. You need both.",
        takeaway: "Score correctness AND helpfulness. They're different.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "Your AI search returns the right paper — but as a 600-word academic abstract when the user asked 'what should I do?'",
        prompt: "Best metric to track first?",
        options: [
          "Accuracy on the eval set",
          "Helpfulness — did the answer move the user forward?",
          "API latency",
          "Cost per token",
        ],
        answer: 1,
        explain: "Correct without helpful is unshipped.",
      }),
    ]),
    level(T, 9, "AI feedback loops", "User feedback → better model.", 4, [
      spark("Closed loops win", {
        type: "microread",
        title: "Build the data flywheel",
        body: "Every thumbs-up/down, every regenerate, every edit is gold. Capture it tagged with the prompt and output. Over months you build a labeled dataset that powers fine-tunes, eval sets, and prompt tuning. Products with feedback loops compound; products without plateau.",
        takeaway: "Capture every signal. Compound monthly.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Implicit > explicit", {
        type: "microread",
        title: "What 'regenerate' really means",
        body: "Explicit feedback (thumbs-up/down) gets ignored 95% of the time. Implicit feedback (the user regenerated, the user edited the output, the user copied half and rewrote half) is gold and ubiquitous. Track every edit a user makes after an AI output: distance edited = quality signal. Cursor knows this — every accept-vs-reject of a suggestion is a training signal. Build for the silent thumbs.",
        takeaway: "Edits and regenerates beat thumbs. Build for the silent.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Log diff distance between AI output and what the user kept. Plot the distribution weekly. The fat right tail is your eval set's next 50 cases.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Highest-quality feedback signal on an AI feature?",
        options: ["Star rating in app store", "How much the user edited the AI's output before accepting", "NPS survey", "Twitter mentions"],
        answer: 1,
        explain: "Edit distance is honest. Stars and surveys are not.",
      }),
      spark("The 👎 with reason", {
        type: "microread",
        title: "Critique tags > free text",
        body: "Free-text 'why' on a 👎 gets used <2% of the time. Six pre-made tags ('too long', 'wrong', 'tone off', 'missed the question', 'too generic', 'unsafe') get used 30%+. Pick the right six for your feature and put them on the 👎 click. The signal density goes up 15× and the data is queryable. LearnAI's own product uses this exact pattern.",
        takeaway: "Six critique tags > free text 'why'.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match the feedback shape to the right next action",
        pairs: [
          { left: "👎 with 'too generic'", right: "Tighten retrieval / context" },
          { left: "👎 with 'wrong'", right: "Add to hard-eval set" },
          { left: "👎 with 'tone off'", right: "Adjust system prompt" },
          { left: "👍 with regenerate next turn", right: "Probably accidental thumbs" },
        ],
        explain: "The same downvote means different things. Tags route to different fixes.",
      }),
      spark("Scenario", {
        type: "scenario",
        setup: "You ship a 👍/👎 + tag UI. Three weeks in, 'too generic' is 60% of all 👎s.",
        prompt: "First fix to try?",
        options: [
          "Switch models",
          "Audit your retrieval / context — generic answers usually mean thin context",
          "Hide the feedback button",
          "Buy more user research",
        ],
        answer: 1,
        explain: "'Generic' is almost always a context problem, not a model problem.",
      }),
      spark("Build card: Edit-distance logger", {
        type: "buildcard",
        title: "Log edit distance on every AI output",
        pitch: "Implicit feedback is your richest signal. This card adds it in a day.",
        promptToCopy: "In our existing AI text-output component, capture: original AI output, final user-saved version, Levenshtein distance, percent kept. Send to PostHog as a custom event with sparkId, userId, model. Add a Grafana dashboard panel showing P50/P90 edit distance per model version.",
        successCriteria: "Each save fires the event. Dashboard shows distribution by model version. You can answer 'did model upgrade reduce edits' from the data.",
      }),
      spark("Compounding feedback is a moat", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "The model is a commodity. The fine-tune dataset built from your users is not. Whoever builds the loop fastest has the only durable advantage.",
        takeaway:
          "Models will keep leveling. Your feedback corpus is the only asset that compounds privately. Treat it like cash, not exhaust.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Tomer London",
          guestRole: "co-founder, Gusto",
          episodeTitle: "Building an AI moat in regulated SaaS",
          timestamp: "00:00:00",
        },
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Set a quarterly 'feedback freshness' goal: every model regression on regen frequency should pull in 50 new eval rows from last week's logs. The corpus should grow faster than the userbase.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("The two metrics every AI feature needs", {
        type: "microread",
        title: "Adoption × retention",
        body: "An AI feature is healthy when both adoption (% of WAU who used it this week) and retention-after-trial (% of users who came back twice) are climbing. One without the other is a trap. High adoption + low retention = novelty. Low adoption + high retention = niche. The 2×2 makes it crisp: only the 'climbing both' cell survives the year. Notion AI lives there. Many AI sidebar features don't.",
        takeaway: "Adoption × retention 2×2. Only one cell ships.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Diagnose the AI feature in each cell of the adoption × retention 2×2",
        pairs: [
          { left: "High adoption, low retention", right: "Novelty — kill or rebuild" },
          { left: "Low adoption, high retention", right: "Niche — reposition or accept" },
          { left: "High adoption, high retention", right: "Compound — invest more" },
          { left: "Low adoption, low retention", right: "Wrong feature — kill" },
        ],
        explain: "The 2×2 dictates the next move every time.",
      }),
      spark("Build card: Critique-tag dashboard", {
        type: "buildcard",
        title: "Surface critique tags weekly",
        pitch: "If you ship the 6-tag 👎 UI without a dashboard, the data sits in a database. This card makes it visible.",
        promptToCopy: "Build a Streamlit (or Next.js) dashboard reading from our PostHog feedback events. Show: top 6 critique tags this week, week-over-week delta, and one example output per tag (anonymized). Email it to me every Monday at 9am.",
        successCriteria: "Dashboard loads in <2s, Monday email arrives, you can answer 'what's the #1 thing to fix this week' in 30 seconds.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Strongest signal that an AI feature has reached escape velocity?",
        options: [
          "It trended on Hacker News",
          "Adoption AND retention-after-trial both climbed for 4 consecutive weeks",
          "VCs are reaching out",
          "Lots of demos requested",
        ],
        answer: 1,
        explain: "Both metrics climbing for a month is the only durable signal.",
      }),
      spark("Karri Saarinen on opinionated defaults", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "We don't ship a settings panel for an AI feature on day one. We ship the right default and learn what people complain about. Settings are a tax on everyone to please ten percent.",
        takeaway:
          "Opinionated defaults beat configurable shrugs. Save the settings panel for the moment a real user can't be made happy without it.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Karri Saarinen",
          guestRole: "co-founder, Linear",
          episodeTitle: "Building Linear: opinions, taste, and AI",
          timestamp: "00:00:00",
        },
      }),
    ]),
    level(T, 10, "Boss: AI PM check", "Final boss.", 6, [
      spark("The job is taste under uncertainty", {
        type: "microread",
        title: "Capstone microread",
        body: "Three years into AI PM, the durable skill isn't 'know the latest model'. It's taste under uncertainty: pick the one feature in ten that compounds, kill the nine that don't, and have the eval set to prove which is which. The PMs who win aren't the most technical or the most creative — they're the most willing to commit, measure, and revise in public.",
        takeaway: "Taste + evidence + public revision. That's the AI PM job.",
        category: "principle",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "After three years of AI being everywhere, the AI product manager job has settled into one durable skill: making the right call when nobody knows the answer yet. That means picking the one idea in ten that compounds, killing the nine that don't, and having an eval set so you can *prove* which was which. The best AI PMs aren't the most technical or the most creative — they're the most willing to commit publicly, measure, and change their minds when the data says so.",
          kid: "An AI product manager's job is to make smart bets when nobody knows the right answer. They pick one idea out of ten to keep, drop the rest, and write a list of test questions to prove they were right. The best ones aren't the smartest in the room — they're the ones who say 'I was wrong, here's the new plan' the fastest.",
        },
      }),
      spark("Lenny's parting shot", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "The PM job in AI isn't going away. It's getting harder, smaller, and more important. Fewer PMs per company, but the ones who survive are doing the work of three.",
        takeaway:
          "The job consolidates. PMs who can write specs, write code, and read evals — three skills in one head — own the new center.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Lenny Rachitsky",
          guestRole: "host, Lenny's Podcast",
          episodeTitle: "What the next 12 months look like for PMs",
          timestamp: "00:00:00",
        },
        ctaPrompt:
          "List three skills you don't have today that an AI-native PM needs. Pick the smallest one. Spend a week on it. Repeat.",
      }),
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: AI PM",
        questions: [
          {
            type: "quickpick",
            prompt: "Most underrated PM artifact for AI features?",
            options: ["Press release", "Eval set", "Pitch deck", "OKR doc"],
            answer: 1,
            explain: "Evals are your spec.",
          },
          {
            type: "quickpick",
            prompt: "User asks for autonomous expense booking. Right roadmap step?",
            options: ["Ship full autopilot day 1", "Start with suggest + 1-tap accept, climb the ladder", "Manual only forever", "Auto-book + email if wrong"],
            answer: 1,
            explain: "Autonomy is earned by trust + evals.",
          },
          {
            type: "quickpick",
            prompt: "Best signal that an AI feature is sustainable?",
            options: ["High API calls", "Cost per user trends down or stable as usage grows", "Lots of integrations", "PR mentions"],
            answer: 1,
            explain: "Unit economics, always.",
          },
        ],
      }),
    ]),
  ],
};
