import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "ai-trends" as const;

export const aiTrends: Topic = {
  id: T,
  name: "AI Trends",
  emoji: "📈",
  tagline: "Where the field is moving — and why it matters to builders.",
  color: "#ffb547",
  visual: "trend",
  levels: [
    level(T, 1, "Reasoning models everywhere", "From chat to thinking.", 4, [
      spark("The reasoning era", {
        type: "microread",
        title: "Why reasoning models exploded",
        body: "Through 2025-2026, every frontier lab shipped 'thinking' modes. Claude with extended thinking, o-series from OpenAI, Gemini Thinking, DeepSeek-R1 open weights. The pattern: same base model, but allowed to generate hidden reasoning before the answer. Effect: huge gains on math, code, planning. Cost: more tokens, more latency. Builders learn to route — fast model for chat, reasoning for hard.",
        takeaway: "Reasoning is now an option, not a feature. Route per task.",
        category: "news",
        addedAt: "2026-02-01",
        bodyByAgeBand: {
          teen: "Models can now 'think out loud' before answering. Claude, GPT, Gemini all have a thinking mode. Same brain, but it pauses to reason. Better at hard math, code, logic — but slower and pricier. Builders pick the mode per question: snappy for chat, thinky for hard.",
        },
      }),
      spark("50/50 odds on superintelligence by 2028", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "I think 50th-percentile chance of hitting some kind of superintelligence is now like 2028.",
        takeaway:
          "One of the people who built GPT-3 thinks superintelligence has 50/50 odds inside three years. You don't have to agree — but if you don't have a position on this, your career strategy is borrowed.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Benjamin Mann",
          guestRole: "co-founder of Anthropic, GPT-3 architect at OpenAI",
          episodeTitle: "Inside Anthropic — alignment, scaling, AGI timelines",
          timestamp: "00:00:06",
        },
      }),
      spark("Claude Opus 4.7 lands", {
        type: "microread",
        title: "Opus 4.7: thinking, but cheaper",
        body: "Anthropic's Opus 4.7 ships with extended thinking on by default and a 1M-context option in beta. The headline: same SWE-bench numbers as 4.5, ~30% lower per-token price, and a new 'compact' thinking mode that uses fewer reasoning tokens before answering. Builders rotating off 4.5 see immediate cost wins on coding agents.",
        takeaway: "Cheaper reasoning makes 'always think' affordable for more flows.",
        category: "news",
        addedAt: "2026-05-01",
        source: { name: "Anthropic", url: "https://www.anthropic.com/news" },
      }),
      spark("Reasoning vs chat: cost gap", {
        type: "microread",
        title: "Reasoning costs 5-15x chat",
        body: "A typical reasoning call burns 3,000-15,000 hidden 'thinking' tokens before answering — invisible to the user, billed to you. For a chat where speed matters, default to a fast model (Haiku, GPT-4.1-mini, Gemini Flash). Save Opus, o3, Gemini Thinking for math, code, planning, ambiguous specs. Routing alone cuts most teams' bills 50%.",
        takeaway: "Don't pay reasoning prices for hello-world chats.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("DeepSeek-R1's open shock", {
        type: "microread",
        title: "When open weights caught up on reasoning",
        body: "DeepSeek-R1 (Jan 2025) showed open-weight models could match o1-class reasoning at a fraction of the cost. Released MIT-licensed with full distilled variants. Hugging Face downloads broke records. The aftershock: Meta, Mistral, Qwen, and others accelerated their own reasoning roadmaps. Closed labs no longer own the reasoning frontier.",
        takeaway: "Open-weight reasoning is real. Closed labs lost the moat in months.",
        category: "news",
        addedAt: "2026-05-01",
        source: { name: "Hugging Face", url: "https://huggingface.co/blog" },
      }),
      spark("Hidden reasoning tokens", {
        type: "tip",
        title: "Tip: ask for the thinking",
        body: "Most reasoning models hide their thinking by default. For debugging, set the API to expose the thinking trace — you'll catch wrong assumptions, see when the model gives up, and write better evals. Anthropic, OpenAI, and Google all support this.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check: reasoning routing", {
        type: "quickpick",
        prompt: "Why route reasoning models per task?",
        options: ["Habit", "Reasoning costs 5-15x — only worth it on hard tasks", "Branding", "API requirement"],
        answer: 1,
        explain: "Cost gap is the whole game.",
      }),
      spark("Match the era", {
        type: "patternmatch",
        prompt: "Match the model to its era",
        pairs: [
          { left: "GPT-3.5 (2022)", right: "Pure chat" },
          { left: "Claude Opus 4.7 (2026)", right: "Reasoning by default" },
          { left: "DeepSeek-R1 (2025)", right: "Open reasoning" },
          { left: "Gemini Thinking (2025)", right: "Multimodal reasoning" },
        ],
        explain: "The line moved from chat → reasoning in three years.",
      }),
      spark("Pick the right model", {
        type: "scenario",
        setup: "You're building a customer-support bot. 90% of tickets are 'where's my refund'. 10% are billing-edge-cases that need real thought.",
        prompt: "How do you spend?",
        options: [
          "Opus 4.7 for everything (safe)",
          "Route: Haiku for the easy 90%, Opus for the 10%",
          "Self-host DeepSeek-R1",
          "Skip AI for this",
        ],
        answer: 1,
        explain: "Routing pays for itself the first day.",
      }),
      spark("Thinking budgets", {
        type: "tip",
        title: "Tip: cap thinking tokens",
        body: "Most APIs let you set a max thinking budget (e.g. 8k tokens). Without it, an Opus or o3 call can quietly burn 50k tokens on an easy task. Set per-route budgets — cheap routes 2k, hard routes 30k.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Build a 2-line model router", {
        type: "buildcard",
        title: "Build a 2-line model router",
        pitch: "Most apps don't need a fancy framework. A 20-line router saves 50% on bills.",
        promptToCopy: "Write me a small TypeScript helper that picks between Anthropic Haiku and Anthropic Opus based on input length, presence of code, and a 'difficulty' enum from the caller. Include a unit test.",
        successCriteria: "You have a function `pickModel(input, hint) → 'haiku' | 'opus'` and a test suite green.",
      }),
      spark("Reasoning self-consistency", {
        type: "microread",
        title: "Self-consistency: cheap accuracy bump",
        body: "On hard math/logic, sample N=5 reasoning traces and pick the majority answer. Used by AlphaCode-2, OpenAI's o1, and many open-source recipes. Costs N× tokens, gains 5-15 accuracy points on benchmarks like MATH and AIME. Diminishing returns past N=10.",
        takeaway: "Sample-and-vote is a free accuracy tier.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: thinking traces", {
        type: "quickpick",
        prompt: "Why expose the thinking trace during dev?",
        options: ["For show", "Catch wrong assumptions and where it gives up", "Token padding", "Required by EULA"],
        answer: 1,
        explain: "Traces are the best free debugger you have.",
      }),
    ]),
    level(T, 2, "Agents go mainstream", "From demos to production.", 4, [
      spark("Beyond toy demos", {
        type: "microread",
        title: "Agents become work",
        body: "By 2026, agentic coding (Claude Code, Devin, Cursor Agent) became default in many engineering teams. Customer-support agents, research agents, ops agents quietly handle most ticket triage at top SaaS. Pattern: narrow scope + tight tools + good evals + human approval for risky steps. Wide-open 'do anything' agents still flop.",
        takeaway: "Narrow, tool-rich, supervised agents — that's what works.",
        category: "news",
        addedAt: "2026-02-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When pitching an agent, name the 5 specific tasks it handles. Vague 'AI assistant' pitches lose to specific 'AI that drafts your weekly report from these 4 dashboards'.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("November 2025: agents crossed the threshold", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "In November we had what I call the inflection point where GPT 5.1 and Claude Opus 4.5 came along. Previously you had to pay very close attention. Suddenly we went from that to almost all of the time it does what you told it to do, which makes all of the difference in the world.",
        takeaway:
          "Late-2025 is the year coding agents crossed the threshold from experimental to reliable. If you tried agents in summer '25 and bounced — you owe yourself another look.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Simon Willison",
          guestRole: "co-creator of Django, coined 'prompt injection'",
          episodeTitle: "The November inflection: AI coding crosses the threshold",
          timestamp: "00:04:23",
        },
      }),
      spark("Agent loops 101", {
        type: "microread",
        title: "Why an agent is just a loop",
        body: "An agent is a model in a while-loop with tools. Plan → call tool → observe result → revise → repeat until done or budget hit. Claude Code, Cursor Agent, Devin all share this skeleton. The hard part is not the loop — it's the tools, the system prompt, and stopping conditions. Most failed agent demos failed at one of those three.",
        takeaway: "Agent = model + loop + tools + a stop rule.",
        category: "principle",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "An agent is a model running in a loop. It plans, calls a tool, sees the result, decides what to do next, repeats. Claude Code is one big loop with file-edit, bash, and grep as tools. The trick isn't the loop — it's giving the model the right tools and a clear way to know it's done.",
        },
      }),
      spark("MCP becomes plumbing", {
        type: "microread",
        title: "Model Context Protocol everywhere",
        body: "Anthropic shipped MCP in late 2024 as an open standard for connecting tools to agents. By 2026, GitHub, Notion, Linear, Slack, Stripe, and every IDE shipped MCP servers. One agent, hundreds of tools, no per-vendor glue. It's USB-C for AI tools.",
        takeaway: "MCP is the boring win. Build against it, not bespoke wrappers.",
        category: "tooling",
        addedAt: "2026-05-01",
        source: { name: "Anthropic", url: "https://www.anthropic.com/news" },
      }),
      spark("Devin, Cursor Agent, Claude Code", {
        type: "microread",
        title: "Three agents, three philosophies",
        body: "Devin (Cognition): autonomous, runs in a sandbox VM, you check back later. Cursor Agent: in your IDE, in your face, fast loops with diffs. Claude Code: terminal-native, scriptable, Unix-philosophy. They overlap, but pick by where you want the human in the loop. Most teams end up running two.",
        takeaway: "Different loops for different jobs. Pick by HITL placement.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tool selection beats prompt poetry", {
        type: "tip",
        title: "Tip: agents fail on tools, not prompts",
        body: "When an agent gets stuck, 80% of the time the bug is in the tool: bad description, missing schema, ambiguous return values, no error mode. Polish your tool definitions before you polish the prompt.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Async agent inflection", {
        type: "microread",
        title: "From sync chat to async agents",
        body: "2026 product UX shift: agents leave chat. They go take 20 minutes, file a PR, post in Slack, ping you when done. ChatGPT Tasks, Devin, Claude background agents — same pattern. The chat box is no longer the surface; the inbox is.",
        takeaway: "Build for inbox UX, not chat UX, when work takes minutes.",
        category: "pattern",
        addedAt: "2026-05-01",
      }),
      spark("Quick check: agent failures", {
        type: "quickpick",
        prompt: "Most likely cause of an agent getting stuck mid-task?",
        options: ["Bad model", "Tool with vague description or no error mode", "Slow network", "Wrong day of week"],
        answer: 1,
        explain: "Agents fail at the tool boundary far more often than at the model.",
      }),
      spark("Match the agent surface", {
        type: "patternmatch",
        prompt: "Match the agent to its native UX",
        pairs: [
          { left: "Cursor Agent", right: "In-IDE diffs" },
          { left: "Devin", right: "Async sandbox VM" },
          { left: "Claude Code", right: "Terminal + scripts" },
          { left: "ChatGPT Tasks", right: "Inbox-style results" },
        ],
        explain: "Same loop, different placement of the human.",
      }),
      spark("Pick a scope", {
        type: "scenario",
        setup: "Your team wants 'an AI agent that handles ops'. Your CTO wants a demo Friday.",
        prompt: "What scope ships?",
        options: [
          "Wide-open agent that triages all incidents",
          "Narrow agent that closes 3 specific runbook types end-to-end",
          "Chatbot that answers ops questions",
          "Wait for a better model",
        ],
        answer: 1,
        explain: "Narrow + end-to-end > wide + half-baked.",
      }),
      spark("Build a runbook agent", {
        type: "buildcard",
        title: "Wire one runbook to Claude Code",
        pitch: "Pick the most repetitive 30-min ops task you do. Make Claude Code do it.",
        promptToCopy: "Read /docs/runbooks/restart-stuck-jobs.md. Build me a slash command that does steps 1-7 of that runbook with my approval at the destructive step. Use bash and grep tools only.",
        successCriteria: "Slash command runs, asks for approval before deletion, prints a summary at the end.",
      }),
      spark("AlphaSignal: agent of the week pattern", {
        type: "microread",
        title: "Curated agent drops weekly",
        body: "AlphaSignal's daily AI digest started a 'Agent of the Week' column in 2026, surfacing one production-grade agent each Friday. Pattern across drops: scoped to one workflow, owns one tool deeply, ships an eval set with the launch post. The discipline of one-tool-per-agent keeps shipping.",
        takeaway: "One agent, one workflow, one eval set. Read AlphaSignal Fridays.",
        category: "news",
        addedAt: "2026-05-01",
        source: { name: "AlphaSignal", url: "https://alphasignal.ai/archive" },
      }),
      spark("Eval-driven agents", {
        type: "tip",
        title: "Tip: write the eval before the agent",
        body: "Pick 20 real tasks. Write the expected output. THEN build the agent. Run the eval after every prompt change. Without this you're flying blind — an agent feels great until it fails on a Tuesday.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 3, "Multimodal as default", "Text, image, audio, video.", 4, [
      spark("One model, many senses", {
        type: "microread",
        title: "Multimodal everywhere",
        body: "Frontier models now handle image input by default and increasingly handle audio + video. Use cases exploding: screenshot-to-code, voice agents, video summarization, document understanding. Builder shift: design UX assuming users will paste screenshots, drag video, talk into a mic.",
        takeaway: "Plan for users to paste anything — image, audio, doc.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Gemini Thinking goes multimodal", {
        type: "microread",
        title: "Reasoning over images and video",
        body: "Gemini Thinking (Google DeepMind, 2025) was the first widely-available model that reasoned over video natively — given a 30-min meeting recording, it can produce a step-by-step decision log and quote timestamps. Use cases: deposition analysis, sports clip review, accessibility captioning.",
        takeaway: "Reasoning + video unlocks a whole category of products.",
        category: "news",
        addedAt: "2026-05-01",
        source: { name: "Google DeepMind", url: "https://deepmind.google/discover/blog/" },
      }),
      spark("Screenshot-to-code", {
        type: "microread",
        title: "Paste a screenshot, get a component",
        body: "v0, bolt.new, Claude Artifacts, Cursor — all default to 'paste an image, get React/Tailwind/whatever'. The bar for 'I have an idea' → 'I have a working UI' is now seconds. The new bottleneck is taste, not implementation.",
        takeaway: "Image-to-UI flipped the design-to-code pipeline.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Voice agents take off", {
        type: "microread",
        title: "Why 2026 is the voice agent year",
        body: "Realtime voice APIs (OpenAI Realtime, Gemini Live, ElevenLabs Conversational) crossed the 'feels human' bar. Sub-500ms turnaround, interruption handling, emotion in voice. Real businesses (clinics, restaurants, sales) replaced phone trees with voice agents in 2026.",
        takeaway: "Voice agents are the new IVR — and the new lead-gen channel.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Tip: feed images, not OCR'd text", {
        type: "tip",
        title: "Tip: stop OCR-ing first",
        body: "If your model is multimodal, send the raw image. OCR loses layout, tables, signatures, handwriting. Modern vision models are better than your OCR pipeline at most documents.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Document understanding", {
        type: "microread",
        title: "PDFs are a solved-ish problem",
        body: "Claude, Gemini, GPT-4o all read PDFs natively now — including scanned, multi-column, bilingual. The legacy stack of Tesseract → layout-parser → custom rules collapsed into one API call. Anthropic ships a dedicated Files API; OpenAI has Assistants. Document AI as a separate product category is shrinking.",
        takeaway: "If you built a doc-AI startup before 2025, your moat moved.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Quick check: multimodal UX", {
        type: "quickpick",
        prompt: "Best UX upgrade for a 2026 AI app?",
        options: ["Auto-dark-mode", "Let users paste screenshots, drag PDFs, talk into a mic", "Faster spinner", "Splash screen"],
        answer: 1,
        explain: "Multimodal input is the new default expectation.",
      }),
      spark("Match the modality", {
        type: "patternmatch",
        prompt: "Match the use case to the modality",
        pairs: [
          { left: "Doctor's note → structured fields", right: "Image input" },
          { left: "Restaurant phone agent", right: "Voice realtime" },
          { left: "30-min Loom → action items", right: "Video reasoning" },
          { left: "Screenshot → React component", right: "Image-to-code" },
        ],
        explain: "Pick the modality that matches the user's natural input.",
      }),
      spark("Build a paste-screenshot lane", {
        type: "buildcard",
        title: "Add paste-screenshot to your form",
        pitch: "Single biggest UX win of 2026: support paste anywhere.",
        promptToCopy: "Add a paste handler to my main input field. If the pasted item is an image, send it to Claude Sonnet with the prompt 'extract structured fields from this screenshot' and pre-fill the form with the result.",
        successCriteria: "User pastes a screenshot of a receipt → form auto-fills with vendor, total, date.",
      }),
      spark("Synthesia + Sora moment", {
        type: "microread",
        title: "Generative video crosses 'good enough'",
        body: "Sora 2, Veo 2, Runway Gen-4 — all crossed the 'commercials and ad shoots are noticing' bar in 2025-2026. Real shops use them for previz, ad variants, social content. Long-form film still loses; short-form social is now half-AI on platforms like TikTok and Reels.",
        takeaway: "Generative video is good enough for short-form. Treat it as a tool, not a threat.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Vision evals look different", {
        type: "tip",
        title: "Tip: image evals need image fixtures",
        body: "Don't eval a vision feature with text-only test cases. Build a fixture set of 50-100 real screenshots, photos, scans your users actually send. Re-run on every model change. Vision regressions silently sneak through text evals.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Long-context multimodal", {
        type: "microread",
        title: "1M-token windows include images",
        body: "Gemini 2.5 Pro and Claude 4.7 with 1M context can ingest hundreds of images in one call. Use case: ingest a whole product catalogue (with photos), or a film's storyboard, or every receipt from a quarter. Pricing tip: image tokens are 1.5-3x text — budget hard.",
        takeaway: "Whole-document, multi-image reasoning is real and budget-sensitive.",
        category: "news",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 4, "Open weights catching up", "Llama, DeepSeek, Mistral, Qwen.", 4, [
      spark("Closed vs open gap", {
        type: "microread",
        title: "The open weights wave",
        body: "Open-weight frontier-class models (DeepSeek, Llama, Qwen, Mistral) closed much of the gap with closed APIs in 2025. They run on your own infra, fine-tune freely, and are perfect for regulated industries. They lag closed models on the hardest benchmarks, but for 80% of product use cases they're plenty.",
        takeaway: "Open is a real option now. Pick by use case + regulation.",
        category: "news",
        addedAt: "2026-02-01",
        bodyByAgeBand: {
          teen: "Free-to-download models like Llama, DeepSeek, Qwen, Mistral got nearly as good as Claude or GPT in 2025. You can run them on your own laptop or server, change them, fine-tune them. They aren't best-in-class on the hardest stuff yet, but for most apps they work fine — and they're free.",
        },
      }),
      spark("Llama 4 ships open MoE", {
        type: "microread",
        title: "Meta's MoE bet",
        body: "Llama 4 (Meta, 2025-2026) shipped as a Mixture-of-Experts: many specialist sub-networks, only a few activate per token. Result: bigger total parameter count at smaller per-token cost. Hugging Face downloads exploded. The OSS ecosystem now ships fine-tunes, GGUF quants, and Ollama recipes within hours of release.",
        takeaway: "MoE makes 'big and cheap' real for open weights.",
        category: "news",
        addedAt: "2026-05-01",
        source: { name: "Hugging Face", url: "https://huggingface.co/blog" },
      }),
      spark("Qwen quietly leads on Chinese-language", {
        type: "microread",
        title: "Qwen owns multilingual",
        body: "Alibaba's Qwen series leads many open-weight benchmarks for Chinese, Arabic, Japanese, and other non-English tasks. If your product serves a global audience, Qwen + a fine-tune outperforms most US-trained open models on non-English work, often by 10-20 points.",
        takeaway: "Pick the open model trained where your users speak.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Mistral's small model lane", {
        type: "microread",
        title: "Mistral bets on small + fast",
        body: "Mistral's strategy: ship the smallest possible model that beats incumbents at a tier. Mistral 7B, then Mixtral, then Mistral Small/Large/Codestral. They show up on the European cloud (Mistral La Plateforme) and inside AWS Bedrock as a sovereign-cloud option for EU enterprises.",
        takeaway: "Mistral = the EU sovereign-cloud open model.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: pick by task, not vibes", {
        type: "tip",
        title: "Tip: benchmark on YOUR tasks",
        body: "Open weights move fast. Don't trust last month's blog post. Build a 50-task eval set from your real user prompts. Run it monthly against the top 5 open + 5 closed models. Pick the cheapest model that crosses your accuracy bar.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("When open beats closed", {
        type: "microread",
        title: "Three reasons to pick open",
        body: "(1) Regulated data — health, defense, gov — can't leave your VPC. (2) Heavy fine-tuning — domain-specific models you control. (3) Volume cost — at >50M tokens/day, hosted open beats per-token closed APIs. Otherwise closed wins on raw quality + ops simplicity.",
        takeaway: "Open wins on data control, fine-tune freedom, and scale economics.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Hosted open: Together, Fireworks, Groq", {
        type: "microread",
        title: "Open weights, hosted infra",
        body: "Don't want to run GPUs but want open models? Together AI, Fireworks, Groq, Replicate host every major open model behind one API. Same OpenAI-compatible interface, $0.20-$2 per million tokens, dedicated endpoints if you grow. The 'best of both' middle path.",
        takeaway: "Hosted open = open model freedom, no GPU ops.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check: open vs closed", {
        type: "quickpick",
        prompt: "Strongest reason to pick an open-weight model?",
        options: ["Lower latency", "Data control + fine-tune freedom + scale economics", "Better marketing", "Smaller files"],
        answer: 1,
        explain: "Those three are the moat. Quality alone rarely is.",
      }),
      spark("Match the open model", {
        type: "patternmatch",
        prompt: "Match the open model to its sweet spot",
        pairs: [
          { left: "DeepSeek-R1", right: "Cheap reasoning" },
          { left: "Llama 4 MoE", right: "Big general-purpose" },
          { left: "Qwen", right: "Multilingual" },
          { left: "Mistral", right: "EU + small/fast" },
        ],
        explain: "Each open lab picked a lane.",
      }),
      spark("Pick a stack", {
        type: "scenario",
        setup: "You sell to EU pharmacies. You can't send patient data outside the EU. Your product is mostly summarization.",
        prompt: "Default model choice?",
        options: [
          "OpenAI GPT-4o (US-hosted)",
          "Mistral Large via Mistral La Plateforme (EU-hosted)",
          "Self-hosted Llama on your own servers",
          "Skip AI",
        ],
        answer: 1,
        explain: "EU residency + good-enough quality + minimal ops.",
      }),
      spark("Try Llama on Ollama", {
        type: "buildcard",
        title: "Run Llama 4 on your laptop",
        pitch: "30-minute experience. Build the muscle for self-hosting before you bet on it.",
        promptToCopy: "Walk me through installing Ollama on macOS, pulling llama4:8b, and writing a 20-line Node script that streams responses from it. Compare cost & latency vs my Anthropic API.",
        successCriteria: "You ran a local Llama call and have a side-by-side latency + cost note.",
      }),
      spark("Hugging Face Hub: model gravity", {
        type: "microread",
        title: "Why HF is the open ecosystem",
        body: "Hugging Face is the GitHub of models — every open release lands there with weights, model card, eval, and one-click deploy. By 2026, 1M+ models, 200K+ datasets, billions of monthly downloads. Builder muscle: get comfortable searching HF before reaching for an API.",
        takeaway: "Search Hugging Face first. APIs are downstream.",
        category: "tooling",
        addedAt: "2026-05-01",
        source: { name: "Hugging Face", url: "https://huggingface.co/blog" },
      }),
      spark("Tip: quants for the impatient", {
        type: "tip",
        title: "Tip: 4-bit quants run on a Mac",
        body: "Most open models ship as 4-bit GGUF quants within hours of release. A 70B model in 4-bit fits in 40GB RAM — runnable on an M3 Max. Use Ollama or LM Studio. Quality drop is small (~2 points on benchmarks); speed gain is huge.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 5, "On-device AI", "Models in your pocket.", 4, [
      spark("Edge models", {
        type: "microread",
        title: "AI without the cloud",
        body: "Apple Intelligence, Gemini Nano, on-device Phi models bring small but capable models to phones and laptops. Wins: privacy, latency, offline. Use cases: smart text replies, summarization, image edits, intent detection. Hybrid stacks (small on-device + big in cloud) are the new frontier UX.",
        takeaway: "Hybrid: small fast on-device + big smart cloud.",
        category: "news",
        addedAt: "2026-02-01",
      }),
      spark("Apple Intelligence's hybrid bet", {
        type: "microread",
        title: "Apple's on-device + Private Cloud Compute",
        body: "Apple Intelligence runs a 3B-parameter model on-device for most tasks, falls back to Apple's Private Cloud Compute (verifiable, attested) for hard ones. Big chunks of the iPhone OS — notification summarization, writing tools, Smart Reply — never leave your device.",
        takeaway: "Hybrid is the new privacy story: on-device default, attested cloud fallback.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Gemini Nano in Chrome", {
        type: "microread",
        title: "A model in the browser",
        body: "Google ships Gemini Nano inside Chrome via the Prompt API. Web apps can call a local LLM with no server, no key, no cost. Use cases shipping in 2026: reader-mode summary, form autofill, page-level translation. Caveat: only Chrome users, only on hardware that meets a bar.",
        takeaway: "The browser is the newest LLM runtime.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Phi-4 small wonders", {
        type: "microread",
        title: "Microsoft's small-model line",
        body: "Microsoft's Phi series (Phi-3, Phi-4) hits well above its parameter count by training on synthetic 'textbook quality' data. A 3.8B Phi outperforms 70B models on many reasoning tasks. The lesson the field absorbed: data quality beats scale at the small end.",
        takeaway: "Curated synthetic data unlocks tiny capable models.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Tip: don't leak your prompts", {
        type: "tip",
        title: "Tip: on-device prompts are still in your binary",
        body: "Just because the model runs on-device doesn't mean your system prompt is safe — it ships in your app bundle and can be extracted. Use platform encrypted storage and avoid embedding sensitive instructions in client-side prompts.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Battery and thermals are real", {
        type: "microread",
        title: "On-device AI eats battery",
        body: "Continuous on-device inference can drain a phone in 90 minutes. Frame your features around bursty calls — summarize on demand, classify on type, not always-on streams. Apple, Samsung, Qualcomm ship NPUs to ease this, but the budget is real and small.",
        takeaway: "Bursty + on-demand wins. Always-on inference burns batteries.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: pick the modality", {
        type: "quickpick",
        prompt: "Best fit for an on-device 3B model?",
        options: ["Long-form writing assistant", "Smart Reply / summarize a notification / classify intent", "Multimodal video reasoning", "Frontier coding"],
        answer: 1,
        explain: "Small models = small, fast, private tasks.",
      }),
      spark("Match the chip", {
        type: "patternmatch",
        prompt: "Match the on-device runtime to its slot",
        pairs: [
          { left: "Gemini Nano in Chrome", right: "Browser" },
          { left: "Apple Intelligence", right: "iPhone / Mac" },
          { left: "Ollama", right: "Developer laptop" },
          { left: "ONNX Runtime Mobile", right: "Cross-platform mobile" },
        ],
        explain: "Same idea, different runtime.",
      }),
      spark("Hybrid scenario", {
        type: "scenario",
        setup: "You're building a journaling app. Most prompts are private and short. A few times a week the user wants a 'what did I learn this month' synthesis.",
        prompt: "How do you split?",
        options: [
          "All in cloud",
          "Daily small calls on-device, monthly synthesis in cloud",
          "All on-device",
          "Skip AI",
        ],
        answer: 1,
        explain: "Match latency + privacy needs to the call shape.",
      }),
      spark("Build with Chrome's Prompt API", {
        type: "buildcard",
        title: "Add a free on-device summary",
        pitch: "Use Chrome's Gemini Nano to ship a feature with $0 inference cost.",
        promptToCopy: "Show me how to detect Chrome's window.ai availability, fall back to my server endpoint when missing, and summarize the page's main article on a button click.",
        successCriteria: "On Chrome with Gemini Nano: instant local summary. On Safari: server fallback works.",
      }),
      spark("Tip: ship a fallback always", {
        type: "tip",
        title: "Tip: assume the device model is missing",
        body: "On-device APIs like Chrome's Prompt API or iOS Foundation Models gate by device class. Always ship a server fallback. Detect → use local → fall back to your API. Never break for users on older hardware.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Edge inference economics", {
        type: "microread",
        title: "Why on-device flips your unit economics",
        body: "Cloud inference cost scales with usage; on-device cost is amortized into the user's hardware. For a free product with 10M MAU and 100 calls/user/day, going hybrid (90% on-device) can save $1M/month. The downside: capability ceiling and cold-start.",
        takeaway: "Hybrid is the cost moat for free / freemium AI products.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 6, "Synthetic data", "Models training models.", 4, [
      spark("Self-feeding loop", {
        type: "microread",
        title: "Synthetic data goes mainstream",
        body: "Frontier models increasingly train on data generated by other models — sometimes themselves. With careful filtering, this expands data efficiently. Risks: model collapse if done naively (echo chambers), bias amplification. Done well, it's a competitive moat — synthetic eval sets, synthetic instruction tuning, synthetic edge cases.",
        takeaway: "Synthetic data, carefully filtered, is the new fuel.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Phi-4's textbook recipe", {
        type: "microread",
        title: "Why textbook-quality synthetic data wins",
        body: "Microsoft's Phi-4 paper (2024) made the case publicly: small models trained on highly-curated synthetic 'textbook quality' Q&A beat much bigger models trained on raw web crawl. The frontier shifted: data curation matters as much as parameter count. Every lab has a synthetic-data team now.",
        takeaway: "Curation > crawl. Small + clean beats big + dirty.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Synthetic eval sets", {
        type: "microread",
        title: "Generate evals at scale",
        body: "Write a 'meta-prompt' that generates 500 hard test cases for your domain. Have a strong model (Opus, o3) author the cases AND the rubrics. Validate a sample by hand. You now have a 50x bigger eval set than you could write manually — and it runs on every PR.",
        takeaway: "Synthetic evals scale faster than human-written ones.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip: validate before you trust", {
        type: "tip",
        title: "Tip: hand-grade 50 synthetic samples",
        body: "Synthetic datasets can be subtly wrong. Always hand-grade 50+ random samples. Cheap insurance — catches rubric drift, hallucinated answers, format violations before they pollute training.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Model collapse risk", {
        type: "microread",
        title: "When synthetic loops eat themselves",
        body: "Train a model on text generated by itself, train the next model on that, repeat — capabilities collapse as rare-event data drops out of the distribution. Mitigation: keep a strong fraction of fresh human data in every training cycle. The fully-synthetic future stays out of reach, for now.",
        takeaway: "Mix synthetic with fresh human data. Pure loops collapse.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Self-rewarded reasoning", {
        type: "microread",
        title: "RLHF without humans (mostly)",
        body: "Anthropic, OpenAI, DeepMind all shipped variants of 'AI feedback' (RLAIF) where the reward model itself is an AI. Cheaper than human raters, scales further, but less reliable on novel categories. Most stacks now blend: human raters for novel/risky, AI raters for in-distribution.",
        takeaway: "AI feedback scales; human feedback grounds. Use both.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: when synthetic helps", {
        type: "quickpick",
        prompt: "Best place to use synthetic data first?",
        options: ["Training your foundation model", "Generating an eval set + edge cases", "Replacing your DB", "Ad copy"],
        answer: 1,
        explain: "Evals scale fastest, with lowest risk.",
      }),
      spark("Build synthetic edge cases", {
        type: "buildcard",
        title: "Generate 50 nasty test cases",
        pitch: "Most prod bugs hide in edge cases you forgot. Have an LLM imagine them.",
        promptToCopy: "I have an invoice-extraction agent. Generate 50 edge-case invoices in JSON: missing fields, weird currencies, multi-page, hand-written subtotals. For each, give the expected output. Format as JSONL.",
        successCriteria: "You have 50 fixtures, ran your agent on them, found at least 3 real bugs.",
      }),
      spark("Match the synthetic use", {
        type: "patternmatch",
        prompt: "Match the synthetic use to its risk",
        pairs: [
          { left: "Eval set generation", right: "Low risk, high leverage" },
          { left: "Instruction fine-tune data", right: "Medium risk — validate" },
          { left: "Pretraining at scale", right: "High risk — needs human data mix" },
          { left: "Reward model training", right: "Medium — needs grounding" },
        ],
        explain: "Risk scales with how core the loop is.",
      }),
    ]),
    level(T, 7, "AI search rewrites the web", "From links to answers.", 4, [
      spark("Search 2.0", {
        type: "microread",
        title: "Answers replace links",
        body: "Perplexity, ChatGPT search, Google AI Overviews changed search behavior. Builders need to think about being cited (LLM-friendly content, structured data, fast pages, clear factual statements). Direct traffic for many sites is dropping; AI-cited traffic is rising. Brand/product visibility now requires LLM-ready content.",
        takeaway: "Optimize for being cited, not just ranked.",
        category: "news",
        addedAt: "2026-02-01",
      }),
      spark("Perplexity's product wedge", {
        type: "microread",
        title: "Perplexity: search-as-conversation",
        body: "Perplexity ($9B+ valuation by 2025) won a slice of search by making citations native — every answer shows sources inline. The product became a verb in some teams. Their bet: enterprise search ($200/mo seats) where source-trust matters most.",
        takeaway: "Citation-first search is a viable wedge against Google.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Google AI Overviews's traffic shift", {
        type: "microread",
        title: "When the SERP answers itself",
        body: "Google's AI Overviews (rolled out 2024-2025) answer many queries on the search page itself. Publishers report 30-60% drops in click-through for informational queries. Survivors are sites that own a brand, are citable, and convert visitors fast.",
        takeaway: "Informational SEO is shrinking. Brand SEO is growing.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("LLM SEO: be quotable", {
        type: "tip",
        title: "Tip: write to be quoted",
        body: "Write paragraphs that stand alone. Lead with the answer, then justify. Use clean H2 headings tied to questions. Add structured data (FAQPage, HowTo). LLMs cite text that's confident, attributed, and readable in isolation.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("ChatGPT Search and SearchGPT", {
        type: "microread",
        title: "OpenAI moves on search",
        body: "ChatGPT Search (2024-2025) wired live web search into the chat interface. By 2026, half of casual searches at some demographics happen there, not Google. The implication for builders: your content needs to be reachable AND parseable by the live-search subsystem.",
        takeaway: "Two SERPs to optimize for now: Google and ChatGPT.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Tip: ship llms.txt", {
        type: "tip",
        title: "Tip: serve a /llms.txt",
        body: "The emerging convention (proposed by Jeremy Howard, 2024) is to publish a single `/llms.txt` at your domain summarizing your site for LLMs. It's robots.txt for the AI era. Costs nothing, helps you get cited correctly.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check: AI search KPI", {
        type: "quickpick",
        prompt: "Best new KPI for AI-era SEO?",
        options: ["Pageviews", "Citations & branded queries inside AI answers", "Bounce rate", "Time on page"],
        answer: 1,
        explain: "Citations are the new ranking signal.",
      }),
      spark("Match the surface", {
        type: "patternmatch",
        prompt: "Match the AI-search surface to its strength",
        pairs: [
          { left: "Perplexity", right: "Citation-first answers" },
          { left: "Google AI Overviews", right: "Mass-market informational" },
          { left: "ChatGPT Search", right: "In-conversation context" },
          { left: "Claude with web search", right: "Long-form research" },
        ],
        explain: "Each surface has a different gravity.",
      }),
      spark("Build a citable page", {
        type: "buildcard",
        title: "Rewrite your top page for citations",
        pitch: "Pick one page that ranks well. Make it 5x more quotable.",
        promptToCopy: "Read this URL. Rewrite it so each H2 starts with the answer, paragraphs are 2-3 sentences max, and a TL;DR sits at the top. Add FAQPage JSON-LD covering the 8 most likely user questions.",
        successCriteria: "Page reads top-down, has 8+ Q&A in JSON-LD, ranks for at least one new question within 30 days.",
      }),
      spark("Real businesses, real shifts", {
        type: "microread",
        title: "Who's winning AI search",
        body: "Reddit, Wikipedia, Stack Overflow, GitHub, official docs sites, news brands — all over-represented in AI citations. Long-tail informational sites are under-represented. Strategy: get cited on Reddit + Wikipedia + your own brand. Stop trying to win on long-tail SEO — that ground is melting.",
        takeaway: "Get cited on Reddit, Wikipedia, and your brand. Skip long-tail SEO.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 8, "AI copilots → AI co-workers", "From 1 task to many.", 4, [
      spark("Co-worker pattern", {
        type: "microread",
        title: "Co-workers, not copilots",
        body: "The shift from 'copilot helping with one task' to 'co-worker owning a workflow end-to-end' is the next wave. Companies wire agents into Slack, Linear, Salesforce — they take a thread, run the steps, post results, pause for approval. The product surface: not a chat box, but a teammate inside your existing tools.",
        takeaway: "Embed agents where work already happens.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Productivity per engineer is up 200%", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "I have never enjoyed coding as much as I do today, because I don't have to deal with all the minutia. Productivity per engineer has increased 200%.",
        takeaway:
          "The ceiling on what one person can ship has just doubled. The engineers winning right now aren't the ones writing more code — they're the ones giving better instructions to agents.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Boris Cherny",
          guestRole: "head of Claude Code, Anthropic",
          episodeTitle: "How Claude Code rewrites the job of an engineer",
          timestamp: "00:00:21",
        },
      }),
      spark("AI in the org chart", {
        type: "microread",
        title: "When agents take a slot",
        body: "By 2026, several startups (Klarna, Shopify, Cursor, Anthropic itself) shipped 'AI co-worker' patterns where agents own a job-to-be-done — first-line support, a recruiter screener, an SDR — with human escalation. The hiring conversation shifted: don't ask 'can we hire?', ask 'human or agent?'.",
        takeaway: "Hiring decisions now include agent-vs-human.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Slack-native agents", {
        type: "microread",
        title: "Why Slack is the agent UI",
        body: "Most knowledge work happens in Slack. Wiring an agent as a Slack bot puts it on the user's existing surface. Patterns shipping: @ops-bot for runbooks, @docs-bot for searching internal wikis, @triage-bot for support tickets. Lower install friction than another dashboard.",
        takeaway: "Meet users in Slack first. Build a dashboard later, if at all.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip: design the approval loop first", {
        type: "tip",
        title: "Tip: pick the human checkpoint",
        body: "Decide before you build: where does a human approve? After plan, before destructive step, after final result, never? Most successful agent products have exactly one approval point — clear, fast, undoable. Two approvals kills usage; zero kills trust.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Linear's AI engineer pattern", {
        type: "microread",
        title: "Issues that file their own PRs",
        body: "Linear + Cursor + Claude Code patterns: ticket gets a label like 'agent-eligible', a background agent picks it up, opens a PR, links it back. Linear's own product team shipped this internally and reported >50% of Tier-3 bugfixes closed by agents in 2026.",
        takeaway: "Wire your ticket tracker to your agent. Issues become PRs.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check: agent placement", {
        type: "quickpick",
        prompt: "Best first place to put an internal agent?",
        options: ["A new dashboard", "Slack/Teams/Linear where work already happens", "Email", "A separate VPN"],
        answer: 1,
        explain: "Reduce install friction. Meet users where they are.",
      }),
      spark("Match the role", {
        type: "patternmatch",
        prompt: "Match the agent role to its primary tool",
        pairs: [
          { left: "AI SDR", right: "CRM + email" },
          { left: "AI engineer", right: "Linear + Git" },
          { left: "AI support tier-1", right: "Help-desk inbox" },
          { left: "AI ops", right: "Slack + runbooks" },
        ],
        explain: "Pick the tool, then the loop.",
      }),
      spark("Scope a pilot", {
        type: "scenario",
        setup: "Your CFO asks: 'Where do we hire a person versus deploy an agent?' Your team has 3 unfilled roles: SDR, junior eng, recruiter screener.",
        prompt: "Best first pilot?",
        options: [
          "All three become agents",
          "Pick the one with the cleanest, most repetitive 70%: recruiter screener",
          "Junior eng — most code is automatable",
          "None — wait for AGI",
        ],
        answer: 1,
        explain: "Pick the role with the highest repetitive fraction first.",
      }),
      spark("Build a Slack triage agent", {
        type: "buildcard",
        title: "Wire a Slack bot to your support inbox",
        pitch: "Triaging tickets is the perfect first agent: clear scope, fast feedback, low risk.",
        promptToCopy: "Build a Slack bot that watches the #support channel. For every new message, pull the user's last 3 tickets, draft a triage label and a suggested reply, and post both as a thread. Add an 'approve' button that posts the reply for real.",
        successCriteria: "Bot posts triages within 30 seconds, human approves with one click, replies fire as the user.",
      }),
      spark("Tip: track agent attribution", {
        type: "tip",
        title: "Tip: tag every agent action",
        body: "Tag every Slack message, PR, ticket, email an agent ships with `agent:<name>`. Now you can measure: how many actions, success rate, override rate, dollars saved. Without this you can't show ROI and the project gets cut.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 9, "Regulation & policy", "EU AI Act, US executive orders.", 4, [
      spark("Compliance landscape", {
        type: "microread",
        title: "Regulation lands",
        body: "EU AI Act phased in through 2025-2026, classifying systems by risk. US states (CA, NY) ship narrower rules on automated decisions. Builders need: provenance for training data, model cards, risk assessments for high-risk uses. Compliance becomes a product feature — enterprise buyers ask for it before signing.",
        takeaway: "Treat compliance as a product axis, not a tax.",
        category: "news",
        addedAt: "2026-02-01",
      }),
      spark("EU AI Act risk tiers", {
        type: "microread",
        title: "How the EU classifies your system",
        body: "EU AI Act splits AI into: Prohibited (social scoring, real-time biometric ID in public), High-risk (hiring, credit, education), Limited-risk (chatbots, deepfakes — must disclose), Minimal-risk (most consumer AI). Most B2B SaaS lands in Limited-risk: you mostly need user disclosure + transparency.",
        takeaway: "Most products are Limited-risk: just disclose clearly.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("California SB-53 and SB-942", {
        type: "microread",
        title: "California's safety + provenance laws",
        body: "California shipped (and partially vetoed) frontier-AI safety bills through 2024-2026. Key landed pieces: large-model safety reports, AI content provenance metadata (SB-942), automated-decision disclosure. If you ship to California users — most US AI products do — you're affected.",
        takeaway: "California is the de-facto US baseline. Comply for one, comply for all.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Provenance & C2PA", {
        type: "microread",
        title: "Cryptographic content tags",
        body: "C2PA (Coalition for Content Provenance and Authenticity) — backed by Adobe, Microsoft, BBC, OpenAI — is the emerging standard for cryptographically signing where content came from. By 2026, OpenAI tags DALL-E and ChatGPT output, Microsoft tags Copilot images, big newsrooms tag photos. Browsers are starting to render the chip.",
        takeaway: "Content provenance is the new HTTPS lock icon.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("Tip: keep a model card per release", {
        type: "tip",
        title: "Tip: write a model card every time",
        body: "Even for fine-tunes. Document training data sources, eval results, known failure modes, risk class. Buyers' security teams now ask for these — saves a week of back-and-forth on every enterprise sale.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("AI bill of materials", {
        type: "microread",
        title: "AIBOM: SBOM for models",
        body: "AIBOM (AI Bill of Materials) tracks every model, dataset, and dependency in your AI stack. Becoming an enterprise procurement requirement, especially in regulated industries. Tools like Anthropic's transparency reports and HF's model cards are the early standard. Stay ahead — auto-generate one from CI.",
        takeaway: "Treat AIBOM like SBOM: required for enterprise.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check: smallest action", {
        type: "quickpick",
        prompt: "Smallest first compliance step for a B2B AI product?",
        options: ["Hire a CISO", "Disclose AI in the UI + ship a model card", "Move to a sovereign cloud", "Pause shipping"],
        answer: 1,
        explain: "Disclosure + model card covers most Limited-risk needs.",
      }),
      spark("Match the law", {
        type: "patternmatch",
        prompt: "Match the regulation to its scope",
        pairs: [
          { left: "EU AI Act", right: "Risk-tier classification, EU-wide" },
          { left: "California SB-942", right: "Content provenance" },
          { left: "C2PA", right: "Cryptographic provenance standard" },
          { left: "GDPR", right: "Personal data protection" },
        ],
        explain: "Different laws, different scopes — read your jurisdiction.",
      }),
      spark("Scenario: enterprise sale", {
        type: "scenario",
        setup: "A Fortune-500 wants to buy your AI product. Their security team sends a 50-question vendor security review.",
        prompt: "What ships fastest?",
        options: [
          "Custom answers per question",
          "Pre-baked AIBOM, model cards, SOC 2, EU-AI-Act self-assessment, DPA template",
          "Promise to get back to them",
          "Refuse the questionnaire",
        ],
        answer: 1,
        explain: "Pre-bake the answers. Sales velocity is a compliance feature.",
      }),
      spark("Build a public model card", {
        type: "buildcard",
        title: "Publish a model card for your product",
        pitch: "30 minutes. Closes more enterprise deals than another marketing page.",
        promptToCopy: "Generate a model card for my AI product following Hugging Face's model card template. Cover: intended use, out-of-scope use, training data summary, eval results, known failure modes, contact for issues.",
        successCriteria: "/model-card published on your domain, linked from your security page.",
      }),
    ]),
    level(T, 10, "Boss: trends check", "Final gate.", 6, [
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: AI Trends",
        questions: [
          {
            type: "quickpick",
            prompt: "What's the smarter way to deploy reasoning models?",
            options: ["Use them for everything", "Route — fast for chat, reasoning for hard", "Avoid them", "Only for math"],
            answer: 1,
            explain: "Per-task routing wins on cost + quality.",
          },
          {
            type: "quickpick",
            prompt: "Where do agents fail most often in production?",
            options: ["Wide-open scope with weak supervision", "Narrow scoped with evals", "On weekends", "When using tools"],
            answer: 0,
            explain: "Scope creep + weak evals = stuck agents.",
          },
          {
            type: "quickpick",
            prompt: "Why care about being LLM-cited?",
            options: ["Vanity", "AI search shifts traffic from links to answers", "SEO trick", "It's free"],
            answer: 1,
            explain: "Citations are the new ranking.",
          },
          {
            type: "quickpick",
            prompt: "Strongest reason to ship hybrid on-device + cloud AI?",
            options: ["Buzzwords", "Privacy + latency + cost flip", "Required by Apple", "Smaller binary"],
            answer: 1,
            explain: "Three real wins, one pattern.",
          },
          {
            type: "quickpick",
            prompt: "Best first compliance step for a B2B AI tool?",
            options: ["Move countries", "Disclose AI use + ship a model card", "Hire 5 lawyers", "Pause"],
            answer: 1,
            explain: "Disclosure + model card covers most risk tiers.",
          },
        ],
      }),
    ]),
  ],
};
