import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "cloud" as const;

export const cloud: Topic = {
  id: T,
  name: "Cloud Computing",
  emoji: "☁️",
  tagline: "Where AI runs: compute, storage, networks, GPUs.",
  color: "#7c5cff",
  visual: "cloud",
  levels: [
    level(T, 1, "What 'the cloud' actually is", "Other people's computers, organized.", 4, [
      spark("Compute as a tap", {
        type: "microread",
        title: "Cloud = on-demand resources",
        body: "The cloud is a giant pool of compute, storage, and networking you rent by the second. AWS, GCP, Azure are the big three; Cloudflare, Fly, Render, Vercel sit on top with friendlier APIs. The point isn't 'someone else's computer' — it's the elasticity: scale to a million users by 5pm, scale to zero by midnight, pay for what you used.",
        takeaway: "Elastic + pay-per-use = the cloud's real magic.",
        visual: "cloud",
        category: "pattern",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "The cloud is renting computers by the second. AWS, Google Cloud, Azure are the big three. Cloudflare, Vercel, Fly, Render put nicer wrappers on top. You pay only for what you use, and you can scale up to a million users at lunch and down to zero at night.",
        },
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "What's the biggest practical advantage of cloud over your own server?",
        options: ["Cheaper always", "Elasticity — scale up and back down on demand", "Better hardware", "Lower latency"],
        answer: 1,
        explain: "Elasticity is the killer feature.",
      }),
      spark("AWS, GCP, Azure: pick one", {
        type: "microread",
        title: "The Big Three's actual differences",
        body: "AWS = widest service catalog, deepest enterprise muscle, complicated console. GCP = best networking + BigQuery + AI infra (TPUs), smallest market share. Azure = best Microsoft-shop integration, government & EU presence. Most teams pick by the rest of their stack: ex-Google? GCP. SQL Server shop? Azure. Default? AWS.",
        takeaway: "Pick the cloud that matches your team's existing skills.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Cloudflare's stealth platform", {
        type: "microread",
        title: "Why Cloudflare is the surprise winner",
        body: "Cloudflare went from CDN to full platform: Workers (edge compute), R2 (S3-compatible storage with no egress fees), D1 (SQLite-on-edge), Durable Objects, Vectorize. Egress is free — a structural advantage over AWS. By 2026 they ship most new AI infra (Workers AI, AI Gateway) and many builders default to them for greenfield.",
        takeaway: "Cloudflare = AWS without the egress tax. Default for new AI builds.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Vercel for the front", {
        type: "microread",
        title: "Vercel's frontend gravity",
        body: "Vercel owns the React/Next.js frontend deploy story. Push to git → preview URL → production deploy in 60 seconds. Edge functions, image optimization, AI SDK all bundled. Most modern AI apps' UI lives on Vercel even when the backend lives elsewhere. Pricing scales sharply at growth — watch the bandwidth tier.",
        takeaway: "Vercel for the front, almost everything else lives elsewhere.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: start with one cloud", {
        type: "tip",
        title: "Tip: avoid multi-cloud day one",
        body: "Multi-cloud adds 10x ops complexity for marginal resilience. Pick one cloud (or one cloud + Cloudflare for edge) until you have an actual reason — like a compliance customer demanding it.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Fly.io's region magic", {
        type: "microread",
        title: "Fly: launch anywhere in 30 seconds",
        body: "Fly.io runs your container in 35+ regions globally with one command. Apps autoscale by region, no Kubernetes needed. Killer move: you can pin a database to one region and run stateless apps everywhere. Used by Supabase, Phoenix shops, indie AI builders. Render and Railway play in the same lane with different tradeoffs.",
        takeaway: "Fly = global PaaS without K8s pain.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Match the cloud", {
        type: "patternmatch",
        prompt: "Match the cloud to its sweet spot",
        pairs: [
          { left: "AWS", right: "Widest catalog, enterprise" },
          { left: "GCP", right: "AI infra + BigQuery" },
          { left: "Cloudflare", right: "Edge + free egress" },
          { left: "Vercel", right: "Next.js frontend" },
        ],
        explain: "Each cloud has a moat. Pick by yours.",
      }),
      spark("Pricing model 101", {
        type: "microread",
        title: "Why your cloud bill surprises you",
        body: "Cloud bills have three shapes: compute (per-second), storage (per-GB-month), and egress (per-GB-out). The killer is usually egress — moving data OUT of the cloud. AWS charges $0.09/GB. Cloudflare charges $0. A chatty AI app moving 10TB/mo pays $900 vs $0 just for data exit. Read the egress before you commit.",
        takeaway: "Egress is the hidden tax. Cloudflare and R2 skip it.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: pick the lane", {
        type: "quickpick",
        prompt: "First cloud for a brand-new AI app with a Next.js frontend?",
        options: ["AWS EC2 + custom Kubernetes", "Vercel for the UI + a managed backend (Render/Fly)", "Bare metal in a colo", "Whichever is cheapest in TCO over 7 years"],
        answer: 1,
        explain: "Speed of shipping > TCO at the start.",
      }),
      spark("Try Fly.io's hello world", {
        type: "buildcard",
        title: "Deploy your first app to Fly",
        pitch: "20 minutes, no credit card to start, your code lives in 3 regions.",
        promptToCopy: "Walk me through installing flyctl, generating a fly.toml for a Node app, and deploying to ord, fra, and syd. Show me how to confirm the regions in `fly status`.",
        successCriteria: "Your /health endpoint responds from at least 3 different regions.",
      }),
    ]),
    level(T, 2, "IaaS vs PaaS vs SaaS", "Three layers of abstraction.", 4, [
      spark("Pizza analogy", {
        type: "microread",
        title: "The classic stack",
        body: "IaaS (EC2, GCE) = you rent the kitchen, you cook everything. PaaS (Vercel, Render, Fly) = you rent a kitchen with a stove ready, you bring ingredients. SaaS (Notion, Slack) = food delivered. Modern teams sit on PaaS for speed, drop to IaaS only when forced. Each layer trades control for speed.",
        takeaway: "PaaS by default. IaaS only when you must.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match each example to its layer",
        pairs: [
          { left: "AWS EC2 instance", right: "IaaS" },
          { left: "Vercel hosting", right: "PaaS" },
          { left: "Notion", right: "SaaS" },
          { left: "GCP Cloud Run", right: "PaaS" },
        ],
        explain: "More managed = higher up the stack.",
      }),
      spark("Render and Railway take Heroku's lane", {
        type: "microread",
        title: "Heroku's heirs",
        body: "Render and Railway shipped the polished Heroku-style PaaS that startups missed. `git push` → live URL. Built-in Postgres, Redis, cron, background workers. Railway leans into 'pretty in 5 minutes', Render into 'reasonable at scale'. Both run on AWS underneath. Most YC batches default to one of them in 2026.",
        takeaway: "Render or Railway = modern Heroku. Pick by taste.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Modal: serverless GPUs", {
        type: "microread",
        title: "Modal: PaaS for AI training",
        body: "Modal Labs runs your Python on serverless GPUs (H100, A100) with one decorator. Cold-start in seconds, scale to thousands of containers, pay per second. Used by AI labs and indie ML hackers when they need GPUs but not the ops. Replicate plays in the same lane (focused on inference). Both shaped like PaaS.",
        takeaway: "Modal = serverless H100s. PaaS for AI workloads.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: PaaS until forced", {
        type: "tip",
        title: "Tip: defer IaaS as long as possible",
        body: "Most teams move to IaaS when they hit cost or compliance walls. Until then, PaaS pays for itself in shipped features. The 'we'll save money on EC2' reasoning is almost always a lie if your team is small.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Cloud Run + Lambda = serverless PaaS", {
        type: "microread",
        title: "Serverless containers",
        body: "GCP Cloud Run, AWS Fargate, AWS Lambda are managed-container or managed-function services. You ship a container or a function, the cloud handles servers, scaling, and (mostly) the OS. Big win for irregular traffic. Cold-start matters: Lambda 100-500ms, Cloud Run 1-3s, Fargate 30-60s on first deploy.",
        takeaway: "Serverless containers = PaaS at the cloud-native layer.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: layer lift", {
        type: "quickpick",
        prompt: "You're a 4-person AI startup, no SRE. What layer do you live on?",
        options: ["IaaS — full control", "PaaS — speed wins", "On-prem — security", "SaaS only — no code"],
        answer: 1,
        explain: "PaaS gives you back 5 hours/week per engineer.",
      }),
      spark("Match the AI PaaS", {
        type: "patternmatch",
        prompt: "Match the AI PaaS to its specialty",
        pairs: [
          { left: "Modal", right: "Serverless training & batch" },
          { left: "Replicate", right: "One-API-call model hosting" },
          { left: "RunPod", right: "Cheap raw GPU pods" },
          { left: "Together AI", right: "Open-model API gateway" },
        ],
        explain: "Each lane optimized for a different job.",
      }),
      spark("Build on Render", {
        type: "buildcard",
        title: "Ship a Next.js + Postgres app to Render",
        pitch: "30 minutes. End up with a managed Postgres, a deployed app, and a green deploy log.",
        promptToCopy: "Walk me through deploying a Next.js app + a managed Render Postgres database. Set up automatic deploys from main, set DATABASE_URL as a secret, run a Prisma migration on deploy.",
        successCriteria: "Push to main → 60-second deploy → app reads/writes from Render Postgres.",
      }),
    ]),
    level(T, 3, "Containers + serverless", "Two ways to ship.", 4, [
      spark("Docker in 60 seconds", {
        type: "microread",
        title: "Containers + serverless",
        body: "A container packages your app + deps in one runnable unit. Run it anywhere — Docker, Kubernetes, Cloud Run, ECS. Serverless (Lambda, Cloud Functions) goes further: no container, no server, just a function that runs on request. Serverless wins for spiky/cheap workloads. Containers win when you need control or steady traffic.",
        takeaway: "Containers = portable. Serverless = automatic scale.",
        category: "pattern",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "A container is your app + everything it needs in one box. Docker makes one. You can run that box on any cloud — AWS, GCP, Azure, Fly. Serverless is the next step: no box at all, just a function the cloud spins up when called. Serverless = quick + spiky. Containers = control + steady.",
        },
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "For new AI products, start on a simple PaaS (Render, Fly, Vercel). Don't touch Kubernetes until you have a real reason — it eats months of your life otherwise.",
        category: "tooling",
        addedAt: "2026-02-01",
      }),
      spark("Multi-stage Dockerfiles", {
        type: "tip",
        title: "Tip: use multi-stage builds",
        body: "Build deps in one stage, copy only artifacts to a thin runtime image (alpine, distroless). Slashes image size from 1GB → 100MB, cuts cold-start, fewer CVEs. Saved on every push, every pull, every cold start.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("AWS Lambda: still the workhorse", {
        type: "microread",
        title: "Lambda's place in 2026",
        body: "AWS Lambda is the original serverless: 10M+ active functions, integrated with every AWS service. Sweet spot: event-driven processing, cron jobs, lightweight APIs. Pricing: $0.20 per 1M requests + per-100ms compute. Watch out for cold-start (100-500ms) and 15-minute time limit.",
        takeaway: "Lambda = AWS's event glue. Wide reach, sharp limits.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Cloudflare Workers: edge serverless", {
        type: "microread",
        title: "Workers: V8 isolates, not containers",
        body: "Cloudflare Workers run JavaScript/TypeScript/WASM in V8 isolates — no container, no cold-start, runs in 300+ data centers. 10ms median start. Wins for: latency-critical APIs, edge logic, AI gateways. Tradeoff: tighter runtime, no full Node API. Workers AI hosts open models on the same edge.",
        takeaway: "Workers = sub-10ms global serverless. AWS Lambda's faster cousin.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("When NOT to do serverless", {
        type: "microread",
        title: "Serverless misfits",
        body: "Serverless loses when: you have steady high traffic (containers cheaper), you need long-lived connections (websockets — special handling), you need GPU (Modal/RunPod/Replicate, not Lambda), or you're hitting cold-start frequently in user-facing flows.",
        takeaway: "Serverless wins for spiky. Containers win for steady.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Kubernetes warning", {
        type: "tip",
        title: "Tip: K8s is a 'last resort' tool",
        body: "Kubernetes is incredible at scale but eats startups alive. Reach for it only when you have multi-team workloads, real horizontal scale, or a specific operator (Ray, Spark, etc.) that needs it. Until then, GKE Autopilot, ECS Fargate, or just PaaS.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: serverless fit", {
        type: "quickpick",
        prompt: "Best serverless fit?",
        options: ["A 24/7 video transcoder running steady", "A Slack bot that fires 100x/day", "A long-running ML training job", "A WebSocket chat backend"],
        answer: 1,
        explain: "Spiky, short, event-driven = serverless heaven.",
      }),
      spark("Match the runtime", {
        type: "patternmatch",
        prompt: "Match the workload to the right home",
        pairs: [
          { left: "Slack bot", right: "AWS Lambda / Workers" },
          { left: "Steady API at 1000 RPS", right: "Cloud Run / ECS Fargate" },
          { left: "GPU inference batch job", right: "Modal / Replicate" },
          { left: "Static frontend", right: "Vercel / Cloudflare Pages" },
        ],
        explain: "Match the workload shape to the runtime shape.",
      }),
      spark("Build a Worker AI gateway", {
        type: "buildcard",
        title: "Cloudflare Worker as your AI gateway",
        pitch: "Wrap your AI API key behind a Worker — rate-limit, log, cache, and route models in 30 lines.",
        promptToCopy: "Write me a Cloudflare Worker that proxies POST requests to api.anthropic.com, adds my Authorization header from a secret, rate-limits to 60/min per IP via KV, logs each request to D1, and caches identical prompts for 5 minutes.",
        successCriteria: "Deployed Worker that hides your key, rate-limits, and shows D1 rows for each call.",
      }),
    ]),
    level(T, 4, "GPUs and AI compute", "Why your AI bill is huge.", 4, [
      spark("H100s and friends", {
        type: "microread",
        title: "Why GPUs cost so much",
        body: "AI inference and training need massive parallel matrix math. GPUs (and now NPUs/TPUs) do this thousands of times faster than CPUs. An H100 GPU rents for $2-8/hour. For inference, providers (Anthropic, Together, Replicate, Fireworks) handle this for you. For training or self-hosting, you'll feel the bill.",
        takeaway: "Use API providers unless you have a strong reason to self-host.",
        visual: "chip",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: cheapest path", {
        type: "quickpick",
        prompt: "Cheapest path to ship an AI app today?",
        options: ["Buy your own GPUs", "Use API providers (Anthropic/OpenAI/etc.)", "Train your own model", "Wait for cheaper hardware"],
        answer: 1,
        explain: "API providers handle the GPU complexity for you.",
      }),
      spark("H100 vs H200 vs B200", {
        type: "microread",
        title: "NVIDIA's GPU ladder in 2026",
        body: "H100 (2022, 80GB HBM3) was the workhorse of the GPT-4 era. H200 (2024, 141GB HBM3e) lifted memory for bigger models. Blackwell B200 (2024-2025) doubled training throughput; Blackwell Ultra B300 ships in 2025-2026. Each rung 1.5-2x faster, 30-50% pricier. AMD MI300X is the credible alternative; most labs still default NVIDIA.",
        takeaway: "Newer GPUs = faster + pricier. Pick by your throughput target.",
        category: "news",
        addedAt: "2026-05-01",
      }),
      spark("RunPod and Lambda Labs: cheap GPUs", {
        type: "microread",
        title: "Where to rent H100s by the hour",
        body: "RunPod and Lambda Labs (the cloud, not AWS Lambda) rent H100s, A100s, and 4090s by the hour, often 30-60% under hyperscalers. Sweet spot: training runs, batch inference, ad-hoc fine-tunes. Tradeoffs: less reliability, fewer regions, simpler networking. CoreWeave is the enterprise-grade alternative.",
        takeaway: "Don't pay AWS list price for GPUs you'd run for 4 hours.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Modal & Replicate: serverless GPUs", {
        type: "microread",
        title: "Pay-per-second AI compute",
        body: "Modal runs Python on serverless GPUs by decorator. Replicate hosts open models behind a unified API. Both bill per second, scale to zero. Modal: training + custom workloads. Replicate: inference + sharing models. Used together with API providers (Anthropic for the smart calls, Replicate for the cheap open ones).",
        takeaway: "Modal for compute-on-demand, Replicate for hosted open models.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: spot instances for training", {
        type: "tip",
        title: "Tip: 60% off with spot",
        body: "AWS spot, GCP preemptible, Azure spot all give 50-90% off — they can be reclaimed with 30s warning. Perfect for training jobs (checkpoint frequently!) and batch inference. Wrong for serving traffic. Pair with checkpointing libraries.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("TPU as the alternative", {
        type: "microread",
        title: "Google's TPU lane",
        body: "Google's TPUs are custom AI chips (v5e, v5p, Trillium/v6) accessible only on GCP. They lead some training benchmarks at lower $/FLOP than NVIDIA — but only if you're inside JAX/PyTorch-XLA and willing to do GCP. Anthropic, DeepMind, and many labs train heavily on TPUs. NVIDIA still dominates inference.",
        takeaway: "TPUs = GCP-locked, often cheaper for training. Niche but real.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check: GPU economics", {
        type: "quickpick",
        prompt: "When does self-hosting GPUs beat APIs?",
        options: ["Always", "Heavy fine-tuning, regulated data, or >50M tokens/day", "Whenever your CFO asks", "Never"],
        answer: 1,
        explain: "Three real reasons. Otherwise APIs win.",
      }),
      spark("Match the GPU spend", {
        type: "patternmatch",
        prompt: "Match the workload to the GPU plan",
        pairs: [
          { left: "One-time fine-tune", right: "RunPod / Lambda Labs spot" },
          { left: "Production inference", right: "API provider (Anthropic, OAI, Together)" },
          { left: "Custom batch ML", right: "Modal serverless" },
          { left: "Hosting open models", right: "Replicate or Together" },
        ],
        explain: "Different shapes, different lanes.",
      }),
      spark("Build a fine-tune on Modal", {
        type: "buildcard",
        title: "Run a tiny fine-tune on Modal",
        pitch: "Get the full self-hosted-GPU muscle memory in an afternoon, with $5.",
        promptToCopy: "Show me a Modal Python function that fine-tunes mistralai/Mistral-7B with QLoRA on a 200-row JSONL dataset, runs on a single A100, and pushes the adapter to my Hugging Face account.",
        successCriteria: "Adapter visible in HF, eval set runs against it, total spend < $5.",
      }),
      spark("Inference cost math", {
        type: "microread",
        title: "Back-of-envelope: API vs self-host",
        body: "API call cost ≈ tokens × $/M-tokens. Self-host cost ≈ (GPU $/hr × hours) ÷ tokens. Crossover for Llama-3-70B-class on H100: ~50M tokens/day. Below that, APIs win on TCO. Above that, self-hosting wins, IF you have the ops headcount.",
        takeaway: "Crossover ≈ 50M tokens/day. Do the math.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 5, "Storage tiers", "Hot, warm, cold.", 4, [
      spark("Match storage to access", {
        type: "microread",
        title: "Don't pay hot prices for cold data",
        body: "S3 Standard ≈ instant access, premium price. S3 Infrequent Access ≈ retrieved monthly. Glacier ≈ retrieved yearly, near-zero cost. Same files, 90%+ cost difference. Move logs and old artifacts to cold tiers automatically (lifecycle policies). For databases, archive cold tables out of your primary DB.",
        takeaway: "Lifecycle policies = invisible cost wins.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("S3 vs R2 vs B2", {
        type: "microread",
        title: "Object storage shootout",
        body: "S3 (AWS) is the default — most APIs target it. R2 (Cloudflare) is S3-compatible with $0 egress. B2 (Backblaze) is the cheapest by storage cost, S3-compatible, with cheap egress via Cloudflare bandwidth alliance. Pick by traffic shape: lots of egress → R2/B2; AWS-native stack → S3.",
        takeaway: "S3 by default; R2 if egress hurts; B2 if storage hurts.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Postgres + pgvector wins", {
        type: "microread",
        title: "Why pgvector beat the dedicated DBs",
        body: "Through 2024-2026, pgvector inside vanilla Postgres caught up with most dedicated vector DBs (Pinecone, Weaviate) for typical RAG workloads. Same DB you already run, same Postgres tools, no extra ops. Supabase, Neon, RDS, GCP CloudSQL all support it. For most apps under 10M vectors, pgvector is enough.",
        takeaway: "pgvector first. Dedicated vector DB only when you outgrow it.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: lifecycle policies", {
        type: "tip",
        title: "Tip: set lifecycle on day one",
        body: "Set lifecycle policies on every bucket: 30-day → IA, 90-day → Glacier, 365-day → delete (or keep with legal hold). Set them now — backfilling lifecycle on 50TB of accumulated data is a special kind of pain.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Embeddings storage math", {
        type: "microread",
        title: "How big is your vector DB?",
        body: "1M embeddings × 1536 dims × 4 bytes (float32) = 6 GB. With metadata + index, ~12 GB. pgvector or Pinecone handles this comfortably. At 100M, you're at 1+ TB and the dedicated DBs (Vespa, Weaviate, Qdrant scale-out) start mattering. Compress (int8) for 4x savings; quantize (PQ) for 32x.",
        takeaway: "Most apps fit in pgvector. Scale forces specialization.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Cold storage for AI artifacts", {
        type: "tip",
        title: "Tip: archive your training data",
        body: "Big training runs leave artifacts: checkpoints, logs, eval traces. Archive them to Glacier Deep Archive or Backblaze B2 Cloud Replication after 90 days — ~$1/TB-month. Cheap insurance for reproducing a result a year later.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: tier choice", {
        type: "quickpick",
        prompt: "Best tier for logs older than 90 days?",
        options: ["S3 Standard — easy access", "Glacier or B2 — pennies per GB", "Delete them all", "Move to Postgres"],
        answer: 1,
        explain: "Cold tiers are 90% cheaper.",
      }),
      spark("Match the storage", {
        type: "patternmatch",
        prompt: "Match the data to its right home",
        pairs: [
          { left: "User-uploaded images", right: "S3 / R2 (object storage)" },
          { left: "Vector embeddings", right: "pgvector / Pinecone" },
          { left: "Big analytics tables", right: "BigQuery / Snowflake" },
          { left: "Audit logs > 90 days", right: "Glacier / B2 cold" },
        ],
        explain: "Each shape wants a different storage.",
      }),
      spark("Build a lifecycle rule", {
        type: "buildcard",
        title: "Add S3 lifecycle in 5 minutes",
        pitch: "Compounding savings. Five minutes today, hundreds of dollars/month forever.",
        promptToCopy: "Write me a Terraform `aws_s3_bucket_lifecycle_configuration` for my logs bucket: transition to IA at 30 days, Glacier at 90, expire at 365. Include a separate rule for /backups/ that never expires.",
        successCriteria: "Terraform plan applies clean. Existing files start transitioning the next night.",
      }),
    ]),
    level(T, 6, "Latency basics", "Where slow comes from.", 4, [
      spark("The latency budget", {
        type: "microread",
        title: "Speed-of-light is a real constraint",
        body: "Cross-region API calls add 50-200ms. Database queries 1-50ms. LLM calls often 500-3000ms. Build a 'latency budget': decide how much of your user-perceived time each layer can spend. Move user-facing inference to the same region as users. Cache aggressively.",
        takeaway: "Latency budget per request. Cache to stay inside it.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip: stream your LLM responses", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Stream LLM responses to users token-by-token. Same total latency, but feels 5x faster because they see progress.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Edge functions: closer is faster", {
        type: "microread",
        title: "Run your code near users",
        body: "Cloudflare Workers, Vercel Edge Functions, Fastly Compute@Edge run code in 100-300+ data centers globally. A user in Sydney hits a Sydney POP, not your Virginia origin. Saves 100-300ms per request — felt as 'snappy' even when nothing else changed. Sweet spot: auth, rewrites, AI gateways.",
        takeaway: "Edge = sub-50ms first byte from anywhere on Earth.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Anthropic prompt caching", {
        type: "microread",
        title: "5-min cache cuts cost & latency",
        body: "Anthropic's prompt caching (also OpenAI, Gemini have variants) caches large repeated prefixes for 5 min, slashing cost ~90% on cache hits and TTFT 30-60%. Required for any RAG / agent app reusing a long system prompt or doc context. Free win for most builders shipped late-2024 onward.",
        takeaway: "Turn on prompt caching — same code, big cost + latency cut.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: parallel tool calls", {
        type: "tip",
        title: "Tip: fan out tool calls",
        body: "If your agent calls 3 independent tools, run them in parallel — saves 60-70% of round-trip time. Anthropic and OpenAI APIs both support parallel tool calls natively. Don't await one then await the next.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Region pinning", {
        type: "microread",
        title: "Pin your DB; replicate where users live",
        body: "Latency-critical pattern: keep one writable Postgres in your home region; deploy read replicas (or stateless app instances) in user regions. Fly.io, Neon, Supabase, AWS RDS all support this. Reads are local-fast; writes still go home but rarely block UX.",
        takeaway: "Pin DB. Replicate stateless. Fast reads everywhere.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: perceived latency", {
        type: "quickpick",
        prompt: "Inference is 2.4s; user complains it's slow. Best fix?",
        options: ["Buy a bigger model", "Stream tokens to the UI as they arrive", "Add a loading GIF", "Cold-tier the DB"],
        answer: 1,
        explain: "Streaming converts dead time into 'progress'.",
      }),
      spark("Match the speedup", {
        type: "patternmatch",
        prompt: "Match the latency fix to the symptom",
        pairs: [
          { left: "Long boring system prompt", right: "Prompt caching" },
          { left: "Multi-region users, single-region DB", right: "Read replicas" },
          { left: "Sequential tool calls", right: "Parallel tool calls" },
          { left: "API far from users", right: "Edge functions" },
        ],
        explain: "Symptom-by-symptom. Pick the surgical fix.",
      }),
      spark("Build a latency budget table", {
        type: "buildcard",
        title: "Sketch your latency budget",
        pitch: "20-minute exercise. Will reshape your roadmap.",
        promptToCopy: "Help me build a latency budget for a chat-style AI app with a target of 1.5s first-byte. Allocate ms across: edge handler, auth, vector search, LLM TTFT, network back to user. Mark which layers I should optimize first to hit 1.5s.",
        successCriteria: "You have a 6-row table summing to ≤ 1500ms with clear next-step bottleneck.",
      }),
      spark("Streaming SSE pattern", {
        type: "microread",
        title: "SSE: the simplest streaming",
        body: "Server-Sent Events (SSE) is HTTP + a content-type that streams text events. Built into every browser fetch. Vercel, Cloudflare Workers, Fly all support it natively. Simpler than WebSockets for one-way streaming (LLM tokens, agent updates). Anthropic and OpenAI streaming APIs are SSE under the hood.",
        takeaway: "SSE is the boring, reliable way to stream LLM output.",
        category: "tooling",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 7, "Networking essentials", "VPCs, CDNs, edges.", 4, [
      spark("VPC + CDN + edge", {
        type: "microread",
        title: "Three networking primitives",
        body: "VPC = your private network in the cloud (isolation, security). CDN = serve static stuff from 200+ edge locations near users (Cloudflare, Akamai). Edge functions = run small code at those edge locations (low latency rewrites, auth checks). Most AI apps need all three.",
        takeaway: "VPC isolates. CDN distributes. Edge runs fast.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Cloudflare CDN gravity", {
        type: "microread",
        title: "Why so much of the web sits on CF",
        body: "Cloudflare proxies ~20% of all websites for free, caches static assets globally, blocks bots and DDoS. The free plan covers most indie projects. The paid plan adds Workers, R2, D1, AI Gateway. Many AI apps default to Cloudflare for the front door even with AWS / GCP behind.",
        takeaway: "Cloudflare is the default front door for the modern web.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Private endpoints & VPC peering", {
        type: "microread",
        title: "Keep AI calls inside your network",
        body: "Anthropic, OpenAI, and Bedrock support private endpoints / VPC peering for enterprise plans — your traffic to the LLM never traverses the public internet. Reduces latency 20-50ms, removes a vendor questionnaire row, satisfies most compliance teams. Required for FSI/healthcare AI in 2026.",
        takeaway: "Private endpoints = compliance + speed for enterprise AI.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip: HTTPS everywhere", {
        type: "tip",
        title: "Tip: never serve over plain HTTP",
        body: "Cloudflare, Fly, Vercel, Render, Railway all auto-provision Let's Encrypt certs. There's literally no reason to ship HTTP in 2026. Set HSTS in your edge layer. Costs nothing.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("DNS & failover", {
        type: "microread",
        title: "DNS-level load balancing",
        body: "Route 53 (AWS), Cloudflare DNS, NS1 do health checks + DNS routing. Failover from one region to another in 30-60 seconds — way before app-layer load balancing notices. Latency-based DNS sends each user to their closest healthy region. Free tier of CF DNS handles most apps.",
        takeaway: "DNS is the cheapest, fastest layer for failover.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Bandwidth alliance + 0 egress", {
        type: "microread",
        title: "Stop paying egress to AWS",
        body: "Cloudflare's Bandwidth Alliance + R2 ($0 egress) + Backblaze B2 ($0 egress to CF) form an axis of free egress. Architecturally: store on R2 / B2, deliver via Cloudflare, never pay AWS the $0.09/GB egress tax. Most public AI demos and downloads on the modern web ride this stack.",
        takeaway: "R2 + Cloudflare = $0 egress for most public traffic.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check: front door", {
        type: "quickpick",
        prompt: "Easiest big network win for a new AI app?",
        options: ["Build your own CDN", "Put Cloudflare in front", "Disable HTTPS", "Run only in us-east-1"],
        answer: 1,
        explain: "30 minutes of setup, durable wins.",
      }),
      spark("Match the layer", {
        type: "patternmatch",
        prompt: "Match the networking job to the right layer",
        pairs: [
          { left: "Block bots / DDoS", right: "Cloudflare" },
          { left: "Isolate prod databases", right: "VPC" },
          { left: "Failover between regions", right: "DNS health checks" },
          { left: "Auth check before backend", right: "Edge function" },
        ],
        explain: "Different jobs, different layers.",
      }),
      spark("Build a Cloudflare front door", {
        type: "buildcard",
        title: "Put Cloudflare in front of your app",
        pitch: "30-minute upgrade. Caching, HTTPS, DDoS, all free.",
        promptToCopy: "Walk me through pointing my domain at Cloudflare DNS, proxying through CF, enabling HTTPS + HSTS, setting a cache rule to cache `/static/*` for 1 year and bypass `/api/*`, and adding a rate-limit rule for /api/* at 60 rpm per IP.",
        successCriteria: "Your domain serves with the orange cloud icon, HTTPS works, /static/ shows CF cache hits, /api/ rate-limits at 60 rpm.",
      }),
    ]),
    level(T, 8, "Cost guardrails", "Stop the runaway bill.", 4, [
      spark("Budgets + alerts", {
        type: "microread",
        title: "Set budgets day one",
        body: "Every cloud has billing alerts. Configure them on day one — daily, weekly, monthly thresholds. Tag every resource by team/feature so you know what's eating your money. Tag your AI calls too (prompt caching, model used, tenant_id) so you can attribute later.",
        takeaway: "Budgets + tags. Day one. Always.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip: panic budget", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Set a 'panic budget' at 2x your expected monthly spend that auto-kills suspicious workloads. Saved many a startup from a $40k inference bill from a bug.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("AI Gateway: meter every model call", {
        type: "microread",
        title: "Cloudflare AI Gateway in front of every API",
        body: "Cloudflare AI Gateway, Helicone, Portkey, LiteLLM all proxy your model calls and give you: per-model spend, per-tenant attribution, rate limits, cache, fallback. Drop-in: change the base URL, get a dashboard. Skip this and you'll be guessing at your AI bill at 2am.",
        takeaway: "Put a gateway between your app and the model API.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Reserved instances + savings plans", {
        type: "microread",
        title: "30-60% off if you commit",
        body: "AWS Savings Plans, GCP Committed Use Discounts, Azure Reserved Instances all give 30-60% off if you commit to 1 or 3 years of usage. Only commit to spend you'd run no matter what — your steady-state baseline. Don't reserve growth or peaks. Compute Savings Plans are the most flexible.",
        takeaway: "Reserve your baseline. Pay on-demand for everything else.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip: tag everything", {
        type: "tip",
        title: "Tip: tag = attribute",
        body: "Tag every resource with team, feature, environment, tenant. Without tags you can't answer 'why is the bill up 30%?'. With tags, you answer it in 5 minutes. Set a tag-required policy in your IaC.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("LLM cost attribution", {
        type: "microread",
        title: "Attribute every model token",
        body: "Tag every LLM call with: tenant_id, feature, model, cached_or_not. Forward to your gateway. Now you can answer: which feature drives 60% of the bill? Which tenant is 5x the average? Without this, your AI cost story is fiction. With it, you can repricing or kill features rationally.",
        takeaway: "No tags on LLM calls = no cost story = no decisions.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: first guardrail", {
        type: "quickpick",
        prompt: "First cost guardrail for a new account?",
        options: ["Hire a FinOps team", "Billing alerts + tags + a panic budget", "Move to a cheaper region", "Switch clouds"],
        answer: 1,
        explain: "Visibility + auto-stop. Day one.",
      }),
      spark("Match the lever", {
        type: "patternmatch",
        prompt: "Match the cost lever to the win",
        pairs: [
          { left: "Reserved instances", right: "30-60% off baseline" },
          { left: "Spot instances", right: "60-90% off batch" },
          { left: "Prompt caching", right: "Up to 90% off repeated context" },
          { left: "AI gateway", right: "Visibility + cap" },
        ],
        explain: "Stack levers; don't rely on one.",
      }),
      spark("Build a cost dashboard", {
        type: "buildcard",
        title: "Wire AI Gateway to your dashboard",
        pitch: "By tomorrow you can answer 'what does each feature cost?'",
        promptToCopy: "Set up Cloudflare AI Gateway in front of my Anthropic calls. Tag each request with feature and tenant_id. Build me a tiny Worker that pulls AI Gateway analytics for the last 7 days and posts a daily Slack message with top 5 features by cost.",
        successCriteria: "Slack gets a daily 'top 5 costliest features' post.",
      }),
      spark("Tip: cost gate on PRs", {
        type: "tip",
        title: "Tip: estimate cost before merging",
        body: "Add a CI step that runs your eval set through the model used in the PR and prints the per-call cost. Reviewer sees 'this PR triples cost per ticket' before merge. Best invented cost gate in the field.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 9, "Disaster recovery", "When the region falls.", 4, [
      spark("Backups + multi-region", {
        type: "microread",
        title: "Backups, failover, RTO/RPO",
        body: "RTO = how fast can you recover. RPO = how much data loss is OK. Pick targets per system, design backups + failover to meet them. For most AI apps: nightly DB backups + cross-region read replica is enough. For payments or critical data: multi-region active-active.",
        takeaway: "Define RTO/RPO. Engineer to meet them.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Test your restore", {
        type: "tip",
        title: "Tip: untested backups don't exist",
        body: "Quarterly: pick a backup, restore it to a fresh DB, run your app against it. The number of teams that find broken backups during a real outage is alarming. Schedule it like a fire drill.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Cell-based architecture", {
        type: "microread",
        title: "AWS-style cells: blast-radius control",
        body: "AWS pioneered 'cells' — independent stacks, each handling a subset of users, sharing nothing. A failure in one cell can't cascade. Adopted by Slack, Stripe, and others. Most startups don't need cells day one, but if you serve regulated customers or are crossing $10M ARR, it's the next architecture goal.",
        takeaway: "Cells limit blast radius. Worth it past a certain scale.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Multi-region trade-offs", {
        type: "microread",
        title: "Active-active is hard; pick warm-standby first",
        body: "Active-active multi-region needs conflict resolution, multi-master DB, careful eventual consistency. Most teams shouldn't start there. Warm-standby (replicate everything; promote on disaster) is 10x simpler, gets you 5-min RPO and 10-min RTO. Active-active only when warm isn't enough.",
        takeaway: "Warm-standby covers most needs. Active-active is the boss-fight.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("AI-app DR specifics", {
        type: "microread",
        title: "DR for the AI parts",
        body: "Don't forget: vector DB backups, embedding pipelines, fine-tuned model weights, eval sets. Many teams DR their app DB but forget the AI surface. Snapshot your vector DB nightly. Version-control your fine-tuned adapters in HF or S3 with checksums. Re-runnable evals on disaster.",
        takeaway: "DR your AI surface. Vectors, adapters, evals.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Region failures are real", {
        type: "microread",
        title: "us-east-1 falls every few years",
        body: "AWS us-east-1 has had multiple multi-hour outages (Dec 2021, June 2023, the recurring DNS / IAM blips). It's the single biggest region for global services and a single point of failure for many startups. If your DR plan is 'us-east-1 won't fall,' it's not a plan.",
        takeaway: "us-east-1 has fallen. Plan for it falling again.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check: simplest DR", {
        type: "quickpick",
        prompt: "Smallest DR upgrade for a one-region SaaS today?",
        options: ["Active-active multi-region", "Nightly DB backups + cross-region read replica + restore test", "Move to bare metal", "Add a 24/7 SRE"],
        answer: 1,
        explain: "Three boring habits cover 95% of risk.",
      }),
      spark("Match the metric", {
        type: "patternmatch",
        prompt: "Match the DR metric to its meaning",
        pairs: [
          { left: "RTO", right: "How fast you recover" },
          { left: "RPO", right: "Acceptable data loss" },
          { left: "MTTR", right: "Mean time to repair" },
          { left: "MTBF", right: "Mean time between failures" },
        ],
        explain: "Each measures a different shape of pain.",
      }),
      spark("Build a restore drill", {
        type: "buildcard",
        title: "Schedule a quarterly restore drill",
        pitch: "Calendar invite + checklist. The cheapest insurance you can build.",
        promptToCopy: "Write me a runbook for restoring my Postgres backup to a fresh staging DB, running smoke tests, and tearing it down. Add a cron-friendly script that does it monthly and posts 'PASS/FAIL + duration' to Slack.",
        successCriteria: "Monthly cron runs, Slack confirms, you have measured RTO data.",
      }),
    ]),
    level(T, 10, "Boss: cloud check", "Final gate.", 6, [
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: Cloud",
        questions: [
          {
            type: "quickpick",
            prompt: "Best default for a brand-new AI side project?",
            options: ["AWS EC2 + custom Kubernetes", "Vercel/Render/Fly (PaaS)", "Buy your own server", "Heroku free tier"],
            answer: 1,
            explain: "PaaS first. Lower complexity per dollar.",
          },
          {
            type: "quickpick",
            prompt: "Inference latency feels slow even though API is fast. Most likely fix?",
            options: ["Bigger model", "Stream responses to user", "Add Kubernetes", "Cold-tier the DB"],
            answer: 1,
            explain: "Streaming = perceived speed.",
          },
          {
            type: "quickpick",
            prompt: "First cost guardrail to set up?",
            options: ["Negotiate enterprise", "Billing alerts + tags + a panic budget", "Move to a cheaper region", "Switch clouds"],
            answer: 1,
            explain: "Visibility + auto-stop. Day one.",
          },
          {
            type: "quickpick",
            prompt: "Strongest reason to pick Cloudflare R2 over AWS S3?",
            options: ["More features", "$0 egress saves a fortune on outbound traffic", "Bigger logo", "Required by law"],
            answer: 1,
            explain: "Egress is the hidden tax.",
          },
          {
            type: "quickpick",
            prompt: "Smallest DR upgrade for a one-region SaaS?",
            options: ["Multi-region active-active", "Nightly backups + cross-region read replica + restore drill", "Bare metal", "Pray"],
            answer: 1,
            explain: "Boring habits beat heroics.",
          },
        ],
      }),
    ]),
  ],
};
