import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "frontier-companies" as const;

export const frontierCompanies: Topic = {
  id: T,
  name: "AI Frontier Companies",
  emoji: "🚀",
  tagline: "Who's building the future and how — Anthropic, OpenAI, Google, more.",
  color: "#7c5cff",
  visual: "rocket",
  levels: [
    level(T, 1, "The AI lab landscape", "The big six.", 6, [
      spark("Who builds the brains", {
        type: "microread",
        title: "Major labs at a glance",
        body: "Anthropic (Claude, safety-first), OpenAI (GPT, ChatGPT scale), Google DeepMind (Gemini, research depth), Meta AI (Llama open weights), xAI (Grok, fast), Mistral (open + premium). Each has a distinct philosophy: research-led vs scale-led, closed vs open, safety-first vs capability-first. Smart builders match labs to their values + use cases.",
        takeaway: "Six labs, six philosophies. Pick by fit, not hype.",
        visual: "rocket",
        category: "company",
        addedAt: "2026-05-01",
        bodyByAgeBand: {
          teen: "Six big AI labs build most of the powerful models you've used. Anthropic makes Claude. OpenAI makes ChatGPT. Google DeepMind makes Gemini. Meta makes Llama and shares the weights. xAI makes Grok. Mistral, in France, ships both open and paid models. They each pick a different bet on safety, openness, and speed.",
          kid: "Six teams build the AI brains most people use. Anthropic makes Claude, OpenAI makes ChatGPT, Google makes Gemini, Meta gives Llama away for free, xAI makes Grok, and Mistral is the one from France. They each have a different style.",
        },
      }),
      spark("Closed vs open weights", {
        type: "microread",
        title: "Two business shapes",
        body: "Closed-weights labs (OpenAI, Anthropic, Google) ship behind APIs — you pay per token, you can't run the model offline. Open-weights labs (Meta, Mistral, DeepSeek, Alibaba's Qwen) publish the file — you can run it on your laptop or your own GPUs. Closed wins on raw frontier capability today; open wins on price-floor pressure, fine-tuning freedom, and on-prem compliance.",
        takeaway: "Closed = best frontier. Open = price floor + on-prem freedom.",
        category: "principle",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "Closed labs (OpenAI, Anthropic, Google) keep the model file private — you only get to talk to it through their server, and you pay per message. Open labs (Meta, Mistral) publish the file. Anyone can download it and run it on their own computer. Closed has the smartest models today, but open keeps prices honest because anyone can host them.",
        },
      }),
      spark("The H100 wall", {
        type: "tip",
        title: "💡 Why GPUs gate the field",
        body: "Frontier training runs need tens of thousands of NVIDIA H100s for months. Only a handful of orgs (Microsoft+OpenAI, Google, Meta, xAI's Colossus, Anthropic via Amazon/Google) can afford the cluster. The GPU constraint, not the algorithm, is the moat right now.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pick a lab by job", {
        type: "patternmatch",
        prompt: "Match the lab to the job it's known to win.",
        pairs: [
          { left: "Anthropic", right: "Long-context coding + safety-strict enterprise" },
          { left: "OpenAI", right: "Broadest API surface + consumer ChatGPT scale" },
          { left: "Google DeepMind", right: "Multimodal + Workspace/Search/Android integration" },
          { left: "Meta AI", right: "Open-weights baseline you can run yourself" },
        ],
        explain: "There is no universal best lab — there are best fits per job. Match by use case before you compare price.",
      }),
      spark("Three philosophies", {
        type: "quickpick",
        prompt: "Which framing best captures Anthropic's bet vs OpenAI's?",
        options: [
          "Anthropic optimizes for distribution; OpenAI optimizes for safety",
          "Anthropic leads with safety + interpretability; OpenAI leads with breadth + scale",
          "They are functionally identical",
          "Anthropic builds open-weight models; OpenAI builds closed",
        ],
        answer: 1,
        explain: "Anthropic's pitch is steerable + interpretable. OpenAI's is biggest surface + biggest reach. Both are real bets.",
      }),
      spark("Why frontier labs reject most users", {
        type: "scenario",
        setup: "Your startup wants priority access to a frontier lab's newest model — not just rate-limit-priority, but pre-release access.",
        prompt: "What is the most reliable lever to actually get it?",
        options: [
          "Tweet about wanting it loudly",
          "Build something genuinely impressive on the previous model + show real spend",
          "Email support repeatedly",
          "Cold-DM the founder's spouse",
        ],
        answer: 1,
        explain: "Frontier labs gate access by demonstrated traction + demonstrated spend. Show, don't ask. Cold outreach without a working build is noise.",
      }),
      spark("Why alignment is a now problem", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "Once we get to superintelligence, it will be too late to align the models. My best granularity forecast for could we have an X-risk or extremely bad outcome is somewhere between 0 and 10%.",
        takeaway:
          "Alignment work is a now problem, not a future one. The window to bake values into a system closes the moment that system gets smarter than you. This shapes which lab you trust — and which one you join.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Benjamin Mann",
          guestRole: "co-founder of Anthropic",
          episodeTitle: "Inside Anthropic — alignment, scaling, AGI timelines",
          timestamp: "00:00:32",
        },
      }),
      spark("Read the system card", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Every frontier model release ships with a system card — the safety report. Anthropic's are public on anthropic.com/news. Reading the first 5 pages tells you the model's actual failure modes faster than any benchmark.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Anthropic",
          url: "https://www.anthropic.com/news",
        },
      }),
      spark("Frontier vs incumbent", {
        type: "microread",
        title: "Big tech ≠ frontier lab",
        body: "Microsoft, Amazon, NVIDIA, Apple are huge in AI — as platform layers. The frontier-model labs (those training the biggest base models) is a smaller club: Anthropic, OpenAI, Google DeepMind, Meta, xAI, Mistral, plus Chinese frontiers (DeepSeek, Qwen). Don't confuse a cloud reseller of someone else's model with the lab that trained it.",
        takeaway: "Frontier = trains the base model. Everyone else is downstream.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Five funding patterns", {
        type: "microread",
        title: "Where the money comes from",
        body: "Anthropic — Amazon ($8B+) and Google as strategics. OpenAI — Microsoft ($13B+) wrapped around an unusual capped-profit. xAI — Musk-led raises plus Tesla/X cross-pollination. Mistral — European sovereign + private capital. Meta + Google — funded out of cash flow from ads. The funding pattern shapes who they ship for.",
        takeaway: "Follow the funding to predict who they'll prioritize.",
        category: "company",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 2, "Anthropic in depth", "Mission, models, products.", 6, [
      spark("Anthropic 101", {
        type: "microread",
        title: "Why Anthropic exists",
        body: "Anthropic was founded in 2021 by ex-OpenAI researchers focused on AI safety. Mission: build reliable, interpretable, steerable AI. Models: Claude family (Haiku/Sonnet/Opus, latest 4.x). Products: Claude.ai, API, Claude Code. Distinctive: Constitutional AI, deep red-teaming, transparent model cards. Loved by enterprises for safety posture + clear policies.",
        takeaway: "Safety-first frontier lab. Strong with regulated buyers.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("The Claude family map", {
        type: "microread",
        title: "Haiku, Sonnet, Opus",
        body: "Anthropic ships Claude in three sizes. Haiku — small, cheap, fast, good for classification + routing. Sonnet — the workhorse most production traffic flows through, strong coding + tool use. Opus — top tier, best at hard reasoning + long agentic runs. Default: start with Sonnet for everything, drop to Haiku for throughput, escalate to Opus when Sonnet is wrong.",
        takeaway: "Default Sonnet. Drop to Haiku for cost. Escalate to Opus for reasoning.",
        category: "company",
        addedAt: "2026-05-01",
        bodyByAgeBand: {
          teen: "Claude comes in three sizes named after poetry: Haiku (small, fast, cheap), Sonnet (the everyday one, balanced), and Opus (the biggest, slowest, smartest). The trick is matching the size to the job — using Opus for tagging emails is like driving a tank to school.",
        },
      }),
      spark("Constitutional AI in one line", {
        type: "microread",
        title: "What 'constitutional' means",
        body: "Most labs RLHF a model to be helpful and harmless using human raters. Anthropic's Constitutional AI uses a written set of principles (its 'constitution') as a second model to critique and improve outputs — humans-in-the-loop only at the principle level. The result: more transparent value-setting, less reliance on rater consensus, easier to audit later.",
        takeaway: "Principles > rater consensus as the source of truth.",
        category: "principle",
        addedAt: "2025-10-01",
        source: {
          name: "Anthropic",
          url: "https://www.anthropic.com/news",
        },
      }),
      spark("Claude Code: the agent shape", {
        type: "microread",
        title: "Why Claude Code matters",
        body: "Claude Code is Anthropic's first-party agentic coding tool — terminal-native, runs in your repo, edits files, runs commands, opens PRs. Strategic signal: Anthropic is betting on the long-running coding agent as the wedge into the developer market. If you build dev-tools, study its UX choices — they're the lab's clearest 'this is what agents look like' bet.",
        takeaway: "Claude Code = Anthropic's bet on the long-running coding agent.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "When pitching to enterprise, lead with safety: model cards, no-train-on-customer-data clause, audit logs. Anthropic + Claude is a great anchor for that conversation.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Read the Anthropic acceptable use policy", {
        type: "tip",
        title: "💡 Read the AUP first",
        body: "Anthropic publishes an Acceptable Use Policy at anthropic.com/legal/aup. Before you build anything user-facing on Claude, read it once — most launch problems trace back to a section the founder skimmed. Saves a takedown email later.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Anthropic",
          url: "https://www.anthropic.com/news",
        },
      }),
      spark("Anthropic match-up", {
        type: "patternmatch",
        prompt: "Match each Anthropic surface to its right job.",
        pairs: [
          { left: "Claude Haiku", right: "High-volume classification + routing" },
          { left: "Claude Sonnet", right: "Default production reasoning + coding" },
          { left: "Claude Opus", right: "Hardest reasoning, long agentic runs" },
          { left: "Claude Code", right: "Terminal-native agentic coding in your repo" },
        ],
        explain: "Right-sizing the model is the cheapest cost lever you have on Anthropic.",
      }),
      spark("Anthropic safety posture", {
        type: "quickpick",
        prompt: "What's most distinctive about Anthropic's positioning vs OpenAI?",
        options: [
          "Bigger context windows",
          "Public Responsible Scaling Policy + interpretability research",
          "Cheaper API pricing",
          "Open weights",
        ],
        answer: 1,
        explain: "Anthropic publishes a Responsible Scaling Policy and a steady drumbeat of interpretability research — both are core to its enterprise pitch.",
      }),
      spark("Mission > offer", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "They get these offers and then they say, 'My best case scenario at Meta is that we make money, and my best case scenario at Anthropic is we affect the future of humanity.'",
        takeaway:
          "The strongest retention mechanism a frontier company has isn't comp — it's a mission so concrete that a $100M offer feels like a downgrade. Builders: pick employers whose mission you'd take a pay cut for.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Benjamin Mann",
          guestRole: "co-founder of Anthropic",
          episodeTitle: "Inside Anthropic — alignment, scaling, AGI timelines",
          timestamp: "00:00:45",
        },
      }),
      spark("Pricing 101 for Claude", {
        type: "microread",
        title: "How Anthropic prices",
        body: "Claude prices per million tokens, split across input vs output, with prompt caching for repeated context (5x cheaper on cache hits) and a 50% off async batch tier. The lever order matters: cache > batch > smaller model > shorter prompts. Most startups overspend by skipping cache and never trying Haiku.",
        takeaway: "Cache hits + batch tier + right-size the model — in that order.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pick the right Claude", {
        type: "scenario",
        setup: "You're routing 10M support tickets/month through Claude. Cost is exploding. Quality matters — wrong intents anger customers.",
        prompt: "What's the highest-leverage first move?",
        options: [
          "Switch everything to Opus",
          "Move classification to Haiku, keep response generation on Sonnet",
          "Drop to GPT-3.5",
          "Reduce volume by hiding the chat widget",
        ],
        answer: 1,
        explain: "Right-sizing — Haiku for classification, Sonnet for response — is the standard pattern. You usually halve cost without touching quality.",
      }),
      spark("Anthropic in numbers", {
        type: "microread",
        title: "The shape of the company",
        body: "Anthropic is among the most valuable private AI labs, with backing from Amazon and Google as strategic investors and a focus on enterprise + safety-strict buyers. Headcount ramped fast through 2024–2025, the org publishes regular Responsible Scaling Policy updates, and the API + Claude.ai business is the main commercial engine.",
        takeaway: "Safety-led, enterprise-led, fast-growing. Bet shape, not just model.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Anthropic",
          url: "https://www.anthropic.com/news",
        },
      }),
    ]),
    level(T, 3, "OpenAI playbook", "Distribution + API breadth.", 6, [
      spark("OpenAI strategy", {
        type: "microread",
        title: "Scale, distribution, breadth",
        body: "OpenAI ships GPT-class models, ChatGPT (huge consumer reach), Whisper (audio), DALL-E (image), Sora (video), agents, structured outputs, batch APIs. Strategy: be the broadest API surface, with biggest ecosystem. Builder takeaway: easy to start, hard to leave (lock-in via fine-tunes + APIs).",
        takeaway: "Broadest surface. Plan for lock-in if you go deep.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("The ChatGPT distribution machine", {
        type: "microread",
        title: "Why ChatGPT is the moat",
        body: "ChatGPT crossed 100M weekly users faster than any consumer product. That distribution becomes a feedback loop: more users → more conversations → better instruction-tuning data → better products → more users. OpenAI's real moat isn't a single model release — it's the consumer-grade feedback loop closed-source rivals don't have at the same scale.",
        takeaway: "The moat is the user-feedback loop, not the latest model.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Inside the GPT family", {
        type: "microread",
        title: "GPT-4o, o-series, mini",
        body: "OpenAI splits its lineup roughly into chat-tuned (GPT-4o, GPT-4o-mini) and reasoning-tuned (o1, o3 — 'think before answering' models). Chat-tuned wins on latency + cost. Reasoning-tuned wins on hard problems where you can wait. The o-series introduced inference-time-thinking as a first-class lever — a major shift.",
        takeaway: "Chat for speed, o-series for hard reasoning, mini for cheap.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Microsoft + OpenAI", {
        type: "microread",
        title: "An unusual marriage",
        body: "Microsoft invested $13B+ for an exclusive cloud + product distribution partnership. OpenAI runs on Azure. Copilot in Office, GitHub, Windows is OpenAI under the hood. The deal is capped-profit, not equity, with revenue-sharing tilts. Strategic effect: Microsoft has the most embedded AI distribution of any company — without operating an AI lab itself.",
        takeaway: "Microsoft + OpenAI is the most powerful distribution alliance in AI.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Tools that came from OpenAI first", {
        type: "patternmatch",
        prompt: "Match each surface to the moment OpenAI normalized it.",
        pairs: [
          { left: "Function calling / tool use", right: "OpenAI's June 2023 update" },
          { left: "JSON-mode / structured outputs", right: "OpenAI shipped first, others followed" },
          { left: "Realtime voice API", right: "OpenAI's GPT-4o launch in 2024" },
          { left: "Assistants + Threads abstraction", right: "OpenAI Assistants API" },
        ],
        explain: "OpenAI sets a lot of API conventions; the rest of the field tracks them.",
      }),
      spark("Tip: prompt-caching on OpenAI", {
        type: "tip",
        title: "💡 Cache the system prompt",
        body: "OpenAI's prompt caching kicks in once a prefix exceeds a threshold and is reused. Put your big stable system prompt + tool definitions FIRST, user-specific stuff LAST. You can cut input cost ~50% on repetitive workloads.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Plus, Pro, Team, Enterprise", {
        type: "microread",
        title: "Reading OpenAI's pricing tiers",
        body: "ChatGPT Plus is the consumer subscription. Pro is the heavy-user tier with priority access to top models + agents. Team is small-org seat-based. Enterprise adds SSO, no-train data clause, audit logs, and custom data retention. Match the tier to the buyer; never sell Plus to an enterprise-security buyer.",
        takeaway: "Match the OpenAI tier to the buyer's compliance posture.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Why GPT lock-in is real", {
        type: "scenario",
        setup: "You've fine-tuned a custom GPT for your product, used the Assistants API for state, and integrated DALL-E for images. A founder asks: 'How easy to switch to Claude?'",
        prompt: "Pick the most honest answer.",
        options: [
          "Trivial — they're all the same",
          "Hard — fine-tunes don't transfer, Assistants state is OpenAI-shaped, surfaces aren't 1:1",
          "Free — just change the model name",
          "Already done by Vercel",
        ],
        answer: 1,
        explain: "Fine-tunes are non-portable; Assistants state lives in OpenAI's servers; image + voice surfaces have no clean equivalents. Lock-in is real — design for portability up front.",
      }),
      spark("OpenAI as research org → product org", {
        type: "microread",
        title: "What changed in 2023–2025",
        body: "OpenAI's public identity shifted from research lab (the 'Generative Pre-trained Transformer' paper era) to product company (ChatGPT, agents, Sora, Operator). The team mix and bonus pool shifted with it. A research-only OpenAI from 2018 wouldn't recognize today's company. That shift is itself the strategy.",
        takeaway: "OpenAI is now a product company that does research, not the reverse.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Watch the Sora story", {
        type: "tip",
        title: "💡 Track Sora as a strategy signal",
        body: "Sora (video generation) is OpenAI's bet that frontier modality coverage matters more than depth in any one. If Sora ships consumer-style features faster than image, voice, or audio peers, it tells you the company's product priorities for the next 12 months.",
        category: "company",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 4, "Google DeepMind", "Research depth + integration.", 6, [
      spark("DeepMind edge", {
        type: "microread",
        title: "Research-meets-scale",
        body: "Google DeepMind merged Brain + DeepMind in 2023. Strengths: deep research (AlphaFold, Gemini), giant infrastructure (TPUs), integration into Workspace + Android + Search. Models: Gemini family, including thinking variants and Nano (on-device). Builder note: best multimodal + tightest integration with Google Cloud + Workspace.",
        takeaway: "Research depth + ecosystem reach. Pick if you live in Google land.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("The Gemini family", {
        type: "microread",
        title: "Pro, Flash, Nano",
        body: "Gemini Pro — flagship, biggest context window in the field at launch (1M+ tokens). Gemini Flash — cheap + fast, the most cost-competitive frontier-grade model on price-per-token. Gemini Nano — small, runs on-device on Pixel + Android. The trio covers cloud-cheap, cloud-flagship, and edge in one family.",
        takeaway: "Gemini wins on context length and on Flash's cost-per-token.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("TPU = Google's silicon edge", {
        type: "microread",
        title: "Why Google trains on its own chips",
        body: "Google doesn't rent NVIDIA H100s — it trains on its own Tensor Processing Units (TPUs). That gives DeepMind cost + supply advantages no one else has, plus deep co-design between hardware and model architecture. TPUs are the reason Gemini Flash can be priced where it is.",
        takeaway: "TPUs are Google's structural cost advantage in training.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("AlphaFold lineage", {
        type: "microread",
        title: "Why AlphaFold matters for AI",
        body: "DeepMind's AlphaFold predicted 200M+ protein structures, won a Nobel Prize for chemistry, and re-shaped biology. For AI builders, the takeaway: domain-specific architectures + training data still beat general LLMs on bounded scientific problems. Consider this when you scope a deep-vertical product.",
        takeaway: "On bounded scientific problems, specialized > general.",
        category: "principle",
        addedAt: "2025-10-01",
        source: {
          name: "Google DeepMind",
          url: "https://deepmind.google/discover/blog/",
        },
      }),
      spark("Google distribution surface", {
        type: "microread",
        title: "Where Gemini ships",
        body: "Gemini lives inside Workspace (Docs, Gmail, Sheets), Android (on-device + Pixel Assistant), Search (AI overviews), Chrome (built-in summaries), Vertex AI (cloud), and the Gemini consumer app. No other lab has anything close to that surface area. The catch: each surface has its own UX constraints — pick the one that fits your use case.",
        takeaway: "Google's distribution surface is unmatched. Pick the slot that fits.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Demis vs Sam vs Dario", {
        type: "patternmatch",
        prompt: "Match each frontier-lab CEO to their primary public bet.",
        pairs: [
          { left: "Demis Hassabis (Google DeepMind)", right: "Science-as-product, AGI via research depth" },
          { left: "Sam Altman (OpenAI)", right: "Product distribution + abundance via scale" },
          { left: "Dario Amodei (Anthropic)", right: "Safety-first frontier capability + interpretability" },
          { left: "Mark Zuckerberg (Meta AI)", right: "Open-weights ubiquity + ecosystem leverage" },
        ],
        explain: "The CEO's public framing predicts a lot of the lab's product choices.",
      }),
      spark("Long-context superpower", {
        type: "tip",
        title: "💡 Use Gemini for long-context jobs",
        body: "When you have a 500K-token codebase or a 600-page PDF and you need a single model to read all of it, Gemini Pro is the practical default. Most other frontier models top out at 200K tokens or hit accuracy degradation earlier.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Where Gemini still struggles", {
        type: "microread",
        title: "Read the eval skeptic's view",
        body: "Gemini's pure-coding agentic performance has historically lagged Claude in head-to-head developer evaluations. It compensates with multimodal + context + price. Builders: don't just read the lab's announcement post — search for the same model on independent leaderboards before committing.",
        takeaway: "Gemini wins multimodal + context. Claude wins coding agents. Test for yours.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Gemini vs Claude scenario", {
        type: "scenario",
        setup: "You're building a feature that summarises a customer's full email history (often 200K+ tokens) and writes a personalised reply. Latency matters; cost matters more.",
        prompt: "Best default starting model?",
        options: [
          "Claude Sonnet — gold-standard for English summarisation",
          "Gemini Flash — long-context + cheapest per token",
          "GPT-4o — broadest API surface",
          "Llama on-prem — no per-token cost",
        ],
        answer: 1,
        explain: "For long-context cheap-per-token summarisation, Gemini Flash is the practical default. Always benchmark on your own inputs.",
      }),
      spark("DeepMind's research drumbeat", {
        type: "tip",
        title: "💡 Subscribe to DeepMind's blog",
        body: "Google DeepMind publishes long, technical posts at deepmind.google/discover/blog/. Reading two per month keeps you ahead on what frontier research is actually doing — independent of marketing posts.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Google DeepMind",
          url: "https://deepmind.google/discover/blog/",
        },
      }),
    ]),
    level(T, 5, "Meta + open weights", "Llama and beyond.", 6, [
      spark("Meta's open bet", {
        type: "microread",
        title: "Why Meta gives weights away",
        body: "Meta open-sources frontier-class weights (Llama series). Strategic logic: drive ecosystem standards, hire from the field that uses your tools, undermine closed-API moats. Effect: thousands of fine-tunes, research acceleration, enterprise on-prem options. The open ecosystem is now serious infrastructure.",
        takeaway: "Open weights = real production option, especially regulated.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("The Llama family", {
        type: "microread",
        title: "Llama 3, 3.1, 3.2, 4",
        body: "Llama 3.1 introduced the 405B-parameter open-weights model (the biggest open release of its time). Llama 3.2 added vision + small on-device sizes. Llama 4 brought a Mixture-of-Experts architecture. The trajectory: bigger ceiling AND better small models, simultaneously. Open ecosystem is no longer 'almost as good' — it's the floor everyone else has to beat.",
        takeaway: "Open Llama is the floor; closed labs have to beat it on margin.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Why open weights kill price", {
        type: "microread",
        title: "The price-floor mechanism",
        body: "Once Llama-class weights are downloadable, every cloud (Together, Fireworks, Groq, Replicate, even AWS Bedrock) can host them and undercut the closed labs on the same capability tier. The closed lab has to charge a margin worth paying — i.e., be measurably better. That's why frontier API prices keep dropping.",
        takeaway: "Open weights are the price-floor enforcement mechanism for the field.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Llama license fine print", {
        type: "tip",
        title: "💡 Read the Llama license",
        body: "Llama's license is permissive but not strict-MIT. It carves out giant-platform usage (>700M MAU) and has acceptable-use clauses. Most startups are fine; if you're at FAANG scale, read carefully. License is on the Meta AI repo on GitHub and Hugging Face.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Where Llama wins", {
        type: "patternmatch",
        prompt: "Match each builder situation to where Llama is the right answer.",
        pairs: [
          { left: "On-prem regulated finance / health", right: "Run Llama in your own VPC" },
          { left: "Latency-critical real-time API", right: "Host Llama on Groq or Fireworks" },
          { left: "Custom fine-tune on internal data", right: "Llama base + LoRA fine-tune" },
          { left: "Edge / on-device inference", right: "Llama 3.2 1B / 3B" },
        ],
        explain: "Each Llama deployment shape solves a problem closed APIs can't.",
      }),
      spark("Quantization in plain English", {
        type: "microread",
        title: "Why a 70B model fits on your laptop",
        body: "Quantization compresses model weights from 16-bit floats down to 4-bit (or even 2-bit) integers. A Llama-3 70B that's normally 140GB shrinks to ~40GB at 4-bit, runs on a single 48GB GPU or even on a Mac with enough RAM. Quality drops slightly; usability rises a lot. GGUF + llama.cpp made this everyday infrastructure.",
        takeaway: "Quantization = the hack that puts frontier models on consumer hardware.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Open does not mean free", {
        type: "quickpick",
        prompt: "What's the biggest hidden cost of running Llama in production yourself?",
        options: [
          "License fee",
          "GPU hardware + ops + redundancy",
          "There is no cost — it's open source",
          "Model card subscription",
        ],
        answer: 1,
        explain: "Llama itself is free. The cost is GPUs, autoscaling, observability, on-call. Often more expensive than just calling a closed API at small scale.",
      }),
      spark("Meta's strategic logic", {
        type: "scenario",
        setup: "Meta gives away frontier-class weights for free. You're a board observer asking: 'Why isn't this strategic suicide?'",
        prompt: "Best one-sentence answer?",
        options: [
          "Meta hopes good karma compounds",
          "Open weights commoditize the model layer, which protects Meta's distribution layer (Instagram, WhatsApp)",
          "Meta accidentally trained too much",
          "It's a tax write-off",
        ],
        answer: 1,
        explain: "Meta's moat is distribution. Commoditizing the model layer prevents OpenAI/Google from building a layer that sits above Meta's apps.",
      }),
      spark("Where Llama runs best", {
        type: "tip",
        title: "💡 If you have to ship Llama in prod",
        body: "Try Together AI, Fireworks, Groq, or Cerebras for managed serving. Use vLLM on your own GPUs only if you've got the ops capacity. Bedrock + Vertex also host Llama if you're already in those clouds.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 6, "xAI, Mistral, Cohere, Inflection", "The serious challengers.", 6, [
      spark("Mid-tier matters", {
        type: "microread",
        title: "Beyond the big three",
        body: "xAI (Grok, fast iteration), Mistral (Euro-based, mix of open + premium), Cohere (enterprise/RAG focus), Inflection (consumer voice). They occupy niches: speed, region, vertical, modality. Smart builders watch them — sometimes you find a better cost/perf fit than the giants.",
        takeaway: "Don't ignore mid-tier. Niches sometimes win on price/perf.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("xAI in one breath", {
        type: "microread",
        title: "Speed, scale, X integration",
        body: "xAI ships Grok, integrated into X (Twitter) and trained on Colossus — the Memphis supercluster Elon Musk built in record time. Strategic moves: aggressive scale-up of GPU footprint, fast iteration cycles, real-time X data as a training advantage. The bet: raw scale + speed beat process-heavy rivals.",
        takeaway: "xAI bets on raw scale + speed over process discipline.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Mistral's Euro positioning", {
        type: "microread",
        title: "Why Mistral matters for the EU",
        body: "Mistral, founded in Paris, is Europe's frontier-lab answer. Its appeal: data residency in EU, sovereign-cloud partnerships, a mix of open-weights and premium closed models. Buyers in regulated EU industries often pick Mistral for compliance reasons even when it isn't the absolute strongest model.",
        takeaway: "Mistral wins EU-sovereignty buyers even when ranked below the giants.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Cohere = enterprise RAG", {
        type: "microread",
        title: "Why Cohere is still around",
        body: "Cohere doubled down on enterprise + RAG instead of chasing consumer chat. Its Command + Embed models are tuned for retrieval-heavy enterprise workflows; its rerankers are best-in-class for re-scoring search results. If you're building a search-anchored enterprise product, Cohere is worth a benchmark.",
        takeaway: "Cohere's niche is enterprise RAG + best-in-class rerankers.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("China's frontier", {
        type: "microread",
        title: "DeepSeek, Qwen, Yi, GLM",
        body: "Chinese labs ship serious frontier models, often open-weights. DeepSeek (mathematical reasoning + coding), Alibaba's Qwen (broad multilingual), 01.AI's Yi (efficient training), Zhipu's GLM-4. They train on different data, optimize for different markets, and put enormous price pressure on the West. Builders ignoring them are missing half the field.",
        takeaway: "Chinese open-weights labs are co-shaping the global price floor.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Pick the right challenger", {
        type: "patternmatch",
        prompt: "Match each challenger to where it's the right pick.",
        pairs: [
          { left: "xAI Grok", right: "Real-time X-integrated experiences" },
          { left: "Mistral", right: "EU data-residency + sovereign cloud" },
          { left: "Cohere", right: "Enterprise RAG + reranking" },
          { left: "DeepSeek", right: "Open-weights coding + math reasoning" },
        ],
        explain: "Mid-tier labs win on niche. Pick by job, not by leaderboard rank.",
      }),
      spark("When to bench a challenger", {
        type: "scenario",
        setup: "Your CEO sees a tweet hyping a small lab's new model. They ask: 'Should we switch?'",
        prompt: "What's the best response?",
        options: [
          "Yes, switch immediately to ride hype",
          "Run a 30-case house eval on the new model + compare to incumbent before any switch",
          "No, never switch",
          "Switch only if the lab is American",
        ],
        answer: 1,
        explain: "Always bench against your own evals before switching infrastructure. Hype is a signal to investigate, not to migrate.",
      }),
      spark("Inflection's pivot", {
        type: "tip",
        title: "💡 Note Inflection's lesson",
        body: "Inflection raised over $1.5B and built Pi (consumer voice AI), then most of its team joined Microsoft in 2024 in an unusual quasi-acquisition. The takeaway for builders: consumer chat is the hardest moat to defend without a giant distribution partner.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("AI21, Reka, AdeptAI", {
        type: "microread",
        title: "Smaller niches, real teams",
        body: "AI21 (Jamba — hybrid SSM/Transformer architecture), Reka (multimodal + edge), Adept AI (action-taking models, since acquired). They show up in vertical evals and sometimes win. Watching them is how you learn what architectures might matter next year.",
        takeaway: "Niche labs preview tomorrow's architectures — track lightly, pick rarely.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Latent Space tracks the niches", {
        type: "tip",
        title: "💡 Read Latent Space",
        body: "swyx + Alessio's Latent Space newsletter + podcast tracks the mid-tier and frontier rigorously. One of the best places to hear founders + researchers from labs the major press skips.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Latent Space",
          url: "https://www.latent.space",
        },
      }),
    ]),
    level(T, 7, "AI-native frontier startups", "The picks-and-shovels & apps.", 6, [
      spark("Two clusters", {
        type: "microread",
        title: "Infra + apps",
        body: "Frontier AI startups split into infra (Modal, Replicate, Together, Fireworks, Pinecone, Weaviate, Helicone) and apps (Cursor, Perplexity, Harvey, Glean, Decagon). Infra companies battle on latency + price + DX. App companies battle on retention + workflow lock-in. Both have minted unicorns rapidly.",
        takeaway: "Infra battles on DX. Apps battle on workflow lock-in.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Cursor's wedge", {
        type: "microread",
        title: "Why Cursor became the AI IDE",
        body: "Cursor forked VS Code, layered AI-first UX (Cmd-K for surgical edits, Composer for multi-file changes, agent mode), and got the keystroke-level UX right. The wedge wasn't a better model — it was a better surface, in the IDE where developers already lived. Now Cursor commands serious revenue and a huge user base.",
        takeaway: "Cursor won on UX-in-the-IDE, not on model quality.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Perplexity's bet", {
        type: "microread",
        title: "Search reinvented",
        body: "Perplexity bet that search-as-a-chat-experience could displace Google for many information-foraging tasks. Strengths: cited sources, clean UX, no SEO spam. Risks: Google can ship the same UX in Search; OpenAI can ship the same UX in ChatGPT. Worth studying because it shows how a small team can turn a big market shape on its head.",
        takeaway: "Perplexity reinvented search UX — but defensibility is the open question.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Harvey + Glean", {
        type: "microread",
        title: "Vertical AI for big companies",
        body: "Harvey targets law (used by Allen & Overy, A&O Shearman). Glean targets enterprise search (Workday, Okta-style buyers). Both win by going deep into one workflow + one trust posture, not wide on capabilities. Vertical depth + enterprise sales = real revenue without needing to be a frontier lab.",
        takeaway: "Vertical AI > horizontal AI when the buyer is a Fortune 500.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Decagon + Sierra: agent CX", {
        type: "microread",
        title: "AI customer support",
        body: "Decagon and Sierra are leading the new wave of customer-experience AI agents. They handle full ticket lifecycles, not just suggestions. The wedge: replace tier-1 agents at lower cost-per-resolution, keep humans for escalation. The buyer is the VP of CX, not the CTO — different sales motion than horizontal AI infra.",
        takeaway: "AI CX startups sell to VP of CX, not VP of Eng. Different motion.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Modal vs Replicate vs Together", {
        type: "patternmatch",
        prompt: "Match each infra company to its sharpest pitch.",
        pairs: [
          { left: "Modal", right: "Serverless GPUs for Python; great DX for batch jobs" },
          { left: "Replicate", right: "One-click hosting for any open model" },
          { left: "Together AI", right: "Fast hosted inference for open-weight LLMs" },
          { left: "Fireworks", right: "High-throughput inference + function calling on open weights" },
        ],
        explain: "All four serve open-weights infra; the wedge is shape of DX.",
      }),
      spark("Vector DB shootout", {
        type: "microread",
        title: "Pinecone vs Weaviate vs pgvector",
        body: "Pinecone — managed, fast, pricey at scale, the easy-button. Weaviate — open-source + managed, hybrid search built in. Qdrant — open-source, Rust, very fast. pgvector — Postgres extension, perfect when you already have Postgres. Default: pgvector until your team feels real pain.",
        takeaway: "Start pgvector. Migrate when scale truly forces.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pinecone tip", {
        type: "tip",
        title: "💡 Pinecone serverless first",
        body: "If you do pick Pinecone, default to serverless. Their pod-based pricing surprises a lot of teams in the second month. Serverless scales to zero between requests.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("AI startup defensibility", {
        type: "quickpick",
        prompt: "What's the most durable moat for an AI-native app startup?",
        options: [
          "Owning the model",
          "Workflow lock-in + proprietary data + distribution",
          "Spending the most on training",
          "Hiring ex-OpenAI",
        ],
        answer: 1,
        explain: "Almost no app startup can out-train the labs. Defensibility comes from the workflow, the data they generate, and where they sit in their customer's day.",
      }),
      spark("Why GTM-velocity matters", {
        type: "microread",
        title: "Speed > model in 2025",
        body: "In 2025-era AI, the model improvements are so fast that this year's frontier is next year's open-weight default. The companies pulling away are those with fastest GTM iteration — they ship a new product surface to a real customer every 2 weeks. The model-quality moat is shrinking; the GTM-velocity moat is widening.",
        takeaway: "GTM velocity is the new moat as model quality commoditizes.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Build a Cursor-style demo", {
        type: "buildcard",
        title: "Build: AI feature inside an existing tool",
        pitch: "Pick a tool you use daily. Add the smallest AI surface you'd actually use. Ship it.",
        promptToCopy:
          "Help me prototype a Chrome extension that adds a Cmd-K palette to the page I'm on, sends the selection + a prompt to Claude or GPT, and replaces the selection with the model's answer. Use plain JS, no framework. Keep total code under 200 lines.",
        successCriteria: "A working extension that selects text, prompts a model, replaces in-place.",
      }),
      spark("Decagon scenario", {
        type: "scenario",
        setup: "You're advising a Series B SaaS company that's spending $4M/year on tier-1 customer support and considering an AI agent platform.",
        prompt: "What's the most informative first metric to ask?",
        options: [
          "Lab leaderboard rank of the underlying model",
          "Resolution rate per conversation + escalation rate to human",
          "Cost per 1M tokens",
          "Whether the agent uses RAG",
        ],
        answer: 1,
        explain: "For CX agents, what matters is whether the agent actually resolved the ticket and how often it escalated. Token cost is irrelevant if the resolution rate is wrong.",
      }),
      spark("Sharp wedge thesis", {
        type: "microread",
        title: "How AI-native winners pick wedges",
        body: "AI-native winners share a pattern: pick one sharp wedge inside an existing daily tool — Cursor in the editor, Perplexity in search, Harvey in legal — then iterate workflow weekly. Not 'general AI for everything' — 'one workflow done unreasonably well.' Latent Space + a16z's portfolio analyses both keep landing on this shape. Builders should ask 'where do my users live every day?' before 'what model should I use?'",
        takeaway: "Sharp wedge in a daily tool > general AI everywhere.",
        category: "principle",
        addedAt: "2025-10-01",
        source: {
          name: "Latent Space",
          url: "https://www.latent.space",
        },
      }),
      spark("Anthropic news drop watch", {
        type: "tip",
        title: "💡 Watch Anthropic news for partnership signals",
        body: "Big AI-native companies often debut their flagship integrations on anthropic.com/news (Cursor, Perplexity, Harvey, Notion all have). Reading the news page weekly tells you who's been paying for serious model spend.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Anthropic",
          url: "https://www.anthropic.com/news",
        },
      }),
    ]),
    level(T, 8, "How to read a model release", "Spec, eval, vibe.", 6, [
      spark("Model release decoder", {
        type: "microread",
        title: "How to read launches",
        body: "When a lab ships a new model, read in this order: (1) capability table — what's actually new. (2) eval scores — but only on benchmarks you trust. (3) pricing — token cost, context size. (4) latency — TPS for streaming. (5) vibes — community demos. Skip the hype thread; it lies. Always test on YOUR eval set before switching production.",
        takeaway: "Capabilities → evals → price → vibes. Never just vibes.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Keep a 30-case 'house eval' you run on every new model release. You'll know in 20 min whether it's actually better for YOUR use case.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Read the model card", {
        type: "tip",
        title: "💡 Skim the model card section by section",
        body: "Every credible release ships a model card. Skim: training data summary → capability claims → known limitations → safety evaluations → red-team summary. The 'known limitations' section is the most valuable — it's where the lab is most honest.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Eval landmines", {
        type: "patternmatch",
        prompt: "Match each eval-reading mistake to the right caution.",
        pairs: [
          { left: "Lab reports 95% on benchmark X", right: "Check whether benchmark X is in the training set" },
          { left: "New model 'beats' incumbent on chart", right: "Check the chart's y-axis range and the test split" },
          { left: "Demo shows complex multi-step task", right: "Cherry-picked. Try your own version." },
          { left: "Cost-per-token claim", right: "Multiply by your typical input + output token shape, not theirs" },
        ],
        explain: "Read every release with skepticism. The lab's job is to make it look good; yours is to find where it isn't.",
      }),
      spark("The Challenger disaster of AI", {
        type: "podcastnugget",
        creatorId: "lenny",
        quote:
          "Lots of people knew those little O-rings were unreliable, but every single time you get away with launching a space shuttle without the O-rings failing, you institutionally feel more confident in what you're doing. We've been using these systems in increasingly unsafe ways. My prediction is we're going to see a Challenger disaster.",
        takeaway:
          "Ship velocity is masking risk. Treat each AI agent run as if the worst-case prompt-injection has already happened — because the day it does, 'we always did it this way' won't save you.",
        source: {
          podcast: "Lenny's Podcast",
          podcastUrl: "https://www.lennysnewsletter.com/podcast",
          guest: "Simon Willison",
          guestRole: "co-creator of Django, coined 'prompt injection'",
          episodeTitle: "The November inflection: AI coding crosses the threshold",
          timestamp: "00:01:08",
        },
      }),
      spark("Migration scenario", {
        type: "scenario",
        setup: "A new model is announced that benchmarks 12% higher than what you ship today on a public benchmark.",
        prompt: "What's the right next step?",
        options: [
          "Switch the production model name tonight",
          "Run your house eval, A/B in shadow mode for a week, then decide",
          "Wait six months for stability",
          "Ignore until your CEO asks",
        ],
        answer: 1,
        explain: "House eval + shadow A/B is the standard discipline. Public benchmarks are a starting signal, never the final answer.",
      }),
      spark("Pricing reading exercise", {
        type: "quickpick",
        prompt: "Lab announces $1/M input + $5/M output. Your typical request is 10K input + 500 output tokens. What's the cost per request?",
        options: ["$0.001", "$0.0125", "$0.06", "$1.50"],
        answer: 1,
        explain: "10K input × $1/M = $0.01. 500 output × $5/M = $0.0025. Total ~$0.0125 per request. Reading pricing requires multiplying by YOUR token shape.",
      }),
      spark("Latency matters more than people say", {
        type: "microread",
        title: "TPS, TTFT, time-to-action",
        body: "Time-to-first-token (TTFT) and tokens-per-second (TPS) decide UX. A model that's 5% smarter but 3x slower is often the wrong choice for a user-facing surface. For agents, what matters is time-to-action — the sum of model latency, tool latency, and orchestrator overhead.",
        takeaway: "Latency is product. Always benchmark TTFT + TPS in your real path.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 9, "Talent + research signals", "Who to follow.", 6, [
      spark("Watch the diaspora", {
        type: "microread",
        title: "People are the signal",
        body: "Lab quality follows people. When senior researchers move (e.g. Anthropic founders left OpenAI, then later moves), expect ripples. Watch ICML/NeurIPS papers, lab blog posts, key Twitter accounts (Karpathy, Demis, Dario, Sam). Also watch arxiv-sanity for papers cited by frontier labs.",
        takeaway: "Follow people, not hype. Diasporas predict shifts.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Researcher moves to watch", {
        type: "microread",
        title: "Diaspora reading list",
        body: "Track: Andrej Karpathy (Tesla → OpenAI → Eureka Labs), Ilya Sutskever (OpenAI → SSI), Mira Murati (OpenAI → Thinking Machines), John Schulman (OpenAI → Anthropic), Jan Leike (OpenAI → Anthropic). Each move re-shapes a lab. Follow them on X and read their first interview after the move.",
        takeaway: "The 'first interview after the move' is highest-signal content.",
        category: "company",
        addedAt: "2026-05-01",
      }),
      spark("Lab blogs to subscribe", {
        type: "tip",
        title: "💡 Three blogs that matter",
        body: "Anthropic's news (anthropic.com/news), Google DeepMind's blog (deepmind.google/discover/blog), and OpenAI's research page. Subscribe via RSS or email — the blog post is always more substantive than the launch tweet.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Google DeepMind",
          url: "https://deepmind.google/discover/blog/",
        },
      }),
      spark("Conferences as signal", {
        type: "microread",
        title: "NeurIPS, ICML, ICLR",
        body: "The big-three ML conferences (NeurIPS, ICML, ICLR) are where frontier labs publish the work behind tomorrow's products. Read the accepted papers list, search by lab affiliation, skim the abstracts. You'll see the next product six months before it launches.",
        takeaway: "Read NeurIPS/ICML accept-lists by lab to predict launches.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Track open-source authors", {
        type: "microread",
        title: "GitHub follows that matter",
        body: "Follow on GitHub: Andrej Karpathy (nanoGPT, Eureka), Georgi Gerganov (llama.cpp), Tim Dettmers (bitsandbytes / quantization), the Hugging Face team accounts, the vLLM team, the LangChain team. Their commit activity is leading-indicator information for what the field will use.",
        takeaway: "GitHub commits are leading-indicator signal. Follow the right authors.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Talent quickpick", {
        type: "quickpick",
        prompt: "A senior researcher announces they're leaving Big Lab A to start their own. What's the highest-signal next read?",
        options: [
          "The Big Lab A's PR statement",
          "Their first long-form interview after the move",
          "Their last paper at the previous lab",
          "All three",
        ],
        answer: 3,
        explain: "All three. PR statement = position. First interview = bet. Last paper = unfinished business they probably want to finish at the new place.",
      }),
      spark("Conference deadline trick", {
        type: "tip",
        title: "💡 Watch deadlines, not announcements",
        body: "Frontier labs time releases around NeurIPS / ICML / Google I/O / Anthropic events. Knowing these calendars means you predict launches by 4–8 weeks. Most launch noise hits the week of a conference.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 10, "Boss: frontier check", "Final gate.", 6, [
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: Frontier Companies",
        questions: [
          {
            type: "quickpick",
            prompt: "Best lab fit for a privacy-strict enterprise feature?",
            options: ["Closed API with no audit", "Anthropic or open-weights on-prem", "Whatever's cheapest", "GPT free tier"],
            answer: 1,
            explain: "Safety + on-prem options matter most.",
          },
          {
            type: "quickpick",
            prompt: "Quickest signal to know if a new model fits your product?",
            options: ["Twitter hype", "Run your 30-case house eval", "Press release", "Benchmarks alone"],
            answer: 1,
            explain: "Your evals > anyone else's.",
          },
          {
            type: "quickpick",
            prompt: "Why follow open-weights labs even if you don't ship them?",
            options: ["Boredom", "They drive prices + research that affect closed labs too", "Cool merch", "Easier APIs"],
            answer: 1,
            explain: "Open ecosystem reshapes the whole market.",
          },
        ],
      }),
    ]),
  ],
};
