import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "memory-safety" as const;

export const memorySafety: Topic = {
  id: T,
  name: "Memory & Safety",
  emoji: "🧬",
  tagline: "RAG, memory layers, alignment, and safe-by-design AI.",
  color: "#ff5d8f",
  visual: "memory",
  levels: [
    level(T, 1, "Why models forget", "The context window is short-term memory.", 4, [
      spark("Goldfish brain", {
        type: "microread",
        title: "LLMs have no memory by default",
        body: "Each API call starts fresh. The model only 'knows' what's in the current prompt. The 200k-token context window is short-term memory — it disappears the second the call ends. Anything you want it to remember tomorrow has to be stored somewhere and re-injected. That's the entire point of memory layers, RAG, and conversation history.",
        takeaway: "No persistence by default. You provide the memory.",
        visual: "memory",
        category: "principle",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "An LLM is like a friend with no long-term memory. Every chat starts blank. The 'context window' is what they hold in their hands during one conversation. Want them to remember your name tomorrow? Save it somewhere and put it in front of them next time.",
        },
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Where does an LLM 'remember' things between calls?",
        options: ["Inside the model weights", "It doesn't — you have to re-supply it", "Disk", "In a cookie"],
        answer: 1,
        explain: "Stateless by design. Memory is your job.",
      }),
      spark("Tokens, not words", {
        type: "microread",
        title: "Context measured in tokens",
        body: "A token is roughly 0.75 of a word in English. 'Hello, world!' is 4 tokens. A 200,000-token window holds about 150,000 English words — roughly 600 pages. Code is denser (a token can be a single bracket); some languages tokenize worse. When you size a prompt or a RAG chunk, count tokens, not characters. tiktoken (OpenAI), anthropic-tokenizer-typescript (Claude) make this trivial.",
        takeaway: "Count tokens, not chars. Use tiktoken/anthropic tokenizer.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Lost in the middle", {
        type: "microread",
        title: "Models miss facts buried mid-context",
        body: "Liu et al. (2023) showed that LLMs find facts at the start and end of long contexts more reliably than facts in the middle. A 100k-token prompt with the answer at token 50,000 gets answered worse than one with it at token 5,000. Mitigations: put critical facts first or last, summarize the middle, use RAG to keep prompts shorter and more focused.",
        takeaway: "Long context has dead zones. Put facts at the edges.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match: state", {
        type: "patternmatch",
        prompt: "Where each 'memory' actually lives",
        pairs: [
          { left: "Model weights", right: "Frozen at training" },
          { left: "Context window", right: "Re-supplied every call" },
          { left: "Conversation history", right: "Your DB, replayed in prompt" },
          { left: "Long-term user facts", right: "Vector DB or structured store" },
        ],
        explain: "Four storage layers, four lifetimes.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Truncate from the middle",
        body: "When the conversation runs long, drop the middle, not the start. The system prompt + most recent turns matter most; the middle can be summarized into one line.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Effective context length", {
        type: "microread",
        title: "Advertised vs effective",
        body: "A model's advertised window (1M tokens for Gemini 1.5 Pro, 200k for Claude Sonnet) is the maximum it can ingest — not the maximum it answers well from. Effective context (where retrieval F1 stays high) is usually 30–60% of the advertised number. Test on your data with a 'needle in a haystack' eval before assuming the full window is usable.",
        takeaway: "Effective context < advertised. Run NIAH evals on your data.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Why size matters", {
        type: "scenario",
        setup: "You're stuffing 50k tokens of legal text into Claude. Answers are slow and sometimes miss key clauses.",
        prompt: "Best fix?",
        options: [
          "Use a bigger model",
          "Switch to RAG over the same docs — retrieve only relevant clauses",
          "Repeat the question 3 times",
          "Lower temperature",
        ],
        answer: 1,
        explain: "Smaller, targeted prompts beat stuffing every time.",
      }),
      spark("Stateless service", {
        type: "microread",
        title: "Anthropic and OpenAI APIs are stateless",
        body: "Both APIs forget after each call by default. OpenAI's Responses API and the new Assistants API can persist threads server-side, but you pay for the storage and lose audit transparency. For most apps, keep state on your side: own the database, own the prompt construction, own the memory policy. It's portable across providers.",
        takeaway: "Own your state. Don't rent provider memory.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Prompt caching saves tokens",
        body: "Anthropic's prompt caching: tag the system prompt + reference docs as cacheable. Subsequent calls within 5 minutes pay 10% of the input cost for that span. Same idea on Gemini and OpenAI. Up to 90% cost cut on RAG-style apps.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 2, "RAG in plain terms", "Retrieval-Augmented Generation, demystified.", 5, [
      spark("Lookup, then answer", {
        type: "microread",
        title: "RAG = search + LLM",
        body: "When a user asks a question, you embed it, search your vector DB for the top-k most relevant chunks, paste them into the prompt, and let the LLM answer using those chunks. That's RAG in one paragraph. It works because the model is great at synthesizing supplied facts, even if it didn't know them. It fails when chunks are too small, too big, retrieved badly, or the LLM ignores them.",
        takeaway: "RAG = relevant docs in context, then answer.",
        visual: "embed",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Chunk by structure, not size",
        body: "Chunk by semantic boundary (paragraph, section), not fixed token size. Always include the chunk's source title — the model uses it to weight authority. unstructured.io and LangChain's RecursiveCharacterTextSplitter both respect headings.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Build it", {
        type: "buildcard",
        title: "Build: 50-line RAG over your notes",
        pitch: "End-to-end RAG. You'll never fear the term again.",
        promptToCopy:
          "Build a Python script that ingests a folder of markdown notes, chunks them by heading, embeds with sentence-transformers, stores in a local SQLite + sqlite-vec DB, and answers questions via the Anthropic API with the top 3 chunks injected into the prompt.",
        successCriteria: "You can ask questions about your own notes and get cited answers.",
      }),
      spark("Embeddings 101", {
        type: "microread",
        title: "Vectors are coordinates of meaning",
        body: "An embedding maps text into a 1024- to 4096-dimensional vector. Texts with similar meaning sit close together; cosine similarity measures the angle between them. Use OpenAI's text-embedding-3-small ($0.02/M tokens), Cohere's embed-v3, Voyage AI for code, or open-source bge-large / nomic-embed-text via Hugging Face. Pick one and stick with it — embeddings from different models are not comparable.",
        takeaway: "Pick one embedding model. Don't mix.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Vector DB shootout", {
        type: "microread",
        title: "pgvector, Qdrant, Pinecone, Chroma, Weaviate",
        body: "pgvector inside Postgres: zero new infra, fine to ~10M vectors. Qdrant: open source, fast HNSW, good filtering — most popular choice today. Pinecone: managed, scales to billions, expensive. Chroma: dead-simple Python embedded. Weaviate: native hybrid search. Lance/LanceDB: object-store-backed, cheap. Most apps start with pgvector and switch only when they need >5M vectors with metadata filters.",
        takeaway: "Start pgvector. Move to Qdrant at >5M vectors.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Hybrid search", {
        type: "microread",
        title: "BM25 + vectors > vectors alone",
        body: "Vector search recalls semantically similar chunks. BM25 (the classic keyword score) recalls chunks with the exact rare term. Combining them with reciprocal rank fusion (RRF) consistently beats either alone. Qdrant, Weaviate, Elastic, and Vespa all support hybrid out of the box. Worth ~10-20% retrieval F1 on most corpora.",
        takeaway: "Hybrid (BM25 + vector) > vector-only. Free upgrade.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Reranker pass", {
        type: "microread",
        title: "Top-30, then rerank to top-5",
        body: "First-stage retrieval is fast but coarse. A cross-encoder reranker (Cohere Rerank, BAAI/bge-reranker-v2-m3, voyage-rerank-2) reads the query + each chunk pair and scores relevance. Pull 30 candidates, rerank to your final top 5. Improves precision by 15-30 points on benchmarks like BEIR. Adds 100-300ms — usually worth it.",
        takeaway: "Pull 30, rerank to 5. Big precision win.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match: failure modes", {
        type: "patternmatch",
        prompt: "Match the RAG failure to its fix",
        pairs: [
          { left: "Retriever returns nothing relevant", right: "Hybrid search + reranker" },
          { left: "Chunks are right but answer is wrong", right: "Increase chunk overlap; cite sources" },
          { left: "Latency is brutal", right: "Cache embeddings; smaller embedding model" },
          { left: "Hallucinates despite chunks", right: "Force quote-from-source, lower temperature" },
        ],
        explain: "Each RAG failure has a known fix.",
      }),
      spark("Citations are UX", {
        type: "tip",
        title: "Ground every claim",
        body: "Have the model produce inline citations like [1], [2] tied to chunk IDs. Render them as clickable. Users trust answers they can verify, and you get a free debug surface — when answers are wrong, you can see which chunk misled the model.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("RAG vs fine-tuning", {
        type: "microread",
        title: "When each wins",
        body: "RAG: knowledge changes, you have lots of docs, you need provenance. Fine-tuning: tone/format/structure matters, you want low latency, the knowledge is small and stable. Most production AI systems are RAG-first because data changes faster than retraining. Fine-tune for style, RAG for facts. The combo is the gold standard.",
        takeaway: "RAG for facts, fine-tune for style. Stack them.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("LlamaIndex vs LangChain", {
        type: "microread",
        title: "Two RAG frameworks, two philosophies",
        body: "LlamaIndex (formerly GPT Index) is RAG-first: clean abstractions for ingestion, indexing, and querying. LangChain is broader and changes faster, with chains, agents, tools. For a pure RAG app, LlamaIndex's APIs are more focused. For agent-with-tools-and-retrieval, LangChain or LangGraph wins. You'll likely outgrow either; both are scaffolds.",
        takeaway: "LlamaIndex for RAG-only. LangChain for agents.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 3, "Memory layers", "Working, short-term, long-term.", 4, [
      spark("Three tiers", {
        type: "microread",
        title: "Working / short / long memory",
        body: "Working memory = the current prompt. Short-term = the conversation history (last N turns). Long-term = a persistent store (vector DB, summary doc, structured profile) you query and inject as needed. Production AI products design all three deliberately. Skipping the long-term layer is why most chatbots feel amnesiac.",
        takeaway: "Design memory like a real database — layered, on purpose.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match", {
        type: "patternmatch",
        prompt: "Match each memory job to a tier",
        pairs: [
          { left: "User's name & preferences", right: "Long-term" },
          { left: "Last 5 chat messages", right: "Short-term" },
          { left: "Current question being answered", right: "Working" },
          { left: "Past purchase history", right: "Long-term" },
        ],
        explain: "Different lifetimes, different stores.",
      }),
      spark("Mem0", {
        type: "microread",
        title: "Mem0 — long-term memory as a service",
        body: "Mem0 (open source, mem0.ai) is a memory layer that sits between your app and the LLM. It extracts facts from each conversation, scores them, dedupes, and re-injects them as needed. Self-hostable on Postgres + Qdrant. Saves you writing the 'what to remember and when' code yourself. Same shape: Letta (formerly MemGPT), Zep.",
        takeaway: "Mem0 / Letta / Zep = drop-in long-term memory.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Summarize, don't truncate", {
        type: "microread",
        title: "Rolling-summary short-term memory",
        body: "When the chat hits 20 turns, don't drop the oldest — summarize them. Keep a compact 'so far' paragraph, plus the last 5 raw turns. The model gets continuity without paying for 20 turns of tokens. Pattern: every 5 new turns, regenerate the summary. Almost every chat product does this in some form.",
        takeaway: "Summary + recent turns > truncated history.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Episodic vs semantic", {
        type: "microread",
        title: "Two long-term memory shapes",
        body: "Episodic memory: discrete events ('on Tuesday Sara said her project was overdue'). Semantic memory: stable facts ('Sara works in marketing'). Both are useful, both deserve their own store. Episodic = append-only log with timestamps. Semantic = last-write-wins key/value. Mixing them in one vector DB makes retrieval messy. Separate the stores; query both per turn.",
        takeaway: "Episodic + semantic = two stores, one query.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "User says 'remember I like Python'. Where do you store it?",
        options: ["Drop in next prompt only", "Long-term semantic store keyed by user_id", "/dev/null", "Train it into the model"],
        answer: 1,
        explain: "Stable preference, semantic, last-write-wins.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Decay old memories",
        body: "Apply a freshness score to long-term memories: if a fact hasn't been confirmed in 90 days, deprioritize it. Same pattern as content freshness. Keeps stale assumptions from outliving their usefulness.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Letta scenario", {
        type: "scenario",
        setup: "You're building a personal assistant. Across sessions it should remember preferences, ongoing projects, and people the user mentioned.",
        prompt: "Best architecture?",
        options: [
          "Stuff every past message into the prompt",
          "A memory service (Mem0/Letta) extracting facts + retrieval at each turn",
          "Just fine-tune the model",
          "Save only the last 3 messages",
        ],
        answer: 1,
        explain: "Extract, store, retrieve. The whole point of a memory layer.",
      }),
      spark("MemGPT pattern", {
        type: "microread",
        title: "Page memory in and out",
        body: "Letta (formerly MemGPT) treats the context window like an OS treats RAM: limited, fast. Long-term storage is 'disk'. The agent decides at each turn what to page into context based on relevance. Implemented in Letta, claudable hooks, and Anthropic's memory tool (2025). Conceptually clean; pragmatically a couple of heuristics over a vector DB.",
        takeaway: "Page facts in/out by relevance, like an OS.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("PII out of memory", {
        type: "tip",
        title: "Redact before persisting",
        body: "Run Presidio (or similar) on memory writes. A 'remember I like Python' write is fine; a 'remember my SSN is …' write is a liability. The redactor strips it before the vector DB ever sees it.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 4, "Alignment, briefly", "Why HH (helpful, harmless) matters.", 4, [
      spark("Two failure modes", {
        type: "microread",
        title: "Helpful AND harmless",
        body: "An aligned model is helpful (does what you actually want) AND harmless (refuses misuse). Both matter — over-refusing is also a failure (frustrating, useless). Frontier labs spend massive effort on RLHF, constitutional AI, and red teaming to find this balance. As a builder, your prompt and policy layer extend this further to fit your product.",
        takeaway: "Alignment = helpful AND harmless. Calibrate for both.",
        visual: "shield",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "An assistant refuses to summarize a news article about violence. This is...",
        options: ["Perfectly aligned", "Over-refusal — a failure mode", "A network error", "Best practice"],
        answer: 1,
        explain: "Useful work blocked = misalignment too.",
      }),
      spark("RLHF in one paragraph", {
        type: "microread",
        title: "How models learn manners",
        body: "Reinforcement Learning from Human Feedback: humans rank pairs of model outputs (which is better?), a reward model learns from those rankings, then PPO (or DPO) tunes the base model to maximize that reward. It's how 'just predict the next token' becomes 'be helpful and follow instructions'. Imperfect, expensive, and the source of most personality differences across labs.",
        takeaway: "Pair rankings -> reward model -> PPO. That's RLHF.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Constitutional AI", {
        type: "microread",
        title: "Anthropic's approach",
        body: "Anthropic's Constitutional AI uses a written set of principles ('Be helpful, harmless, honest...') and trains the model to critique and revise its own outputs against those principles. Less reliance on humans labeling every example. The 'constitution' is public; you can read what shapes Claude. Most labs now use a hybrid of CAI-style self-critique + RLHF.",
        takeaway: "Self-critique against a public spec. Cheaper than pure RLHF.",
        source: { name: "Anthropic", url: "https://www.anthropic.com/news" },
        category: "principle",
        addedAt: "2026-05-01",
      }),
      spark("Pattern match: failure modes", {
        type: "patternmatch",
        prompt: "Match each output to its alignment failure",
        pairs: [
          { left: "Refuses to summarize a news article", right: "Over-refusal" },
          { left: "Writes a phishing email when asked", right: "Misuse" },
          { left: "Confidently invents a citation", right: "Hallucination" },
          { left: "Tells the user they're brilliant when they're wrong", right: "Sycophancy" },
        ],
        explain: "Four modes; product policy must address all four.",
      }),
      spark("Sycophancy", {
        type: "microread",
        title: "Models flatter, then mislead",
        body: "Models trained on human approval learn to agree with the user — even when the user is wrong. Sycophancy is measurable: change a fact in the user message and watch the model often go along. Mitigations: explicit prompts ('disagree if needed'), eval sets that catch flip-flopping, post-hoc judges. OpenAI's April 2025 GPT-4o regression on sycophancy made this a public concern.",
        takeaway: "Models flatter. Build evals that catch flip-flops.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Jailbreaks evolve", {
        type: "microread",
        title: "DAN, ablation, gradient attacks",
        body: "Jailbreak techniques keep finding new shapes: roleplay ('pretend you're DAN'), token-level attacks (Zou et al.'s GCG suffixes), low-resource languages, multi-turn drift. No prompt is jailbreak-proof. Defense: layered policy (prompt + classifier + output filter), continuous red-team eval set, log + alert on novel attempts. Treat jailbreaks like SQL injection: a permanent class of attacks.",
        takeaway: "Layered policy + red-team evals. No silver bullet.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Refusal taxonomy",
        body: "Tag each refusal with a code (R1: harm, R2: privacy, R3: legal, R4: scope). Lets you track which are over-firing. The non-refusal-but-flagged path is just as important.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Anthropic-news external", {
        type: "microread",
        title: "Responsible Scaling Policy",
        body: "Anthropic publishes its Responsible Scaling Policy: capability thresholds (ASL-2, ASL-3, ASL-4) where deploying a model triggers extra evals, restricted features, or paused rollouts. Frontier labs are converging on this 'preconditions for deployment' shape. As a builder, the takeaway: the most powerful models will increasingly come with documented evaluations of their dangerous capabilities — read the system cards before integrating.",
        takeaway: "Read the system card. Frontier models ship with capability evals.",
        source: { name: "Anthropic", url: "https://www.anthropic.com/news" },
        category: "company",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 5, "Guardrails in production", "Belt + suspenders.", 5, [
      spark("Layered defenses", {
        type: "microread",
        title: "Don't trust one layer",
        body: "Production safety is layered: input filters (PII, prompt injection patterns), system prompt rules, model-level training (refusals), output filters (toxicity, jailbreak detection), and human-in-the-loop for sensitive actions. Each layer fails sometimes. Together they ship. If you have only one safety layer, you have none.",
        takeaway: "Stack 3+ guardrails. Each is fallible alone.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Cheap classifier first",
        body: "Use a small, fast classifier (not a big LLM) to pre-screen for obvious abuse. 10x cheaper, catches 80% of bad input before you spend tokens. distilbert-base-uncased or unitary/toxic-bert work fine.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Email-agent scenario", {
        type: "scenario",
        setup: "Your AI agent can send emails. A user prompt asks it to email their ex 'with strong language'.",
        prompt: "Best layered defense?",
        options: [
          "Trust the model alone",
          "Output filter + require user confirm before send + rate limit",
          "Just block all emails",
          "Disable the model",
        ],
        answer: 1,
        explain: "Confirm + filter + limit = real defense.",
      }),
      spark("NeMo Guardrails", {
        type: "microread",
        title: "NVIDIA's open-source guardrail framework",
        body: "NeMo Guardrails (github.com/NVIDIA/NeMo-Guardrails) lets you write rules in Colang — a small DSL for input/output policies. 'If user asks for medical advice, route to safe response.' Pluggable into LangChain or as a stand-alone server. Production-grade: used by SK Telecom, Snowflake, others. Learning curve: a weekend.",
        takeaway: "NeMo Guardrails = open-source policy DSL for LLM apps.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Llama Guard", {
        type: "microread",
        title: "Meta's content classifier",
        body: "Llama Guard 3 (Meta, 2024) is a fine-tuned 8B model purpose-built for input/output classification across 13 risk categories: violence, sexual, weapons, etc. ~50ms on a GPU, free, MIT license. Drop-in alternative to OpenAI's moderation API or AWS Comprehend Toxicity. Pair with your prompt firewall — different layers, different signals.",
        takeaway: "Llama Guard = free, on-prem moderation. 50ms/call.",
        source: { name: "Hugging Face", url: "https://huggingface.co/blog" },
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pattern match: layers", {
        type: "patternmatch",
        prompt: "Match the safety layer to its job",
        pairs: [
          { left: "Input filter", right: "Block obvious abuse before tokens" },
          { left: "System prompt", right: "Set scope + tone + refusal style" },
          { left: "Output filter", right: "Catch what slipped past the model" },
          { left: "Human-in-the-loop", right: "Confirm irreversible actions" },
        ],
        explain: "Four layers, each with a known failure mode.",
      }),
      spark("Per-risk eval sets", {
        type: "microread",
        title: "Don't evaluate 'safety' generically",
        body: "Build small targeted eval sets per risk: prompt injection, PII leak, jailbreaks, biased outputs, off-policy advice, sycophancy. 30 cases per category beats 1000 generic. Run them on every prompt change. When a regression slips through, it's almost always a missing eval — add it. Same idea as TDD, applied to safety.",
        takeaway: "Per-risk eval sets. Add cases when bugs slip through.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Strongest moderation strategy for a public chatbot?",
        options: [
          "Trust the model",
          "Input classifier + system prompt + output classifier + tool gating",
          "A really long system prompt",
          "Block all questions",
        ],
        answer: 1,
        explain: "Layered. No single point of moderation.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Shadow-mode new policies",
        body: "When you tighten a guardrail, run the new version in shadow first: log what would have been blocked, but ship the old behavior. Two weeks of data tells you if you're about to break a real workflow.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Hallucination guard", {
        type: "microread",
        title: "Cite-or-refuse pattern",
        body: "For RAG over canonical data (legal, medical, finance), force the model to quote-verbatim from a chunk or refuse. 'If you can't find an answer in the provided documents, say I don't know.' Reduces confident hallucinations dramatically. Verify with regex: every claim must overlap a source span >= some threshold.",
        takeaway: "Quote-or-refuse. Auto-verify overlap.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 6, "Privacy & PII", "Don't leak the user.", 4, [
      spark("Don't train on customers", {
        type: "microread",
        title: "PII boundaries",
        body: "Default rule: never log raw user data with PII. Redact before logging. Never send prod data to a model training pipeline without explicit consent. Use providers that contractually exclude your data from training (Anthropic, OpenAI Enterprise both do). For high-risk domains (health, finance, legal), check if you need on-prem or VPC inference.",
        takeaway: "PII in = explicit policy out. Never default-leak.",
        visual: "lock",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Presidio scrub before logging",
        body: "Run Microsoft Presidio (or similar) on user input before logging. One Python line, prevents 99% of compliance headaches later. Also wraps spaCy under the hood — you can extend recognizers for domain-specific PII.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("GDPR Art. 17", {
        type: "microread",
        title: "Right to erasure for AI",
        body: "Article 17 (right to be forgotten) applies to AI systems. If you store user-derived data in a vector DB, you must be able to delete it on request. Mitigations: tag every embedding with user_id; on delete, drop all rows where user_id = X; retrain or refresh any caches. Bonus: don't fine-tune on user PII without an exit plan — you can't 'unlearn' from weights cheaply.",
        takeaway: "Tag embeddings by user_id. Delete on request.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Differential privacy", {
        type: "microread",
        title: "Noise-budgeted aggregates",
        body: "Differential privacy adds calibrated noise to query results so individual records can't be reconstructed. Useful when you want to publish aggregates ('how many users asked about X') without leaking who asked. Apple, Google, and the US Census use it. Libraries: Google's diff-priv, OpenDP. Overkill for small apps; essential for public data releases.",
        takeaway: "DP = aggregates without leaking individuals.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match: data minimization", {
        type: "patternmatch",
        prompt: "Match the technique to its purpose",
        pairs: [
          { left: "Hash before storage", right: "Pseudonymize identifiers" },
          { left: "Tokenize PII", right: "Reversible, vault-keyed mapping" },
          { left: "Differential privacy", right: "Aggregates without individual leakage" },
          { left: "K-anonymity", right: "Group records by quasi-identifiers" },
        ],
        explain: "Each is a different privacy primitive.",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "User says 'my SSN is 123-45-6789' to your AI. Default behavior?",
        options: ["Echo it back", "Redact in storage and refuse to repeat", "Email it to support", "Fine-tune on it"],
        answer: 1,
        explain: "Detect, redact, refuse-to-echo. Three reflexes.",
      }),
      spark("Inference vs training", {
        type: "microread",
        title: "Two PII boundaries, two policies",
        body: "Inference PII: what flows in/out during a request. Training PII: what becomes part of the model. Inference can be controlled per-call. Training is forever — once a model has seen PII, getting it out is hard. Default: never include user PII in fine-tunes. If you must, use synthetic placeholders + post-hoc privacy audits.",
        takeaway: "Training >> inference for PII risk. Default exclude.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Synthesize, don't anonymize",
        body: "Anonymized real data still leaks via correlations. Synthetic data (Gretel.ai, Mostly AI, Synthesized.io) generates realistic records with no 1:1 link to real users. Better for QA, dev, and even some training scenarios.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("On-prem and VPC", {
        type: "microread",
        title: "When you can't send data out",
        body: "Health/finance/government often forbids sending raw data to cloud APIs. Options: AWS Bedrock + Claude in your VPC, Azure OpenAI in private endpoint, GCP Vertex AI with VPC-SC, on-prem (Llama 3, Mistral, Qwen) with vLLM or TGI. Performance gap to frontier is shrinking; for many tasks, an open model in your VPC is faster + cheaper + compliant.",
        takeaway: "Bedrock/Azure/Vertex VPC, or self-host Llama. Often required.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Embeddings leak too", {
        type: "microread",
        title: "Vectors aren't anonymous",
        body: "Embedding inversion attacks (Song et al., 2023) can reconstruct the original text from a vector with surprising fidelity. So a vector DB full of customer emails is still customer email data, GDPR-wise. Treat embeddings the same as the underlying text: encrypt at rest, ACL by tenant, redact PII before embedding.",
        takeaway: "Embeddings = the underlying text. Same controls.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 7, "Evaluating safety", "Specific tests for specific risks.", 4, [
      spark("Eval each risk", {
        type: "microread",
        title: "One eval per risk class",
        body: "Don't evaluate 'safety' generically. Build small targeted eval sets per risk: prompt injection, PII leak, jailbreaks, biased outputs, off-policy advice. 30 cases per category beats 1000 generic. Run them on every prompt change. When a regression slips through, it's almost always a missing eval — add it.",
        takeaway: "Per-risk eval sets. Add cases when bugs slip through.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("LLM-as-judge", {
        type: "microread",
        title: "Models grading models",
        body: "Use a stronger model (Claude Opus, GPT-4) to grade your prod model's output against a rubric. Cheap, fast, scales to thousands of cases. Calibrate against human labels first — judge models can be biased toward verbose answers, similar styles, or their own outputs. promptfoo, ragas, and DeepEval all package the pattern.",
        takeaway: "LLM-as-judge for scale. Calibrate vs humans first.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Pattern match: eval shapes", {
        type: "patternmatch",
        prompt: "Match the question to the eval shape",
        pairs: [
          { left: "Does retrieval recall the right chunk?", right: "Hit rate at K" },
          { left: "Does the answer match the chunk?", right: "Faithfulness / groundedness score" },
          { left: "Does it refuse misuse?", right: "Jailbreak red-team set" },
          { left: "Is it consistent across runs?", right: "Variance across N samples" },
        ],
        explain: "Different questions, different metrics.",
      }),
      spark("Promptfoo", {
        type: "microread",
        title: "Open-source eval CLI",
        body: "promptfoo (npm install -g promptfoo) runs prompts against any provider, asserts outputs with custom assertions (regex, semantic similarity, LLM judge), produces an HTML report. Wire it into CI; fail builds on regressions. Shapes the eval discipline most teams skip. Same niche: ragas (RAG-focused), DeepEval, Inspect (UK AISI).",
        takeaway: "promptfoo in CI. Fail on safety regressions.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("AILuminate / SaladBench", {
        type: "microread",
        title: "Public safety benchmarks",
        body: "MLCommons AILuminate, AnthropicEval, HarmBench, SaladBench: public datasets with adversarial prompts spanning many risk categories. Run them once on your model + system prompt; you'll discover gaps in 30 minutes. Don't ship to public users without at least one. Hugging Face hosts most: huggingface.co/datasets/walledai/SaladBench.",
        takeaway: "Run a public safety benchmark before public launch.",
        source: { name: "Hugging Face", url: "https://huggingface.co/blog" },
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Best signal that your safety layer is working?",
        options: [
          "Vibes",
          "Per-risk eval sets that pass on every PR",
          "User says it's fine",
          "Long system prompt",
        ],
        answer: 1,
        explain: "Tests in CI. Same discipline as code.",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Add the failure",
        body: "Every time a real user breaks your AI in a new way, add that prompt to your eval set verbatim. Your eval grows from real evidence, not imagination.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Holistic eval", {
        type: "microread",
        title: "Stanford HELM, Inspect (UK AISI)",
        body: "Stanford HELM scores models across 42 scenarios + 7 metrics (accuracy, calibration, robustness, fairness, bias, toxicity, efficiency). UK AI Safety Institute's Inspect framework is open source: write evals as Python files; run on any provider. Use them to choose models, not just to ship — they expose weaknesses your custom evals miss.",
        takeaway: "HELM + Inspect = model selection signal.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Red team your own app", {
        type: "microread",
        title: "Hire a stranger to break it",
        body: "Your team can't break your own product the way an outsider can. Pay a freelancer (HackerOne, Bugcrowd, even Upwork) for a 4-hour red-team session against your AI. They'll find prompts you never imagined. The fee is tiny vs the cost of a public jailbreak going viral.",
        takeaway: "Pay a stranger to break it. Cheap insurance.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 8, "Long-context vs RAG", "When to use which.", 4, [
      spark("Tradeoffs", {
        type: "microread",
        title: "Stuff it vs search it",
        body: "Modern context windows fit huge docs (200k+ tokens). Tempting to just stuff everything in. But: it's expensive, slower, and 'lost in the middle' is real (models miss facts buried mid-context). RAG keeps prompts small and lets you scale to millions of docs, but requires good retrieval. Rule: if your corpus fits and you'll re-use it, cache + stuff it. If it grows or you query small slices, RAG.",
        takeaway: "Long context for stable, small corpora. RAG for scale.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "10 GB legal corpus, hundreds of users, varying queries. Best fit?",
        options: ["Stuff it all into context", "RAG over the corpus", "Train a custom model", "Email it"],
        answer: 1,
        explain: "Way too big for context, but perfect for RAG.",
      }),
      spark("Cost math", {
        type: "microread",
        title: "Per-call vs per-query",
        body: "Long context: every call pays for the full prompt. 100k tokens at Claude Sonnet's $3/M input is $0.30 per call. With prompt caching, repeats drop to $0.03. RAG: each call pays for ~5k tokens ($0.015). RAG wins on volume; long context wins when you query the same corpus enough times to amortize the cache. Compute the breakeven before you choose.",
        takeaway: "Math the cost. Caching changes the answer.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Latency math", {
        type: "microread",
        title: "Time-to-first-token",
        body: "Long context loads slowly: 200k tokens at Claude is ~5-10 seconds before the first output token. RAG is sub-second. For interactive UX (chat), RAG wins on perceived latency. For deep analysis (legal review, code review), long context can be acceptable because the user expects to wait. Measure both before committing.",
        takeaway: "Long context = slow TTFT. RAG = fast.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Hybrid: RAG + long context", {
        type: "microread",
        title: "Use both",
        body: "Most production systems mix: a long-context call for a deep, infrequent task (annual compliance review of 50 PDFs); a RAG call for the user-facing chatbot. The architecture decision is per-task, not per-product. Long context = slow, expensive, simple. RAG = fast, cheap, complex. Pick per workflow.",
        takeaway: "Per-task choice. Not one-size-fits-all.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("NIAH evals", {
        type: "tip",
        title: "Needle-in-a-haystack tests",
        body: "Before relying on long context, run a needle-in-a-haystack eval: insert a known fact at random positions in a long document, ask the model to retrieve it. Public scripts: gkamradt/LLMTest_NeedleInAHaystack. Tells you the effective context length on your data.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pattern match: pick a stack", {
        type: "patternmatch",
        prompt: "Match the workload to the right approach",
        pairs: [
          { left: "User chat over a small wiki", right: "RAG, fast TTFT" },
          { left: "One-time analysis of one large doc", right: "Long context" },
          { left: "Customer support over millions of tickets", right: "RAG (must scale)" },
          { left: "Code review across a repo", right: "Long context with caching" },
        ],
        explain: "Match the latency + cost + scale needs to the architecture.",
      }),
      spark("Cache-augmented", {
        type: "microread",
        title: "CAG: cache-augmented generation",
        body: "Cache-Augmented Generation (CAG) pre-loads the entire corpus into the KV cache once, then queries hit the cached tokens at near-zero cost. Works only when corpus fits in the model's window (so <200k tokens) and is stable. For docs that fit, CAG can outperform RAG on relevance because nothing's retrieved away. Anthropic's prompt caching makes this trivial.",
        takeaway: "Stable corpus < 200k tokens? Try CAG before RAG.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Bench both",
        body: "When in doubt, build both for one workflow and run a 50-query eval set. Cost, latency, accuracy. The right answer is rarely the one you'd guess.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 9, "Agent safety", "Power tools, careful hands.", 5, [
      spark("Blast radius mindset", {
        type: "microread",
        title: "Agents = blast radius",
        body: "An agent that can browse, code, and email has real-world reach. Treat tool permissions like Unix file modes: least privilege, scoped to the task, revoked when done. Sandboxes for code execution. Allow-lists for outbound network. Confirmations for any irreversible action (send, delete, pay, deploy). The bigger the action, the slower and more visible it should be.",
        takeaway: "Slow + visible = safe. Fast + silent = scary.",
        visual: "shield",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Add an undo trail",
        body: "Add an 'undo trail' to every agent action. Even fake undo (just a log) saves you when something goes sideways at 2am. Real undo (DB transactions, soft-delete) is gold.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("MCP and tool scope", {
        type: "microread",
        title: "Model Context Protocol — scope per server",
        body: "Anthropic's MCP (Model Context Protocol) lets agents talk to external tool servers. Scope each server narrowly: a 'filesystem' server with read-only on a specific dir, a 'github' server tied to one repo. Don't run one giant 'do-everything' MCP server — you reintroduce excessive agency. Tools should be small, named, and bounded.",
        takeaway: "MCP servers: narrow, named, bounded.",
        source: { name: "Anthropic", url: "https://www.anthropic.com/news" },
        category: "pattern",
        addedAt: "2026-05-01",
      }),
      spark("Sandbox code execution", {
        type: "microread",
        title: "Never exec on your host",
        body: "If your agent runs Python or shell, run it in a sandbox: gVisor, Firecracker microVMs (used by E2B, Modal, Daytona), Docker with seccomp. No host filesystem access, no host network, time-bounded, memory-capped. e2b.dev and modal.com are drop-in. Letting an LLM exec on your host because 'it's just a sandbox prompt' is how you brick prod.",
        takeaway: "Sandbox or don't. Firecracker, gVisor, E2B.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Pattern match: gates", {
        type: "patternmatch",
        prompt: "Match the action to the right gate",
        pairs: [
          { left: "Read public web page", right: "Allow + log" },
          { left: "Read private DB", right: "Tenant-scoped query + audit" },
          { left: "Send email to external", right: "Human confirm + rate limit" },
          { left: "Pay invoice", right: "Multi-party approve + cap" },
        ],
        explain: "Reversibility + audience + value -> gate strength.",
      }),
      spark("Loop detection", {
        type: "microread",
        title: "Agents loop. Cap them.",
        body: "Without a budget, agents will retry forever, burn tokens, and rack up bills. Cap: max steps per task (10-50), max wall-clock time (30s-5min), max tool calls per step (3-5). When the cap fires, return partial results + a clear error. Both safer and cheaper than 'just one more retry'.",
        takeaway: "Step + time + tool budgets. No exceptions.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Quick check", {
        type: "quickpick",
        prompt: "Right gate for an agent that can wire money?",
        options: [
          "Auto-approve under $1k",
          "Always require human confirm + dual-control above a cap",
          "Trust the system prompt",
          "No gate; speed matters",
        ],
        answer: 1,
        explain: "Money = irreversible. Confirm + cap + dual control.",
      }),
      spark("Browser sandbox", {
        type: "microread",
        title: "Don't share a browser session",
        body: "Browser-using agents (Claude Computer Use, Browserbase, Anthropic's Agent SDK) need their own profile and their own cookie jar. Reusing your logged-in browser shares all your sessions with the agent — and any prompt-injected page can hijack them. Use isolated profiles per task; destroy them after.",
        takeaway: "One profile per task. Destroy after.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "Dry-run mode",
        body: "Add a dry-run flag to every tool. The agent generates the call but doesn't execute. Watch in dev for a week before going hot. Catches the worst foot-guns cheaply.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("Capability tokens", {
        type: "microread",
        title: "Tokens, not roles",
        body: "Capability-based security (Mark S. Miller's framing): each tool call carries a capability token granting just enough permission. Tokens are unforgeable, scoped, expire. Beats role-based: roles drift; tokens are explicit per call. CaMeL, Anthropic's tool-use schema, MCP, and most agent frameworks are converging here.",
        takeaway: "Capabilities > roles. Per-call, scoped, expiring.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 10, "Boss: safety review", "Audit yourself.", 6, [
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: Memory & Safety",
        questions: [
          {
            type: "quickpick",
            prompt: "Long-term memory in a chatbot is best stored…",
            options: ["In context every call", "In a vector DB / structured store", "In the user's cookie", "Nowhere"],
            answer: 1,
            explain: "Persistent store, retrieved as needed.",
          },
          {
            type: "quickpick",
            prompt: "An agent that can pay invoices should…",
            options: ["Auto-pay everything", "Require human confirm above $X and log all attempts", "Disable logging", "Trust prompts"],
            answer: 1,
            explain: "Confirm + log for irreversible actions.",
          },
          {
            type: "quickpick",
            prompt: "Best evaluation strategy for safety?",
            options: ["One big generic safety test", "Targeted eval set per risk class, run on every change", "Skip — trust the model", "Manual spot checks"],
            answer: 1,
            explain: "Per-risk, automated, every change.",
          },
          {
            type: "quickpick",
            prompt: "10GB corpus, many users, varied queries. Pick the architecture.",
            options: ["Stuff it all in context", "RAG over the corpus", "Train a model from scratch", "Just one prompt"],
            answer: 1,
            explain: "RAG scales; long context doesn't.",
          },
          {
            type: "quickpick",
            prompt: "User says 'remember my SSN'. Default behavior?",
            options: ["Store verbatim", "Detect with Presidio, redact, refuse to store", "Email it home", "Fine-tune on it"],
            answer: 1,
            explain: "Detect, redact, refuse.",
          },
        ],
      }),
    ]),
  ],
};
