import type { Topic } from "../../types";
import { level, spark } from "../helpers";

const T = "open-source" as const;

export const openSource: Topic = {
  id: T,
  name: "Open Source AI",
  emoji: "🌐",
  tagline: "The trendy projects you should know — and use.",
  color: "#28e0b3",
  visual: "open",
  levels: [
    level(T, 1, "Why open source matters", "Power, learning, leverage.", 6, [
      spark("Three reasons", {
        type: "microread",
        title: "Why builders care about OSS",
        body: "(1) You can read the code — best way to learn how real systems work. (2) You're not locked in — own the stack, fork if needed. (3) Standards emerge from OSS (LangChain, Llama, transformers). Even if you ship on closed APIs, your stack is full of OSS — be respectful, contribute back, and use it as a learning ground.",
        takeaway: "OSS = teacher, leverage, insurance.",
        category: "principle",
        addedAt: "2025-10-01",
        bodyByAgeBand: {
          teen: "Open source is a project where the code is public. Anyone can read it, copy it, run it, change it. In AI, the biggest jump in the last few years is open-weights models (Llama, Mistral, Qwen) — you can download the brain itself. That changes who gets to build.",
          kid: "Open source means anyone can read the recipe. With AI, that's huge — even normal people can download and run the same model big companies use.",
        },
      }),
      spark("What 'open' actually means", {
        type: "microread",
        title: "Code, weights, data — three different opens",
        body: "Open-source software (OSS): code is public + permissive license. Open-weights model: the trained weights are public, often under a slightly restrictive license — code to use them is OSS. Open-data model: rare. The training dataset is public too. Most 'open' AI today is open-weights, not open-data. Knowing the difference saves you from license surprises.",
        takeaway: "Open code, open weights, and open data are three different things.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Permissive vs copyleft", {
        type: "tip",
        title: "💡 License taxonomy in 30 seconds",
        body: "MIT / Apache 2.0 — permissive, do almost anything. GPL — copyleft, derivatives must also be GPL. AGPL — same but for network use. Llama / Gemma — custom licenses with usage carve-outs. For AI, you'll mostly hit Apache 2.0 + custom 'almost-Apache' licenses. Read once before relying on it.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Open-weight giants today", {
        type: "patternmatch",
        prompt: "Match the open-weights model family to the lab that releases it.",
        pairs: [
          { left: "Llama", right: "Meta" },
          { left: "Mistral / Mixtral", right: "Mistral AI" },
          { left: "Qwen", right: "Alibaba" },
          { left: "DeepSeek-V / R", right: "DeepSeek" },
          { left: "Gemma", right: "Google DeepMind" },
        ],
        explain: "These five families cover most of the high-quality open-weights frontier in 2026.",
      }),
      spark("Why labs open-source at all", {
        type: "quickpick",
        prompt: "What's the most accurate framing of why frontier labs release open-weight models?",
        options: [
          "They feel guilty about being closed",
          "Standards leverage + ecosystem leverage + recruiting + price-floor pressure on rivals",
          "They're not the real frontier model",
          "Government regulation forces it",
        ],
        answer: 1,
        explain: "Open weights compound four kinds of leverage at once. It's strategy, not charity.",
      }),
      spark("Hugging Face is the hub", {
        type: "microread",
        title: "Why HF anchors the field",
        body: "Hugging Face hosts most of the open-weights ecosystem: models, datasets, and Spaces (hosted demos). It's where Meta drops Llama, where Alibaba drops Qwen, where the eval leaderboards live, and where most of the community fine-tunes appear. If you build with open AI, you'll touch HF every week.",
        takeaway: "Hugging Face is the GitHub of AI — central to the whole open ecosystem.",
        category: "tooling",
        addedAt: "2026-05-01",
        source: {
          name: "Hugging Face",
          url: "https://huggingface.co/blog",
        },
      }),
      spark("OSS ≠ free of effort", {
        type: "scenario",
        setup: "A founder says: 'We'll just use open-source models for everything — it'll be free!'",
        prompt: "What's the most honest pushback?",
        options: [
          "Agree — open is always cheapest",
          "Open weights are free; ops, hardware, eval, on-call are not. Often more expensive than a paid API at small scale.",
          "Disagree — open isn't real",
          "Recommend SaaS only",
        ],
        answer: 1,
        explain: "The right framing: open eliminates licensing, not effort. Hosting + eval + on-call are real cost lines.",
      }),
      spark("OSS is a learning lab", {
        type: "tip",
        title: "💡 Read one OSS repo a week",
        body: "Pick one repo from the open AI stack (vLLM, llama.cpp, LangChain, DSPy). Read its README + one source file. Twenty minutes a week. After three months you'll understand the stack better than 90% of builders.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("OSS contribution etiquette", {
        type: "microread",
        title: "How to PR without getting yelled at",
        body: "Open issue first, link to the bug or feature. Read CONTRIBUTING.md. Keep PRs small. Add a test. Say what you tried before deciding it was a bug. Be patient with the maintainer — most OSS is free labor done at night. Match the project's style; don't reformat unrelated files.",
        takeaway: "Small, tested, kind, and matched-to-style PRs get merged.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 2, "Hugging Face ecosystem", "The GitHub of AI.", 6, [
      spark("HF in one breath", {
        type: "microread",
        title: "Why Hugging Face matters",
        body: "Hugging Face hosts hundreds of thousands of open models, datasets, and spaces. The transformers library standardized how Python loads models. Datasets library standardized how you stream big training data. If you build with open models, your week revolves around HF Hub. Free for most use, paid for inference endpoints.",
        takeaway: "HF Hub is the open AI center of gravity.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Hugging Face",
          url: "https://huggingface.co/blog",
        },
        bodyByAgeBand: {
          teen: "Hugging Face is like GitHub but for AI — a website where anyone can upload a trained model, a dataset, or a tiny demo, and anyone else can download it and run it. If you've ever installed a model in four lines of Python, that worked because of the transformers library, which Hugging Face made.",
        },
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Run any open model in 4 lines: `from transformers import pipeline; p = pipeline('text-generation', 'meta-llama/Meta-Llama-3-8B-Instruct'); print(p('Hi'))`. Test 5 models in an afternoon.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("HF surfaces map", {
        type: "patternmatch",
        prompt: "Match each Hugging Face surface to its job.",
        pairs: [
          { left: "Models", right: "Find / download model weights" },
          { left: "Datasets", right: "Stream + version-control training data" },
          { left: "Spaces", right: "Free hosted demo for any model" },
          { left: "Inference Endpoints", right: "Production hosting (paid)" },
          { left: "Leaderboards", right: "Compare models on standard evals" },
        ],
        explain: "The HF surfaces stack: weights, data, demo, prod, scoreboards.",
      }),
      spark("AutoTrain + LoRA", {
        type: "microread",
        title: "Fine-tune without a PhD",
        body: "HF AutoTrain and PEFT (Parameter-Efficient Fine-Tuning, mostly LoRA) made fine-tuning approachable. You don't retrain the whole model — you train a small adapter on top. Llama 3 8B + a 50-row dataset + a 30-min LoRA on a Colab GPU is enough to specialize behavior. The barrier to fine-tuning fell massively in 2024–2025.",
        takeaway: "LoRA + AutoTrain make fine-tuning a weekend task, not a moonshot.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Datasets as first-class data", {
        type: "microread",
        title: "Why HF Datasets is underrated",
        body: "Datasets gives you streaming, lazy-loading, versioning, and standard splits over multi-TB corpora. You can load 'wikipedia' in one line and start training. For RAG builders: search HF Datasets before scraping — half the public corpora you want already exist there with proper attribution.",
        takeaway: "Search HF Datasets before scraping anything.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Spaces is free demo hosting", {
        type: "tip",
        title: "💡 Ship a demo on Spaces",
        body: "Hugging Face Spaces gives you free CPU + small GPU demo hosting via Gradio or Streamlit. Push a repo, get a public URL. Best zero-friction way to share a working AI demo with non-technical stakeholders.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Open LLM leaderboard", {
        type: "microread",
        title: "How to read the leaderboards",
        body: "HF's Open LLM Leaderboard ranks open models on MMLU, GSM8K, HellaSwag, ARC, TruthfulQA, Winogrande. Caveats: easy to overfit a benchmark; small differences are noise; new models routinely cycle in. Use the leaderboard to filter your shortlist, not pick the winner.",
        takeaway: "Leaderboards filter shortlists. Your evals pick winners.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Trending tab", {
        type: "tip",
        title: "💡 Browse HF Trending weekly",
        body: "huggingface.co/models?sort=trending shows what the community has downloaded most this week. 5 minutes a week, you'll spot the model wave before it hits the discourse.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Hugging Face",
          url: "https://huggingface.co/blog",
        },
      }),
      spark("Pick the right HF size", {
        type: "scenario",
        setup: "You need an open model for entity-extraction in a Python pipeline. Latency budget: 200ms. Hosting budget: a single $0.50/hr GPU.",
        prompt: "Best starting model size?",
        options: [
          "70B+ flagship",
          "1B–3B fine-tuned for extraction (Llama 3.2 1B, Phi 3.5 mini)",
          "Cloud frontier API with 50ms",
          "GPT-4 via OpenAI",
        ],
        answer: 1,
        explain: "Small fine-tuned models smoke giant ones at narrow extraction tasks at a fraction of cost.",
      }),
      spark("HF blog tracks the field", {
        type: "tip",
        title: "💡 Subscribe to HF blog",
        body: "huggingface.co/blog covers new models, fine-tuning recipes, and tooling launches with a strong technical-detail bias. Anchor read for anyone building on open AI.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Hugging Face",
          url: "https://huggingface.co/blog",
        },
      }),
    ]),
    level(T, 3, "LangChain, LlamaIndex, DSPy", "Frameworks.", 6, [
      spark("Three styles", {
        type: "microread",
        title: "Pick your framework",
        body: "LangChain: huge, batteries-included, sometimes overengineered — great for speed. LlamaIndex: RAG-first, cleaner abstractions for retrieval. DSPy: programmable prompts, compiles for you, research-led, steeper learning curve. Many builders go bare metal (raw API + small custom code) — frameworks help quick start, can hurt long-term.",
        takeaway: "Try a framework. Drop to bare metal when it gets in the way.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("LangChain in one paragraph", {
        type: "microread",
        title: "What LangChain actually is",
        body: "LangChain is a Python (and JS) framework that wraps every model + every tool + every vector store + every retriever behind unified interfaces. Strengths: huge community, fastest path from 'idea' to 'demo', LangGraph for stateful agent workflows, LangSmith for tracing. Weakness: abstraction tax — sometimes the wrapper is harder than the underlying API.",
        takeaway: "LangChain = breadth. Best for fast prototypes, scrutinize for prod.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("LlamaIndex sweet spot", {
        type: "microread",
        title: "When LlamaIndex wins",
        body: "LlamaIndex is RAG-first: ingest docs, build an index, query with the right retrieval algorithm + reranker + post-processing. If your product is 'chat with your data,' LlamaIndex's abstractions are cleaner than LangChain's. If your product is 'agents that take actions,' LangChain or bare-metal usually fits better.",
        takeaway: "RAG-heavy → LlamaIndex. Agent-heavy → LangChain or bare metal.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("DSPy: prompts as code", {
        type: "microread",
        title: "Why DSPy is different",
        body: "Most frameworks treat prompts as strings. DSPy treats them as compilable programs — you specify what you want, DSPy uses an optimizer to figure out the best prompt against your eval set. Steeper learning curve, but produces more robust pipelines once you commit. Stanford-led research project with growing production use.",
        takeaway: "DSPy compiles prompts against an eval. Robust, steep learning curve.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("LangGraph", {
        type: "microread",
        title: "Stateful agent graphs",
        body: "LangGraph is the LangChain team's bet on stateful agent workflows — a graph DSL for cycles, branches, human-in-the-loop, and durable state. It's effectively replacing the older LangChain Agents class for serious agent builds. Worth learning if you're shipping multi-step LLM workflows.",
        takeaway: "LangGraph > old LangChain Agents for stateful, multi-step workflows.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("When to drop the framework", {
        type: "tip",
        title: "💡 Dropping frameworks isn't failure",
        body: "If you spend more time fighting the framework's abstractions than writing logic, drop it. Most frontier-shipping teams use a thin wrapper around the lab's SDK + a vector store + a tracing tool. Frameworks help shape #1; they often slow shape #5.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Framework match-up", {
        type: "patternmatch",
        prompt: "Match each framework to its sweet spot.",
        pairs: [
          { left: "LangChain + LangGraph", right: "Multi-step agent workflows + breadth of integrations" },
          { left: "LlamaIndex", right: "RAG-anchored Q&A products" },
          { left: "DSPy", right: "Eval-driven, prompt-compiled pipelines" },
          { left: "Vercel AI SDK", right: "Streaming AI features inside Next.js apps" },
        ],
        explain: "Framework choice = match the abstraction to the dominant workload.",
      }),
      spark("Vercel AI SDK", {
        type: "microread",
        title: "The TypeScript option",
        body: "If you're shipping AI inside a Next.js / TypeScript app, the Vercel AI SDK is purpose-built. Streaming, tool calling, generative UI helpers, model-provider abstraction. Smaller than LangChain, but specifically tuned for the modern web app shape.",
        takeaway: "TS + Next.js? Vercel AI SDK before LangChain.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Picking from scratch", {
        type: "scenario",
        setup: "You're starting a new RAG product on Python this week. You have one engineer and a 4-week deadline.",
        prompt: "Most pragmatic stack?",
        options: [
          "DSPy + custom optimizer",
          "LlamaIndex + Qdrant + a tracing tool, drop to bare metal where needed",
          "Roll your own framework",
          "Wait for next-gen frameworks",
        ],
        answer: 1,
        explain: "LlamaIndex covers RAG well; Qdrant is a fast open vector store; tracing keeps you sane. Drop to bare metal at the seams.",
      }),
      spark("Tip: instrument from day one", {
        type: "tip",
        title: "💡 Trace before you optimize",
        body: "Hook LangSmith, Langfuse, or OpenLLMetry on day one of any framework build. You can't tune what you can't see. Most framework regret comes from skipping tracing then trying to debug a 12-step chain.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 4, "Vector DBs", "pgvector, Chroma, Qdrant, Weaviate.", 6, [
      spark("Picking a vector store", {
        type: "microread",
        title: "Vector DB landscape",
        body: "pgvector — Postgres extension, perfect for adding vectors to existing apps. Chroma — local, dev-friendly, great for prototyping. Qdrant + Weaviate + Milvus — purpose-built, scale to billions. Pinecone (closed) — managed for serious scale. Start small with pgvector or Chroma, migrate when you cross 10M+ vectors.",
        takeaway: "Start tiny (pgvector). Migrate when scale forces.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("pgvector first", {
        type: "microread",
        title: "Why pgvector wins by default",
        body: "If you already run Postgres, pgvector adds vectors with one extension and zero ops change. Backups, replication, ACL, transactions — all reuse what you already have. For under 10M vectors and dimension ≤ 1536, pgvector is good enough for production. The 'just use Postgres' rule applies to vector search too.",
        takeaway: "Already on Postgres? pgvector. Don't migrate until pain forces it.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Chroma for laptops", {
        type: "microread",
        title: "Local-first vector store",
        body: "Chroma runs in-process or as a tiny server. Zero setup, ergonomic Python API, fine for under 1M vectors. Perfect for prototypes, demos, RAG-on-your-Obsidian, internal tools. Once you outgrow it, you migrate, not re-architect.",
        takeaway: "Chroma is the laptop / prototype default.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Qdrant + Weaviate vs Milvus", {
        type: "microread",
        title: "Three open-source heavyweights",
        body: "Qdrant — Rust, fast, easy single-node + managed cloud. Weaviate — Go, hybrid search built in (vectors + BM25 + filters), strong graph features. Milvus — distributed-first, scales to billions, more operational complexity. Pick Qdrant for speed-of-DX; Weaviate for hybrid search; Milvus for billion-vector scale.",
        takeaway: "Qdrant fast, Weaviate hybrid, Milvus billions.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Hybrid search > vector-only", {
        type: "microread",
        title: "Why dense + sparse beats either alone",
        body: "Pure vector search misses exact-match terms (product names, error codes). Pure keyword (BM25) misses semantic similarity. Hybrid search combines both with a reranker. Most production RAG that beats baselines uses dense + sparse + a reranker like Cohere Rerank or BGE-Reranker. Plain similarity is the floor, not the ceiling.",
        takeaway: "Hybrid = dense + sparse + rerank. Always > pure vector search.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Embedding choices", {
        type: "patternmatch",
        prompt: "Match each embedding option to its right job.",
        pairs: [
          { left: "OpenAI text-embedding-3-small", right: "Cheap closed default, broad coverage" },
          { left: "BGE / E5 (open weights)", right: "Self-hosted English-strong embeddings" },
          { left: "Cohere Embed v3", right: "Enterprise multilingual + reranker pair" },
          { left: "Voyage AI", right: "High-recall dense embeddings, code + finance domains" },
        ],
        explain: "Pick by language coverage, hosting need, and benchmark on your queries.",
      }),
      spark("Vector DB scale heuristic", {
        type: "tip",
        title: "💡 The migration trigger",
        body: "Migrate off pgvector / Chroma when you hit one of: 10M+ vectors, p99 latency > 100ms, or hybrid-search needs you can't write yourself in SQL. Until then, you're optimizing for vanity.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Build: pgvector RAG in 30 min", {
        type: "buildcard",
        title: "Build: pgvector RAG over your notes",
        pitch: "30 minutes, fully open stack. You'll grok vector search by doing it.",
        promptToCopy:
          "Walk me through standing up a Postgres + pgvector instance in Docker, embedding a folder of Markdown notes with the BGE-small open model via sentence-transformers, and writing a Python script that queries by similarity. Then add hybrid search using `tsvector` for keywords. Total under 100 lines.",
        successCriteria: "Working similarity search + hybrid keyword search over your own notes.",
      }),
      spark("Vector store quickpick", {
        type: "quickpick",
        prompt: "Smallest team building a 5-engineer SaaS — best vector store default?",
        options: ["Pinecone enterprise tier", "pgvector inside their existing Postgres", "Build their own", "Milvus cluster"],
        answer: 1,
        explain: "pgvector reuses existing infra and ops knowledge. Migrate later only if forced.",
      }),
      spark("Embedding tip", {
        type: "tip",
        title: "💡 Always re-embed on model swap",
        body: "Embeddings are model-specific. If you swap embedding models, re-embed everything. Mixing two embedding spaces silently breaks similarity. Track the embedding model name as a column on the vectors table.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 5, "vLLM, llama.cpp, Ollama", "Serving open models locally.", 6, [
      spark("Three serving stacks", {
        type: "microread",
        title: "Run models on your hardware",
        body: "Ollama — easiest, brew install, run any model in 1 command. Great for laptops + dev. llama.cpp — battle-tested C++ engine, runs on CPU, M1/M2 fast, no GPU required. vLLM — production-grade, super fast batching, GPU. Pick by: dev (Ollama) → local (llama.cpp) → prod (vLLM).",
        takeaway: "Ollama → llama.cpp → vLLM as you scale.",
        category: "tooling",
        addedAt: "2026-05-01",
        bodyByAgeBand: {
          teen: "Three free tools let you run AI models on your own computer. Ollama is the easiest — type one command and it just works. llama.cpp is the magic that makes models run on regular Macs. vLLM is what big companies use when they have real GPUs. Most people start with Ollama on a laptop.",
        },
      }),
      spark("Build it", {
        type: "buildcard",
        title: "Build: chat with a local model",
        pitch: "5 min on a laptop. Total privacy.",
        promptToCopy:
          "Help me install Ollama, pull `llama3.2:3b`, then write a tiny Python REPL using `requests` that streams responses from `http://localhost:11434/api/chat`. No external APIs.",
        successCriteria: "Working chat that runs entirely on your machine.",
      }),
      spark("vLLM in one paragraph", {
        type: "microread",
        title: "Why vLLM eats GPU vendors' lunch",
        body: "vLLM introduced PagedAttention — a memory layout that lets a single GPU serve many concurrent requests with KV-cache sharing. Result: 2-10x throughput vs naive serving on the same GPU. It's now the de-facto open serving stack for production LLM hosting. Most managed open-model APIs (Together, Fireworks, Anyscale) use vLLM under the hood.",
        takeaway: "vLLM = the open-source production serving standard.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("llama.cpp magic", {
        type: "microread",
        title: "Why a Mac runs Llama 70B",
        body: "Georgi Gerganov's llama.cpp shipped a quantized C++ inference engine that runs Llama-class models on CPU + Apple Silicon GPU + plain CUDA. The GGUF format it pioneered is now the standard for local model weights. If you've ever run an LLM on a MacBook, thank llama.cpp.",
        takeaway: "llama.cpp + GGUF = the reason local LLMs are mainstream.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Ollama for dev", {
        type: "tip",
        title: "💡 Default to Ollama for laptop dev",
        body: "ollama pull llama3.2 → ollama run llama3.2. That's it. OpenAI-compatible API on localhost:11434. Switch any of your code's `base_url` to it and you're testing locally with no API costs.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Serving match-up", {
        type: "patternmatch",
        prompt: "Match each serving stack to its right job.",
        pairs: [
          { left: "Ollama", right: "Laptop dev + offline experimentation" },
          { left: "llama.cpp", right: "CPU / Apple Silicon inference, embedded apps" },
          { left: "vLLM", right: "GPU production serving with high throughput" },
          { left: "TGI (Hugging Face)", right: "HF-stack production serving alternative to vLLM" },
        ],
        explain: "Pick by hardware + concurrency + DX. Mix as needed.",
      }),
      spark("Quantization tradeoff", {
        type: "microread",
        title: "Q4 vs Q6 vs Q8",
        body: "GGUF + GPTQ + AWQ all let you trade quality for size. Q8 — almost lossless, 50% size. Q4 — meaningful quality drop on small models, fine on 70B+. Q6 — sweet spot for most use cases. Below Q4 — only for emergency-sized hardware. Test on your eval set before picking.",
        takeaway: "Q6 is the everyday default. Q4 only for big models on tight hardware.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Groq + Cerebras: speed-only plays", {
        type: "microread",
        title: "Custom silicon for OSS",
        body: "Groq runs open-weight models on its LPU chip and gets eye-watering tokens/sec (often 500+ TPS on Llama-70B). Cerebras WSE-3 does the same with even bigger throughput on a wafer-scale chip. Both host open models specifically — you're not locked into a closed one. Use them when latency is the product.",
        takeaway: "Groq + Cerebras host open weights at extreme speed. Latency-first.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Local privacy scenario", {
        type: "scenario",
        setup: "A regulated-industry buyer requires that no customer prompt leaves their VPC, ever.",
        prompt: "Best stack to demo to them?",
        options: [
          "OpenAI with a no-train clause",
          "Llama 3 on vLLM, deployed in their VPC, behind their VPN",
          "Ollama on the founder's laptop",
          "Pinecone as a workaround",
        ],
        answer: 1,
        explain: "On-prem in-VPC inference is the only contract that cleanly meets 'data never leaves'. Llama + vLLM is the standard answer.",
      }),
      spark("Production serving tip", {
        type: "tip",
        title: "💡 Always benchmark TPS on your shape",
        body: "Inference TPS on a synthetic prompt ≠ TPS on your real prompts. Run vLLM / Groq / Cerebras with your actual prompt distribution before committing. Bench input length, output length, concurrency together.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 6, "OSS agent frameworks", "AutoGen, CrewAI, Swarm.", 6, [
      spark("Multi-agent kits", {
        type: "microread",
        title: "Open agent stacks",
        body: "AutoGen (Microsoft) — research-grade multi-agent. CrewAI — friendlier, role-based teams. Swarm (OpenAI) — minimalist handoff pattern. SmolAgents (HF) — tiny, code-first agents. Each tries to standardize 'agent talks to agent + tools'. Reality: most production agents are still hand-rolled, but reading these helps you understand patterns.",
        takeaway: "Read 1-2 frameworks. Roll your own when needed.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("AutoGen's research roots", {
        type: "microread",
        title: "Why AutoGen still matters",
        body: "AutoGen, Microsoft Research's multi-agent framework, normalized the 'orchestrator + specialist agents + group chat' pattern. Heavy on flexibility, lighter on opinionated defaults. Best when your agent topology is unusual or your team has time to invest in framework learning.",
        takeaway: "AutoGen = flexible, research-flavored. Worth reading even if you don't ship it.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("CrewAI for role-based teams", {
        type: "microread",
        title: "Friendlier agent kit",
        body: "CrewAI takes the 'team of agents with roles' metaphor and ships an opinionated framework around it: a researcher agent + a writer agent + an editor agent collaborate on a goal. Ergonomic Python API, fast onboarding. Used in lots of customer-facing automation demos. Watch for over-abstraction in deeper builds.",
        takeaway: "CrewAI = role-based teams, friendly DX, watch the abstraction layer.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Swarm: minimalism wins", {
        type: "microread",
        title: "Why OpenAI's Swarm is short",
        body: "OpenAI's Swarm (later renamed and relaunched as Agents SDK) is deliberately small: an agent is a function with tools and a handoff list. Agents pass control to each other. No graphs, no DAGs, no DSL. The minimalism is the design point — read the source in an hour, learn the pattern, then build your own.",
        takeaway: "Swarm/Agents SDK = pattern-as-library, not framework.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("SmolAgents from HF", {
        type: "microread",
        title: "Code-first tiny agents",
        body: "Hugging Face's smolagents lets agents emit Python code, which is then executed in a sandbox — code is the action language. The advantage: language models are great at writing code, less great at picking from a JSON tool list. Smolagents elevates code-as-action as a first-class pattern.",
        takeaway: "SmolAgents bets that code > tool-call as the action language.",
        category: "tooling",
        addedAt: "2026-05-01",
        source: {
          name: "Hugging Face",
          url: "https://huggingface.co/blog",
        },
      }),
      spark("browser-use", {
        type: "microread",
        title: "Open-source browser agents",
        body: "browser-use is an OSS Python library that lets a model drive a real browser via Playwright — it sees the page DOM, clicks, types, screenshots. Open alternative to OpenAI Operator + Anthropic Computer Use. Useful for building scraping + automation that needs to log in or click through SPAs.",
        takeaway: "browser-use = open browser-driving agent. Replaces brittle scraping.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Agent framework match-up", {
        type: "patternmatch",
        prompt: "Match each agent kit to its sweet spot.",
        pairs: [
          { left: "AutoGen", right: "Research, unusual topologies, custom flow" },
          { left: "CrewAI", right: "Role-based 'team of specialists' product demos" },
          { left: "OpenAI Agents SDK", right: "Minimal handoff pattern, OpenAI-anchored stack" },
          { left: "browser-use", right: "Browser-driving automation agents" },
        ],
        explain: "Match the agent kit's metaphor to the workflow you're building.",
      }),
      spark("When to roll your own", {
        type: "tip",
        title: "💡 Most prod agents are hand-rolled",
        body: "Almost every shipping LLM-agent product has a hand-rolled core: a state machine + tool registry + loop, with a tracing tool. Frameworks help shape #1; hand-rolled wins shape #5. Use frameworks to learn patterns, then re-implement with your own state shape.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Hand-roll scenario", {
        type: "scenario",
        setup: "Your team has shipped an MVP using CrewAI. You need to add per-tenant rate limits, custom retry, and tool gating. You spend a week fighting CrewAI's internals.",
        prompt: "Best move?",
        options: [
          "Fork CrewAI",
          "Replace with a 200-line state-machine + tool registry over the lab's SDK",
          "Switch to AutoGen",
          "Wait for CrewAI v2",
        ],
        answer: 1,
        explain: "When you fight a framework's internals more than you write logic, the framework is in the way. A small custom state-machine usually wins.",
      }),
      spark("Bench against your loop", {
        type: "tip",
        title: "💡 Always test agents on your real loop",
        body: "Frameworks demo on cherry-picked loops. Test on YOUR most common 5 loops. Measure: total tool calls, cost, p95 latency, and resolution rate. Most framework decisions reverse after a real-world run.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
    ]),
    level(T, 7, "Open evals + datasets", "What everyone benchmarks on.", 5, [
      spark("Eval suites", {
        type: "microread",
        title: "Famous benchmarks",
        body: "MMLU (broad knowledge), HumanEval (code), GSM8K (math), HellaSwag (commonsense), MT-Bench (chat), SWE-bench (real GitHub issues). When labs claim 'SOTA', they cite these. Pitfalls: overfitting to benchmarks. Use as one signal among many — your real evals matter more.",
        takeaway: "Know the names. Trust your own evals more.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("SWE-bench is the new bar", {
        type: "microread",
        title: "Why coding agents care about SWE-bench",
        body: "SWE-bench Verified curates real GitHub issues + their PR fixes from popular Python repos. An agent must read the codebase, identify the bug, write the fix, and pass the existing tests. It's one of the few benchmarks that resists overfitting because the tests are real. Anthropic, OpenAI, and Google all chase scores here.",
        takeaway: "SWE-bench Verified = the most informative coding-agent benchmark today.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Eval landmines", {
        type: "tip",
        title: "💡 Always check for contamination",
        body: "Benchmarks leak into training data. If a model trained after benchmark X was published reports a huge X score, suspect contamination. Use 'held-out' or 'verified' splits where possible. New benchmarks have a few months of clean reading before they leak.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Build a house eval", {
        type: "microread",
        title: "30 cases is enough",
        body: "Most production teams need 30 cases that cover their top failure modes. Add new cases as failures show up. Run on every model swap. The act of writing the eval forces clarity about what 'good' means — half the value is in the writing, not the running.",
        takeaway: "30-case house eval > public benchmarks. Write yours this week.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
      spark("Open eval frameworks", {
        type: "microread",
        title: "Tools that run evals for you",
        body: "lm-eval-harness (EleutherAI) — runs the standard battery against any model. Promptfoo — TS-friendly eval framework, great for product teams. DeepEval — pytest-style assertions for LLM outputs. Inspect (UK AI Safety Institute) — research-grade eval orchestration. Pick one and stop hand-rolling eval scripts.",
        takeaway: "Pick lm-eval-harness, Promptfoo, DeepEval, or Inspect. Stop hand-rolling.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Public datasets to know", {
        type: "patternmatch",
        prompt: "Match each public dataset to its job.",
        pairs: [
          { left: "Common Crawl", right: "Web-scale unfiltered text training corpus" },
          { left: "The Pile", right: "Curated diverse training corpus" },
          { left: "FineWeb (HF)", right: "Cleaned, deduped pretraining data" },
          { left: "OpenAssistant", right: "Open-licensed instruction-tuning data" },
        ],
        explain: "Knowing the canonical datasets helps you reason about what models actually learned from.",
      }),
      spark("Eval scenario", {
        type: "scenario",
        setup: "You're picking between Llama 3.1 70B and Mistral Large for a customer-support assistant.",
        prompt: "What's the most useful evaluation step?",
        options: [
          "Compare MMLU scores",
          "Run both against 30 real anonymized tickets + score on resolution + tone",
          "Pick the cheaper one",
          "Pick the one with more downloads",
        ],
        answer: 1,
        explain: "Generic benchmarks tell you almost nothing about your specific use case. House eval on real tickets is the only honest comparison.",
      }),
    ]),
    level(T, 8, "OSS observability", "Helicone, Langfuse, Phoenix.", 6, [
      spark("LLM observability OSS", {
        type: "microread",
        title: "See what your AI is doing",
        body: "Helicone, Langfuse, OpenLLMetry, Phoenix (Arize) — all open source, all instrument LLM calls so you can see latency, cost, prompts, responses, eval scores. Set up day one. Without it you're flying blind in prod. Many also offer hosted versions if you don't want to self-host.",
        takeaway: "Instrument from day one. OSS makes it free.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("OpenLLMetry: the standard", {
        type: "microread",
        title: "Why OpenLLMetry matters",
        body: "OpenLLMetry, by Traceloop, extends OpenTelemetry semantic conventions to LLM apps. Instead of vendor-locked tracing, you emit standard OTel traces — and any backend (Datadog, New Relic, Langfuse, Phoenix) reads them. Use it if you already run OTel.",
        takeaway: "OpenLLMetry = OpenTelemetry for LLM apps. Vendor-neutral.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Langfuse: dev-friendly", {
        type: "microread",
        title: "Langfuse strengths",
        body: "Langfuse is open-source, ergonomic, integrates cleanly with LangChain + LlamaIndex + DSPy + the OpenAI SDK. Strong UI for traces + scores + datasets. Self-hostable on Docker; managed cloud available. Default pick when you want a 'just works' OSS observability tool for your AI app.",
        takeaway: "Langfuse = the friendliest OSS observability for LLM apps.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Phoenix from Arize", {
        type: "microread",
        title: "Phoenix's eval-first angle",
        body: "Phoenix, by Arize, leans hardest on evaluation: dataset versioning, eval runs, score visualization. If your team already does ML observability with Arize, Phoenix is the LLM extension. Strong for regulated industries that need auditable eval runs.",
        takeaway: "Phoenix = eval-first OSS observability. Strong for regulated buyers.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Helicone: proxy mode", {
        type: "microread",
        title: "Why Helicone's proxy is clever",
        body: "Helicone slots in as an OpenAI-compatible proxy: change one base_url and you get cost + latency + prompt logs without touching SDK code. The fastest possible 'turn on observability' shape. Good for teams with no time to instrument from scratch.",
        takeaway: "Helicone proxy = fastest 'turn on observability' move.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Observability match-up", {
        type: "patternmatch",
        prompt: "Match each OSS observability tool to its differentiator.",
        pairs: [
          { left: "Langfuse", right: "Friendly UI, framework integrations, dev-first" },
          { left: "Phoenix (Arize)", right: "Eval-anchored, dataset-first, regulated buyers" },
          { left: "Helicone", right: "OpenAI-compatible proxy, near-zero integration cost" },
          { left: "OpenLLMetry", right: "OTel-native, vendor-neutral, slot into existing stack" },
        ],
        explain: "Pick by integration shape, not feature checklist.",
      }),
      spark("Tip: log the prompt + the response", {
        type: "tip",
        title: "💡 Always log both prompt and response",
        body: "It's tempting to log only metadata for cost reasons. Don't. The prompt + response pair is the only thing that lets you debug a regression. Encrypt + retention-trim if needed, but capture both.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Observability quickpick", {
        type: "quickpick",
        prompt: "When should you instrument LLM observability?",
        options: ["After your first incident", "Day one", "After hitting 10K users", "Never — it's overhead"],
        answer: 1,
        explain: "Day one. The cheapest thing you'll do for the longest payoff. Skipping it is the #1 cause of LLM-app regressions you can't reproduce.",
      }),
      spark("Cost guardrails", {
        type: "microread",
        title: "Use observability to cap spend",
        body: "Most OSS observability tools include per-user / per-org cost dashboards + alerts. Set hard alerts at 50%, 80%, 100% of monthly budget. Add a kill-switch on a feature flag to gate the most-expensive paths if costs explode. Cheaper than a surprise bill.",
        takeaway: "Wire cost alerts + a kill-switch before you scale users.",
        category: "principle",
        addedAt: "2025-10-01",
      }),
    ]),
    level(T, 9, "Trendy OSS to watch", "Worth bookmarking.", 6, [
      spark("Names to know", {
        type: "microread",
        title: "Repos worth a star",
        body: "ggerganov/llama.cpp (CPU inference), open-webui (chat UI for any model), comfyanonymous/ComfyUI (image gen), unsloth (fast fine-tuning), Marker / Docling (PDF extraction for RAG), browser-use (browser agents), mem0 (memory layer), LiteLLM (provider abstraction), continue (open Cursor alternative).",
        takeaway: "Star these. They cover most builder needs.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Tip & Trick", {
        type: "tip",
        title: "💡 Tip & Trick",
        body: "Once a month, browse Hugging Face's trending models page and GitHub's trending Python repos for tag 'llm'. 10 minutes that keeps you current.",
        category: "pattern",
        addedAt: "2025-10-01",
      }),
      spark("LiteLLM: one SDK to rule them", {
        type: "microread",
        title: "Why LiteLLM saves your bacon",
        body: "LiteLLM exposes 100+ model providers behind a single OpenAI-compatible interface. Switch from OpenAI to Claude to Gemini to Llama-on-Together by changing a model name string. Includes routing, fallback, retry, cost tracking. The pragmatic 'don't lock me in' tool for any prod LLM stack.",
        takeaway: "LiteLLM = one SDK, 100+ providers, escape-hatch built in.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("ComfyUI: the image powerhouse", {
        type: "microread",
        title: "Node-based image generation",
        body: "ComfyUI is a node-graph UI for Stable Diffusion-class image generation. Power users build pipelines with controlnets, LoRAs, custom samplers, video extensions. Heavy learning curve, deep ceiling. The center of gravity for serious open-image work.",
        takeaway: "ComfyUI = serious open-image gen. Steep curve, huge ceiling.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("unsloth: fast fine-tuning", {
        type: "microread",
        title: "Why unsloth matters",
        body: "unsloth makes Llama / Mistral / Gemma fine-tuning 2-5x faster on the same GPU through hand-tuned kernels. Free tier up to a model size threshold; paid for bigger. Default OSS choice for LoRA + QLoRA fine-tuning when you have a single GPU.",
        takeaway: "unsloth = the fastest single-GPU fine-tuner. Default to it.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("mem0: memory layer", {
        type: "microread",
        title: "Why mem0 fills a gap",
        body: "mem0 is an open-source memory layer for AI agents — persist + retrieve user-specific facts, preferences, history across sessions. Plays well with LangChain, LlamaIndex, raw OpenAI. Solves the 'every conversation starts cold' problem without you building a custom store.",
        takeaway: "mem0 = open agent memory layer. Skip building your own.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("Marker + Docling: PDF for RAG", {
        type: "microread",
        title: "Open PDF-to-Markdown",
        body: "Marker (VikParuchuri) and Docling (IBM) extract structured Markdown from messy PDFs — tables, headings, equations, lists. Both are open and high-quality. Use them in RAG ingestion pipelines instead of writing brittle PDF parsers from scratch. Marker is faster on average; Docling has stronger table recovery.",
        takeaway: "Marker / Docling > custom PDF parsers for RAG ingestion.",
        category: "tooling",
        addedAt: "2026-05-01",
      }),
      spark("OSS to watch match-up", {
        type: "patternmatch",
        prompt: "Match each trendy OSS project to its purpose.",
        pairs: [
          { left: "open-webui", right: "Self-hosted ChatGPT-style UI for any model" },
          { left: "continue", right: "Open Cursor-alternative VS Code extension" },
          { left: "browser-use", right: "Browser-driving agent framework" },
          { left: "ComfyUI", right: "Node-based image / video generation" },
          { left: "LiteLLM", right: "Unified SDK across 100+ model providers" },
        ],
        explain: "These projects cover most builder workflows that aren't just 'call a model'.",
      }),
      spark("HF blog tracks releases", {
        type: "tip",
        title: "💡 huggingface.co/blog as a feed",
        body: "Treat the HF blog like a daily-driver newsfeed for OSS AI. New techniques, model launches, training cookbooks. Often more substantive than X threads on the same topics.",
        category: "company",
        addedAt: "2026-05-01",
        source: {
          name: "Hugging Face",
          url: "https://huggingface.co/blog",
        },
      }),
      spark("OSS adoption scenario", {
        type: "scenario",
        setup: "Your team uses OpenAI exclusively. Costs are climbing. Leadership wants you to evaluate OSS without breaking production.",
        prompt: "Lowest-risk first move?",
        options: [
          "Replace everything with Llama overnight",
          "Wrap calls in LiteLLM, route 5% of traffic to a hosted Llama 70B + measure quality + cost in shadow mode for two weeks",
          "Stop measuring",
          "Wait for permission",
        ],
        answer: 1,
        explain: "LiteLLM + shadow A/B is the low-risk migration shape. Measure before you cut.",
      }),
    ]),
    level(T, 10, "Boss: open source check", "Final gate.", 6, [
      spark("Boss Cell", {
        type: "boss",
        title: "Boss: Open Source AI",
        questions: [
          {
            type: "quickpick",
            prompt: "Easiest way to run an open model on your laptop?",
            options: ["Build CUDA from source", "Install Ollama, pull a model", "Train your own", "Buy an H100"],
            answer: 1,
            explain: "Ollama in 1 command.",
          },
          {
            type: "quickpick",
            prompt: "Best lightweight start for a vector DB inside an existing app?",
            options: ["Pinecone enterprise", "pgvector in Postgres", "Custom search index", "Redis only"],
            answer: 1,
            explain: "Same DB, vectors added.",
          },
          {
            type: "quickpick",
            prompt: "When should you DROP a framework?",
            options: ["Never", "When it costs more than it saves (debugging, abstraction tax)", "When you raise a Series A", "On Tuesdays"],
            answer: 1,
            explain: "Frameworks age into liabilities. Reassess yearly.",
          },
        ],
      }),
    ]),
  ],
};
